### PR TITLE
Do not map unregistered IDs

### LINKED ISSUE #4238: Error seen in Litgpt's Llama3 RoPE
Thunder Pytest Command:
```
pytest thunder/tests/test_networks.py -k test_memory_litgpt_llama3 -s
```

Error:
```|
Error from segmentation group 3:  INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/compute_at_map.cpp":1549, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. iS547{4}
has not been processed in this Compute At Map, yet the disjoint set for it was requested.
```

Repro:
```
# nvfuser version: 0.2.27+git802f042
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id8(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[1, 4, 2048, 16], contiguity=[None, True, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[3, 2, 1, 0])
    T1 = fd.define_tensor(shape=[2048, 16], contiguity=[True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[1, 0])
    T2 = fd.define_tensor(shape=[1, 4, 2048, 16], contiguity=[None, True, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[3, 2, 1, 0])
    T3 = fd.define_tensor(shape=[2048, 16], contiguity=[True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[1, 0])
    T4 = fd.define_tensor(shape=[1, 4, 2048, 16], contiguity=[None, True, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[3, 1, 2, 0])
    T20 = fd.ops.slice(T0, start_indices=[0, 0, 0, 0], end_indices=[1, 4, 2048, 16], strides=[1, 1, 1, 1], manual_normalization=0)
    T26 = fd.ops.broadcast_in_dim(T1, shape=[1, 4, 2048, 16], broadcast_dims=[2, 3])
    T42 = fd.ops.slice(T2, start_indices=[0, 0, 0, 0], end_indices=[1, 4, 2048, 16], strides=[1, 1, 1, 1], manual_normalization=0)
    T43 = fd.ops.cast(T20, dtype=DataType.Float)
    T44 = fd.ops.cast(T26, dtype=DataType.Float)
    T45 = fd.ops.cast(T42, dtype=DataType.Float)
    T46 = fd.ops.mul(T44, T43)
    T47 = fd.ops.mul(T44, T45)
    T48 = fd.ops.cast(T46, dtype=DataType.BFloat16)
    T49 = fd.ops.cast(T47, dtype=DataType.BFloat16)
    T65 = fd.ops.slice(T48, start_indices=[0, 0, 0, 0], end_indices=[1, 4, 2048, 8], strides=[1, 1, 1, 1], manual_normalization=0)
    T81 = fd.ops.slice(T49, start_indices=[0, 0, 0, 0], end_indices=[1, 4, 2048, 8], strides=[1, 1, 1, 1], manual_normalization=0)
    T82 = fd.ops.cast(T65, dtype=DataType.Float)
    T83 = fd.ops.cast(T81, dtype=DataType.Float)
    T84 = fd.ops.neg(T82)
    T90 = fd.ops.broadcast_in_dim(T3, shape=[1, 4, 2048, 16], broadcast_dims=[2, 3])
    S91 = fd.define_scalar(0, dtype=DataType.Int)
    T97 = fd.ops.full(shape=[1, 4, 2048, 0], fill_value=S91, dtype=DataType.BFloat16)
    T98 = fd.ops.neg(T83)
    T99 = fd.ops.cast(T84, dtype=DataType.BFloat16)
    T100 = fd.ops.cast(T90, dtype=DataType.Float)
    S101 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T111 = fd.ops.pad(T97, [0, 16, 0, 0, 0, 0, 0, 0], S101)
    T112 = fd.ops.cast(T98, dtype=DataType.BFloat16)
    T128 = fd.ops.slice(T48, start_indices=[0, 0, 0, 8], end_indices=[1, 4, 2048, 16], strides=[1, 1, 1, 1], manual_normalization=0)
    S129 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T139 = fd.ops.pad(T99, [8, 0, 0, 0, 0, 0, 0, 0], S129)
    T140 = fd.ops.mul(T100, T43)
    T141 = fd.ops.cast(T111, dtype=DataType.Float)
    T157 = fd.ops.slice(T49, start_indices=[0, 0, 0, 8], end_indices=[1, 4, 2048, 16], strides=[1, 1, 1, 1], manual_normalization=0)
    S158 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T168 = fd.ops.pad(T112, [8, 0, 0, 0, 0, 0, 0, 0], S158)
    T169 = fd.ops.mul(T100, T45)
    S170 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T180 = fd.ops.pad(T128, [0, 8, 0, 0, 0, 0, 0, 0], S170)
    T181 = fd.ops.cast(T139, dtype=DataType.Float)
    T182 = fd.ops.add(T141, T140)
    S183 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T193 = fd.ops.pad(T157, [0, 8, 0, 0, 0, 0, 0, 0], S183)
    T194 = fd.ops.cast(T168, dtype=DataType.Float)
    T195 = fd.ops.add(T141, T169)
    T196 = fd.ops.cast(T180, dtype=DataType.Float)
    T197 = fd.ops.add(T182, T181)
    T198 = fd.ops.cast(T193, dtype=DataType.Float)
    T199 = fd.ops.add(T195, T194)
    T200 = fd.ops.add(T197, T196)
    T201 = fd.ops.add(T199, T198)
    T202 = fd.ops.cast(T200, dtype=DataType.BFloat16)
    T203 = fd.ops.cast(T201, dtype=DataType.BFloat16)
    T210 = fd.ops.reshape(T4, new_shape=[1, 4, 1, 2048, 16])
    T217 = fd.ops.reshape(T202, new_shape=[1, 4, 1, 2048, 16])
    T224 = fd.ops.reshape(T203, new_shape=[1, 4, 1, 2048, 16])
    T225 = fd.ops.cat([T224, T217, T210], dim=2, manual_padding=0)
    T226 = fd.ops.permute(T225, dims=[0, 3, 1, 2, 4])
    T231 = fd.ops.reshape(T226, new_shape=[1, 2048, 192])
    T235 = fd.ops.reshape(T231, new_shape=[2048, 192])
    fd.add_output(T231)
    fd.add_output(T235)

with FusionDefinition() as fd:
    nvfuser_fusion_id8(fd)

inputs = [
    torch.testing.make_tensor((1, 4, 2048, 16), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((2048, 16), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((1, 4, 2048, 16), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((2048, 16), dtype=torch.bfloat16, device='cuda:0'),
    torch.randn(131072, dtype=torch.bfloat16, device='cuda:0').as_strided((1, 4, 2048, 16), (64, 16, 64, 1)),
]
fd.execute(inputs)
```

### PR DESCRIPTION
**Pull request by naoyam**
Fixes #4238

This is to fix an error when a tensor has exprs that are outside of TensorDomain::allIDs().

### CODE REVIEW

**Comment by naoyam** [comment]
!test

**Comment by naoyam** [comment]
!test

**Comment by naoyam** [comment]
!test

**Comment by naoyam** [comment]
!test

File: tests/cpp/test_compute_at_map.cpp [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+#include <ops/all_ops.h>
+#include <runtime/fusion_executor_cache.h>
+#include <tests/cpp/utils.h>
+#include <tests/cpp/validator.h>
+
+namespace nvfuser {
+
+using ComputeAtMapTest = NVFuserTest;
+
+TEST_F(ComputeAtMapTest, FusionMappingRelation) {
```
Comment (naoyam) [inline tests/cpp/test_compute_at_map.cpp:21]: Just moved from test_gpu3

File: tests/cpp/test_compute_at_map.cpp [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+
+  KernelExecutor ke;
+  ke.compile(fusion, {t0, t1});
+  auto cg_outputs = ke.run({t0, t1});
+
+  testValidate(fusion, cg_outputs, {t0, t1}, __LINE__, __FILE__);
+}
+
+// Repro of issue #4238
+TEST_F(ComputeAtMapTest, UnregisteredAlmostExactExpr) {
```
Comment (naoyam) [inline tests/cpp/test_compute_at_map.cpp:64]: New test
