### PR TITLE
Fix concretization and execution with padded expanded empty inputs

### LINKED ISSUE #870: Execution error with pad fusion on expanded input
An error was encountered involving expanded inputs (see https://github.com/NVIDIA/Fuser/issues/596#issuecomment-1714465618).

```python
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id11(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[-1, -1, -1], contiguity=[None, None, None], dtype=DataType.Double, is_cpu=False)
    S1 = fd.define_scalar(-3.70753, dtype=DataType.Double)
    T2 = fd.ops.pad(T0, [0, 0, 1, 1, 1, 0], S1)
    fd.add_output(T2)

with FusionDefinition() as fd:
    nvfuser_fusion_id11(fd)

inputs = [
    torch.randn((0,), dtype=torch.float64, device='cuda:0').as_strided((2, 0, 3), (0, 0, 0)),
]
fd.execute(inputs)
```
We encounter the following error:
> Traceback (most recent call last):
File "/opt/pytorch/nvfuser/nvfuser/__init__.py", line 122, in execute
    result = self._execute(
RuntimeError: val.hasValue() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/executor.cpp":1108, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Tried to evaluate the extent, ( ceilDiv(( ( ( 2 * ( (( (( getMetaData(T0) )).logical_size ))[2] ) ) * ( (( (( getMetaData(T0) )).logical_size ))[0] ) ) + ( ( (( (( getMetaData(T0) )).logical_size ))[2] ) * 2 ) ), 128) ) for the ptype: blockIdx.x to set launch bounds but could not. Exception raised from computeLaunchParams at /opt/pytorch/nvfuser/csrc/executor.cpp:1108 (most recent call first):               

This Fusion concretizes as
```
Inputs:
  T0_g[ bS0{i0}, bS9{0}, bS2{i2} ], double
Outputs:
  T1_g[ bS11{( ( i0 + ( (nvfuser_index_t)(1) ) ) + ( (nvfuser_index_t)(0) ) )}rf, iS6{( ( 0 + ( (nvfuser_index_t)(1) ) ) + ( (nvfuser_index_t)(1) ) )}rf, bS7{i2}rf ], double

%kernel_math {
i12 = (nvfuser_index_t)(1);
i14 = (nvfuser_index_t)(0);
i16 = (nvfuser_index_t)(1);
i18 = (nvfuser_index_t)(1);
i20 = (nvfuser_index_t)(0);
i22 = (nvfuser_index_t)(0);
T1_g[ bS11{( ( i0 + ( (nvfuser_index_t)(1) ) ) + ( (nvfuser_index_t)(0) ) )}rf, iS6{( ( 0 + ( (nvfuser_index_t)(1) ) ) + ( (nvfuser_index_t)(1) ) )}rf, bS7{i2}rf ]
   = pad( T0_g[ bS0{i0}, bS9{0}, bS2{i2} ], {i12, i14, i16, i18, i20, i22} )
}
```

I suspect there is an inconsistency between how input scalars are bound, since `i0` and `i2` should be bound to 2 and 3 during concretization. They should also be bound as elements of `getMetaData(T0).logical_size` later during execution.

### PR DESCRIPTION
**Pull request by jacobhinkle**
Stacked on #610; see https://github.com/NVIDIA/Fuser/issues/876#issuecomment-1731347156.

This PR:

- Changes the `analyzeResizes` pass in concretization to inspect expanded extents
- Changes root->rfactor propagation in concretization to return early when IterType is already concretized. This avoids propagating `Broadcast` in this test when we have already marked the resized ID as `Iteration`.
- Changes `PrecomputedValues::bindInputs` to bind not only metadata but also the actual `TensorView` arguments.

I noticed that the `ExpressionEvaluator` used during compilation contained more bound scalars than the one used at execution where we fail to evaluate the extent. We had `i0` and `i2` bound at execution, but we did not have `T0` bound, so we could not compute `getMetaData(T0)`. At compilation, `T0` was bound so there was no problem until execution.

Note that at compilation, we use `auto expr_eval = executor_utils::bindInputs(args, kernel);` whereas at compilation we use `evaluatorPrecomputedValues()->bindInputs(args);`. The difference is that `PrecomputedValues::bindInputs` will call `bindTensorMetaData` instead of binding the actual tensor. This PR also binds the actual tensor in addition to its metadata in that method.

Fixes #870

### CODE REVIEW

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

**Comment by zasdfgbnm** [comment]
Could you check the benchmark result for the cpp and python benchmarks in https://github.com/NVIDIA/Fuser/issues/749

**Comment by jjsjann123** [comment]
> Could you check the benchmark result for the cpp and python benchmarks in #749

Out of curiosity, are we expecting trivial changes in this PR to have big impact on overhead?!

**Comment by zasdfgbnm** [comment]
> > Could you check the benchmark result for the cpp and python benchmarks in #749
> 
> Out of curiosity, are we expecting trivial changes in this PR to have big impact on overhead?!

No, I don't expect so. Just want to confirm.

**Comment by jacobhinkle** [comment]
> Could you check the benchmark result for the cpp and python benchmarks in #749

The shape inference benchmarks look like this on `main`:
```
-------------------------------------------------------------------------------------------
Benchmark                                                 Time             CPU   Iterations
-------------------------------------------------------------------------------------------
LayerNormBackward_ShapeInference                       7898 us         7898 us           84
LayerNormForward_ShapeInference                        1994 us         1994 us          353
LayerNormBackward_NoShapeInferenceCachedBaseline       1339 us         1339 us          521
LayerNormForward_NoShapeInferenceCachedBaseline         467 us          467 us         1499 
```
and like this on this branch:

```
-------------------------------------------------------------------------------------------
Benchmark                                                 Time             CPU   Iterations
-------------------------------------------------------------------------------------------
LayerNormBackward_ShapeInference                       8194 us         8194 us           88
LayerNormForward_ShapeInference                        1948 us         1948 us          343
LayerNormBackward_NoShapeInferenceCachedBaseline       1263 us         1263 us          547
LayerNormForward_NoShapeInferenceCachedBaseline         461 us          461 us         1475
```

Where can I find the python benchmarks?

**Comment by zasdfgbnm** [comment]
> Where can I find the python benchmarks?

The python one is in https://github.com/NVIDIA/Fuser/issues/749#issuecomment-1689896825

File: csrc/evaluator_common.cpp [hunk 1]
```diff
@@ -170,9 +170,8 @@ void PrecomputedValues::bindInputs(const KernelArgumentHolder& args) {
       if (!tensor.is_cpu()) {
         bindTensorMetaData(tensor_input, tensor);
       }
-    } else {
-      bindValue(input->evaluatorIndex(), *args[i]);
     }
+    bindValue(input->evaluatorIndex(), *args[i]);
```
Comment (zasdfgbnm) [inline csrc/evaluator_common.cpp:174]: Oops, I think I remembered why I felt worried about this. At some point, I tried to do the same thing, but eventually gave up. Because doing so will make `PrecomputedValues` hold ownership of tensors, and as a result, memory usage will go up a lot.

Comment (jacobhinkle) [reply csrc/evaluator_common.cpp:174]: Ah that makes sense. So we don't want `PrecomputedValues` or `ExpressionEvaluator` to own any tensor buffers, but it might be nice to still hold them. We could bind a `Pointer` instead but I think we might still wind up owning the tensor in the `PolymorphicValue` that points to. We could also introduce a `TensorMeta` class that doesn't own its data but holds sizes, strides, dtype, device, and data pointer. I am not sure whether that would slow down evaluation of CPU aten ops though, since we'd need to construct an `at::Tensor` when evaluating those ops then.

Comment (jacobhinkle) [reply csrc/evaluator_common.cpp:174]: OK I'm trying to understand the existing `TensorMetaData` class now. I think maybe we could bind these values as the the outputs of `IrBuilder::metadataExpr(tv)` instead of binding to `tv` directly?

**Comment by jacobhinkle** [comment]
!build

File: csrc/evaluator_common.cpp (hunk 1 above)
Comment (zasdfgbnm) [reply csrc/evaluator_common.cpp:174]: I think it is OK for `ExpressionEvaluator` to bind tensors, actually, we are evaluating tensor expressions. Because we do not carry instances of `ExpressionEvaluator` for long time.

Comment (jacobhinkle) [reply csrc/evaluator_common.cpp:174]: But if we bind `tens` to `tv` in `ExpressionEvaluator ee` then later we bind a `PrecomputedValues pv` to `ee`, then we `evaluate` an expression with `tv` as an input, won't that populate `pv` with `tens`?

Comment (zasdfgbnm) [reply csrc/evaluator_common.cpp:174]: No, I don't think so.  `PrecomputedValues` -> `ExpressionEvaluator` is one-directional.

https://github.com/NVIDIA/Fuser/blob/5ff26b9ed9cc6d59b92490ba535c366e91747f28/csrc/expr_evaluator.cpp#L162-L166

Comment (jacobhinkle) [reply csrc/evaluator_common.cpp:174]: Got it. I'll revert the last PR then and add a note that we bind to `ExpressionEvaluator` but should avoid binding to `PrecomputedValues`.

File: csrc/polymorphic_value.h [hunk 2]
```diff
@@ -181,6 +181,12 @@ class StructHandle {
   StructHandle& operator=(const StructHandle& other) = default;
   StructHandle& operator=(StructHandle&& other) = default;
 
+  //! This is a shallow comparison operator that just checks whether we point to
+  //! the same exact Struct
+  bool operator==(const StructHandle& other) const {
+    return struct_ptr_ == other.struct_ptr_;
+  }
+
```
Comment (jacobhinkle) [inline csrc/polymorphic_value.h:189]: After binding a `TensorMetaData` handle in `PolymorphicValues`, without this I was hitting the following error:
>    what():  ret.has_value() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/lib/dynamic_type/src/dynamic_type/dynamic_type.h":741, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Cannot compute N7nvfuser12StructHandleE == N7nvfuser12StructHandleE : incompatible type
Exception raised from operator== at /opt/pytorch/nvfuser/lib/dynamic_type/src/dynamic_type/dynamic_type.h:741 (most recent call first):

Adding this shallow pointer comparison fixes it, but @zasdfgbnm please let me know if this is safe to add.

File: csrc/scheduler/normalization_inner.h [hunk 3]
```diff
@@ -65,17 +65,17 @@ class InnerPersistentKernelScheduler : public SchedulerEntry {
       const scheduler_utils::ReductionTvProperties& properties);
 };
 
-TORCH_CUDA_CU_API std::shared_ptr<ReductionParams> getInnerPersistentHeuristics(
+std::shared_ptr<ReductionParams> getInnerPersistentHeuristics(
```
Comment (jacobhinkle) [inline csrc/scheduler/normalization_inner.h:68]: Lintrunner was failing...

**Comment by jacobhinkle** [comment]
!build

File: csrc/evaluator_common.cpp [hunk 4]
```diff
@@ -342,6 +343,23 @@ void PrecomputedValues::bindTensorMetaData(
...
+  // we do not want them to own large objects.
+  std::shared_ptr<Struct> struct_ = std::make_shared<TensorMetaData>();
+  TensorMetaData* metadata = (TensorMetaData*)struct_.get();
+  metadata->dtype =
+      std::get<PrimDataType>(aten_to_data_type(tensor.scalar_type()).type);
+  metadata->data = tensor.data_ptr();
+  metadata->logical_size = tensor.sizes();
+  metadata->logical_stride = tensor.strides();
+  metadata->alloc_size = tensor.sizes();
+  metadata->alloc_stride = tensor.strides();
```
Comment (jacobhinkle) [inline csrc/evaluator_common.cpp:360]: How should we handle these? Currently this is failing in the test `AllocationDomainTest.NHWC4d_To_NHWC4d_CUDA`. In that test we have a memcpy fusion with channels-last inputs and outputs and we schedule vectorization of size 4. I get the error
> terminate called after throwing an instance of 'nvfuser::nvfError'                                                               
  what():  is_contiguous || size == 1 || is_expanded_broadcasting || (still_rightmost && stride == 1) || (!still_rightmost && stride % word_size == 0) INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/executor_utils.cpp":545, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Vectorization of T0_g[ iS15{( (( (( getMetaData(T0) )).logical_size ))[0] )}, iS16{( (( (( getMetaData(T0) )).logical_size ))[1] )}, iS17{( (( (( getMetaData(T0) )).logical_size ))[2] )}, iS18{( 
(( (( getMetaData(T0) )).logical_size ))[3] )} ] with word size 4 not possible due to invalid stride. Domain: iS18{( (( (( getMetaData(T0) )).logical_size ))[3] )}, stride: 21, cur_contig_stride: 1, non contig due to slice: 0

Inspecting this a bit I see that `logical_stride` and `alloc_stride` are the same because of the line above, but they should differ for this channels-last example.

**Comment by jacobhinkle** [comment]
!build

File: csrc/polymorphic_value.h (hunk 2 above)
Comment (zasdfgbnm) [reply csrc/polymorphic_value.h:189]: I think this makes sense

**Review by zasdfgbnm — APPROVED** [review]

**Comment by jacobhinkle** [comment]
I think this fixes the original problem. However, in doing so it exposes #596 in the `pytest_ops.py` slice correctness tests. Those tests include a fusion like this:
```
Fusion before concretization:
Inputs:  T0_g[ iS0{i0}, iS1{i1}, iS2{i2} ], float
Outputs:
  T1_g[ ?S4{1}rf, ?S6{6}rf, ?S8{5}rf ], float
%kernel_math {
T1_g[ ?S4{1}rf, ?S6{6}rf, ?S8{5}rf ]
   = slice( T0_g[ iS0{i0}, iS1{i1}, iS2{i2} ], { {1, 2, 1} {0, 6, 1} {3, 8, 1} } )
}
```
The output `IterDomain`s are currently symbolic, even though the extents are constant. These extents should actually depend on the inputs since if they are zero, even `?S4` might have zero extent. The problem at hand is that before this PR (e.g. on main commit b96d5691a) this is concretized as
```
Concretized Fusion:
Inputs:
  T0_g[ iS0{i0}, iS1{i1}, iS2{i2} ], float
Outputs:
  T1_g[ iS12{1}rf, iS13{6}rf, iS14{5}rf ], float

%kernel_math {T1_g[ iS12{1}rf, iS13{6}rf, iS14{5}rf ]
   = slice( T0_g[ iS0{i0}, iS1{i1}, iS2{i2} ], { {1, 2, 1} {0, 6, 1} {3, 8, 1} } )}
```
That is, the output iterdomain is concretized as `Iteration` since the input is marked as `Iteration` with size 1. This is somewhat related to #900 since in that proposal we would concretize `?S0` as broadcast as well. Anyway, this is the reverse problem from what is fixed in this PR, but the erroneous concretization was helping avoid triggering #596 previously. I would like to wait until a solution is found for that issue before merging this. If instead the current fix is needed urgently, I can disable the slice tests temporarily; i think this is the only failure in our test suite.

File: csrc/evaluator_common.cpp (hunk 4 above)
Comment (zasdfgbnm) [reply csrc/evaluator_common.cpp]: Sorry, missed this message. Is this still the case?

File: csrc/evaluator_common.cpp [hunk 5]
```diff
@@ -342,6 +343,25 @@ void PrecomputedValues::bindTensorMetaData(
...
   }
+
+  // Here we bind TensorMetaData so that GetMetaData expressions can be
+  // evaluated. Note that we do not bind the at::Tensor itself here since that
+  // would mean PrecomputedValues will own the tensor. Unlike
+  // ExpressionEvaluator, PrecomputedValues objects are typically long-lived, so
+  // we do not want them to own large objects.
+  // To do this we create a temporary ExpressionEvaluator so that we can compute
+  // the metadata once, then save it
+  ExpressionEvaluator ee;
```
Comment (zasdfgbnm) [inline csrc/evaluator_common.cpp:354]: There's some sharp edges here. For example, if between rfactor domain and root domain, there's a split whose factor is a fusion input, then this will fail, because we do not have it binded. But for now, I think it's fine because we do not have such case. Let's leave this as is. In the future we might need to refactor if this becomes an issue.

**Comment by jjsjann123** [comment]
> ...
> That is, the output iterdomain is concretized as `Iteration` since the input is marked as `Iteration` with size 1. This is somewhat related to #900 since in that proposal we would concretize `?S0` as broadcast as well. Anyway, this is the reverse problem from what is fixed in this PR, but the erroneous concretization was helping avoid triggering #596 previously. I would like to wait until a solution is found for that issue before merging this. If instead the current fix is needed urgently, I can disable the slice tests temporarily; i think this is the only failure in our test suite.
```
>Fusion before concretization:
Inputs:  T0_g[ iS0{i0}, iS1{i1}, iS2{i2} ], float
Outputs:
  T1_g[ ?S4{1}rf, ?S6{6}rf, ?S8{5}rf ], float
%kernel_math {
T1_g[ ?S4{1}rf, ?S6{6}rf, ?S8{5}rf ]
   = slice( T0_g[ iS0{i0}, iS1{i1}, iS2{i2} ], { {1, 2, 1} {0, 6, 1} {3, 8, 1} } )
}
```
> These extents should actually depend on the inputs since if they are zero, even ?S4 might have zero extent.

IIUC, all extends from a slice is dependent on the actual input sizes. i.e. if we slice out of range, the behavior is that it'll just crop at the boundary so output range is indeed dynamic.

So this is backing up the idea in #900 :smile:

**Comment by jacobhinkle** [comment]
> all extends from a slice is dependent on the actual input sizes

This is true. It's incorrect now as we assume `0 <= start <= stop <= extent` in `slice`, but #460 would replace these with the proper expressions.

File: csrc/evaluator_common.cpp (hunk 5 above)
Comment (jacobhinkle) [reply csrc/evaluator_common.cpp:354]: Great point. We should at minimum bind `this` here so that any precomputed values that are already bound will be available. I'll also add a comment about this pitfall.

File: csrc/evaluator_common.cpp (hunk 4 above)
Comment (jacobhinkle) [reply csrc/evaluator_common.cpp]: Oh this comment is outdated now since I realize we should just use `ExpressionEvaluator` to get the metadata object here instead of trying (and failing) to replicate it as I did previously.

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build
