### PR TITLE
Resolve broadcasts resulting from a PadOp

### LINKED ISSUE #357: Symbolic iter domains should not exact map when aligned
I am trying to make the following test pass:
```c++
// Test dynamic pad followed by broadcast resolution
TEST_F(NVFuserTest, DynamicPadBroadcast_CUDA) {
  std::unique_ptr<Fusion> fusion_ptr = std::make_unique<Fusion>();
  Fusion& fusion = *fusion_ptr.get();
  FusionGuard fg(&fusion);

  TensorView* tv0 = makeSymbolicTensor(2);
  fusion.addInput(tv0);
  TensorView* tv1 = makeSymbolicTensor(2);
  fusion.addInput(tv1);

  // 2d axis order here is YX
  auto ypad = IrBuilder::create<Int>();
  fusion.addInput(ypad);
  auto xpad = IrBuilder::create<Int>();
  fusion.addInput(xpad);

  // two-way resizes to cut square tv down to broadcastable size in either axis
  auto tv0_pad = pad(tv0, {fusion.zeroVal(), xpad, fusion.zeroVal(), ypad});

  // This will potentially resolve the y or x broadcast
  auto p = mul(tv0_pad, tv1);
  fusion.addOutput(p);

  fusion.printMath();
/*
Inputs:                                                                                                                          
  T0_g[ iS0{i0}, iS1{i2} ], float                                                                                                
  T1_g[ iS2{i3}, iS3{i4} ], float                                                                                                
  i5, int64_t                                                                                                                    
  i6, int64_t                                                                                                                    
Outputs:                                                                                                                         
  T3_g[ iS8{( i0 + i5 )}, iS9{( i2 + i6 )} ], float                                                                              
                                                                                                                                 
%kernel_math {                                                                                                                   
T2_l[ ?S5{( i0 + i5 )}rf, ?S7{( i2 + i6 )}rf ]                                                                                   
   = pad( T0_g[ iS0{i0}, iS1{i2} ], {0, i5, 0, i6} )                                                                             
T3_g[ iS8{( i0 + i5 )}, iS9{( i2 + i6 )} ]                                                                                       
   = T2_l[ ?S5{( i0 + i5 )}rf, ?S7{( i2 + i6 )}rf ]                                                                              
   * T1_g[ iS2{i3}, iS3{i4} ];                                                                                                   
}
*/

  FusionExecutorCache fusion_executor_cache(std::move(fusion_ptr));

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor at_x = at::randn({5, 5}, options);
  at::Tensor at_y = at::randn({5, 5}, options);

  std::vector<c10::IValue> aten_inputs({at_x, at_y, 0, 0});
  std::vector<at::Tensor> outputs;

  // shrink first axis so that the multiplication resolves a broadcast
  aten_inputs[2] = -4;
  aten_inputs[3] = 0;
  outputs = fusion_executor_cache.runFusionWithInputs(aten_inputs);
  testValidate(fusion_executor_cache.fusion(), outputs, aten_inputs, {at_x[0].unsqueeze(0) * at_y}, __LINE__, __FILE__);
}
```
During concretization, we try and evaluate the extent of dynamic resize. In this case, we want to evaluate extents of `?S5{( i0 + i5 )}rf` and `?S7{( i2 + i6 )}rf`. To compute these we use an expression evaluator, which actually throws an error:
> C++ exception with description "known_size == this_size INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/expr_evaluator.cpp":210, please report a bug to PyTorch. Conflicting sizes: 5, 1 

The following initial values are bound correctly based on inputs:
> Binding 5 to i0
> Binding 5 to i2
> Binding 5 to i3
> Binding 5 to i4
> Binding -4 to i5
> Binding 0 to i6

The error comes in `ExpressionEvaluator::propagateBoundValuesThroughExactMaps` when evaluating `i0 + i5` which evaluates to 1 but has `known_size == 5`. I believe this is because earlier, the multiplication sees a `Symbolic` domain aligned with an `Iteration` domain and interprets this as an exact map. I think the fix is to adjust the exact map condition to never set an exact mapping to/from `Symbolic` domains.

### LINKED ISSUE #596: Static pad to broadcast fails to schedule
This is a corner case for `Resize` ops that hasn't had a lot of attention yet, in which we use pad in a way that results in a broadcast that is then resolved.

```c++
TEST_F(NVFuserTest, PadToBroadcast) {
  auto fusion = std::make_unique<Fusion>();
  FusionGuard fg(fusion.get());

  auto tv0 = makeConcreteTensor({2});
  auto tv1 = makeConcreteTensor({3});
  fusion->addInput(tv0);
  fusion->addInput(tv1);

  auto tv2 = pad(tv0, {fusion->zeroVal(), IrBuilder::create<Scalar>(-1)});
  auto tv3 = mul(tv1, tv2);
  fusion->addOutput(tv3);

  // Fusion is not dynamic
  EXPECT_FALSE(fusion->hasDynamicTransform());

  fusion->printMath();
  /*
Inputs:
  T0_g[ iS0{2} ], float
  T1_g[ iS1{3} ], float
Outputs:
  T3_g[ iS4{3} ], float                                                                                                                                                                                                                                           %kernel_math {
T2_l[ bS3{1}rf ]
   = pad( T0_g[ iS0{2} ], {0, -1} )
T3_g[ iS4{3} ]
   = T1_g[ iS1{3} ]
   * T2_l[ bS3{1}rf ];
}
  */
  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);

  auto t0 = at::randn({2}, options);
  auto t1 = at::randn({3}, options);
  std::vector<c10::IValue> aten_inputs({t0, t1});

  auto args = KernelArgumentHolder::createKernelArgumentHolder(aten_inputs);
  FusionKernelRuntime runtime(std::move(fusion), args);
  /*
terminate called after throwing an instance of 'c10::Error'
  what():  it != broadcast_origin_map_.end() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/device_lower/analysis/trivial_broadcast.cpp":98, please report a bug to PyTorch.
Broadcast origin info not found for producer broadcast domain: bS3{1}rf of T2_l[ bS3{1}rf ]
Exception raised from handle at /opt/pytorch/nvfuser/csrc/device_lower/analysis/trivial_broadcast.cpp:98 (most recent call first)
  */

  runtime.compileFusionParallel(args);
  auto cg_outputs = runtime.runWithInputs(args);

  auto t2_padded = at::pad(t0, {0, -1});
  auto ref_t2 = t1 * t2_padded;

  testValidate(
      runtime.fusionSegments()->completeFusion(),
      cg_outputs,
      aten_inputs,
      {ref_t2},
      __LINE__,
      __FILE__);
}
```

Simply determining the output `IterType` is not sufficient to be able to actually resolve the broadcast. We instead need to have an actual tensor allocated to act as the broadcast origin. This can be done in this case by translating the `pad` to
```c++
  auto tv2 = broadcast(select(tv0, 0, fusion->zeroVal()), {true});
```
in which case `select` introduces the needed intermediate tensor which is the origin of the following broadcast.

Note that dynamic `pad` faces a similar issue but that we should probably fix this static case first. Static and dynamic slice will face a similar problem (related to #511).

### PR DESCRIPTION
**Pull request by jacobhinkle**
This changes broadcast analysis to drop the assumption that all broadcasts are created through a `BroadcastOp`. This change allows a broadcast to be introduced between root and rfactor of any tensor, which happens if we pad an `Iteration` domain with negative pad widths, resulting in a `Broadcast` domain.

This adds a `map_symbolic` option to `PairwiseRootDomainMap`, which defaults to false and has the following effect (condition 5):
- When `map_symbolic == false`, symbolic `IterDomain`s are only mapped with one another if their extent expressions match (`sameAs`). This is the default mode and safely handles cases where one symbolic value will concretize to broadcast that is resolved by the other.
- When `map_symbolic == true`, symbolic `IterDomain`s are mapped regardless of their extent expressions. This mode is useful for producer to consumer mappings when we know we are not resolving a broadcast, but a placeholder extent expression might be used in the consumer. It is only used for propagating concretizations from producer to consumer, in which case we need to exact map aligned symbolic IDs.

Fixes #596. Fixes #357

### CODE REVIEW

**Comment by jacobhinkle** [comment]
Dynamic test is currently failing in `ExpressionEvaluator::propagateBoundValuesThroughExactMaps` due to #357 which we should probably finally address.

File: test/test_resize.cpp [hunk 1]
```diff
@@ -2252,4 +2252,197 @@ TEST_F(NVFuserTest, SliceVectorization) {
...
+  std::vector<Val*> pad_width_vals;
+  pad_width_vals.reserve(pad_widths.size());
+  for ([[maybe_unused]] auto _ : pad_widths) {
+    auto w_val = IrBuilder::create<Scalar>(DataType::Int);
+    fusion->addInput(w_val);
+    pad_width_vals.push_back(w_val);
+  }
+
+  auto tv2 = pad(tv0, pad_width_vals);
+  auto tv3 = mul(tv1, tv2);
```
Comment (jacobhinkle) [inline test/test_resize.cpp:2364]: This test currently fails. The Fusion is concretized properly:
```
Inputs:
  T0_g[ iS0{i0}, iS1{i2}, iS2{i3}, iS3{i4}, iS4{i5} ], float
  T1_g[ iS5{i6}, iS6{i7}, iS7{i8}, iS8{i9}, iS9{i10} ], float
  i11, int64_t
  i12, int64_t
  i13, int64_t
  i14, int64_t
  i15, int64_t
  i16, int64_t
  i17, int64_t
  i18, int64_t
Outputs:
  T3_g[ iS19{i6}, iS20{i7}, iS21{i8}, iS22{i9}, iS23{i10} ], float                                                               
%kernel_math {
T2_l[ iS10{i0}, bS24{( ( i2 + i17 ) + i18 )}rf, iS25{( ( i3 + i15 ) + i16 )}rf, bS26{( ( i4 + i13 ) + i14 )}rf, iS27{( ( i5 + i11
 ) + i12 )}rf ]
   = pad( T0_g[ iS0{i0}, iS1{i2}, iS2{i3}, iS3{i4}, iS4{i5} ], {0, 0, i17, i18, i15, i16, i13, i14, i11, i12} )
T3_g[ iS19{i6}, iS20{i7}, iS21{i8}, iS22{i9}, iS23{i10} ]
   = T1_g[ iS5{i6}, iS6{i7}, iS7{i8}, iS8{i9}, iS9{i10} ]
   * T2_l[ iS10{i0}, bS24{( ( i2 + i17 ) + i18 )}rf, iS25{( ( i3 + i15 ) + i16 )}rf, bS26{( ( i4 + i13 ) + i14 )}rf, iS27{( ( i5
+ i11 ) + i12 )}rf ];
}
```
but then it is segmented at `tv2` (pointwise rejects with `cannot find reference tensor`). I think the pointwise scheduler should be able to schedule this, but the segmented Fusion also dies, since we cannot bind the input shape to `tv2` since it has a definition.

I think we may just need to rewrite the extent of the output as `oneVal()` when concretizing resizes as broadcasts.

Comment (jacobhinkle) [reply test/test_resize.cpp:2374]: This was fixed in #630 and these tests are now passing after merging from main.

File: csrc/dynamic_transform.cpp [hunk 2]
```diff
@@ -745,12 +746,13 @@ bool DynamicTransformConcretizer::propagateFromProducerToConsumer(
...
 
+      auto p_it = c2p.find(root_id);
       TORCH_INTERNAL_ASSERT(
-          c2p.find(root_id) != c2p.end(),
+          p_it != c2p.end(),
           "No input ID found to map with output ID: ",
           root_id->toString());
 
-      auto input_id = c2p.at(root_id);
+      auto input_id = p_it->second;
```
Comment (jacobhinkle) [inline csrc/dynamic_transform.cpp:755]: Just avoiding a second hash table lookup.

File: csrc/root_domain_map.cpp [hunk 3]
```diff
@@ -182,6 +183,16 @@ std::unordered_map<IterDomain*, IterDomain*> PairwiseRootDomainMap::map(
...
 
+    // Condition 5
+    // At least one ID is symbolic.
+    // Map producer to consumer if and only if their extents are identical
+    if ((producer_id->isSymbolic() || consumer_id->isSymbolic()) &&
+        (!producer_id->extent()->sameAs(consumer_id->extent()))) {
+      itc++;
+      itp++;
+      continue;
+    }
```
Comment (jacobhinkle) [inline csrc/root_domain_map.cpp:194]: This replaces earlier iterations on handling exact mapping of Symbolic domains, which I think were more cumbersome. The meaning of a `Symbolic` IterType is that it could potentially be a `Broadcast` domain. This is essentially reflecting that the extent expression hasn't been evaluated yet. If we have identical extents for two aligned `Symbolic` IterDomains, this should mean they will have the same IterType after concretization. In that case, they should be exact mapped. This lets us propagate bound extents in `ExpressionEvaluator` much more easily, while still avoiding exact mapping between transformed symbolic domains.

File: csrc/dynamic_transform.cpp [hunk 4]
```diff
@@ -727,6 +728,13 @@ bool DynamicTransformConcretizer::propagateFromProducerToConsumer(
 
   auto def = consumer->definition();
 
+  std::vector<std::unordered_map<IterDomain*, IterDomain*>> c2p_maps;
+  for (auto producer : ir_utils::filterByType<TensorView>(def->inputs())) {
+    PairwiseRootDomainMap root_map(producer, consumer);
+    c2p_maps.push_back(
+        root_map.mapConsumerToProducer(consumer->domain(), producer->domain()));
+  }
```
Comment (jacobhinkle) [inline csrc/dynamic_transform.cpp:736]: Precomputing c2p maps so they don't need to be recomputed for each consumer ID/producer pair.

**Comment by jacobhinkle** [comment]
!build

**Comment by jjsjann123** [comment]
sounds like this also resolves the example here: https://github.com/NVIDIA/Fuser/issues/596#issuecomment-1714465618
where an empty pad on a size-0 gives back a broadcast dimension.

Would you mind adding that as part of the test here?

File: csrc/device_lower/analysis/trivial_broadcast.cpp [hunk 5]
```diff
@@ -95,6 +92,14 @@ void ConcretizedBroadcastDomains::dispatch(Expr* expr) {
         const bool is_concretized =
             !c_id->isBroadcast() && !c_id->isReduction();
         auto it = broadcast_origin_map_.find(p_id);
+        if (it == broadcast_origin_map_.end()) {
+          // The consumer might be broadcast even though the producer is not, if
+          // this is a pad to size 1. In such case, we set the consumer as the
+          // origin of the broadcast.
+          broadcast_origin_map_.emplace(
```
Comment (naoyam) [inline csrc/device_lower/analysis/trivial_broadcast.cpp:99]: Why `c_id` is added here? It may not be a broadcast domain, right?

I think we would need to look at each tensor and see if it has an rfactor broadcast domain to look for a new broadcast.

Comment (jacobhinkle) [reply csrc/device_lower/analysis/trivial_broadcast.cpp:99]: You're right. I think this might have only worked since the only time the condition was being hit was for pads to broadcast. In that case there is only a single producer so this is fine, although we should probably still check `c_id->isBroadcast()`.

I think currently the only time we'll wind up with a `Broadcast` ID without a `BroadcastOp` is from a `PadOp`. Reshapes explicitly broadcast if a target size is 1, and `cat` appears with upstream `PadOp`s in the IR which would handle the broadcasting. The current approach in this PR is kind of a landmine; if we introduce a new op that can produce a broadcast we can hit this cryptic error again. I'm don't know how to handle it more elegantly yet.

Comment (naoyam) [reply csrc/device_lower/analysis/trivial_broadcast.cpp:99]: Doesn't `SliceOp` also possibly produce broadcast domains?

> if we introduce a new op that can produce a broadcast we can hit this cryptic error again. I'm don't know how to handle it more elegantly yet.

I wonder why this check doesn't get triggered when a broadcast is produced by a pad op, which is then resolved:

```
    NVF_ERROR(
            it != broadcast_origin_map_.end(),
            "Broadcast origin info not found for producer broadcast domain: ",
            p_id->toString(),
            " of ",
            producer->toString());
```

File: csrc/root_domain_map.h [hunk 6]
```diff
@@ -531,7 +543,7 @@ class TORCH_CUDA_CU_API ComputeAtRootDomainMapBuilder
 //! domains with non-broadcast domains.
 class TORCH_CUDA_CU_API ExactRootDomainMap : public RootDomainMap {
  public:
-  ExactRootDomainMap(Fusion* fusion);
+  ExactRootDomainMap(Fusion* fusion, bool map_symbolic = false);
```
Comment (naoyam) [inline csrc/root_domain_map.h:546]: When do we need to map symbolic domains? Is it actually used?

File: csrc/dynamic_transform.cpp [hunk 7]
```diff
@@ -807,17 +821,16 @@ bool DynamicTransformConcretizer::propagateFromProducerToConsumer(
...
-          consumer->domain(), producer->domain());
-
-      NVF_ERROR(
-          c2p.find(root_id) != c2p.end(),
-          "No input ID found to map with output ID: ",
-          root_id->toString());
+    for (const auto& c2p : c2p_maps) {
+      auto p_it = c2p.find(root_id);
+      if (p_it == c2p.end()) {
+        // We might not have mapped this ID to this producer, for example if the
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:827]: `PairwiseRootDomainMap` by default maps producer broadcast domains with consumer non-broadcast domains, so I think this comment is not correct.

File: csrc/dynamic_transform.cpp [hunk 8]
```diff
@@ -794,6 +795,19 @@ bool DynamicTransformConcretizer::propagateFromProducerToConsumer(
 
   auto def = consumer->definition();
 
+  std::vector<std::unordered_map<IterDomain*, IterDomain*>> c2p_maps;
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:798]: Why is this taken out of the loop below?

File: test/test_dynamic_transform.cpp [hunk 9]
```diff
@@ -63,6 +63,10 @@ TEST_F(NVFuserTest, DynamicTransform1_CUDA) {
     expr_eval.bind(tv0->axis(1)->extent(), 3L);
     expr_eval.bind(reshape_shape0, 3L);
     expr_eval.bind(reshape_shape1, 4L);
+    // We cannot infer the shape of tv1 from the above bound values, since
+    // either axis of tv2 might be broadcast against one from tv1.
+    expr_eval.bind(tv1->axis(0)->extent(), 3L);
+    expr_eval.bind(tv1->axis(1)->extent(), 4L);
```
Comment (naoyam) [inline test/test_dynamic_transform.cpp:69]: What error would there be if the additional bindings were not done?

File: csrc/dynamic_transform.cpp (hunk 8 above)
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:798]: Previously we were recomputing `PairwiseRootDomainMap root_map(producer, consumer)` for each root axis. This just precomputes each producer/consumer map once before iterating over the root domain.

File: csrc/dynamic_transform.cpp (hunk 7 above)
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:827]: You're right. I think we should just assert `p_it != c2p.end()` like we were before.

File: test/test_dynamic_transform.cpp (hunk 9 above)
Comment (jacobhinkle) [reply test/test_dynamic_transform.cpp:69]: Since the IterDomains are Symbolic, they do not exact map, so we will get an error that `expr_eval` cannot evaluate the size of `tv1` if we don't add this here. We need to evaluate that size for concretization in order to check whether it is empty.

File: csrc/root_domain_map.h (hunk 6 above)
Comment (jacobhinkle) [reply csrc/root_domain_map.h:546]: This is done in concretization inside `propagateFromProducerToConsumer`
```c++
  for (auto producer : ir_utils::filterByType<TensorView>(def->inputs())) {
    PairwiseRootDomainMap root_map(producer, consumer);
    // We map symbolic domains here regardless of whether their extents match.
    // This is safe because we are propagating from a producer which should have
    // already been concretized. The consumer might have a different extent
    // which will be equivalent to (but not necessarily sameAs) the producer's,
    // and we just want to use its IterType to concretize the consumer ID.
    root_map.mapSymbolic(true);
```

Comment (naoyam) [reply csrc/root_domain_map.h:546]: That's `PairwiseRootDomainMap`. Do we need `map_symbolic` of `ExactRootDomainMap`?

File: csrc/device_lower/analysis/trivial_broadcast.cpp (hunk 5 above)
Comment (naoyam) [reply csrc/device_lower/analysis/trivial_broadcast.cpp:99]: I think what we would need to do here is to have `handle(TensorView* tv)` and register new broadcast domains that appear as rfactor domains. That should make sure all broadcast domains in `broadcast_origin_map_`. Once we add some other ways to introduce new broadcast domains, the error check below (at line 103) should trigger. We may want to improve its error message.

File: test/test_dynamic_transform.cpp (hunk 9 above)
Comment (naoyam) [reply test/test_dynamic_transform.cpp:69]: Hmm, but `reshape_shape0` and `reshape_shape1` are also bound. Aren't we using them as the extents of `tv1`?

Comment (jacobhinkle) [reply test/test_dynamic_transform.cpp:69]: Not of `tv1`. The reshape is `tv2` and those are its extents, but `tv1` is another input that will wind up exact mapped to `tv2`.

File: csrc/device_lower/analysis/trivial_broadcast.cpp (hunk 5 above)
Comment (jacobhinkle) [reply csrc/device_lower/analysis/trivial_broadcast.cpp:99]: Ah ok that's a good idea. I will give it a shot. Thanks!

Comment (jacobhinkle) [reply csrc/device_lower/analysis/trivial_broadcast.cpp:100]: I just pushed a change that does what I think you suggested:
- Removes `handle(BroadcastOp*)`
- Removes change to `dispatch(Expr*)`
- Adds `handle(TensorView*)` which looks for rfactor IDs that are broadcast and have definitions, and registers them as origins.

Comment (jacobhinkle) [reply csrc/device_lower/analysis/trivial_broadcast.cpp:101]: I am hitting some errors with this approach
> [E thread_pool.cpp:110] Exception in thread pool task: predicated_parallel_types.none() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/device_lower/analysis/sync_information.cpp":57, please report a bug with repro script to NVFuser at https://github.co
m/NVIDIA/Fuser/issues. Invalid parallelization of tensor t10. The tensor is parallelized with (threadIdx.x), but it's invalid to use the types as the tensor is also predicated with them., thread pred: (threadIdx.x)   
```
I'll look into this soon.

Comment (jacobhinkle) [reply csrc/device_lower/analysis/trivial_broadcast.cpp]: OK I think i get it. The problem is that `BroadcastOp` outputs don't have rfactor domains. So we'll just need to keep the `BroadcastOp` handling method.

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

File: test/test_dynamic_transform.cpp (hunk 9 above)
Comment (naoyam) [reply test/test_dynamic_transform.cpp:69]: That makes sense. Thanks!

**Review by naoyam — APPROVED** [review]
LGTM. Thanks for the fix!
