### PR TITLE
Fix non-determinism in getSimplificationMap

### LINKED ISSUE #779: Run-to-run non-determinism in `TorchGatherSumAdd_CUDA` test
Running `NVFUSER_DUMP=cuda_kernel nvfuser_tests --gtest_filter='*TorchGatherSumAdd*'` multiple times gives different kernels currently on TOT (7aaa6c34). I have verified that the `scheduler_params` and `fusion_ir` printouts match, but the `kernel_ir` printout reflects the changes we see in the generated cuda code. The differences are typically like this:
image

Initially I thought this was because the inputs to the fusion, which are random, were not generated deterministically. However, I've verified that the random seeds are set properly and the inputs match. Additionally, different iterations of the test differ each time it is run. So I suspected there is nondeterminism in some lowering layer. Using `lower_verbose`, I think I've narrowed it down to `replaceSymbolicSizes`.

### PR DESCRIPTION
**Pull request by jacobhinkle**
Fixes #779

### CODE REVIEW

File: csrc/device_lower/pass/replace_size.cpp [hunk 1]
```diff
@@ -150,6 +150,14 @@ std::unordered_map<Val*, Val*> getSimplificationMap(Fusion* fusion) {
     auto* set = entry.first;
     auto input_id = entry.second;
     for (auto id : *set) {
+      auto prev_it = extent_to_min_input_id_extent.find(id->extent());
+      // We loop in an unspecified order, so we might overwrite
+      // extent_to_min_input_id_extent[id->extent()]. For reproducibility's
+      // sake, only do so if it would lower the index of the mapped value.
+      if (prev_it != extent_to_min_input_id_extent.end() &&
+          prev_it->second->name() < input_id->extent()->name()) {
```
Comment (zasdfgbnm) [inline csrc/device_lower/pass/replace_size.cpp:158]: nit:
```suggestion
          prev_it->second->name() <= input_id->extent()->name()) {
```

**Review by zasdfgbnm — APPROVED** [review]
LGTM

**Review by naoyam — APPROVED** [review]
Thanks for the fix!
