### PR TITLE
AllocationDomainPass sets correct allocation orders for SdpaFwdOp/SdpaBwdOp. 

### LINKED ISSUE #3194: Reshape/transpose operators in BFloat16 causing errors
I am seeing a strange bug where the datatype of a reshape and transpose ops is affecting the error of a much further downstream op. 

Cast output of linear0 from bfloat16->float before reshape/transpose, then cast back to bfloat16 before sdpa, note the casts should be redundant, and map to a pointwise scheduler
linear0 max error: 0.015625
          max relative error: 0.0062561
          failing elements: 0, 0% of tensor
linear0 max error: 0.0078125
          max relative error: 0.00294495
          failing elements: 0, 0% of tensor
sdpa max error: 0.000488281
          max relative error: 0.000289917
          failing elements: 0, 0% of tensor
sdpa max error: 0.000976562
          max relative error: 0.00050354
          failing elements: 0, 0% of tensor
linear1 max error: 0.00634766
          max relative error: 0.00524194
          failing elements: 0, 0% of tensor
linear1 max error: 0.00634766
          max relative error: 0.00524194
          failing elements: 0, 0% of tensor
dropout max error: 0.00705302
          max relative error: 0.00524198
          failing elements: 0, 0% of tensor
dropout max error: 0.00705302
          max relative error: 0.00524198
          failing elements: 0, 0% of tensor

No casting, reshape/transpose stay in bfloat16. From the preseg_fusion dump, the reshape/transpose are mapped to no-op scheduler. 
linear0 max error: 0.015625
          max relative error: 0.0062561
          failing elements: 0, 0% of tensor
linear0 max error: 0.0078125
          max relative error: 0.00294495
          failing elements: 0, 0% of tensor
sdpa max error: 0.000488281
          max relative error: 0.000289917
          failing elements: 0, 0% of tensor
sdpa max error: 0.000976562
          max relative error: 0.00050354
          failing elements: 0, 0% of tensor
**linear1 max error: 1.10844
          max relative error: 0.91536
          failing elements: 174249, 88.6276% of tensor
linear1 max error: 1.10844
          max relative error: 0.91536
          failing elements: 174249, 88.6276% of tensor
dropout max error: 1.2316
          max relative error: 0.91536
          failing elements: 158645, 80.691% of tensor
dropout max error: 1.2316
          max relative error: 0.91536
          failing elements: 158645, 80.691% of tensor**

Repro:
Checkout my fork, transformer_linear
$ git clone https://github.com/cowanmeg/Fuser.git --recursive
$ git checkout transformer_linear

$ mpirun -np 2 bin/test_multidevice --gtest_filter='DistributedTransformerTest.MultiheadAttention/__bfloat'

Note: Comments are in function `mha_qkv` of where to add/remove casts to observe behavior.

### LINKED ISSUE #3386: SdpaFwdOp::evaluate produces a tensor whose stride order doesn't match the output allocation domain.
Therefore, the consumer kernel of that output can read input data in the wrong order and generate wrong results. I suspect it has caused #3194 but I've yet to confirm that. 

I've yet to write a simple repro, but the root cause seems pretty clear now: 

The output TV of SdpaFwdOp expects the output to be contiguous and major-to-minor: https://github.com/NVIDIA/Fuser/blob/96d64b61612f3248062c7d17c68582f94b92e37c/csrc/ops/composite.cpp#L492. 

However, the output tensor of SdpaFwdOp::evaluate isn't guaranteed to be contiguous or to be major-to-minor: 
1. Regarding contiguity, https://github.com/NVIDIA/Fuser/blob/8bd9984d0125a09a13c170a507a2deff7ae748cf/csrc/ir/nodes.cpp#L4564, if kicks in, makes the output tensor non-contiguous in the last dimension. 
2. Regarding stride order, `at::_scaled_dot_product_flash_attention` propagates the input's stride order. In forward prop, the input Q/K/V are sliced, reshaped, and transposed from the output of MHA's first linear layer. So the typical memory format is [b,s,h,e], not [b,h,s,e] as specified in the output TV. 

Related: this is similar to the problem discussed in https://github.com/NVIDIA/Fuser/issues/2425, but they are not quite the same. Hence, a different ticket.

### PR DESCRIPTION
**Pull request by wujingyue**
Fixes #3386 and fixes #3194.

### CODE REVIEW

**Comment by wujingyue** [comment]
!test

File: csrc/ir/utils.h [hunk 1]
```diff
@@ -658,6 +658,25 @@ std::optional<std::vector<int64_t>> computePermutation(
   return permutation;
 }
 
+template <typename T>
+std::vector<T> applyPermutation(
```
Comment (jjsjann123) [inline csrc/ir/utils.h:662]: :clap:

File: tests/cpp/test_allocation_order_inference.cpp [hunk 2]
```diff
@@ -1,31 +1,31 @@
 // clang-format off
 /*
- * SPDX-FileCopyrightText: Copyright (c) 2023-present NVIDIA CORPORATION & AFFILIATES.
+ * SPDX-FileCopyrightText: Copyright (c) 2024-present NVIDIA CORPORATION & AFFILIATES.
```
Comment (jjsjann123) [inline tests/cpp/test_allocation_order_inference.cpp:3]: Out of curiosity, what's the reason for the change here?

**Review by jjsjann123 — APPROVED** [review]
:bow:

File: csrc/preseg_passes/allocation_order_inference.cpp [hunk 3]
```diff
@@ -336,6 +336,52 @@ void inferenceAllocationOrder(
   }
 }
 
+namespace {
+// Propagate allocation orders from an SDPA's inputs to outputs. This is
+// necessary to make an SPDA's allocation domain consistent with the output
+// at::Tensor from expression evaluation. Currently, we call ATen to evaluate
+// SDPAs so matching their behavior, despite being fragile, is the best
+// solution.
+class SdpaPropagator : public OptOutConstDispatch {
```
Comment (Priya2698) [inline csrc/preseg_passes/allocation_order_inference.cpp:345]: Users in nvfuser can set stride_order for these inputs `fd.add_output(out, stride_order)`.  In that case, we should not be propagating this order since it will lead to errors. It will likely require inserting tensor ops within these ops.

Not requesting a change in this PR specifically. This was part of the motivation for Issue #2425. Related issue for matmul/linear: Issue #2427.

File: tests/cpp/test_allocation_order_inference.cpp (hunk 2 above)
Comment (wujingyue) [reply tests/cpp/test_allocation_order_inference.cpp:3]: I'll revert this change. I got conflicting suggestions from the internet, but the general consensus seems to be put the year of creation.

File: csrc/preseg_passes/allocation_order_inference.cpp (hunk 3 above)
Comment (wujingyue) [reply csrc/preseg_passes/allocation_order_inference.cpp:345]: That's right -- I'll change `propagateAllocation` to only propagate when the destination doesn't have allocation.

**Comment by wujingyue** [comment]
!test

**Comment by wujingyue** [comment]
!test

**Review by Priya2698 — APPROVED** [review]
LGTM.
