### PR TITLE
Fix getContigMergeOfInnerSize for device-parallel logical dimensions

### LINKED ISSUE #5920: Misaligned memory access with 3D sharding
Repro: https://github.com/NVIDIA/Fuser/pull/5919

With `NVFUSER_DUMP=fusion_ir`,
```
T1_g___bfloat[iblockIdx.x42{( ceilDiv(( ceilDiv(( i2 * ( i0 * ( ( ceilDiv(i3, 2) ) * 128 ) ) ), 2) ), 128) )}, iUS41{1}, iV39{2}, ithreadIdx.x43{128}, ideviceIdx.y32{2}, ideviceIdx.x33{2}] ca_pos( 2 ) produce_pos( 2 ) (DeviceMesh{{0 1}{2 3}})
  logical domain: (iS28{i0}, iS29{128}, iS30{i2}, iS31{i3}, ideviceIdx.y32{2})
  allocation domain: (iS30{i2}, iS28{i0}, iS29{128}, ideviceIdx.x33{2}, iS34{( ceilDiv(i3, 2) )}, ideviceIdx.y32{2})
  contiguity: t t t t t t
    Outer split: iS31{i3} by factor 2 -> ideviceIdx.x33{2}, iS34{( ceilDiv(i3, 2) )}
    Merge: iS29{128} and iS34{( ceilDiv(i3, 2) )} -> iS35{( ( ceilDiv(i3, 2) ) * 128 )}
    Merge: iS28{i0} and iS35{( ( ceilDiv(i3, 2) ) * 128 )} -> iS36{( i0 * ( ( ceilDiv(i3, 2) ) * 128 ) )}
    Merge: iS30{i2} and iS36{( i0 * ( ( ceilDiv(i3, 2) ) * 128 ) )} -> iS37{( i2 * ( i0 * ( ( ceilDiv(i3, 2) ) * 128 ) ) )}
    Split: iS37{( i2 * ( i0 * ( ( ceilDiv(i3, 2) ) * 128 ) ) )} by factor 2 -> iS38{( ceilDiv(( i2 * ( i0 * ( ( ceilDiv(i3, 2) ) * 128 ) ) ), 2) )}, iV39{2}
    Split: iS38{( ceilDiv(( i2 * ( i0 * ( ( ceilDiv(i3, 2) ) * 128 ) ) ), 2) )} by factor 1 -> iS40{( ceilDiv(( i2 * ( i0 * ( ( ceilDiv(i3, 2) ) * 128 ) ) ), 2) )}, iUS41{1}
    Split: iS40{( ceilDiv(( i2 * ( i0 * ( ( ceilDiv(i3, 2) ) * 128 ) ) ), 2) )} by factor 128 -> iblockIdx.x42{( ceilDiv(( ceilDiv(( i2 * ( i0 * ( ( ceilDiv(i3, 2) ) * 128 ) ) ), 2) ), 128) )}, ithreadIdx.x43{128}
  loop domain: (iblockIdx.x42{( ceilDiv(( ceilDiv(( i2 * ( i0 * ( ( ceilDiv(i3, 2) ) * 128 ) ) ), 2) ), 128) )}, iUS41{1}, iV39{2}, ithreadIdx.x43{128}, ideviceIdx.y32{2}, ideviceIdx.x33{2})
```

Is vector size 2 a problem? The innermost dimension size is `10/cp_size=5`. 

Incidentally, I was reading https://github.com/NVIDIA/Fuser/blob/1bded433e7fbbaaaf8ea3773dfbe1332813f73f6/csrc/scheduler/vectorize_helper.cpp#L833. Does this break for multi-dimensional meshes? `getProjectedExtent(logical_id)` might not even be divisible by number of devices, although it should be divisible by the size of the corresponding mesh axis. cc @Priya2698

### PR DESCRIPTION
**Pull request by wujingyue**
Fixes #5920

### CODE REVIEW

**Comment by wujingyue** [comment]
!test

File: csrc/scheduler/vectorize_helper.cpp [hunk 1]
```diff
@@ -829,8 +829,13 @@ Val* ContiguousInnerDimensionsMapper::getContigMergeOfInnerSize(
       break;
     }
 
-    auto sharded_extent = SimplifyingIrBuilder::divExpr(
-        getProjectedExtent(logical_id), num_devices);
+    Val* sharded_extent;
+    if (logical_id->isDeviceDim()) {
+      sharded_extent = of_tv->container()->oneVal();
```
Comment (jjsjann123) [inline csrc/scheduler/vectorize_helper.cpp:834]: IIUC, the patch is for the case where we don't have any expr between logical and allocation. Looked seemed straightforward to me.

Yet I'm surprised that this didn't get caught earlier.
