### PR TITLE
Fix ReplayTransformations to properly set isRFactorProduct. 

### LINKED ISSUE #1857: ReplayTransformations don't set isRFactorProduct correctly.
E.g. https://github.com/NVIDIA/Fuser/blob/71d9b555b401655c0d664b94e8abb7021ce29637/csrc/transform_iter.cpp#L53-L54 uses the default `rfactor_domain=false`. I guess this has been fine for now because we only use it to replay leaf transformations. However, this caused my pending https://github.com/NVIDIA/Fuser/pull/1846 to fail when replaying a pointwise unary op. 

I added a reproducer in #1846. The error message is
```
C++ exception with description "id_a->definition() == nullptr || id_a->isRFactorProduct() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/root_domain_map.cpp":546, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Non-root domain is not supported: iS37{2}
```

Apparently, when scheduling a pointwise kernel, ComputeAtMap relies on isRFactorProduct to skip mapping certain IterDomains.

### PR DESCRIPTION
**Pull request by wujingyue**
This PR adds a knob to copy isRFactorProduct from the IterDomain being replayed. I hate knobs but couldn't find a better way. Plenty of ReplayTransformations users (e.g. https://github.com/NVIDIA/Fuser/blob/a684e2a220ed6daa14673d4c492b8eb80c299ce0/csrc/scheduler/utils.cpp#L2171 triggered by https://github.com/NVIDIA/Fuser/blob/8226e61a2a843e8e4ad8c6c2801b019f654828d1/test/test_gpu3.cpp#L7320) replay rfactor transforms on a TensorView without rfactor. Therefore, ReplayTransformations cannot copy isRFactorProduct unconditionally. 

Fixes #1857.

### CODE REVIEW

**Comment by wujingyue** [comment]
!build

File: csrc/transform_iter.cpp [hunk 1]
```diff
@@ -50,8 +50,14 @@ void ReplayTransformations::handle(Split* s) {
...
   // Replay the split onto mapped
+  NVF_ERROR(s->outer()->isRFactorProduct() == s->inner()->isRFactorProduct());
   auto outs = IterDomain::split(
-      mapped, s->factor(), s->innerSplit(), s->startOffset(), s->stopOffset());
+      mapped,
+      s->factor(),
+      s->innerSplit(),
+      s->startOffset(),
+      s->stopOffset(),
+      replay_rfactor_ && s->outer()->isRFactorProduct());
```
Comment (naoyam) [inline csrc/transform_iter.cpp:60]: Suppose `mapped` is an rfactor product, this would result in an non-rfactor product output if `replay_rfactor_` is false. Should it be considered an error?

Comment (wujingyue) [reply csrc/transform_iter.cpp:60]: > Suppose mapped is an rfactor product, this would result in an non-rfactor product output if replay_rfactor_ is false.

That's right. 

> Should it be considered an error?

That's already the current behavior and I'm not making it worse at least :)

AFAICT, it's not necessarily an error. Users of ReplayTransformations may want to replay rfactor-to-leaf transformations on a new rfactor domain. The results of those transformations shouldn't be marked `rf`. Correct?

Comment (wujingyue) [reply csrc/transform_iter.cpp:60]: Below is a real scenario that happens ToT. It's not for split per say, but for merge, which I think is close enough to show the idea. It can be reproduced with `bin/nvfuser_tests --gtest_filter=*ForIncompliantLayout`. 

The pointwise scheduler tries to replay the consumer's root-to-leaf transformations on the producer's rfactor domain. Dimension 0 of the producer's rfactor doesn't have `rf` but dimension 1 has `rf`. 

image

File: csrc/transform_iter.cpp [hunk 2]
```diff
@@ -253,7 +262,7 @@ void ReplayTransformations::handle(Resize* exp) {
         mapped,
         exp->leftExpand(),
         exp->rightExpand(),
-        mapped->isRFactorProduct());
```
Comment (naoyam) [inline csrc/transform_iter.cpp:256]: I suspect this should have been `false` always. It would have resulted in an `rfactor` domain outside of the root-rfactor transformation.

**Review by naoyam — APPROVED** [review]
LGTM.

File: csrc/transform_iter.cpp (hunk 2 above)
Comment (wujingyue) [reply csrc/transform_iter.cpp:256]: Agreed. I did try to test this line of change alone and found all tests passed. Probably a lack of test coverage

**Comment by wujingyue** [comment]
!build
