### PR TITLE
Don't try to index broadcast IDs as they should always be zero and there may not be a valid path from loop IDs

### LINKED ISSUE #3688: nvfuser:__init__.py:330 An error occurred while executing nvFuser FusionDefinition
From the Thunder CI in https://github.com/Lightning-AI/lightning-thunder/pull/1622 .

I can reproduce in a lightning studio with L40s+cu121 but not on my 3080+cu125 not sure if the cuda version matters.
Also seems to happen with nightly nvfuser installed from nvidia-PyPI.

nvfuser:__init__.py:330 An error occurred while executing nvFuser FusionDefinition 67.
If you believe this is a bug or need assistance, please file an issue at https://github.com/NVIDIA/Fuser/issues/new
Here's a script to reproduce the error:

```python
# CUDA devices:
#  0: NVIDIA GeForce RTX 3090
#  1: NVIDIA GeForce RTX 3090
# torch version: 2.5.1+cu121
# cuda version: 12.1
# nvfuser version: 0.2.24+git6eb2bc0
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id67(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[5, 5, 7680], contiguity=[True, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[2, 1, 0])
    T1 = fd.define_tensor(shape=[5, 32], contiguity=[True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[1, 0])
    T2 = fd.define_tensor(shape=[5, 32], contiguity=[True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[1, 0])
    T9 = fd.ops.reshape(T0, new_shape=[5, 5, 32, 3, 80])
    T10 = fd.ops.permute(T9, dims=[0, 2, 3, 1, 4])
    T29 = fd.ops.slice(T10, start_indices=[0, 0, 0, 0, 0], end_indices=[5, 32, 1, 5, 80], strides=[1, 1, 1, 1, 1], manual_normalization=0)
    T48 = fd.ops.slice(T10, start_indices=[0, 0, 1, 0, 0], end_indices=[5, 32, 2, 5, 80], strides=[1, 1, 1, 1, 1], manual_normalization=0)
    T54 = fd.ops.reshape(T48, new_shape=[5, 32, 5, 80])
    T70 = fd.ops.slice(T54, start_indices=[0, 0, 0, 0], end_indices=[5, 32, 5, 32], strides=[1, 1, 1, 1], manual_normalization=0)
    T76 = fd.ops.reshape(T29, new_shape=[5, 32, 5, 80])
    T92 = fd.ops.slice(T70, start_indices=[0, 0, 0, 16], end_indices=[5, 32, 5, 32], strides=[1, 1, 1, 1], manual_normalization=0)
    T108 = fd.ops.slice(T76, start_indices=[0, 0, 0, 0], end_indices=[5, 32, 5, 32], strides=[1, 1, 1, 1], manual_normalization=0)
    T109 = fd.ops.cast(T92, dtype=DataType.Float)
    T125 = fd.ops.slice(T108, start_indices=[0, 0, 0, 16], end_indices=[5, 32, 5, 32], strides=[1, 1, 1, 1], manual_normalization=0)
    T126 = fd.ops.neg(T109)
    T127 = fd.ops.cast(T125, dtype=DataType.Float)
    T143 = fd.ops.slice(T70, start_indices=[0, 0, 0, 0], end_indices=[5, 32, 5, 16], strides=[1, 1, 1, 1], manual_normalization=0)
    T144 = fd.ops.cast(T126, dtype=DataType.BFloat16)
    T145 = fd.ops.neg(T127)
    T151 = fd.ops.broadcast_in_dim(T1, shape=[5, 32, 5, 32], broadcast_dims=[2, 3])
    T152 = fd.ops.cat([T144, T143], dim=-1, manual_padding=0)
    T158 = fd.ops.broadcast_in_dim(T2, shape=[5, 32, 5, 32], broadcast_dims=[2, 3])
    T174 = fd.ops.slice(T108, start_indices=[0, 0, 0, 0], end_indices=[5, 32, 5, 16], strides=[1, 1, 1, 1], manual_normalization=0)
    T175 = fd.ops.cast(T145, dtype=DataType.BFloat16)
    T176 = fd.ops.cast(T151, dtype=DataType.Float)
    T177 = fd.ops.cast(T152, dtype=DataType.Float)
    T178 = fd.ops.cast(T158, dtype=DataType.Float)
    T179 = fd.ops.cast(T70, dtype=DataType.Float)
    T180 = fd.ops.cat([T175, T174], dim=-1, manual_padding=0)
    T181 = fd.ops.mul(T177, T176)
    T182 = fd.ops.mul(T179, T178)
    T183 = fd.ops.cast(T180, dtype=DataType.Float)
    T184 = fd.ops.cast(T108, dtype=DataType.Float)
    T185 = fd.ops.add(T182, T181)
    T186 = fd.ops.mul(T183, T176)
    T187 = fd.ops.mul(T184, T178)
    T203 = fd.ops.slice(T54, start_indices=[0, 0, 0, 32], end_indices=[5, 32, 5, 80], strides=[1, 1, 1, 1], manual_normalization=0)
    T204 = fd.ops.cast(T185, dtype=DataType.BFloat16)
    T205 = fd.ops.add(T187, T186)
    S206 = fd.define_scalar(5, dtype=DataType.Int)
    S207 = fd.define_scalar(0, dtype=DataType.Int)
    S208 = fd.define_scalar(1, dtype=DataType.Int)
    T209 = fd.ops.iota(S206, S207, S208, dtype=DataType.Int)
    T210 = fd.ops.cat([T204, T203], dim=-1, manual_padding=0)
    T226 = fd.ops.slice(T76, start_indices=[0, 0, 0, 32], end_indices=[5, 32, 5, 80], strides=[1, 1, 1, 1], manual_normalization=0)
    T227 = fd.ops.cast(T205, dtype=DataType.BFloat16)
    T231 = fd.ops.broadcast_in_dim(T209, shape=[5, 1], broadcast_dims=[0])
    T232 = fd.ops.permute(T210, dims=[0, 1, 3, 2])
    T233 = fd.ops.cat([T227, T226], dim=-1, manual_padding=0)
    T237 = fd.ops.broadcast_in_dim(T209, shape=[1, 5], broadcast_dims=[1])
    S238 = fd.define_scalar(0, dtype=DataType.Int)
    T239 = fd.ops.add(T231, S238)
    T240 = fd.ops.cast(T232, dtype=DataType.Float)
    T241 = fd.ops.cast(T233, dtype=DataType.Float)
    T245 = fd.ops.broadcast_in_dim(T237, shape=[5, 5], broadcast_dims=[0, 1])
    T249 = fd.ops.broadcast_in_dim(T239, shape=[5, 5], broadcast_dims=[0, 1])
    S250 = fd.define_scalar(0.334370, dtype=DataType.Double)
    T251 = fd.ops.mul(T240, S250)
    S252 = fd.define_scalar(0.334370, dtype=DataType.Double)
    T253 = fd.ops.mul(T241, S252)
    T254 = fd.ops.ge(T249, T245)
    T255 = fd.ops.cast(T251, dtype=DataType.BFloat16)
    T256 = fd.ops.cast(T253, dtype=DataType.BFloat16)
    T262 = fd.ops.broadcast_in_dim(T254, shape=[5, 32, 5, 5], broadcast_dims=[2, 3])
    fd.add_output(T255)
    fd.add_output(T256)
    fd.add_output(T262)

with FusionDefinition() as fd:
    nvfuser_fusion_id67(fd)

inputs = [
    torch.testing.make_tensor((5, 5, 7680), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((5, 32), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((5, 32), dtype=torch.bfloat16, device='cuda:0'),
]
fd.execute(inputs)
```

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nvfuser/__init__.py", line 319, in execute
    results = self._execute(
RuntimeError:  INTERNAL ASSERT FAILED at "/workspace/Fuser/csrc/runtime/fusion_kernel_runtime.cpp":407, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Detected exception while compiling fusion segments in parallel. Error messages from all threads are printed below.

Error from segmentation group 7:  INTERNAL ASSERT FAILED at "/workspace/Fuser/csrc/bfs.h":241, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. BFS traversal could not visit some nodes:  idg{111 112 553 554 558 559 633 634 637 638 974 975 984 985 994 995 1004 1005 1014 1015} (from:  idg{653 662 672 682 692 702 712 722 752 762 772 782 792 802 822 832 842 852 862 872 902 912 922 932 942 962 972 982 1002 1012 1022 1032 1049 1050} idg{657 667 677 687 697 707 717 727 737 747 757 767 777 787 847 857 867 877 887 897 907 917 927 937 947 957 967 1027 1037 1047} idg{658 668 678 688 698 708 718 728 738 748 758 768 778 788 848 858 868 878 888 898 908 918 928 938 948 958 968 1028 1038 1048} idg{656 666 676 686 696 706 716 726 736 746 756 766 776 786 846 856 866 876 886 896 906 916 926 936 946 956 966 1026 1036 1046} idg{652 661 671 681 691 701 711 721 731 751 761 771 781 791 801 821 831 841 851 861 871 881 901 911 921 931 941 961 971 981 1001 1011 1021 1031} idg{654 663 673 683 693 703 713 723 733 753 763 773 783 793 803 823 833 843 853 863 873 883 903 913 923 933 943 963 973 983 1003 1013 1023 1033}), visited: ( idg{811 991 1041} idg{810 990 1040} idg{812 992 1042} idg{809 989 1039} idg{91 113 203 225 250 266 276 428 442 456 460 465 474 488 492 496 500 504 519 528 532 537 551 555 560 564 569 573 577 581 585 611 619 623 627 632 635 639 643 647} idg{649 659 669 679 689 699 709 719 729 749 759 769 779 789 799 819 829 839 849 859 869 879 899 909 919 929 939 959 969 979 999 1009 1019 1029} idg{813 993 1043} idg{205 226 249 265 275 429 443 457 462 466 475 489 493 497 501 506 520 529 534 538 552 557 561 566 570 574 578 582 586 631 636 640 644 648} idg{653 662 672 682 692 702 712 722 752 762 772 782 792 802 822 832 842 852 862 872 902 912 922 932 942 962 972 982 1002 1012 1022 1032 1049 1050} idg{657 667 677 687 697 707 717 727 737 747 757 767 777 787 847 857 867 877 887 897 907 917 927 937 947 957 967 1027 1037 1047} idg{202 224 248 264 274 427 441 455 473 487 491 495 499 503 518 527 531 536 550 563 568 572 576 580 584 610 618 622 626 630} idg{201 223 247 263 273 426 440 454 472 486 490 494 498 502 517 526 530 535 549 562 567 571 575 579 583 609 617 621 625 629} idg{658 668 678 688 698 708 718 728 738 748 758 768 778 788 848 858 868 878 888 898 908 918 928 938 948 958 968 1028 1038 1048} idg{656 666 676 686 696 706 716 726 736 746 756 766 776 786 846 856 866 876 886 896 906 916 926 936 946 956 966 1026 1036 1046} idg{652 661 671 681 691 701 711 721 731 751 761 771 781 791 801 821 831 841 851 861 871 881 901 911 921 931 941 961 971 981 1001 1011 1021 1031} idg{654 663 673 683 693 703 713 723 733 753 763 773 783 793 803 823 833 843 853 863 873 883 903 913 923 933 943 963 973 983 1003 1013 1023 1033} idg{92 114 461 556 565 612} idg{651 660 670 680 690 700 710 720 730 750 760 770 780 790 800 820 830 840 850 860 870 880 900 910 920 930 940 960 970 980 1000 1010 1020 1030} idg{650 655 664 665 674 675 684 685 694 695 704 705 714 715 724 725 734 735 744 745 754 755 764 765 774 775 784 785 844 845 854 855 864 865 874 875 884 885 894 895 904 905 914 915 924 925 934 935 944 945 954 955 964 965 1024 1025 1034 1035 1044 1045})
Exception raised from traverse at /workspace/Fuser/csrc/bfs.h:241 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x162 (0x7f431444050b in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #1: nvfuser::nvfErrorFail(char const*, char const*, unsigned int, char const*, std::string const&) + 0x3e (0x7f431481f71e in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #2: <unknown function> + 0x5e8e23 (0x7f43148f5e23 in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x5eb026 (0x7f43148f8026 in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x5d82ba (0x7f43148e52ba in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x5d9405 (0x7f43148e6405 in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x61bd03 (0x7f4314928d03 in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #7: <unknown function> + 0x43b16a (0x7f431474816a in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #8: <unknown function> + 0x443b87 (0x7f4314750b87 in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #9: <unknown function> + 0x433aff (0x7f4314740aff in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #10: <unknown function> + 0x433aff (0x7f4314740aff in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #11: <unknown function> + 0x433aff (0x7f4314740aff in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #12: <unknown function> + 0x443b87 (0x7f4314750b87 in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #13: <unknown function> + 0x433aff (0x7f4314740aff in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #14: <unknown function> + 0x433aff (0x7f4314740aff in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #15: <unknown function> + 0x433aff (0x7f4314740aff in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #16: <unknown function> + 0x432a6b (0x7f431473fa6b in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #17: <unknown function> + 0x3f671b (0x7f431470371b in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #18: nvfuser::GpuLower::run() + 0x1e5 (0x7f43146fcb55 in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #19: nvfuser::KernelExecutor::compile(nvfuser::Fusion*, nvfuser::KernelArgumentHolder const&, nvfuser::LaunchParams const&, nvfuser::CompileParams, nvfuser::SchedulerType) + 0x5aa (0x7f4314b22dfa in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #20: <unknown function> + 0x81e618 (0x7f4314b2b618 in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #21: <unknown function> + 0x855716 (0x7f4314b62716 in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #22: <unknown function> + 0x85667e (0x7f4314b6367e in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #23: c10::ThreadPool::main_loop(unsigned long) + 0x2b3 (0x7f4480ea6dd3 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #24: <unknown function> + 0x7bf27 (0x7f4480ea6f27 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #25: <unknown function> + 0x145c0 (0x7f448211c5c0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch.so)
frame #26: <unknown function> + 0x94ac3 (0x7f44836b7ac3 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #27: clone + 0x44 (0x7f4483748bf4 in /usr/lib/x86_64-linux-gnu/libc.so.6)


Use NVFUSER_DISABLE=parallel_compile to simplify error message.
Exception raised from compileFusionParallel at /workspace/Fuser/csrc/runtime/fusion_kernel_runtime.cpp:407 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x162 (0x7f431444050b in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #1: nvfuser::nvfErrorFail(char const*, char const*, unsigned int, char const*, std::string const&) + 0x3e (0x7f431481f71e in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #2: nvfuser::FusionKernelRuntime::compileFusionParallel(nvfuser::KernelArgumentHolder) + 0x15d4 (0x7f4314b68d64 in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #3: nvfuser::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&, std::optional<nvfuser::PrimDataType>, std::optional<signed char>) + 0x1b6 (0x7f4314b57ed6 in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #4: nvfuser::python_frontend::FusionDefinition::execute(c10::ArrayRef<c10::IValue> const&, std::optional<signed char>, bool, bool, bool, std::vector<std::string, std::allocator<std::string> >, std::vector<std::string, std::allocator<std::string> >) const + 0xb4d (0x7f4314d0eeed in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x1bfe53 (0x7f43144cce53 in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x2742a6 (0x7f43145812a6 in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #7: <unknown function> + 0x2d4732 (0x7f43145e1732 in /usr/local/lib/python3.10/dist-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #8: <unknown function> + 0x18b282 (0x55ff92bd7282 in /usr/bin/python3.10)
frame #9: _PyObject_MakeTpCall + 0x25b (0x55ff92bcdb4b in /usr/bin/python3.10)
frame #10: <unknown function> + 0x198ebb (0x55ff92be4ebb in /usr/bin/python3.10)
frame #11: _PyEval_EvalFrameDefault + 0x1a22 (0x55ff92bc2cf2 in /usr/bin/python3.10)
frame #12: <unknown function> + 0x198be1 (0x55ff92be4be1 in /usr/bin/python3.10)
frame #13: PyObject_Call + 0x122 (0x55ff92be5882 in /usr/bin/python3.10)
frame #14: _PyEval_EvalFrameDefault + 0x2c89 (0x55ff92bc3f59 in /usr/bin/python3.10)
frame #15: _PyObject_FastCallDictTstate + 0xc4 (0x55ff92bccd14 in /usr/bin/python3.10)
frame #16: _PyObject_Call_Prepend + 0x5c (0x55ff92be1d4c in /usr/bin/python3.10)
frame #17: <unknown function> + 0x29e054 (0x55ff92cea054 in /usr/bin/python3.10)
frame #18: _PyObject_MakeTpCall + 0x25b (0x55ff92bcdb4b in /usr/bin/python3.10)
frame #19: _PyEval_EvalFrameDefault + 0x5c7d (0x55ff92bc6f4d in /usr/bin/python3.10)
frame #20: _PyFunction_Vectorcall + 0x7c (0x55ff92bd7aec in /usr/bin/python3.10)
frame #21: _PyEval_EvalFrameDefault + 0x2c89 (0x55ff92bc3f59 in /usr/bin/python3.10)
frame #22: _PyFunction_Vectorcall + 0x7c (0x55ff92bd7aec in /usr/bin/python3.10)
frame #23: _PyEval_EvalFrameDefault + 0x2c89 (0x55ff92bc3f59 in /usr/bin/python3.10)
frame #24: _PyFunction_Vectorcall + 0x7c (0x55ff92bd7aec in /usr/bin/python3.10)
frame #25: _PyEval_EvalFrameDefault + 0x58aa (0x55ff92bc6b7a in /usr/bin/python3.10)
frame #26: _PyFunction_Vectorcall + 0x7c (0x55ff92bd7aec in /usr/bin/python3.10)
frame #27: _PyEval_EvalFrameDefault + 0x2c89 (0x55ff92bc3f59 in /usr/bin/python3.10)
frame #28: _PyFunction_Vectorcall + 0x7c (0x55ff92bd7aec in /usr/bin/python3.10)
frame #29: _PyEval_EvalFrameDefault + 0x2c89 (0x55ff92bc3f59 in /usr/bin/python3.10)
frame #30: <unknown function> + 0x198d2e (0x55ff92be4d2e in /usr/bin/python3.10)
frame #31: torch::autograd::PyNode::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x9e (0x7f447b43b58e in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_python.so)
frame #32: <unknown function> + 0x55cafbb (0x7f446b537fbb in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so)
frame #33: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) + 0x15de (0x7f446b5320ce in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so)
frame #34: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) + 0x69f (0x7f446b532d2f in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so)
frame #35: torch::autograd::Engine::execute_with_graph_task(std::shared_ptr<torch::autograd::GraphTask> const&, std::shared_ptr<torch::autograd::Node>, torch::autograd::InputBuffer&&) + 0x3d5 (0x7f446b52d325 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so)
frame #36: torch::autograd::python::PythonEngine::execute_with_graph_task(std::shared_ptr<torch::autograd::GraphTask> const&, std::shared_ptr<torch::autograd::Node>, torch::autograd::InputBuffer&&) + 0x25 (0x7f447b436fe5 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_python.so)
frame #37: torch::autograd::Engine::execute(std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool, bool, bool, std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&) + 0xbac (0x7f446b53055c in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cpu.so)
frame #38: torch::autograd::python::PythonEngine::execute(std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool, bool, bool, std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&) + 0x56 (0x7f447b436f76 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_python.so)
frame #39: THPEngine_run_backward(_object*, _object*, _object*) + 0x300 (0x7f447b4353f0 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_python.so)
frame #40: <unknown function> + 0x18b282 (0x55ff92bd7282 in /usr/bin/python3.10)
frame #41: PyObject_Call + 0xbb (0x55ff92be581b in /usr/bin/python3.10)
frame #42: _PyEval_EvalFrameDefault + 0x6c1d (0x55ff92bc7eed in /usr/bin/python3.10)
frame #43: _PyFunction_Vectorcall + 0x7c (0x55ff92bd7aec in /usr/bin/python3.10)
frame #44: _PyEval_EvalFrameDefault + 0x1a22 (0x55ff92bc2cf2 in /usr/bin/python3.10)
frame #45: _PyFunction_Vectorcall + 0x7c (0x55ff92bd7aec in /usr/bin/python3.10)
frame #46: _PyEval_EvalFrameDefault + 0x1a22 (0x55ff92bc2cf2 in /usr/bin/python3.10)
frame #47: _PyFunction_Vectorcall + 0x7c (0x55ff92bd7aec in /usr/bin/python3.10)
frame #48: _PyEval_EvalFrameDefault + 0x818 (0x55ff92bc1ae8 in /usr/bin/python3.10)
frame #49: _PyFunction_Vectorcall + 0x7c (0x55ff92bd7aec in /usr/bin/python3.10)
frame #50: _PyEval_EvalFrameDefault + 0x2c89 (0x55ff92bc3f59 in /usr/bin/python3.10)
frame #51: _PyFunction_Vectorcall + 0x7c (0x55ff92bd7aec in /usr/bin/python3.10)
frame #52: _PyEval_EvalFrameDefault + 0x2c89 (0x55ff92bc3f59 in /usr/bin/python3.10)
frame #53: _PyFunction_Vectorcall + 0x7c (0x55ff92bd7aec in /usr/bin/python3.10)
frame #54: _PyEval_EvalFrameDefault + 0x2c89 (0x55ff92bc3f59 in /usr/bin/python3.10)
frame #55: _PyFunction_Vectorcall + 0x7c (0x55ff92bd7aec in /usr/bin/python3.10)
frame #56: _PyEval_EvalFrameDefault + 0x58aa (0x55ff92bc6b7a in /usr/bin/python3.10)
frame #57: <unknown function> + 0x198be1 (0x55ff92be4be1 in /usr/bin/python3.10)
frame #58: _PyEval_EvalFrameDefault + 0x58aa (0x55ff92bc6b7a in /usr/bin/python3.10)
frame #59: _PyFunction_Vectorcall + 0x7c (0x55ff92bd7aec in /usr/bin/python3.10)
frame #60: _PyObject_FastCallDictTstate + 0x16d (0x55ff92bccdbd in /usr/bin/python3.10)
frame #61: _PyObject_Call_Prepend + 0x5c (0x55ff92be1d4c in /usr/bin/python3.10)
frame #62: <unknown function> + 0x29e054 (0x55ff92cea054 in /usr/bin/python3.10)
frame #63: _PyObject_MakeTpCall + 0x25b (0x55ff92bcdb4b in /usr/bin/python3.10)
```

### PR DESCRIPTION
**Pull request by naoyam**
Fixes #3688 

The error of #3688 is because some of the broadcast logical IDs are not reachable when indexing. Specifically, this happened when indexing the logical IDs of a consumer tensor of a pad op. https://github.com/NVIDIA/Fuser/blob/main/csrc/device_lower/pass/index.cpp#L2698-L2699

When a consumer has broadcast logical IDs, they may not be reachable from the loop domain when inlined, and that's why the indexing traversal fails as seen in #3688. Note that for usual indexing paths such as `getLinearIndex` and `getPredicates`, they always filter out broadcast IDs from indexing because they should always use zero.

This PR always excludes broadcast IDs from indexing by changing `computeIndex`, which is the common indexing interface for all use cases including `getLinearIndex`, `getPredicates`, `getIndexFor`, etc. 

To be honest, I'm not 100% confident if we should really always ignore broadcast IDs, but I'm not aware of any concrete counter cases. Given that, this seems to be the most reasonable fix to me.

### CODE REVIEW

**Comment by naoyam** [comment]
!test --diff

**Comment by naoyam** [comment]
Here's a simple repro:

```
TEST_F(IndexingTest, BroadcastLogicalDomainIndexing) {
  auto fusion_ptr = std::make_unique<Fusion>();
  auto& fusion = *fusion_ptr;
  FusionGuard fg(fusion_ptr.get());

  std::vector<int64_t> shape1{1, 32};
  std::vector<int64_t> shape2{8, 34};

  auto tv0 = makeConcreteTensor(shape1);
  fusion.addInput(tv0);
  auto tv1 = makeConcreteTensor(shape2);
  fusion.addInput(tv1);

  auto tv2 = pad(tv0, {fusion.oneVal(), fusion.oneVal()});
  auto tv3 = add(tv2, tv1);
  fusion.addOutput(tv3);

  tv2->inlineAt(-1);

  fusion.printMath();
  fusion.printKernel();
}
```

```
Inputs:
  T0_g_float[bS0{1}, iS1{32}]
  T1_g_float[iS2{8}, iS3{34}]
Outputs:
  T3_g_float[iS7{8}, iS8{34}] produce_pos( 2 )

%kernel_math {
T2_l_float[bS4{1}, iS6{34}rf] ca_pos( 2 )
   = pad( T0_g_float[bS0{1}, iS1{32}], {0, 0, 1, 1} )
T3_g_float[iS7{8}, iS8{34}] produce_pos( 2 )
   = T2_l_float[bS4{1}, iS6{34}rf] ca_pos( 2 )
   + T1_g_float[iS2{8}, iS3{34}];
} // %kernel_math

unknown file: Failure
C++ exception with description " INTERNAL ASSERT FAILED at "/home/nmaruyama/nvfuser/debug2/csrc/bfs.h":241, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. BFS traversal could not visit some nodes:  idg{0 4} (from:  idg{2 7} idg{3 6 8}), visited: ( idg{1 5} idg{3 6 8} idg{2 7})
```

```
(gdb) bt
#0  0x00007fffdd95735a in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x000055555637a573 in nvfuser::nvfCheckFail (
    func=0x555555f072fe <.L__FUNCTION__._ZN7nvfuser3BFSISt10shared_ptrINS_21VectorOfUniqueEntriesIPNS_4ExprESt4hashIS4_EEEES1_INS2_IPNS_3ValES5_ISA_EEEENS_19ValGraphDefinitionsENS_12ValGraphUsesENS_14ValGraphInputsENS_15ValGraphOutputsEE8traverseEv> "traverse", file=0x555555ea8d28 <.L.str.93> "/home/nmaruyama/nvfuser/debug2/csrc/bfs.h", line=241, msg=...) at /home/nmaruyama/nvfuser/debug2/csrc/exceptions.cpp:275
#2  0x000055555637a7cd in nvfuser::nvfErrorFail (
    func=0x555555f072fe <.L__FUNCTION__._ZN7nvfuser3BFSISt10shared_ptrINS_21VectorOfUniqueEntriesIPNS_4ExprESt4hashIS4_EEEES1_INS2_IPNS_3ValES5_ISA_EEEENS_19ValGraphDefinitionsENS_12ValGraphUsesENS_14ValGraphInputsENS_15ValGraphOutputsEE8traverseEv> "traverse", file=0x555555ea8d28 <.L.str.93> "/home/nmaruyama/nvfuser/debug2/csrc/bfs.h", line=241,
    condMsg=0x555555ee5fba <.L.str.81> " INTERNAL ASSERT FAILED at \"/home/nmaruyama/nvfuser/debug2/csrc/bfs.h\":241, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. ", userMsg=...)
    at /home/nmaruyama/nvfuser/debug2/csrc/exceptions.cpp:301
#3  0x00005555560df189 in nvfuser::BFS<std::shared_ptr<nvfuser::VectorOfUniqueEntries<nvfuser::Expr*, std::hash<nvfuser::Expr*> > >, std::shared_ptr<nvfuser::VectorOfUniqueEntries<nvfuser::Val*, std::hash<nvfuser::Val*> > >, nvfuser::ValGraphDefinitions, nvfuser::ValGraphUses, nvfuser::ValGraphInputs, nvfuser::ValGraphOutputs>::traverse (this=0x7fffffffab10) at /home/nmaruyama/nvfuser/debug2/csrc/bfs.h:241
#4  0x00005555564f70c5 in nvfuser::IndexingTraversal::getExprsBetween (expr=0x55555b12a8a0, graph=..., from_domains=..., to_domains=...) at /home/nmaruyama/nvfuser/debug2/csrc/id_model/indexing_traversal.cpp:297
#5  0x00005555564de8bd in nvfuser::TensorIndexer::computeIndex (this=0x55555b146010, expr=0x55555b12a8a0, index_ids=..., for_loops=...) at /home/nmaruyama/nvfuser/debug2/csrc/id_model/indexing.cpp:957
#6  0x00005555564de351 in nvfuser::TensorIndexer::getIndexFor (this=0x55555b146010, expr=0x55555b12a8a0, as_consumer=true, index_ids=..., for_loops=...) at /home/nmaruyama/nvfuser/debug2/csrc/id_model/indexing.cpp:854
#7  0x0000555556526943 in nvfuser::Index::getConsumerPerDimLogicalIndex (consumer_tv=0x55555b12c5f0, loops=..., rotated_loops=...) at /home/nmaruyama/nvfuser/debug2/csrc/index_compute.cpp:1622
```

File: csrc/id_model/indexing.cpp [hunk 1]
```diff
@@ -939,9 +939,23 @@ IndexingInfo TensorIndexer::computeIndex(
     const std::vector<ForLoop*>& for_loops) const {
   const auto loop_domains = getLoopIds(expr, id_model_);
 
+  // Set aside broadcast IDs as their indices should always be zero
+  // and there may not be reachable from the loop domain
+  std::vector<IterDomain*> broadcast_index_ids;
+  broadcast_index_ids.reserve(index_ids.size());
+  std::vector<IterDomain*> non_broadcast_index_ids;
+  non_broadcast_index_ids.reserve(index_ids.size());
```
Comment (jacobhinkle) [inline csrc/id_model/indexing.cpp:947]: Nit: we probably don't need to reserve since we will have different amounts for these.

**Review by jacobhinkle — APPROVED** [review]
LGTM

File: csrc/id_model/indexing.cpp (hunk 1 above)
Comment (naoyam) [reply csrc/id_model/indexing.cpp:947]: I just did this because `index_ids.size` should be small and it's probably better to just allocate some maximum size. Anyway, I don't think this would actually matter much.

**Comment by naoyam** [comment]
!build

**Comment by naoyam** [comment]
!build

**Comment by naoyam** [comment]
!build
