### PR TITLE
Target arch validation

### LINKED ISSUE #1760: Validate use of bf16 (and other relatively new hardware features)
(Originally in #1758)

The bf16 type is only supported on sm80 and later. Currently, nvFuser will just fail when we compile a generated kernel with nvrtc. While we do not care too much about pre-A100 generations, we should at least do:

- More informative error messages rather than just nvrtc compilation failure
- Explicitly define the required minimum architecture version

When we lower a `Fusion` to a `Kernel`, we should define the minimum required version. The default should be sm70, i.e., the V100 version. When the `Kernel` has `bf16` vals, it should at least be `sm80`. Other recent architecture features such as memcpy_async and TMA should also set the minimum version accordingly.

This minimum version should then be checked before the `Kernel` is compiled by nvrtc. Now that we have the information about the required minimum version, we should be able to give more helpful information.

### PR DESCRIPTION
**Pull request by jacobhinkle**
This introduces a minimum device version attribute to the kernel summary and populates it by traversing the fusion early in lowering to find ops or data types introduced after sm70. This version constraint is checked in FusionExecutor::compileFusion and if the target arch doesn't satisfy the constraint then an informative error message is given. Currently BFloat16, cp.async and cp.async.bulk are checked, as are the various MMA macros.

Fixes #1760

### CODE REVIEW

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

File: csrc/device_lower/analysis/device_version.cpp [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+        "LoadStoreOpType::CpAsyncBulkTensorTile requires Hopper (9.0) or newer");
+  }
+}
+
+void MinimumDeviceVersion::ensureVersion(
+    std::pair<int, int> version,
+    std::string reason) {
+  if (version > min_version_) {
+    min_version_ = version;
+    reason_ = reason;
```
Comment (jacobhinkle) [inline csrc/device_lower/analysis/device_version.cpp:56]: There can be multiple reasons for ensuring the same version, but it would be slightly more complicated to list them all, so we will only include the latest reason in the error message.

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

File: test/test_gpu3.cpp [hunk 2]
```diff
@@ -7745,7 +7765,11 @@ TEST_F(NVFuserTest, AllInputDtypes) {
     output = IrBuilder::addExpr(output, idx);
     output = IrBuilder::addExpr(output, i32);
     output = IrBuilder::addExpr(output, b);
-    output = IrBuilder::addExpr(output, castOp(DataType::Double, bf16));
+    if (at::cuda::getCurrentDeviceProperties()->major >= 8) {
+      auto bf16 = IrBuilder::create<Val>(DataType::BFloat16);
+      fusion->addInput(bf16);
+      output = IrBuilder::addExpr(output, castOp(DataType::Double, bf16));
+    }
```
Comment (jacobhinkle) [inline test/test_gpu3.cpp:7772]: This test worked previously on V100, even though the fusion contains BFloat16.

**Comment by jacobhinkle** [comment]
Should we also check cuda version?

File: csrc/executor.cpp [hunk 3]
```diff
@@ -331,6 +331,29 @@ void FusionExecutor::compileFusion(
...
   kir::Kernel* kernel = lowered_->kernel();
+
+  const kir::KernelSummary& kernel_summary = kernel->summary();
+
+  // TODO: this replicates the target GPU version computation from
+  // executor_utils.
+  std::pair<int, int> target_arch;
+  bool compile_to_sass = false;
+  executor_utils::queryTargetGPUVersion(
+      properties, target_arch.first, target_arch.second, compile_to_sass);
```
Comment (wujingyue) [inline csrc/executor.cpp:342]:
```suggestion
  executor_utils::queryTargetGPUVersion(
      properties, std::ref(target_arch.first), std::ref(target_arch.second), /*compile_to_sass=*/false);
```

std::ref makes it clear to the reader that this variable can be modified by the callee.

File: csrc/device_lower/analysis/device_version.h [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+#include <vector>
+
+namespace nvfuser {
+
+class LoopIndexing;
+class ComputeAtMap;
+
+//! Traverses a Fusion to find the minimum supported CUDA compute capability
+//! that will be able to run the generated kernel.
+class MinimumDeviceVersion : IterVisitor {
```
Comment (wujingyue) [inline csrc/device_lower/analysis/device_version.h:27]:
```suggestion
class MinimumDeviceVersion : private IterVisitor {
```

I rarely used private inheritance so I forgot about the default :) 

Nit: I'm not a big fan of using inheritance when it's not an "is-a" relation. I'd probably do composition instead -- adding a public IterVisitor as a member.

**Review by wujingyue — APPROVED** [review]

File: csrc/executor.cpp [hunk 5]
```diff
@@ -331,6 +331,29 @@ void FusionExecutor::compileFusion(
...
+
+  NVF_CHECK(
```
Comment (zasdfgbnm) [inline csrc/executor.cpp:344]: Could you move this code down after `getStructuredCode` before nvRTC? Doing so is helpful because, for example, when I am developing Hopper, I don't want to always grab a Hopper machine: sometimes I can just use whatever machine and using `DebugDumpOption::CudaKernel` to check is sufficient for me.

**Review by zasdfgbnm — APPROVED** [review]

File: csrc/executor.cpp (hunk 3 above)
Comment (jacobhinkle) [reply csrc/executor.cpp:342]: I don't have much experience with `std::ref` but that sounds good to me.

File: csrc/executor.cpp (hunk 5 above)
Comment (jacobhinkle) [reply csrc/executor.cpp]: Great suggestion. I moved it and verified that the generated kernel is now printed before the error.
