### PR TITLE
Fix Issue 3117

### LINKED ISSUE #3117: Check Tensor.dims equals the rank of the corresponding TensorView.
This is a follow-up to #3114. A bug could have been surfaced earlier if we had checked the equality. 

> To compare a `Tensor` and its `TensorView`, you'd have to construct the cpp `Fusion` by calling `fd.execute`. Then, for each tensor, get its `TensorView` via `getFusionState(size_t index)`, then compare their dimensions.

_Originally posted by @rdspring1 in https://github.com/NVIDIA/Fuser/pull/3114#pullrequestreview-2349490294_

### PR DESCRIPTION
**Pull request by rdspring1**
Fixes #3117 

This PR creates `verifyTensorDimensions` to check that `Tensor.dims` equals the rank of the corresponding `TensorView`. It is called in `FusionDefinition::finalizeDefinition` after `buildFusionIr`.

### CODE REVIEW

**Comment by rdspring1** [comment]
!build

File: csrc/python_frontend/fusion_definition.cpp [hunk 1]
```diff
@@ -189,6 +190,23 @@ void FusionDefinition::updateSymbolicStates(
   }
 }
 
+void FusionDefinition::verifyTensorDimensions() {
+  NVF_CHECK(id().has_value(), "Invalid fusion id!");
+
+  std::vector<Tensor> all_tensors = tensors();
+  for (Tensor& t : all_tensors) {
+    Val* v = getFusionState(t.index);
+    NVF_ERROR(v->isA<TensorView>());
```
Comment (wujingyue) [inline csrc/python_frontend/fusion_definition.cpp:199]:
```suggestion
    NVF_ERROR(v->isA<TensorView>(), v->toString());
```

File: csrc/python_frontend/fusion_definition.cpp [hunk 2]
```diff
@@ -189,6 +190,23 @@ void FusionDefinition::updateSymbolicStates(
...
+    int64_t tv_ndims = v->as<TensorView>()->nDims();
```
Comment (wujingyue) [inline csrc/python_frontend/fusion_definition.cpp:200]:
```suggestion
    const int64_t tv_ndims = v->as<TensorView>()->nDims();
```

**Review by wujingyue — APPROVED** [review]
Thank you!

**Comment by rdspring1** [comment]
!build
