### PR TITLE
Place broadcasts outside iteration in 3D reduction

### LINKED ISSUE #1471: codegen issue on consecutive reduction
```
RuntimeError: false INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/executor.cpp":404, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Allocations must be based on constant integers for local memory. However, found: T5_l[ iblockIdx.y92{( (( (( getMetaData(T0) )).logical_size ))[1] )}, rS41{( ceilDiv(( ceilDiv(( ceilDiv(( ( (( (( getMetaData(T0) )).logical_size ))[0] ) * ( (( (( getMetaData(T0) )).logical_size ))[2] ) ), blockDim.x) ), 1) ), gridDim.x) )}rf, iblockIdx.z44{gridDim.z}, iS45{( ceilDiv(( ceilDiv(1, 2) ), gridDim.z) )}, iS43{2}, iblockIdx.x40{gridDim.x}rf, ithreadIdx.x37{blockDim.x}rf, rUS39{1}rf ] ca_pos( 1 ) produce_pos( 2 ),  have dynamic allocations but are placed in local memory.
```

```
===== Reduction Parameters ========

Red On Fastest Dim
3D Schedule
Outer Reduction: cross grid - blockIdx.z / split grid dim / unroll / factor 2
Iteration Domain: blockIdx.y /
Inner Reduction Domain: cross block - threadIdx.x / cross grid - blockIdx.x / split grid dim / split grid dimension /
Launch Parameters: BlockDim.x = 4, BlockDim.y = -1, BlockDim.z = -1, GridDim.x = 2, GridDim.y = -1, GridDim.z = 2, Smem Size = 0
Compile Parameters: index_type = NotSet, maxrregcount = 255, enable_magic_zero = 1, enable_ptxas_verbose = 0

====================================


%kernel {
T3_l[ iblockIdx.y15{i1}, iS60{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * i2 ), blockDim.x) ), 1) ), gridDim.x) )}, bblockIdx.z63{gridDim.z}, bS64{( ceilDiv(( ceilDiv(i3, 2) ), gridDim.z) )}, bUR62{2}, iblockIdx.x59{gridDim.x}, ithreadIdx.x56{blockDim.x}, iUS58{1} ] ca_pos( 2 )
   = Set( T0_g[ iS1{i1}, iS71{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * i2 ), blockDim.x) ), 1) ), gridDim.x) )}, bS74{gridDim.z}, bS75{( ceilDiv(( ceilDiv(i3, 2) ), gridDim.z) )}, bS73{2}, iS70{gridDim.x}, iS67{blockDim.x}, iS69{1} ], cache_op=Streaming )
T5_l[ iblockIdx.y32{i1}, rS41{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * i2 ), blockDim.x) ), 1) ), gridDim.x) )}rf, iblockIdx.z44{gridDim.z}, iS45{( ceilDiv(( ceilDiv(1, 2) ), gridDim.z) )}, iS43{2}, iblockIdx.x40{gridDim.x}rf, ithreadIdx.x37{blockDim.x}rf, rUS39{1}rf ] ca_pos( 1 ) produce_pos( 2 )
   = reduction( T3_l[ iblockIdx.y15{i1}, iS60{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * i2 ), blockDim.x) ), 1) ), gridDim.x) )}, bblockIdx.z63{gridDim.z}, bS64{( ceilDiv(( ceilDiv(i3, 2) ), gridDim.z) )}, bUR62{2}, iblockIdx.x59{gridDim.x}, ithreadIdx.x56{blockDim.x}, iUS58{1} ] ca_pos( 2 ), op = add, initial value = double(0), allreduce = false )
T1_l[ iblockIdx.y48{i1}, bblockIdx.z52{gridDim.z}, bS53{( ceilDiv(( ceilDiv(1, 2) ), gridDim.z) )}, bS51{2}, rblockIdx.x46{gridDim.x}, rthreadIdx.x47{blockDim.x} ] ca_pos( 1 ) produce_pos( 1 )
   = reduction( T5_l[ iblockIdx.y32{i1}, rS41{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * i2 ), blockDim.x) ), 1) ), gridDim.x) )}rf, iblockIdx.z44{gridDim.z}, iS45{( ceilDiv(( ceilDiv(1, 2) ), gridDim.z) )}, iS43{2}, iblockIdx.x40{gridDim.x}rf, ithreadIdx.x37{blockDim.x}rf, rUS39{1}rf ] ca_pos( 1 ) produce_pos( 2 ), op = add, initial value = double(0), allreduce = false )
d10 = reciprocal(double(40));
T4_l[ iblockIdx.y8{i1}, bblockIdx.z78{gridDim.z}, bS79{( ceilDiv(( ceilDiv(i3, 2) ), gridDim.z) )}, bS77{2} ] ca_pos( 1 ) produce_pos( 1 )
   = T1_l[ iblockIdx.y48{i1}, bblockIdx.z52{gridDim.z}, bS53{( ceilDiv(( ceilDiv(1, 2) ), gridDim.z) )}, bS51{2}, rblockIdx.x46{gridDim.x}, rthreadIdx.x47{blockDim.x} ] ca_pos( 1 ) produce_pos( 1 )
   * d10;
T2_g[ iblockIdx.y18{i1}, bblockIdx.z82{gridDim.z}, bS83{( ceilDiv(( ceilDiv(i3, 2) ), gridDim.z) )}, bUR81{2} ] ca_pos( 1 ) produce_pos( 1 )
   = Set( T4_l[ iblockIdx.y8{i1}, bblockIdx.z78{gridDim.z}, bS79{( ceilDiv(( ceilDiv(i3, 2) ), gridDim.z) )}, bS77{2} ] ca_pos( 1 ) produce_pos( 1 ), cache_op=Streaming )


T5_l[ iblockIdx.y32{i1}, rS41{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * i2 ), blockDim.x) ), 1) ), gridDim.x) )}rf, iblockIdx.z44{gridDim.z}, iS45{( ceilDiv(( ceilDiv(1, 2) ), gridDim.z) )}, iS43{2}, iblockIdx.x40{gridDim.x}rf, ithreadIdx.x37{blockDim.x}rf, rUS39{1}rf ] ca_pos( 1 ) produce_pos( 2 )
 root domain : (rS31{i0}rf, iblockIdx.y32{i1}, rS33{i2}rf, bS34{i3})
  Merge: rS31{i0}rf and rS33{i2}rf -> iS35{( i0 * i2 )}rf
  Split: iS35{( i0 * i2 )}rf by factor blockDim.x -> iS36{( ceilDiv(( i0 * i2 ), blockDim.x) )}rf, ithreadIdx.x37{blockDim.x}rf, start offset: 0, stop offset: 0
  Split: iS36{( ceilDiv(( i0 * i2 ), blockDim.x) )}rf by factor 1 -> iS38{( ceilDiv(( ceilDiv(( i0 * i2 ), blockDim.x) ), 1) )}rf, rUS39{1}rf, start offset: 0, stop offset: 0
  Outer split: iS38{( ceilDiv(( ceilDiv(( i0 * i2 ), blockDim.x) ), 1) )}rf by factor gridDim.x -> iblockIdx.x40{gridDim.x}rf, rS41{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * i2 ), blockDim.x) ), 1) ), gridDim.x) )}rf, start offset: 0, stop offset: 0
 rfactor domain : (iblockIdx.x40{gridDim.x}rf, rS41{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * i2 ), blockDim.x) ), 1) ), gridDim.x) )}rf, rUS39{1}rf, ithreadIdx.x37{blockDim.x}rf, iblockIdx.y32{i1}, bS34{i3})
 contiguity: t n n t t n
  Split: bS34{i3} by factor 2 -> iS42{( ceilDiv(1, 2) )}, iS43{2}, start offset: 0, stop offset: 0
  Outer split: iS42{( ceilDiv(1, 2) )} by factor gridDim.z -> iblockIdx.z44{gridDim.z}, iS45{( ceilDiv(( ceilDiv(1, 2) ), gridDim.z) )}, start offset: 0, stop offset: 0
 leaf domain : (iblockIdx.y32{i1}, rS41{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * i2 ), blockDim.x) ), 1) ), gridDim.x) )}rf, iblockIdx.z44{gridDim.z}, iS45{( ceilDiv(( ceilDiv(1, 2) ), gridDim.z) )}, iS43{2}, iblockIdx.x40{gridDim.x}rf, ithreadIdx.x37{blockDim.x}rf, rUS39{1}rf)
```

Repro here:
```
import torch
from nvfuser import FusionDefinition, DataType
def nvfuser_fusion_id12(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[-1, -1, -1, 1], contiguity=[True, True, True, None], dtype=DataType.Double, is_cpu=False)
    T1 = fd.ops.sum(T0, axes=[2, 0], keepdim=False, dtype=DataType.Null)
    S2 = fd.define_scalar(40.0000, dtype=DataType.Double)
    S3 = fd.ops.reciprocal(S2)
    T4 = fd.ops.mul(T1, S3)
    fd.add_output(T4)

with FusionDefinition() as fd:
    nvfuser_fusion_id12(fd)

inputs = [
    torch.randn((280,), dtype=torch.float64, device='cuda:0').as_strided((8, 7, 5, 1), (35, 5, 1, 1)),
]
fd.execute(inputs)
```

Interestingly, when we change the last dimension from broadcast to a normal iterative dimension, everything works fine.

### PR DESCRIPTION
**Pull request by jacobhinkle**
Fixes #1471

### CODE REVIEW

**Comment by jacobhinkle** [comment]
!build --diff

File: test/test_gpu3.cpp [hunk 1]
```diff
@@ -8694,6 +8694,45 @@ TEST_F(NVFuserTest, ChainProjectionToPersistentProducer) {
...
+  FusionExecutor fe;
+  fe.compileFusion(fusion, inputs, reduction_params->lparams);
+  auto cg_outputs = fe.runFusion(inputs, reduction_params->lparams);
+
+  // NOTE: here we manually compute a reference tensor. This is to avoid an
+  // error in getReductionSize() which finds the rfactor tensorview which has a
+  // partial sum over a dimension whose size is a block dim.
+  auto ref = at::sum(t0, {2, 0});
+  ASSERT_TRUE(at::allclose(ref, cg_outputs.at(0)));
+  //testValidate(fusion, cg_outputs, inputs, __LINE__, __FILE__);
```
Comment (jacobhinkle) [inline test/test_gpu3.cpp:8733]: This was surprising.
> C++ exception with description "inferred_extent.hasValue() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/validator_utils.h":228, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Couldn't figure out what the dimensions of a tensorview is in evaluation for validation. rS39{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * i2 ), blockDim.x) ), 1)), gridDim.x) )}rf in T4_l[ iblockIdx.z31{gridDim.z}, iS32{( ceilDiv(( ceilDiv(i1, 2) ), gridDim.z) )}, rS39{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * i2 ), blockDim.x) ), 1) ), gridDim.x) )}rf, iS30{2}, bblockIdx.y28{1}, iblockIdx.x38{gridDim.x}rf, ithreadIdx.x35{blockDim.x}rf, rUS37{1}rf ] ca_pos( 2 ) produce_pos( 3 )                                                                           
Exception raised from getReductionSize at /opt/pytorch/nvfuser/csrc/validator_utils.h:228 (most recent call first):

Comment (jacobhinkle) [reply test/test_gpu3.cpp:8733]: The problematic ID is `rS39{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * i2 ), blockDim.x) ), 1) ), gridDim.x) )}rf`.

**Comment by jacobhinkle** [comment]
diff --bench

**Comment by jacobhinkle** [comment]
!build --diff

**Comment by jacobhinkle** [comment]
!build --diff

File: test/test_gpu3.cpp (hunk 1 above)
Comment (jjsjann123) [reply test/test_gpu3.cpp]: I'm seeing the validation is still commented out, does that mean the example still won't run?

Comment (jacobhinkle) [reply test/test_gpu3.cpp]: It runs, it's just that the validation code cannot determine what tolerance to use. That's because the rfactored sum has a sum axis with an extent that's a function of a grid dim, and the evaluator code doesn't bind launch params when evaluating sizes. I tried passing my own tolerances but I think it still tried to evaluate those extents and hit the same error. I can remove the comment and leave the current check as it's sufficient, and default allclose tols work here.

Comment (jacobhinkle) [reply test/test_gpu3.cpp]: We could probably just modify testValidate to accept an optional LaunchParams which it will bind to its ExprEvaluator if given. I'll give that a shot later and if it's a small change include it. Otherwise can split into another PR.

**Review by jjsjann123 — APPROVED** [review]
Ha thanks for explaining this. Sounds like a good plan to me.

Stamping to unblock merging.

File: test/test_gpu3.cpp (hunk 1 above)
Comment (jacobhinkle) [reply test/test_gpu3.cpp]: Actually just adding the `lparams` to the `testValidate` call gets us further, but we still hit https://github.com/NVIDIA/Fuser/blob/main/csrc/ir/nodes.cpp#L1455-L1457. Instead, I'm now just copying the un-scheduled Fusion and using that at validation.

**Comment by naoyam** [comment]
It's also strange that the reduction scheduler tries to unroll and parallelize a broadcast domain. That also seems like something we should fix.
