### PR TITLE
fixing fusion segmenter dropping allocation domain

### LINKED ISSUE #1021: (maybe) indexing issue gives wrong result
cpp example created below trying to leverage the allocation domain.
```
TEST_F(NVFuserTest, AllocationDomainContiguity) {
  std::unique_ptr<Fusion> fusion_ptr = std::make_unique<Fusion>();
  Fusion* fusion = fusion_ptr.get();
  FusionGuard fg(fusion);

  auto tv0 = TensorViewBuilder()
                 .ndims(2)
                 .shape({-1, -1})
                 .build();

  std::vector<IterDomain*> alloc_domain = {tv0->axis(1), tv0->axis(0)};
  tv0->setAllocationDomain(alloc_domain, {false, true});
  fusion->addInput(tv0);

  auto s0 = IrBuilder::create<Val>(5, DataType::Float);
  auto tv1 = add(tv0, s0);
  fusion->addOutput(tv1);

  fusion->printMath();
  fusion->printTransforms();
  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor t0 = at::randn({8, 8}, options).as_strided({4, 8}, {1, 8});

  FusionExecutorCache fec(std::move(fusion_ptr));
  auto outputs = fec.runFusionWithInputs({t0});
  auto t1 = t0.add(5.0);
  std::cout << "input: " << t0 << std::endl;

  std::cout << "out : " << outputs[0] << std::endl;
  std::cout << "ref: " << t1 << std::endl;

  testValidate(fusion, outputs, {t0}, {t1}, __LINE__, __FILE__);
}
```

I'm getting wrong results from nvfuser.

```
Inputs:
  T0_g[ iS0{i0}, iS1{i1} ], float
Outputs:
  T1_g[ iS2{i0}, iS3{i1} ], float

%kernel_math {
T1_g[ iS2{i0}, iS3{i1} ]
   = T0_g[ iS0{i0}, iS1{i1} ]
   + float(5);
}

T0_g[ iS0{i0}, iS1{i1} ]
 root domain : (iS0{i0}, iS1{i1})
 allocation domain : (iS1{i1}, iS0{i0})
 contiguity: f t
 leaf domain : (iS0{i0}, iS1{i1})
T1_g[ iS2{i0}, iS3{i1} ]
 root domain : (iS2{i0}, iS3{i1})
 contiguity: t t
 leaf domain : (iS2{i0}, iS3{i1})

======= Codegen output for kernel: kernel1 =======

__global__ void kernel1(Tensor<float, 2, 2> T0, Tensor<float, 2, 2> T1) {
  nvfuser_index_t i0;
  i0 = ((nvfuser_index_t)threadIdx.x) + (128LL * ((nvfuser_index_t)blockIdx.x));
  if ((i0 < (T0.logical_size[0LL] * T0.logical_size[1LL]))) {
    float T2[1];
    T2[0] = 0;
    T2[0]
       = T0[((T0.alloc_stride[0LL] * (i0 / T0.logical_size[1LL])) + (i0 % T0.logical_size[1LL]))];
    float T3[1];
    T3[0]
      = T2[0]
      + 5.000000000e+00f;
    T1[i0]
       = T3[0];
  }
}

======================================

Arguments for kernel1:
Inputs:
  Tensor(sizes=[4, 8], stride=[1, 8], float, cuda:0)
Outputs:
  Float [4, 8] (strides = [8, 1], address = 0x7f2c8b200200)
Intermediate global buffers:
input: -0.9247 -1.0745 -0.1271  0.0697 -0.5965  0.0141 -0.1836 -0.5499
-0.4253 -0.3631  1.2169 -0.0074 -0.3283  0.4532  0.3824 -0.3231
-2.6438 -1.6711  1.4353  1.8969 -0.9086  1.6349  0.3918 -0.5469
 0.1452  2.2655  1.0605  0.6878 -0.8059  0.7124 -0.0830  0.9049
[ CUDAFloatType{4,8} ]
out :  4.0753  4.5747  2.3562  5.1452  4.8791  4.4203  4.3771  4.6716
 4.5747  2.3562  5.1452  4.8791  4.4203  4.3771  4.6716  3.9255
 2.3562  5.1452  4.8791  4.4203  4.3771  4.6716  3.9255  4.6369
 5.1452  4.8791  4.4203  4.3771  4.6716  3.9255  4.6369  3.3289
[ CUDAFloatType{4,8} ]
ref:  4.0753  3.9255  4.8729  5.0697  4.4035  5.0141  4.8164  4.4501
 4.5747  4.6369  6.2169  4.9926  4.6717  5.4532  5.3824  4.6769
 2.3562  3.3289  6.4353  6.8969  4.0914  6.6349  5.3918  4.4531
 5.1452  7.2655  6.0605  5.6878  4.1941  5.7124  4.9170  5.9049
[ CUDAFloatType{4,8} ]
```

Look here we have `at::Tensor t0 = at::randn(...).as_strided( /*size=*/ {4, 8}, /*stride=*/ {1, 8});`
input T0 has a permuted allocation domain. its outer dimension is non-contiguous.

So per this input here. `Tensor(sizes=[4, 8], stride=[1, 8], float, cuda:0)`
```
    T2[0]
       = T0[((T0.alloc_stride[0LL] * (i0 / T0.logical_size[1LL])) + (i0 % T0.logical_size[1LL]))];
```

There seems to be an inconsistency here.
alloc_stride[0] should be `8` instead of `1`. But looks like we are not compensating for that when we hook up inputs.

### PR DESCRIPTION
**Pull request by jjsjann123**
Fixes #1021

### CODE REVIEW

**Review by jacobhinkle — COMMENTED** [review]
Good idea. It seems like this implementation will work for stride order, but not if there are Exprs between alloc and rfactor. In that case we would need a replay.

**Comment by jjsjann123** [comment]
> Good idea. It seems like this implementation will work for stride order, but not if there are Exprs between alloc and rfactor. In that case we would need a replay.

Good point.
I thought replay can only be applied towards either a producer or consumer. Do we have something that's like
`new_alloc = replayAs(old_alloc, old_rfactor, new_root)`

**Comment by jacobhinkle** [comment]
> > Good idea. It seems like this implementation will work for stride order, but not if there are Exprs between alloc and rfactor. In that case we would need a replay.
> 
> Good point.
> I thought replay can only be applied towards either a producer or consumer. Do we have something that's like
> `new_alloc = replayAs(old_alloc, old_rfactor, new_root)`

I am not 100% sure but I was thinking BestEffortReplay could do this.

**Comment by xwang233** [comment]
!build

**Comment by xwang233** [comment]
!build

**Comment by xwang233** [comment]
!build

File: csrc/fusion_segmenter.cpp [hunk 1]
```diff
@@ -1489,6 +1489,32 @@ void convertInputRfactorsToRoots(Fusion* fusion) {
     NVF_ERROR(new_root_domain.size() == tv->domain()->contiguity().size());
     auto new_td = IrBuilder::create<TensorDomain>(
         new_root_domain, tv->domain()->contiguity());
+
```
Comment (naoyam) [inline csrc/fusion_segmenter.cpp:1492]: I wonder if we really need this function at all. Some code may be naively assuming fusion inputs do not have rfactor domains, but I don't think that's necessary. Maybe just try disabling this function entirely?

**Comment by naoyam** [comment]
> > > Good idea. It seems like this implementation will work for stride order, but not if there are Exprs between alloc and rfactor. In that case we would need a replay.
> > 
> > 
> > Good point.
> > I thought replay can only be applied towards either a producer or consumer. Do we have something that's like
> > `new_alloc = replayAs(old_alloc, old_rfactor, new_root)`
> 
> I am not 100% sure but I was thinking BestEffortReplay could do this.

That would be `ReplayTransformations`, but again do we really need this?

File: csrc/fusion_segmenter.cpp (hunk 1 above)
Comment (jjsjann123) [reply csrc/fusion_segmenter.cpp:1492]: I guess I can try removing this one and see if the world would just crash and burn...

Comment (naoyam) [reply csrc/fusion_segmenter.cpp:1492]: Thanks for the cleanup! 😉

**Comment by jjsjann123** [comment]
CI is all green. what's the parse job failure that was reported?!?! @xwang233

**Comment by xwang233** [comment]
That's from an old run (with the same commit), since Github doesn't allow deleting commit status. You may ignore that. Sorry for the confusions.

**Comment by jjsjann123** [comment]
!build

**Comment by jjsjann123** [comment]
errr. nuking it didn't work. 

I'm seeing failures on:
`NVFuserTest.ResizePadToBroadcastDynamic_CUDA`
`NVFuserTest.FusionReshapeReductionShmoo_CUDA`

and the second test failure actually killed the node. :angry:

**Comment by jjsjann123** [comment]
lol, the error message gives me headache.
Looks like it failed to infer launch params.

https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/71022350/raw
```
Exception in thread pool task: val.hasValue() INTERNAL ASSERT FAILED at
...
Exception raised from computeLaunchParams at /opt/pytorch/nvfuser/csrc/executor.cpp:1113 (most recent call first)
```

**Comment by jjsjann123** [comment]
Here's the failing test fusion printMath.

```
Inputs:
  T0_g[ iS0{i0}, iS1{i2}, iS2{i3}, iS3{i4}, iS4{i5} ], float
  T1_g[ iS5{i6}, iS6{i7}, iS7{i8}, iS8{i9}, iS9{i10} ], float
  i11, int64_t
  i12, int64_t
  i13, int64_t
  i14, int64_t
  i15, int64_t
  i16, int64_t
  i17, int64_t
  i18, int64_t
Outputs:
  T3_g[ iS19{i6}, iS20{i7}, iS21{i8}, iS22{i9}, iS23{i10} ], float

%kernel_math {
i20 = (nvfuser_index_t)(i17);
i22 = (nvfuser_index_t)(i18);
i24 = (nvfuser_index_t)(i15);
i26 = (nvfuser_index_t)(i16);
i28 = (nvfuser_index_t)(i13);
i30 = (nvfuser_index_t)(i14);
i32 = (nvfuser_index_t)(i11);
i34 = (nvfuser_index_t)(i12);
T2_g[ iS10{i0}, bS24{( ( i2 + ( (nvfuser_index_t)(i17) ) ) + ( (nvfuser_index_t)(i18) ) )}rf, iS25{( ( i3 + ( (nvfuser_index_t)(i15) ) ) + ( (nvfuser_index_t)(i16) ) )}rf, bS26{( ( i4 + ( (nvfuser_index_t)(i13) ) ) + ( (nvfuser_index_t)(i14) ) )}rf, iS27{( ( i5 + ( (nvfuser_index_t)(i11) ) ) + ( (nvfuser_index_t)(i12) ) )}rf ]
   = pad( T0_g[ iS0{i0}, iS1{i2}, iS2{i3}, iS3{i4}, iS4{i5} ], {0, 0, i20, i22, i24, i26, i28, i30, i32, i34} )
T3_g[ iS19{i6}, iS20{i7}, iS21{i8}, iS22{i9}, iS23{i10} ]
   = T1_g[ iS5{i6}, iS6{i7}, iS7{i8}, iS8{i9}, iS9{i10} ]
   * T2_g[ iS10{i0}, bS24{( ( i2 + ( (nvfuser_index_t)(i17) ) ) + ( (nvfuser_index_t)(i18) ) )}rf, iS25{( ( i3 + ( (nvfuser_index_t)(i15) ) ) + ( (nvfuser_index_t)(i16) ) )}rf, bS26{( ( i4 + ( (nvfuser_index_t)(i13) ) ) + ( (nvfuser_index_t)(i14) ) )}rf, iS27{( ( i5 + ( (nvfuser_index_t)(i11) ) ) + ( (nvfuser_index_t)(i12) ) )}rf ];
}
```

we are segmenting the pointwise op after the pad into a separate kernel.
This is the output when we are keeping the rfactor on input (T2_g).
```
(gdb) print fusion->printMath(true)
Inputs:
  T1_g[ iS101{( ceilDiv(( ceilDiv(( ceilDiv(( i6 * ( i7 * ( i8 * ( i9 * i10 ) ) ) ), 128) ), 1) ), 1) )}, iS102{1}, iS100{1}, iS98{128} ], float
  T2_g[ iS81{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * ( ( ( i2 + ( (nvfuser_index_t)(i17) ) ) + ( (nvfuser_index_t)(i18) ) ) * ( ( ( i3 + ( (nvfuser_index_t)(i15) ) ) + ( (nvfuser_index_t)(i16) ) ) * ( ( ( i4 + ( (nvfuser_index_t)(i13) ) ) + ( (nvfuser_index_t)(i14) ) ) * ( ( i5 + ( (nvfuser_index_t)(i11) ) ) + ( (nvfuser_index_t)(i12) ) ) ) ) ) ), 128) ), 1) ), 1) )}, iS82{1}, iS80{1}, iS78{128} ], float
Outputs:
  T3_g[ iblockIdx.x51{( ceilDiv(( ceilDiv(( ceilDiv(( i6 * ( i7 * ( i8 * ( i9 * i10 ) ) ) ), 128) ), 1) ), 1) )}, iUS52{1}, iS50{1}, ithreadIdx.x48{128} ] ca_pos( 2 ) produce_pos( 4 ), float

%kernel_math {
T4_l[ iblockIdx.x91{( ceilDiv(( ceilDiv(( ceilDiv(( i6 * ( i7 * ( i8 * ( i9 * i10 ) ) ) ), 128) ), 1) ), 1) )}, iUS92{1}, iS90{1}, ithreadIdx.x88{128} ] ca_pos( 2 )
   = Set( T1_g[ iS101{( ceilDiv(( ceilDiv(( ceilDiv(( i6 * ( i7 * ( i8 * ( i9 * i10 ) ) ) ), 128) ), 1) ), 1) )}, iS102{1}, iS100{1}, iS98{128} ], cache_op=Streaming )
T5_l[ iblockIdx.x71{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * ( ( ( i2 + ( (nvfuser_index_t)(i17) ) ) + ( (nvfuser_index_t)(i18) ) ) * ( ( ( i3 + ( (nvfuser_index_t)(i15) ) ) + ( (nvfuser_index_t)(i16) ) ) * ( ( ( i4 + ( (nvfuser_index_t)(i13) ) ) + ( (nvfuser_index_t)(i14) ) ) * ( ( i5 + ( (nvfuser_index_t)(i11) ) ) + ( (nvfuser_index_t)(i12) ) ) ) ) ) ), 128) ), 1) ), 1) )}, iUS72{1}, iS70{1}, ithreadIdx.x68{128} ] ca_pos( 2 )
   = Set( T2_g[ iS81{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * ( ( ( i2 + ( (nvfuser_index_t)(i17) ) ) + ( (nvfuser_index_t)(i18) ) ) * ( ( ( i3 + ( (nvfuser_index_t)(i15) ) ) + ( (nvfuser_index_t)(i16) ) ) * ( ( ( i4 + ( (nvfuser_index_t)(i13) ) ) + ( (nvfuser_index_t)(i14) ) ) * ( ( i5 + ( (nvfuser_index_t)(i11) ) ) + ( (nvfuser_index_t)(i12) ) ) ) ) ) ), 128) ), 1) ), 1) )}, iS82{1}, iS80{1}, iS78{128} ], cache_op=AllLevels )
T6_l[ iblockIdx.x61{( ceilDiv(( ceilDiv(( ceilDiv(( i6 * ( i7 * ( i8 * ( i9 * i10 ) ) ) ), 128) ), 1) ), 1) )}, iUS62{1}, iS60{1}, ithreadIdx.x58{128} ] ca_pos( 4 ) produce_pos( 2 )
   = T4_l[ iblockIdx.x91{( ceilDiv(( ceilDiv(( ceilDiv(( i6 * ( i7 * ( i8 * ( i9 * i10 ) ) ) ), 128) ), 1) ), 1) )}, iUS92{1}, iS90{1}, ithreadIdx.x88{128} ] ca_pos( 2 )
   * T5_l[ iblockIdx.x71{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * ( ( ( i2 + ( (nvfuser_index_t)(i17) ) ) + ( (nvfuser_index_t)(i18) ) ) * ( ( ( i3 + ( (nvfuser_index_t)(i15) ) ) + ( (nvfuser_index_t)(i16) ) ) * ( ( ( i4 + ( (nvfuser_index_t)(i13) ) ) + ( (nvfuser_index_t)(i14) ) ) * ( ( i5 + ( (nvfuser_index_t)(i11) ) ) + ( (nvfuser_index_t)(i12) ) ) ) ) ) ), 128) ), 1) ), 1) )}, iUS72{1}, iS70{1}, ithreadIdx.x68{128} ] ca_pos( 2 );
T3_g[ iblockIdx.x51{( ceilDiv(( ceilDiv(( ceilDiv(( i6 * ( i7 * ( i8 * ( i9 * i10 ) ) ) ), 128) ), 1) ), 1) )}, iUS52{1}, iS50{1}, ithreadIdx.x48{128} ] ca_pos( 2 ) produce_pos( 4 )
   = Set( T6_l[ iblockIdx.x61{( ceilDiv(( ceilDiv(( ceilDiv(( i6 * ( i7 * ( i8 * ( i9 * i10 ) ) ) ), 128) ), 1) ), 1) )}, iUS62{1}, iS60{1}, ithreadIdx.x58{128} ] ca_pos( 4 ) produce_pos( 2 ), cache_op=Streaming )
}
```
And this is what we have when we clean up the rfactor domain on inputs.
```
(gdb) print fusion->printMath(true)
Inputs:
  T1_g[ iS115{( ceilDiv(( ceilDiv(( ceilDiv(( i6 * ( i7 * ( i8 * ( i9 * i10 ) ) ) ), 128) ), 1) ), 1) )}, iS116{1}, iS114{1}, iS112{128} ], float
  T2_g[ iS95{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * ( i480 * ( i481 * ( i482 * i483 ) ) ) ), 128) ), 1) ), 1) )}, iS96{1}, iS94{1}, iS92{128} ], float
Outputs:
  T3_g[ iblockIdx.x65{( ceilDiv(( ceilDiv(( ceilDiv(( i6 * ( i7 * ( i8 * ( i9 * i10 ) ) ) ), 128) ), 1) ), 1) )}, iUS66{1}, iS64{1}, ithreadIdx.x62{128} ] ca_pos( 2 ) produce_pos( 4 ), float

%kernel_math {
T4_l[ iblockIdx.x105{( ceilDiv(( ceilDiv(( ceilDiv(( i6 * ( i7 * ( i8 * ( i9 * i10 ) ) ) ), 128) ), 1) ), 1) )}, iUS106{1}, iS104{1}, ithreadIdx.x102{128} ] ca_pos( 2 )
   = Set( T1_g[ iS115{( ceilDiv(( ceilDiv(( ceilDiv(( i6 * ( i7 * ( i8 * ( i9 * i10 ) ) ) ), 128) ), 1) ), 1) )}, iS116{1}, iS114{1}, iS112{128} ], cache_op=Streaming )
T5_l[ iblockIdx.x85{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * ( i480 * ( i481 * ( i482 * i483 ) ) ) ), 128) ), 1) ), 1) )}, iUS86{1}, iS84{1}, ithreadIdx.x82{128} ] ca_pos( 2 )
   = Set( T2_g[ iS95{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * ( i480 * ( i481 * ( i482 * i483 ) ) ) ), 128) ), 1) ), 1) )}, iS96{1}, iS94{1}, iS92{128} ], cache_op=AllLevels )
T6_l[ iblockIdx.x75{( ceilDiv(( ceilDiv(( ceilDiv(( i6 * ( i7 * ( i8 * ( i9 * i10 ) ) ) ), 128) ), 1) ), 1) )}, iUS76{1}, iS74{1}, ithreadIdx.x72{128} ] ca_pos( 4 ) produce_pos( 2 )
   = T4_l[ iblockIdx.x105{( ceilDiv(( ceilDiv(( ceilDiv(( i6 * ( i7 * ( i8 * ( i9 * i10 ) ) ) ), 128) ), 1) ), 1) )}, iUS106{1}, iS104{1}, ithreadIdx.x102{128} ] ca_pos( 2 )
   * T5_l[ iblockIdx.x85{( ceilDiv(( ceilDiv(( ceilDiv(( i0 * ( i480 * ( i481 * ( i482 * i483 ) ) ) ), 128) ), 1) ), 1) )}, iUS86{1}, iS84{1}, ithreadIdx.x82{128} ] ca_pos( 2 );
T3_g[ iblockIdx.x65{( ceilDiv(( ceilDiv(( ceilDiv(( i6 * ( i7 * ( i8 * ( i9 * i10 ) ) ) ), 128) ), 1) ), 1) )}, iUS66{1}, iS64{1}, ithreadIdx.x62{128} ] ca_pos( 2 ) produce_pos( 4 )
   = Set( T6_l[ iblockIdx.x75{( ceilDiv(( ceilDiv(( ceilDiv(( i6 * ( i7 * ( i8 * ( i9 * i10 ) ) ) ), 128) ), 1) ), 1) )}, iUS76{1}, iS74{1}, ithreadIdx.x72{128} ] ca_pos( 4 ) produce_pos( 2 ), cache_op=Streaming )
}
```

So I compared the before and after on that kernel. Looks like with the rfactor thing in place, the input tensor view seems to be carrying something coming from the previous pad operation?!

**Comment by jjsjann123** [comment]
I put a separate issue to track the suggested removal #1040

For this PR. I'll revert that and refactor to use the replay suggested by Jacob/Naoya.

**Comment by jjsjann123** [comment]
!build

**Comment by jjsjann123** [comment]
!build

**Comment by jacobhinkle** [comment]
> Looks like with the rfactor thing in place, the input tensor view seems to be carrying something coming from the previous pad operation?!

This is a little bit tricky. See #840. That carryover scalar comes from concretization where we currently are modifying extents downstream of dynamic reshapes. Note also #912 which would preserve extents during concretization instead but which also hits this issue on the first segment instead of the second one; that one is relatively easy to fix by just including the output sizes in the `inputs()` to `ViewOp`.

For #840 I need to fix the traversal before merging since currently it includes scalars that are already included as extents of input TVs. Once that is done these tests should pass again.

**Comment by jjsjann123** [comment]
IIUC, we can just wait until your fixes are in and re-evaluate nuking the function.

Meanwhile, does this PR serve as a reasonable workaround at this time so we can move forward with our allocation domain plumbing on inputs?

**Comment by jacobhinkle** [comment]
> IIUC, we can just wait until your fixes are in and re-evaluate nuking the function.
> 
> Meanwhile, does this PR serve as a reasonable workaround at this time so we can move forward with our allocation domain plumbing on inputs?

Yes. I think so. We can address #1040 once #840 goes through, or in conjunction. Thanks!

**Comment by naoyam** [comment]
@jjsjann123 @jacobhinkle Another potential error would be misusing root domains in place of rfactor domains. In early days we tended to think only about root domains even when rfactor should be used. There may be still some code for fusion/segment inputs as they are (currently) guaranteed to not have rfactor domains.

File: csrc/fusion_segmenter.cpp [hunk 2]
```diff
@@ -1489,6 +1490,23 @@ void convertInputRfactorsToRoots(Fusion* fusion) {
...
+    if (tv->domain()->hasAllocation()) {
+      // we need to replay the new root domain following the old rfactor domain
```
Comment (naoyam) [inline csrc/fusion_segmenter.cpp:1495]: Could you add tests that actually require this replay? The current one only reorders the domains.

Comment (jjsjann123) [reply csrc/fusion_segmenter.cpp:1495]: Turns out testing this is tricky, since we don't have `convertInputRfactorsToRoots` exposed.

So we only hit this function when we go through automatic scheduler, which triggers segmentation. But automatic scheduler do not support complex transforms on allocation domain.

The reason is that, `setAllocationDomain` has a check that requires allocation domain "consistent" with leaf domain (read `nvfuser::ir_utils::validateDomainEquivalence`). So in order to set a merge or something like that on the allocation domain, I need to apply the same transformation on leaf.
But we are not supposed to hand a `transformed` fusion to automatic scheduler.

Here's the issue when I try to run this example.
```
  auto tv0 = TensorViewBuilder().ndims(3).shape({-1, -1, -1}).build();
  fusion->addInput(tv0);
  auto s0 = IrBuilder::create<Val>(5, DataType::Float);
  auto tv1 = add(tv0, s0); 
  fusion->addOutput(tv1);

  tv0->merge(0, 1);

  std::vector<IterDomain*> alloc_domain = {tv0->axis(2)};
  IterDomain* merged_id = 
      IterDomainBuilder(fusion->zeroVal(), mul(tv0->axis(0)->extent(), tv0->axis(1)->extent()))
          .parallel_type(tv0->axis(0)->getParallelType())
          .iter_type(tv0->axis(0)->getIterType())
          .build();
  IrBuilder::create<Merge>(tv0->axis(0)->container(), merged_id, tv0->axis(0), tv0->axis(1));
  alloc_domain.push_back(merged_id);

  tv0->setAllocationDomain(alloc_domain, {false, true});
```

```
C++ exception with description "derived_domain_ == frontier_ INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/ir/utils.cpp":877, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Invalid derived domain. Initial domain: iS2{i2}, iS3{( i0 * i1 )}. Derived domain: iS0{i0}, iS1{i1}, iS2{i2}
```

If we really want to test this code path with transformation, I guess we can expose this function directly. But that feels a bit too much. tagging @naoyam for a second opinion.

Comment (naoyam) [reply csrc/fusion_segmenter.cpp:1495]: Is there a typo here?: `std::vector<IterDomain*> alloc_domain = {tv0->axis(2)};`. Since `tv0` is merged to a 2D tensor, `tv0->axis(2)` should not work, right?

Comment (jjsjann123) [reply csrc/fusion_segmenter.cpp:1495]: sorry I copied the wrong code.... I was trying to manually schedule it after running into the error.
Then I realized that manual scheduling won't hit the same code path, unless I expose the function.

Comment (jjsjann123) [reply csrc/fusion_segmenter.cpp:1495]: If you look at this
```
  std::vector<IterDomain*> alloc_domain = {tv0->axis(2)};
  IterDomain* merged_id = 
      IterDomainBuilder(fusion->zeroVal(), mul(tv0->axis(0)->extent(), tv0->axis(1)->extent()))
          .parallel_type(tv0->axis(0)->getParallelType())
          .iter_type(tv0->axis(0)->getIterType())
          .build();
  IrBuilder::create<Merge>(tv0->axis(0)->container(), merged_id, tv0->axis(0), tv0->axis(1));
  alloc_domain.push_back(merged_id);
```

You can see that I was manually merging the two iterdomain.

Comment (naoyam) [reply csrc/fusion_segmenter.cpp:1495]: I'm not entirely sure what you're trying to do here, but the error is because of the manual merge, which doesn't update the leaf domain. The check in `setAllocationDomain` is to make sure the allocation domain sits between the root and leaf domains, and now the code is trying to set an allocation domain that's outside of the path.

Conceptually, this should be completely fine since the new allocation domain is equivalent to the leaf domain. However, I don't think the current indexing works with that since it basically assumes the allocation domain consists of IterDomains that are ascendants of leaf IterDomains. Fundamentally, it should be possible to traverse from leaf IterDomains to whatever allocation domains, but that's not how it works at this moment.

For this PR, can we just set up a tensor with an allocation domain that sits between root and rfactor domains? Isn't there a test doing that already?

Comment (jjsjann123) [reply csrc/fusion_segmenter.cpp:1495]: both my attempts at getting the cpp test failed... got into new codegen issue. Opened #1047 #1048 to track those.

Comment (naoyam) [reply csrc/fusion_segmenter.cpp:1495]: 😅

Comment (naoyam) [reply csrc/fusion_segmenter.cpp:1495]: Thanks for trying it out. Looks like there are still many things we need to do in the  scheduler, as expected. 

For the meantime, please add an assertion that the allocation domain is just an reordered rfactor domain. Or we could expose this function as public so that we could test it without going through the scheduler/segmenter. Either seems fine to me.

Comment (jjsjann123) [reply csrc/fusion_segmenter.cpp:1495]: I'll add an assertion for now. since that's easier to remove later when we try to fix other utils in the scheduler.

**Comment by jjsjann123** [comment]
rolled everything back to the original commit without the replay refactor.
:cry:

**Comment by jjsjann123** [comment]
!build

**Comment by jjsjann123** [comment]
failing CI is irrelevant and patched here: https://github.com/NVIDIA/Fuser/pull/1058

**Comment by jjsjann123** [comment]
!build

**Review by naoyam — APPROVED** [review]
LGTM, but why there're lots of diff changes? False alarms?

**Comment by jjsjann123** [comment]
> LGTM, but why there're lots of diff changes? False alarms?

hmmm. I'm surprised that code changes here causes code diff... I'll try to take a look at that before merging this one.

**Comment by jjsjann123** [comment]
```
00:05:13 FAILED: CMakeFiles/nvfuser_tests.dir/test/test_gpu_fused_reduction.cpp.o 
00:05:13 /usr/bin/c++ -DUSE_C10D_GLOO -DUSE_C10D_NCCL -DUSE_DISTRIBUTED -DUSE_GTEST -DUSE_RPC -DUSE_TENSORPIPE -I/opt/pytorch/nvfuser/cmake/../third_party/benchmark/include -I/opt/pytorch/nvfuser -I/opt/pytorch/nvfuser/csrc -I/opt/pytorch/nvfuser/lib/dynamic_type/src -I/opt/pytorch/nvfuser/third_party/flatbuffers/include -isystem /opt/pytorch/nvfuser/cmake/../third_party/googletest/googlemock/include -isystem /opt/pytorch/nvfuser/cmake/../third_party/googletest/googletest/include -isystem /opt/pytorch/nvfuser/cmake/../third_party/flatbuffers/include -isystem /opt/pytorch/nvfuser/third_party/googletest/googletest/include -isystem /opt/pytorch/nvfuser/third_party/googletest/googletest -isystem /opt/pytorch/nvfuser/third_party/googletest/googlemock/include -isystem /opt/pytorch/nvfuser/third_party/googletest/googlemock -isystem /usr/local/lib/python3.10/site-packages/torch/include -isystem /usr/local/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -isystem /usr/local/cuda/include -Wno-psabi -D_GLIBCXX_USE_CXX11_ABI=0 -O3 -DNDEBUG -Wall -Wno-unused-function -D_GLIBCXX_USE_CXX11_ABI=0 -Werror -MD -MT CMakeFiles/nvfuser_tests.dir/test/test_gpu_fused_reduction.cpp.o -MF CMakeFiles/nvfuser_tests.dir/test/test_gpu_fused_reduction.cpp.o.d -o CMakeFiles/nvfuser_tests.dir/test/test_gpu_fused_reduction.cpp.o -c /opt/pytorch/nvfuser/test/test_gpu_fused_reduction.cpp
00:05:13 c++: fatal error: Killed signal terminated program cc1plus
```

OOM on those CI machines?

I'm also seeing some diff coming from here `https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/71309358` which the CI seems to be unable to find the diff file?!

cc'ing @xwang233

**Comment by xwang233** [comment]
>00:05:24 Using 256 jobs for compilation

Probably the build concurrency was too high. I've added a limit on the concurrency. Feel free to restart a build.

**Comment by zasdfgbnm** [comment]
> > 00:05:24 Using 256 jobs for compilation
> 
> Probably the build concurrency was too high. I've added a limit on the concurrency. Feel free to restart a build.

Should we increase this value?
https://github.com/NVIDIA/Fuser/blob/ecc912382269872ea00960dad74d5a05438be6c5/setup.py#L318

**Comment by jjsjann123** [comment]
I'm gonna ignore the issue then since it feels low risk for this PR to impact generated code.
Merging as-is
