### PR TITLE
preserving allocation domain transform on aliased output

### LINKED ISSUE #3957: Stride mismatch error with correct contiguity info
When running the following code snippet I get a stride mismatch error. The error message says that the contiguity is `[t, t]` even though it's specified in the FusionDefinition to be `[False, True]`:
```py
RuntimeError: Stride mismatch with contiguity info.  allocation domain: iS14{2}, iS15{2}: sizes: [2, 2]: strides: [3, 1]; contiguity: t, t; dim: 0; expected stride: 2; actual stride: 3
Exception raised from validateAllocationSizesAndStrides at /home/iyashchuk/dev/Fuser/csrc/tensor_metadata.cpp:262
```
```py
# torch version: 2.7.0a0+git1335882
# cuda version: 12.8
# nvfuser version: 0.2.25+git6b0b17e
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id0(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[2, 2], contiguity=[False, True], dtype=DataType.Float, is_cpu=False, stride_order=[1, 0])
    S1 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T2 = fd.ops.gt(T0, S1)
    S3 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T4 = fd.ops.where(T2, T0, S3)
    T5 = fd.ops.cast(T4, dtype=DataType.Float)
    T6 = fd.ops.set(T5)
    fd.add_output(T6, T0)
    fd.add_output(T6)

with FusionDefinition() as fd:
    nvfuser_fusion_id0(fd)

inputs = [
    torch.randn(5, dtype=torch.float32, device='cuda:0').as_strided((2, 2), (3, 1)),
]
fd.execute(inputs)
```

### PR DESCRIPTION
**Pull request by jjsjann123**
Fixes #3957 

The issue was that when we specify output alias, we need to update the (allocation domain and contiguity) of the alias to be identical to the source.

### CODE REVIEW

**Comment by jjsjann123** [comment]
!test

File: csrc/ir/utils.cpp [hunk 1]
```diff
@@ -38,7 +38,9 @@ bool isSimpleTVSet(Expr* expr) {
 
   return ldst->opType() == LoadStoreOpType::Set &&
       // The hasRoot() check is to prevent picking up Set.Permute ops here
-      !out_tv->hasRoot();
+      !out_tv->hasRoot() &&
+      // The hasAllocation() check is to prevent picking up restriding ops
+      !out_tv->hasAllocation();
```
Comment (jjsjann123) [inline csrc/ir/utils.cpp:43]: This is for `remove_bcast_squeeze`, where we are treating `isSimpleTVSet` as a mere copy.

Comment (jjsjann123) [reply csrc/ir/utils.cpp:43]: without this, that optimization pass would alter output without considering the impact on `contiguity` and `allocation domain` change when changing output.

File: csrc/fusion.cpp [hunk 2]
```diff
@@ -785,6 +786,12 @@ void Fusion::aliasOutputToInput(
     output = set(output);
   }
 
+  // replays the allocation domain and contiguity of input on output
+  NVF_CHECK(output->isA<TensorView>() && input->isA<TensorView>(),
+            "aliasing output to input is only supported for TensorView");
+  auto new_domain = TransformReplay::selfAllocationReplay(output->as<TensorView>()->domain(), input->as<TensorView>()->domain());
+  output->as<TensorView>()->setAllocationDomain(new_domain->allocation(), new_domain->contiguity());
```
Comment (jjsjann123) [inline csrc/fusion.cpp:793]: when we are aliasing output to input, the two needs to have `identical` allocation domain and contiguity. (technically we only needed compatible allocation domain, but this is easier for the time being).

File: csrc/transform_replay.cpp [hunk 3]
```diff
@@ -233,6 +233,59 @@ TensorDomain* TransformReplay::fullSelfReplay(
...
+
+  return IrBuilder::createInContainer<TensorDomain>(
+      new_self_root->container(),
+      new_self_root->maybeRoot(),
+      new_self_root->logical(),
+      new_alloc_domain,
+      new_self_root->loop(),
+      self->contiguity(),
+      new_self_root->additionalIDs());
+}
```
Comment (jjsjann123) [inline csrc/transform_replay.cpp:287]: I need a better test for this.

Comment (jjsjann123) [reply csrc/transform_replay.cpp:287]: Need to get a test to validate that we indeed support cases where we have transforms not just as a permutation. I *think* I needed some cpp tests.

**Comment by jjsjann123** [comment]
!test

**Comment by jjsjann123** [comment]
keeping my :crossed_fingers:

**Comment by jjsjann123** [comment]
!test --diff

**Comment by jjsjann123** [comment]
!test --diff

**Comment by jjsjann123** [comment]
!test --diff

**Comment by jjsjann123** [comment]
!test --diff

**Comment by jjsjann123** [comment]
!test --diff

**Comment by jjsjann123** [comment]
!test --diff

File: csrc/transform_replay.cpp [hunk 4]
```diff
@@ -233,6 +233,97 @@ TensorDomain* TransformReplay::fullSelfReplay(
       new_self_root->contiguity());
 }
 
+TensorDomain* TransformReplay::selfAllocationReplay(
```
Comment (jjsjann123) [inline csrc/transform_replay.cpp:236]: I tagged @wujingyue because I think you asked for something similar to this?

Though I'm not totally sure if this does what you want, because I'm addressing some requirement from `remove_bcast_squeeze`, which I think we can also refactor this one and put some logic on the user side, if we needed a more generic replay later.

File: csrc/transform_replay.cpp [hunk 5]
```diff
@@ -233,6 +233,97 @@ TensorDomain* TransformReplay::fullSelfReplay(
...
+        // whether we resolve to true or false shouldn't matter since it's going
+        // to be concretized as a broadcast dimension
+        mapped_contiguity[i] =
+            it->second->isBroadcast() ? std::nullopt : std::make_optional(true);
+      }
+      mapped_alloc_domain[i++] = it->second;
+    }
+  }
+
+  // We need to put back the reduction IDs that are not mapped
```
Comment (wujingyue) [inline csrc/transform_replay.cpp:298]: Yes but in a potentially different order. Is that fine? For example,
```
self: logical=[ix, iy, r], alloc=[iy, r, ix]
new_self: logical=[ix, iy, r]
```
will set new_alloc_domain to be `[iy, ix, r]` instead of `[iy, r, ix]`.

Comment (wujingyue) [reply csrc/transform_replay.cpp:298]: I'm asking this because if the order of reductions doesn't matter we can simplify put reductions at the end.

**Review by wujingyue — COMMENTED** [review]
LGTM overall -- there are some details that I want to make sure I understand to have a good mental model

File: csrc/transform_replay.h [hunk 6]
```diff
@@ -227,6 +227,11 @@ class NVF_API TransformReplay {
       const TensorDomain* new_self_root,
       const TensorDomain* self);
 
+  // Self replay only the allocation transformation.
+  static TensorDomain* selfAllocationReplay(
```
[the remark this answers is not in the document]
Comment (jjsjann123) [reply csrc/transform_replay.h:231]: Don't have a strong opinion on this. Given the name of the function `selfAllocationReplay`, I think update `new_self_root` might be a better ideal. I'll update that.

File: csrc/transform_replay.cpp (hunk 5 above)
Comment (jjsjann123) [reply csrc/transform_replay.cpp:298]: My general answer is that reduction *shouldn't* matter in allocation domain, where it might have some effect is that, we usually check for permutation from logical to allocation, and try to restore the order in loop domain for better memory access. Hence my attempt to keep reduction in the same place as in logical when possible.
But granted, that logic probably should have considered dropping reduction anyway, since it's pretty trivial.

TL;DR, I think you are right and I should just try to keep them at the end for simplicity.

File: csrc/preseg_passes/remove_bcast_squeeze.cpp [hunk 7]
```diff
@@ -389,6 +390,16 @@ TensorView* maybeDoReplacement(TensorView* orig) {
     }
   }
 
+  // If we are replacing an output, we need to preserve the memory layout by
```
Comment (naoyam) [inline csrc/preseg_passes/remove_bcast_squeeze.cpp:393]: Can we do this check in `Fusion::replaceOutput`?

Comment (jjsjann123) [reply csrc/preseg_passes/remove_bcast_squeeze.cpp:393]: That check needs to be opt-in. We have places where we are explicitly altering memory layout. i.e. mark alias prepare and sharding propagation that would intentionally change the memory layout.

But it would be nice to have a check on that.

So the check would actually be checking for compatible transforms. i.e. the two transforms might not necessarily be the same, but they should be equivalent... This feels like something @wujingyue and @zasdfgbnm were discussing together.

Comment (jjsjann123) [reply csrc/preseg_passes/remove_bcast_squeeze.cpp:393]: Opened this to track #3994

**Comment by jjsjann123** [comment]
I'm surprised seeing a segfault with the python_bc_advisory thing. I didn't change any python API. No idea where that segfault is coming from.

File: csrc/transform_replay.cpp [hunk 8]
```diff
@@ -233,6 +236,98 @@ TensorDomain* TransformReplay::fullSelfReplay(
...
+  // Map for replay
+  id_map axis_map;
+  {
+    int64_t i = 0;
+    for (auto id : self_logical) {
+      // Note: we don't want to check for equal `isRFactorProduct`, since we
+      // could replay Allocation of the output of a reduction to a later
+      // consumer tensor, which would not have the rfactor flag on.
+      NVF_ERROR(
+          new_self_logical[i]->isSymbolic() || id->isSymbolic() ||
```
Comment (wujingyue) [inline csrc/transform_replay.cpp:269]:
```suggestion
      IterDomain* new_id = new_self_logical[i];
      NVF_ERROR(
          new_id->isSymbolic() || id->isSymbolic() ||
```
`new_id` can then be used for the rest of the loop to save typing and reading.

File: csrc/transform_replay.cpp [hunk 9]
```diff
@@ -233,6 +236,98 @@ TensorDomain* TransformReplay::fullSelfReplay(
...
+      TensorDomain::noReductions(self_allocation);
+
+  // we replay only non-reduction IDs. The reason is that, we might have
+  // non-mapping reduction IDs between self and new_self_root. This is used in
+  // `RemoveBcastSqueeze`.
+  ReplaySelf replay(self_allocation_no_reduction, axis_map);
+  std::vector<IterDomain*> new_alloc_domain;
+  std::vector<std::optional<bool>> new_contiguity;
+  new_alloc_domain.reserve(new_self_root->logical().size());
+  new_contiguity.reserve(new_self_root->logical().size());
```
Comment (wujingyue) [inline csrc/transform_replay.cpp:294]:
```suggestion
  new_alloc_domain.reserve(self_allocation.size());
  new_contiguity.reserve(self_allocation.size());
```

File: csrc/transform_replay.cpp [hunk 10]
```diff
@@ -233,6 +236,98 @@ TensorDomain* TransformReplay::fullSelfReplay(
...
+
+  {
+    // Push back the reduction IDs that are not mapped
+    for (auto id : new_self_root->logical()) {
+      if (id->isReduction()) {
+        new_alloc_domain.push_back(id);
+        new_contiguity.emplace_back(std::nullopt);
```
Comment (wujingyue) [inline csrc/transform_replay.cpp:301]:
```suggestion
        new_contiguity.push_back(std::nullopt);
```
https://abseil.io/tips/112

File: csrc/transform_replay.cpp [hunk 11]
```diff
@@ -233,6 +236,98 @@ TensorDomain* TransformReplay::fullSelfReplay(
...
+  // non-mapping reduction IDs between self and new_self_root. This is used in
+  // `RemoveBcastSqueeze`.
+  ReplaySelf replay(self_allocation_no_reduction, axis_map);
+  std::vector<IterDomain*> new_alloc_domain;
+  std::vector<std::optional<bool>> new_contiguity;
+  new_alloc_domain.reserve(new_self_root->logical().size());
+  new_contiguity.reserve(new_self_root->logical().size());
+
+  {
+    // Push back the reduction IDs that are not mapped
```
Comment (wujingyue) [inline csrc/transform_replay.cpp:297]: Question: do they have to be up front or is the order arbitrary?

File: csrc/transform_replay.cpp [hunk 12]
```diff
@@ -233,6 +236,98 @@ TensorDomain* TransformReplay::fullSelfReplay(
...
+    for (auto id : new_self_root->logical()) {
+      if (id->isReduction()) {
+        new_alloc_domain.push_back(id);
+        new_contiguity.emplace_back(std::nullopt);
+      }
+    }
+
+    // Pushing the mapped IDs and corresponding contiguity flags
+    for (size_t i = 0; i < self_contiguity.size(); i++) {
```
Comment (wujingyue) [inline csrc/transform_replay.cpp:306]:
```suggestion
    for (size_t i : c10::irange(self_allocation.size())) {
```

File: csrc/transform_replay.cpp [hunk 13]
```diff
@@ -233,6 +236,98 @@ TensorDomain* TransformReplay::fullSelfReplay(
...
+      IterDomain* id = self_allocation[i];
+      if (id->isReduction()) {
+        continue;
+      }
+      auto it = replay.getReplay().find(id);
+      NVF_ERROR(
+          it != replay.getReplay().end(),
+          "Error during replay, didn't replay an axis.");
```
Comment (wujingyue) [inline csrc/transform_replay.cpp:314]:
```suggestion
          "failed to replay IterDomain: ", id);
```

File: csrc/transform_replay.cpp [hunk 14]
```diff
@@ -233,6 +236,98 @@ TensorDomain* TransformReplay::fullSelfReplay(
...
+      if (it->second->isBroadcast() == self_contiguity[i].has_value()) {
```
Comment (wujingyue) [inline csrc/transform_replay.cpp:315]: This feels like a bug or a misuse. Is there a good use case for is-broadcast to be inconsistent between `self` and `new_self`?

File: csrc/transform_replay.cpp [hunk 15]
```diff
@@ -233,6 +236,98 @@ TensorDomain* TransformReplay::fullSelfReplay(
...
+  // Replay producer dimensions.
+  const std::vector<IterDomain*>& self_allocation = self->maybeAllocation();
+  const std::vector<std::optional<bool>>& self_contiguity = self->contiguity();
+  const std::vector<IterDomain*>& self_allocation_no_reduction =
+      TensorDomain::noReductions(self_allocation);
+
+  // we replay only non-reduction IDs. The reason is that, we might have
+  // non-mapping reduction IDs between self and new_self_root. This is used in
+  // `RemoveBcastSqueeze`.
+  ReplaySelf replay(self_allocation_no_reduction, axis_map);
```
Comment (wujingyue) [inline csrc/transform_replay.cpp:290]:
```suggestion
  // we replay only non-reduction IDs. The reason is that, we might have
  // non-mapping reduction IDs between self and new_self_root. This is used in
  // `RemoveBcastSqueeze`.
  ReplaySelf replay(TensorDomain::noReductions(self_allocation), axis_map);
```

File: csrc/transform_replay.cpp [hunk 16]
```diff
@@ -170,7 +170,10 @@ TensorDomain* TransformReplay::fullSelfReplay(
 
   NVF_ERROR(
       new_self_root->maybeRoot().size() == self->maybeRoot().size(),
-      "Invalid number of IterDomains provided.");
+      "Invalid number of IterDomains provided: ",
+      new_self_root->maybeRoot().size(),
+      " vs ",
+      self->maybeRoot().size());
```
Comment (wujingyue) [inline csrc/transform_replay.cpp:176]:
```suggestion
      new_self_root->maybeRoot(),
      " vs ",
      self->maybeRoot());
```
makes error messages more useful. Root domains are typically short so readers shouldn't have a problem counting.

**Review by wujingyue — APPROVED** [review]

File: csrc/transform_replay.cpp (hunk 10 above)
Comment (jjsjann123) [reply csrc/transform_replay.cpp:301]: Yeah this one looks ugly to me as well.

Linter was complaining about the use of `push_back` earlier and I decided to follow the suggestion to change to push_back just to make it happy. https://github.com/NVIDIA/Fuser/actions/runs/13573500356/job/37944072306

I can have a nolinter comment to silence the linter instead.

File: csrc/transform_replay.cpp (hunk 11 above)
Comment (jjsjann123) [reply csrc/transform_replay.cpp:297]: This is just an arbitrary decision. I'll put a comment about it.

File: csrc/transform_replay.cpp (hunk 15 above)
Comment (jjsjann123) [reply csrc/transform_replay.cpp:290]: No this won't work.
https://github.com/NVIDIA/Fuser/blob/9125e06bc6e4d67c5e417c96b5b0a367bab0b7c7/csrc/transform_replay.cpp#L157-L160

ReplaySelf's constructor takes a const reference. `TensorDomain::noReductions()` return would go out of scope after the constructor.

File: csrc/transform_replay.cpp [hunk 17]
```diff
@@ -233,6 +236,98 @@ TensorDomain* TransformReplay::fullSelfReplay(
...
+  id_map axis_map;
+  {
+    int64_t i = 0;
+    for (auto id : self_logical) {
+      // Note: we don't want to check for equal `isRFactorProduct`, since we
+      // could replay Allocation of the output of a reduction to a later
+      // consumer tensor, which would not have the rfactor flag on.
+      NVF_ERROR(
+          new_self_logical[i]->isSymbolic() || id->isSymbolic() ||
+              new_self_logical[i]->isBroadcast() == id->isBroadcast(),
```
[the remark this answers is not in the document]
Comment (jjsjann123) [reply csrc/transform_replay.cpp:270]: This function could be used before concretization, i.e. `Fusion::aliasOutputToInput` call this.

i.e. we could have a symbolic ID that was later concretized as a broadcast dimension. But when this function is called, we don't have that information to resolve the symbolic IDs yet, so we'll just assume the user program is correct and we will be able to resolve it consistently later.

File: csrc/transform_replay.cpp (hunk 14 above)
Comment (jjsjann123) [reply csrc/transform_replay.cpp:315]: This is the same reason with the comment above about symbolic IDs. If we are dealing with symbolic ID, we just need to make sure that the contiguity flag on the given ID is consistent with itself.

Later during concretization, it will fix the consistency globally.

**Comment by jjsjann123** [comment]
!test --diff

**Comment by jjsjann123** [comment]
Failure doesn't seem to be relevant. We also have all test cleared in 4e6d81e.

I'm merging this PR as-is.
