### PR TITLE
Avoid segfault in segmentation with dangling unary ops

### LINKED ISSUE #585: Segfault segmenting in presence of dangling unary Op chain from inputs
I encountered a segfault during segmentation when implementing #449 in `SegmentCandidateFinder::forwardInputs()` at https://github.com/NVIDIA/Fuser/blob/main/csrc/fusion_segmenter.cpp#L3408. That method tries to build a chain of `UnaryOp`s from inputs, and implicitly assumes that there are uses for each output. This is triggered whenever we must segment (i.e. the complete `Fusion` cannot be scheduled) and there is a chain of `UnaryOp`s from an input that eventually is unused.
```c++
TEST_F(NVFuserTest, FusionDanglingUnaryOp_CUDA) {
  auto fusion = std::make_unique<Fusion>();
  FusionGuard fg(fusion.get());

  // Create a segmented Fusion. We call segment_set here to ensure the whole
  // Fusion cannot be scheduled. This triggers segmentation, so that
  // forwardInputs() is called. The structure of this Fusion is not important;
  // it is only important that it must be segmented.
  auto size = IrBuilder::create<Scalar>(5);
  auto tv0 = full({size}, fusion->zeroVal(), DataType::Int);
  auto tv1 = segment_set(tv0);
  fusion->addOutput(tv1);

  // Now take in an input that has a chain of UnaryOp uses that terminates in a
  // Val with no uses. This triggers a segfault in forwardInputs().
  Val* alpha = IrBuilder::create<Scalar>(DataType::Int);
  fusion->addInput(alpha);
  neg(castOp(DataType::Float, alpha));

  FusionExecutorCache executor_cache(std::move(fusion));

  executor_cache.runFusionWithInputs({11});
}
```

### PR DESCRIPTION
**Pull request by jacobhinkle**
Fixes #585

### CODE REVIEW

File: csrc/fusion_segmenter.cpp [hunk 1]
```diff
@@ -3399,13 +3399,21 @@ void SegmentCandidateFinder::forwardInputs() {
         continue;
       }
 
-      if (expr->output(0)->uses().size() > 1) {
+      // expr is a unary op so there is a single output. Here we look at that
+      // output's further uses
+      auto output_uses = expr->output(0)->uses();
```
Comment (naoyam) [inline csrc/fusion_segmenter.cpp:3404]:
```suggestion
      const auto& output_uses = expr->output(0)->uses();
```

File: csrc/fusion_segmenter.cpp [hunk 2]
```diff
@@ -3399,13 +3399,21 @@ void SegmentCandidateFinder::forwardInputs() {
...
+
+      if (output_uses.size() == 1) {
+        // If there is a single use, visit it to try and extend the chain of
+        // unaryOps
+        to_visit.emplace_back(output_uses[0]);
```
Comment (naoyam) [inline csrc/fusion_segmenter.cpp:3409]: Not going to happen anymore, but just in case:

```suggestion
        to_visit.emplace_back(output_uses.at(0));
```

**Review by naoyam — APPROVED** [review]
LGTM. The reason this only happens with a scalar and not with a tensor is that we delete uses that do not lead to fusion outputs. So, if a unary-op sequence from a tensor input does not lead to an output, the uses of the fusion input should be empty, so we shouldn't add anything to `to_visit`.

**Comment by naoyam** [comment]
Nice catch and thanks for fixing!
