### PR TITLE
Do not replace one output with another in RemoveBcastSqueeze pass

### LINKED ISSUE #3833: A Fusion Definition returns an empty list even though it has two `fd.add_output`s
In the following snippet, `out`, the output of the fusion definition is an empty list.
IIUC, the definition calls `fd.add_output`, so the return list should not be empty. 

```python
# CUDA devices:
#  0: NVIDIA H100 80GB HBM3
#  1: NVIDIA H100 80GB HBM3
#  2: NVIDIA H100 80GB HBM3
#  3: NVIDIA H100 80GB HBM3
#  4: NVIDIA H100 80GB HBM3
#  5: NVIDIA H100 80GB HBM3
#  6: NVIDIA H100 80GB HBM3
#  7: NVIDIA H100 80GB HBM3
# torch version: 2.7.0a0+ecf3bae40a
# cuda version: 12.8
# nvfuser version: 0.2.25+git6627725
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id0(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[1, 1, 576], contiguity=[None, None, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[2, 1, 0])
    T1 = fd.define_tensor(shape=[1, 576], contiguity=[None, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[1, 0])
    T5 = fd.ops.reshape(T0, new_shape=[1, 576])
    T6 = fd.ops.set(T5)
    fd.add_output(T6, T1)
    fd.add_output(T5)

with FusionDefinition() as fd:
    nvfuser_fusion_id0(fd)

inputs = [
    torch.testing.make_tensor((1, 1, 576), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((1, 576), dtype=torch.bfloat16, device='cuda:0'),
]
out = fd.execute(inputs)
print(f"$$$ {out = }")
```

This is a tinier script derived from the following lightning-thunder script:
```python
import torch
import thunder


def f(
    l_stack0_: torch.Tensor,
    l_latent_cache_: torch.Tensor,
):
    v_input = l_stack0_.unsqueeze(1)
    k_input = l_latent_cache_.unsqueeze(1)
    k_input[(Ellipsis, slice(None, 512, None))] = v_input
    return k_input


def main():
    inputs = [
        torch.testing.make_tensor(
            (1, 512),
            dtype=torch.bfloat16,
            device="cuda:0",
            requires_grad=False,
            low=-0.0888671875,
            high=0.03173828125,
        ).as_strided((1, 512), (576, 1)),
        torch.testing.make_tensor(
            (1, 576),
            dtype=torch.bfloat16,
            device="cuda:0",
            requires_grad=False,
            low=-17.5,
            high=19.75,
        ).as_strided((1, 576), (576, 1)),
    ]
    jitted_f = thunder.jit(f, disable_torch_autograd=True)

    try:
        jitted_f(*inputs)
    except Exception:
        extrace = thunder.last_traces(jitted_f)[-1]
        print(extrace)

        nvfuser_bsym = extrace.bound_symbols[6]
        call_ctx = nvfuser_bsym._get_call_ctx()
        nvfusion_wrapper = list(call_ctx.values())[0]
        print(nvfusion_wrapper)
        print(nvfusion_wrapper.last_used.last_repro_script())
        raise


if __name__ == "__main__":
    main()
```
which shows an error of

```
Traceback (most recent call last):
  File "/workspace/multi_dim_copy_with_setitem.py", line 37, in main
    jitted_f(*inputs)
  File "/workspace/lightning-thunder/thunder/__init__.py", line 741, in wrapped
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/workspace/lightning-thunder/thunder/__init__.py", line 779, in fn_
    result = cache_entry.computation_fn(*inps)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/lightning-thunder/thunder/__init__.py", line 705, in wrapped
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/lightning-thunder/thunder/executors/torchex.py", line 170, in no_autocast_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "thunder.computation_2", line 20, in computation
ValueError: not enough values to unpack (expected 1, got 0)
```

### PR DESCRIPTION
**Pull request by jacobhinkle**
This PR simply prevents the RemoveBcastSqueeze pass from introducing repeated outputs, which can clobber aliasing and cause other issues.

Fixes #3833

### CODE REVIEW

**Comment by jacobhinkle** [comment]
!test

**Comment by jacobhinkle** [comment]
!test

File: csrc/preseg_passes/remove_bcast_squeeze.cpp [hunk 1]
```diff
@@ -337,6 +337,12 @@ TensorView* maybeDoReplacement(TensorView* orig) {
   }
   NVF_ERROR(replacement != orig, "Expected non-trivial replacement");
 
+  if (orig->isFusionOutput() && replacement->isFusionOutput()) {
```
Comment (jjsjann123) [inline csrc/preseg_passes/remove_bcast_squeeze.cpp:340]: IIUC, we are only worried about messing with aliases. So we really only need to reject when the two output aliases aren't the same?
`&& fusion->getOutputAlias(orig) != fusion->getOutputAlias(replacement)`

Comment (jacobhinkle) [reply csrc/preseg_passes/remove_bcast_squeeze.cpp:340]: That's true but if we replace one output with another, we will have two outputs aliasing each other. I _think_ that's OK but not sure.

Comment (jjsjann123) [reply csrc/preseg_passes/remove_bcast_squeeze.cpp:340]: > we will have two outputs aliasing each other. 

how would that be the case then? If we add an equal op to the struct below, two outputs having the same AliasInfo meaning they'll be aliasing to the same source. Replacing those shouldn't introduce new pattern to the graph.

```
struct AliasInfo {
  AllocationType type;
  Val* aliased_io;
  bool hide_output;
}
```

**Review by jjsjann123 — APPROVED** [review]
stamping. Let's merge this.

File: csrc/preseg_passes/remove_bcast_squeeze.cpp (hunk 1 above)
Comment (jacobhinkle) [reply csrc/preseg_passes/remove_bcast_squeeze.cpp:340]: I could alternatively change this to do replacement if either is not an output or if `io_alias_[orig].aliased_io == io_alias_[replacement].aliased_io` which should be when both are reusing same buffer or both are not reusing any input.

Comment (jjsjann123) [reply csrc/preseg_passes/remove_bcast_squeeze.cpp:340]: > then doing the replacement will result in replacement showing up in fusion->outputs() twice.

I think that one is safe.

> io_alias_[orig].aliased_io == io_alias_[replacement].aliased_io

That is not enough I think. we do need to ensure they share the same properties as `hide_output` as well as `AllocationType`. Otherwise, the replacement is still altering semantics.

Comment (jjsjann123) [reply csrc/preseg_passes/remove_bcast_squeeze.cpp:340]: sorry I'm nitpicking on this one.

I'm less worried about the changes in this PR, as I don't think it's that big of a deal if we miss out some replacement opportunities here.

But we might want to add an check to ensure that other passes in general wouldn't accidentally replace some values and alter semantics....

Comment (jacobhinkle) [reply csrc/preseg_passes/remove_bcast_squeeze.cpp:340]: > sorry I'm nitpicking on this one.

Nah, I think this is important as it defines the semantics of aliasing. :-)

> But we might want to add an check to ensure that other passes in general wouldn't accidentally replace some values and alter semantics....

Yeah, this is the first time I've considered the possibility of modifying aliasing behavior by just replacing one output. I am not exactly sure where to put such a check. Something like mapping aliases before the preseg passes then again after?

Comment (jjsjann123) [reply csrc/preseg_passes/remove_bcast_squeeze.cpp:340]: I *think* we would want to do that inside `Fusion::replaceOutput`. Is there any other place where one can mess with the output?

We can do that in a separate PR.

**Comment by jacobhinkle** [comment]
!test

File: csrc/fusion.h [hunk 2]
```diff
@@ -90,6 +90,37 @@ struct AliasInfo {
   // Whether integration should hide the output from users. This is currently
   // only used for ReuseBuffer.
   bool hide_output;
+
+  bool operator==(const AliasInfo& other) const {
```
Comment (jjsjann123) [inline csrc/fusion.h:94]: :clap:

File: csrc/fusion.cpp [hunk 3]
```diff
@@ -331,6 +331,23 @@ void Fusion::replaceOutput(Val* output, Val* replacement) {
   // (https://github.com/csarofeen/pytorch/issues/1112)
   if (io_alias_.count(output) != 0) {
     auto input = io_alias_[output];
+    if (replacement->isFusionOutput()) {
```
Comment (jjsjann123) [inline csrc/fusion.cpp:334]: I'm not certain about having this check inside the if block.

If we just want to avoid changing semantics, we should check that `replacement` and old `output` should have the same alias info before the replacement. So I think it should be inside the previous if block where

`if (find_output != outputs_.end()) {`

**Comment by jacobhinkle** [comment]
I think the check is non-trivial. I'm going to move it to another PR so we can get this issue fixed quickly.

**Comment by jacobhinkle** [comment]
!test

**Comment by jacobhinkle** [comment]
!test

**Comment by jacobhinkle** [comment]
!test

**Comment by jacobhinkle** [comment]
I still cannot repro this on H100 or H200, but it's suspicious that it is this new test that is failing on the CI machines. I will continue investigating.

**Comment by jacobhinkle** [comment]
!test

**Comment by jacobhinkle** [comment]
Adding `skip_serde_check=True` seems to fix the failures, but I'm not sure why this should be necessary yet.

**Comment by jacobhinkle** [comment]
I'm going to add that flag and merge so that we can unblock #3833, but I will continue checking why this is necessary as it might indicate a bug in our serde or serde test framework.

**Comment by jacobhinkle** [comment]
!test
