### PR TITLE
Only forward inputs whose single use is UnaryOp (segmentation)

### LINKED ISSUE #1301: Inferring output shape failure
To reproduce the error:
```
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id1(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[-1, -1, -1], contiguity=[True, True, True], dtype=DataType.Float, is_cpu=False)
    T1 = fd.define_tensor(shape=[-1, -1, -1], contiguity=[True, True, None], dtype=DataType.Float, is_cpu=False)
    T2 = fd.define_tensor(shape=[-1, -1, -1], contiguity=[None, None, True], dtype=DataType.BFloat16, is_cpu=False)
    T3 = fd.define_tensor(shape=[-1, -1, -1], contiguity=[True, True, True], dtype=DataType.BFloat16, is_cpu=False)
    T4 = fd.define_tensor(shape=[-1, -1, 1], contiguity=[True, True, None], dtype=DataType.Float, is_cpu=False)
    T5 = fd.define_tensor(shape=[-1, -1, -1], contiguity=[True, True, True], dtype=DataType.BFloat16, is_cpu=False)
    T6 = fd.ops.cast(T5, dtype=DataType.Float)
    S7 = fd.define_scalar(16, dtype=DataType.Int)
    S8 = fd.define_scalar(128, dtype=DataType.Int)
    S9 = fd.define_scalar(768, dtype=DataType.Int)
    V10 = fd.define_vector([S7, S8, S9], dtype=DataType.Int)
    T11 = fd.ops.broadcast_in_dim(T4, shape=V10, broadcast_dims=[0, 1, 2])
    T12 = fd.ops.mul(T0, T11)
    T13 = fd.ops.cast(T2, dtype=DataType.Float)
    T14 = fd.ops.cast(T3, dtype=DataType.Float)
    T15 = fd.ops.cast(T3, dtype=DataType.Float)
    T16 = fd.ops.sum(T15, axes=[0, 1], keepdim=False, dtype=DataType.Null)
    T17 = fd.ops.cast(T16, dtype=DataType.BFloat16)
    T18 = fd.ops.mul(T14, T13)
    T19 = fd.ops.mul(T14, T12)
    T20 = fd.ops.sum(T19, axes=[0, 1], keepdim=False, dtype=DataType.Null)
    T21 = fd.ops.cast(T20, dtype=DataType.BFloat16)
    T22 = fd.ops.mul(T18, T11)
    T23 = fd.ops.mul(T18, T0)
    T24 = fd.ops.sum(T23, axes=[2], keepdim=False, dtype=DataType.Null)
    S25 = fd.define_scalar(16, dtype=DataType.Int)
    S26 = fd.define_scalar(128, dtype=DataType.Int)
    S27 = fd.define_scalar(1, dtype=DataType.Int)
    V28 = fd.define_vector([S25, S26, S27], dtype=DataType.Int)
    T29 = fd.ops.broadcast_in_dim(T24, shape=V28, broadcast_dims=[0, 1])
    T30 = fd.ops.neg(T22)
    T31 = fd.ops.sum(T30, axes=[2], keepdim=False, dtype=DataType.Null)
    S32 = fd.define_scalar(16, dtype=DataType.Int)
    S33 = fd.define_scalar(128, dtype=DataType.Int)
    S34 = fd.define_scalar(1, dtype=DataType.Int)
    V35 = fd.define_vector([S32, S33, S34], dtype=DataType.Int)
    T36 = fd.ops.broadcast_in_dim(T31, shape=V35, broadcast_dims=[0, 1])
    S37 = fd.define_scalar(-0.500000, dtype=DataType.Double)
    T38 = fd.ops.mul(S37, T29)
    S39 = fd.define_scalar(3.00000, dtype=DataType.Double)
    T40 = fd.ops.pow(T4, S39)
    T41 = fd.ops.mul(T38, T40)
    T42 = fd.ops.sum(T36, axes=[2], keepdim=False, dtype=DataType.Null)
    T43 = fd.ops.sum(T41, axes=[2], keepdim=False, dtype=DataType.Null)
    S44 = fd.define_scalar(16, dtype=DataType.Int)
    S45 = fd.define_scalar(128, dtype=DataType.Int)
    S46 = fd.define_scalar(1, dtype=DataType.Int)
    V47 = fd.define_vector([S44, S45, S46], dtype=DataType.Int)
    T48 = fd.ops.broadcast_in_dim(T43, shape=V47, broadcast_dims=[0, 1])
    S49 = fd.define_scalar(16, dtype=DataType.Int)
    S50 = fd.define_scalar(128, dtype=DataType.Int)
    S51 = fd.define_scalar(768, dtype=DataType.Int)
    V52 = fd.define_vector([S49, S50, S51], dtype=DataType.Int)
    T53 = fd.ops.broadcast_in_dim(T48, shape=V52, broadcast_dims=[0, 1, 2])
    S54 = fd.define_scalar(2.00000, dtype=DataType.Double)
    T55 = fd.ops.mul(S54, T53)
    T56 = fd.ops.sub(T6, T1)
    T57 = fd.ops.mul(T55, T56)
    S58 = fd.define_scalar(768.000, dtype=DataType.Double)
    S59 = fd.ops.reciprocal(S58)
    T60 = fd.ops.mul(T57, S59)
    S61 = fd.define_scalar(16, dtype=DataType.Int)
    S62 = fd.define_scalar(128, dtype=DataType.Int)
    S63 = fd.define_scalar(1, dtype=DataType.Int)
    V64 = fd.define_vector([S61, S62, S63], dtype=DataType.Int)
    T65 = fd.ops.broadcast_in_dim(T42, shape=V64, broadcast_dims=[0, 1])
    S66 = fd.define_scalar(16, dtype=DataType.Int)
    S67 = fd.define_scalar(128, dtype=DataType.Int)
    S68 = fd.define_scalar(768, dtype=DataType.Int)
    V69 = fd.define_vector([S66, S67, S68], dtype=DataType.Int)
    T70 = fd.ops.broadcast_in_dim(T65, shape=V69, broadcast_dims=[0, 1, 2])
    S71 = fd.define_scalar(0.00130208, dtype=DataType.Double)
    T72 = fd.ops.mul(S71, T70)
    T73 = fd.ops.add(T60, T72)
    T74 = fd.ops.add(T22, T73)
    T75 = fd.ops.cast(T74, dtype=DataType.BFloat16)
    fd.add_output(T17)
    fd.add_output(T21)
    fd.add_output(T75)

with FusionDefinition() as fd:
    nvfuser_fusion_id1(fd)

inputs = [
    torch.randn((1572864,), dtype=torch.float32, device='cuda:0').as_strided((16, 128, 768), (98304, 768, 1)),
    torch.randn((2048,), dtype=torch.float32, device='cuda:0').as_strided((16, 128, 768), (128, 1, 0)),
    torch.randn((768,), dtype=torch.bfloat16, device='cuda:0').as_strided((16, 128, 768), (0, 0, 1)),
    torch.randn((1572864,), dtype=torch.bfloat16, device='cuda:0').as_strided((16, 128, 768), (98304, 768, 1)),
    torch.randn((2048,), dtype=torch.float32, device='cuda:0').as_strided((16, 128, 1), (128, 1, 1)),
    torch.randn((1572864,), dtype=torch.bfloat16, device='cuda:0').as_strided((16, 128, 768), (98304, 768, 1)),
]
fd.execute(inputs)
```
Get the error message:
```
Traceback (most recent call last):
  File "/opt/pytorch/nvfuser/nvfuser/__init__.py", line 123, in execute
    result = self._execute(
RuntimeError: inferred_val.hasValue() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/executor.cpp":537, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Could not launch kernel as program could not infer i11(i11) for the buffer T518_g[ iS1424{i11}, iS1425{i12}, iS1426{i13} ]
Exception raised from inferShape at /opt/pytorch/nvfuser/csrc/executor.cpp:537 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x8d (0x7f169cdf9f25 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #1: nvfuser::nvfErrorFail(char const*, char const*, unsigned int, char const*, std::string const&) + 0x53 (0x7f169cf34b53 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #2: <unknown function> + 0x2e9f90 (0x7f169cf37f90 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #3: <unknown function> + 0x2ee870 (0x7f169cf3c870 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #4: nvfuser::FusionExecutor::inferOutputSizes(nvfuser::Fusion*, nvfuser::KernelArgumentHolder const&) + 0x217 (0x7f169cf3ce77 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #5: nvfuser::FusionKernelRuntime::compileFusionParallel(nvfuser::KernelArgumentHolder) + 0x4d3 (0x7f169d071483 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #6: nvfuser::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&, std::optional<nvfuser::PrimDataType>, std::optional<signed char>) + 0xac3 (0x7f169d07cc53 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #7: nvfuser::python_frontend::FusionDefinition::execute(c10::ArrayRef<c10::IValue> const&, bool, bool, std::optional<signed char>) const + 0x161 (0x7f169d35b321 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #8: <unknown function> + 0xef2fe (0x7f169d6952fe in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #9: <unknown function> + 0x170267 (0x7f169d716267 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
```

### PR DESCRIPTION
**Pull request by jacobhinkle**
Fixes #1301 

That issue demonstrated a case where `forwardInputs` could skip an expression, then also fail to add its outputs as a new input; the result is a segment without any input including the original unforwarded one. This change follows `UnaryOp` output uses only if those uses are themselves `UnaryOps`; otherwise we terminate and add that output as a new forwarded input.

### CODE REVIEW

**Comment by jacobhinkle** [comment]
!build --diff

**Review by tfogal — APPROVED** [review]
LGTM. thanks for ths fix!

File: csrc/fusion_segmenter.cpp [hunk 1]
```diff
@@ -3502,7 +3502,7 @@ void SegmentCandidateFinder::forwardInputs() {
       // output's further uses
       const auto& output_uses = expr->output(0)->uses();
 
-      if (output_uses.size() == 1) {
+      if (output_uses.size() == 1 && output_uses[0]->isA<UnaryOp>()) {
```
Comment (wujingyue) [inline csrc/fusion_segmenter.cpp:3505]: I'm trying to understand the code around this. I don't understand why we check for `output_uses.size() == 1`.
For the test case you added, it seems fine to have T14 and T15 be the forwarded inputs (regardless of their number of uses), so we segment from them to the three outputs. What am I missing?

**Review by wujingyue — APPROVED** [review]
The change itself is a strict improvement, so LGTM!

File: csrc/fusion_segmenter.cpp (hunk 1 above)
Comment (jacobhinkle) [reply csrc/fusion_segmenter.cpp:3505]: Yeah, if any use is not forwarded, then we would terminate at the branching point. I don't think that necessarily has to happen though, as you say. If instead we just forward whenever all uses are UnaryOps, I think that would be fine too. We might eventually stop forwarding along each branch somewhere, but I don't really see why that would be a problem. I'll try it out soon.
