### PR TITLE
Visit extent scalars in `SegmentCandidateFinder::resolveScalarsInGroup`

### LINKED ISSUE #656: More lost scalars during segmentation for dynamic reshape
```c++
// Test concretizing a pad that follows a reshape. This requires the
// ExpressionEvaluator used in concretization to propagate shapes properly
// across symbolic reshapes in order to infer the size of the downstream pad.
TEST_F(NVFuserTest, DynamicReshapePad_CUDA) {
  std::unique_ptr<Fusion> fusion_ptr = std::make_unique<Fusion>();
  Fusion& fusion = *fusion_ptr.get();
  FusionGuard fg(&fusion);

  TensorView* tv0 = makeSymbolicTensor(2);
  fusion.addInput(tv0);

  auto s0 = IrBuilder::create<Val>(DataType::Int);
  auto s1 = IrBuilder::create<Val>(DataType::Int);
  auto s2 = IrBuilder::create<Val>(DataType::Int);
  auto s3 = IrBuilder::create<Val>(DataType::Int);
  fusion.addInput(s0);
  fusion.addInput(s1);
  fusion.addInput(s2);
  fusion.addInput(s3);

  auto tv1 = reshape(tv0, {s2, s3});
  auto tv2 = pad(tv1, {fusion.zeroVal(), s0, fusion.zeroVal(), s1});
  fusion.addOutput(tv2);

  /*
Symbolic Fusion:
Inputs:
  T0_g[ iS0{i0}, iS1{i2} ], float
  i3, int64_t
  i4, int64_t
  i5, int64_t
  i6, int64_t
Outputs:
  T2_g[ ?S7{( i5 + i4 )}rf, ?S9{( i6 + i3 )}rf ], float

%kernel_math {
T1_l[ ?S4{i5}rf, ?S5{i6}rf ] = view( T0_g[ iS0{i0}, iS1{i2} ] )
T2_g[ ?S7{( i5 + i4 )}rf, ?S9{( i6 + i3 )}rf ]
   = pad( T1_l[ ?S4{i5}rf, ?S5{i6}rf ], {0, i4, 0, i3} )
}

Concretized Fusion:
Inputs:
  T0_g[ iS0{i0}, iS1{i2} ], float
  i3, int64_t
  i4, int64_t
  i5, int64_t
  i6, int64_t
Outputs:
  T2_g[ iS21{( i5 + i4 )}rf, iS22{( i6 + i3 )}rf ], float

%kernel_math {
T3_l[ iS15{3}rf, iS16{( ceilDiv(( i0 * i2 ), 3) )}rf ] = view( T0_g[ iS0{i0}, iS1{i2} ] )
T2_g[ iS21{( i5 + i4 )}rf, iS22{( i6 + i3 )}rf ]
   = pad( T3_l[ iS15{3}rf, iS16{( ceilDiv(( i0 * i2 ), 3) )}rf ], {0, i4, 0, i3} )
}

T0_g[ iS0{i0}, iS1{i2} ]
 root domain : (iS0{i0}, iS1{i2})
 contiguity: f f
 leaf domain : (iS0{i0}, iS1{i2})
T3_l[ iS15{3}rf, iS16{( ceilDiv(( i0 * i2 ), 3) )}rf ]
 root domain : (iS12{i0}rf, iS13{i2}rf)
  Merge: iS12{i0}rf and iS13{i2}rf -> iS14{( i0 * i2 )}rf
  Outer split: iS14{( i0 * i2 )}rf by factor 3 -> iS15{3}rf, iS16{( ceilDiv(( i0 * i2 ), 3) )}rf, start offset: 0, stop offset: 0
 rfactor domain : (iS15{3}rf, iS16{( ceilDiv(( i0 * i2 ), 3) )}rf)
 contiguity: t t
 leaf domain : (iS15{3}rf, iS16{( ceilDiv(( i0 * i2 ), 3) )}rf)
T2_g[ iS21{( i5 + i4 )}rf, iS22{( i6 + i3 )}rf ]
 root domain : (iS19{i5}rf, iS20{i6}rf)
  Resize: iS19{i5}rf by 0 and i4 -> iS21{( i5 + i4 )}rf
  Resize: iS20{i6}rf by 0 and i3 -> iS22{( i6 + i3 )}rf
 rfactor domain : (iS21{( i5 + i4 )}rf, iS22{( i6 + i3 )}rf)
 contiguity: t t
 leaf domain : (iS21{( i5 + i4 )}rf, iS22{( i6 + i3 )}rf)
  */

  FusionExecutorCache fusion_executor_cache(std::move(fusion_ptr));

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor at_x = at::randn({4, 3}, options);
  std::vector<c10::IValue> aten_inputs = {at_x, 1, 1, 3, 4};
  auto at_y = at::pad(at_x.reshape({3, 4}), {0, 1, 0, 1});

  auto outputs = fusion_executor_cache.runFusionWithInputs(aten_inputs);
  /*
terminate called after throwing an instance of 'c10::Error'
  what():  val.hasValue() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/executor.cpp":1039, please report a bug to
PyTorch. Tried to evaluate the extent, ( ceilDiv(( ( ( ( i5 * i6 ) + ( i5 * i3 ) ) + ( i4 * i6 ) ) + ( i4 * i3 ) ), 128) )
 for the ptype: blockIdx.x to set launch bounds but could not.
  */

  testValidate(
      fusion_executor_cache.fusion(),
      outputs,
      aten_inputs,
      {at_y},
      __LINE__,
      __FILE__);
}
```
The fusion gets segmented at `T3` and the second segment cannot evaluate the output extent, just like in #629. The fix in that case (#630) was to propagate the replaced extents during concretization. In this case that approach does not resolve the issue, since the downstream `pad` op builds an extent expression using the fusion inputs `i5` and `i6`. Although we register those values for mutation, the actual rfactor extents in `T2` are `i5 + i4` and `i6 + i3` so they are not replaced. It is not necessarily clear that replacing them before segmentation is always advantageous either: before segmentation we don't know if the original expression with fusion inputs, e.g. `i6 + i3`, will be easier to compute than the concretized one: `ceilDiv(( i0 * i2), 3) + i3`.

### PR DESCRIPTION
**Pull request by jacobhinkle**
During segmentation, groups are defined as lists of `Expr`s. When finalizing the segmentation, scalar inputs that might be needed are sprinkled in using `resolveScalarsInGroup`. The method `resolveScalarsInGroup` attempts to find all scalars needed in the group and adds their defining exprs to the group; in this way scalars can be recomputed for multiple groups if needed. When the `SegmentedGroup` is finalized, all expression inputs in all the `Expr`s in the group are added as inputs (deduplicated, removing constants, etc.).

Currently, `resolveScalarsInGroup` only processes the inputs of current `Expr`s to look for input scalars using `input->isScalar()`. As seen in #656, we also need to look at output extents in some cases. This PR modifies that method to look also at intermediate IterDomain expressions and their attributes, to more aggressively search for scalars.

Fixes #656.

### CODE REVIEW

**Comment by jacobhinkle** [comment]
Opened in error

**Comment by jacobhinkle** [comment]
!build

File: csrc/fusion_segmenter.cpp [hunk 1]
```diff
@@ -3579,11 +3579,65 @@ void SegmentCandidateFinder::resolveScalarsInGroup(SegmentedGroup* group) {
...
+      if (attr_val->isScalar()) {
+        to_visit.push_back(attr_val);
+      } else if (auto tv = dynamic_cast<TensorView*>(attr_val)) {
+        processTV(tv);
+      }
+    }
+    for (auto output : expr->outputs()) {
+      // We must be able to compute output extents for expression, so here we
+      // ensure the scalars involved are all available to this group
+      if (auto tv = dynamic_cast<TensorView*>(output)) {
```
Comment (naoyam) [inline csrc/fusion_segmenter.cpp:3639]: Do we have tests to exercise this case?

File: test/test_resize.cpp [hunk 2]
```diff
@@ -2758,6 +2758,87 @@ TEST_F(ResizeTest, SliceAndReshapeRepro540Manual) {
...
+  fusion.addInput(s0);
+  fusion.addInput(s1);
+  fusion.addInput(s2);
+  fusion.addInput(s3);
+
+  auto tv1 = reshape(tv0, {s2, s3});
+  auto tv2 = pad(tv1, {fusion.zeroVal(), s0, fusion.zeroVal(), s1});
+  fusion.addOutput(tv2);
+
+  FusionExecutorCache fusion_executor_cache(std::move(fusion_ptr));
```
Comment (naoyam) [inline test/test_resize.cpp:2785]: Can you please assert that the fusion is indeed segmented? That's not ideal and we definitely want to improve that.

File: csrc/fusion_segmenter.cpp (hunk 1 above)
Comment (jacobhinkle) [reply csrc/fusion_segmenter.cpp:3639]: The `ReshapeToPad` test hits this since the missing scalar appeared only in the root domain of the `pad` output in the second segment.

Comment (naoyam) [reply csrc/fusion_segmenter.cpp:3639]: Hmm, then the input tensor of the `pad` op should have the same extent, so shouldn't it use the same scalar?

Comment (jacobhinkle) [reply csrc/fusion_segmenter.cpp:3639]: In the unsegmented fusion the input has the same extent as you say. But when it is segmented the inputs have their roots set as the rfactor with new input scalars for the extents.

Comment (naoyam) [reply csrc/fusion_segmenter.cpp:3639]: > But when it is segmented the inputs have their roots set as the rfactor with new input scalars for the extents.

Are you referring to the inputs of a fusion segment?

Comment (jacobhinkle) [reply csrc/fusion_segmenter.cpp:3639]: Yes. In the test we have a segment with a single pad expression. In that case the expression input is a segment input so it has had its extents replaced.

Comment (naoyam) [reply csrc/fusion_segmenter.cpp:3639]: OK, so the pad input tensor becomes a segment input. It originally has the root and rfactor domains as it's the output of the reshape op, but we only keep the rfactor domain for segment inputs, so the input only has the root domain that was originally the rfactor domain. Am I right?

Still not sure why the pad output would be a problem...

Comment (jacobhinkle) [reply csrc/fusion_segmenter.cpp:3639]: I think you're right; the pad example does not need output scalars. However, the slice example from https://github.com/NVIDIA/Fuser/issues/656#issuecomment-1701593471 does need this. In that case the `slice` output contains `i5` which is not found in the segment and is exact mapped to the remapped rfactor->root of `T3`. The only way to find it is to traverse root->rfactor in the output of the `SliceOp`. In fact, I think since we have the segment input scalars and since every input to a segment expr is either a segment input or the output of another expr in the segment, it should suffice to look at only attributes and outputs of all expressions in the segment...

Comment (jacobhinkle) [reply csrc/fusion_segmenter.cpp:3639]: In #912 we see that even when we do not replace sizes with `ceilDiv` expressions in reshape, we can hit this problem. In that case there is no longer a problem in the second segment, but the first segment is 
```
Inputs:                                                                                                                          
  T0_g[ iS0{i0}, iS1{i2}, iS2{i3}, iS3{i4} ], float                                                                              
Outputs:                                                                                                                         
  T8_g[ iS40{i0}, iS47{( i2 / i5 )}rf, iS48{( (nvfuser_index_t)(i5) )}rf, iS42{i3}, iS43{i4} ], float                            
                                                                                                                                 
%kernel_math {                                                                                                                   
T8_g[ iS40{i0}, iS47{( i2 / i5 )}rf, iS48{( (nvfuser_index_t)(i5) )}rf, iS42{i3}, iS43{i4} ] = view( T0_g[ iS0{i0}, iS1{i2}, iS2{
i3}, iS3{i4} ] )                                                                                                                 
} 
```
and since `i5` is not an input to the `ViewOp`, it is not included as a segment input. We could of course have the new shapes included in `ViewOp::inputs()`instead which would also address this particular case.

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

File: csrc/fusion_segmenter.cpp (hunk 1 above)
Comment (naoyam) [reply csrc/fusion_segmenter.cpp:3654]: This makes sense and seems reasonable. Can you please leave a little more detailed comment why this is necessary?

**Review by naoyam — APPROVED** [review]
LGTM. Thanks for the fix.

**Comment by jacobhinkle** [comment]
I converted this back to draft since the current method is including more scalars than needed. Any root domain extent does not need to be included if it is exact mapped to an extent that is already computable. We could temporarily bind inputs to an `ExpressionEvaluator` and find `InputsOf` uncomputable scalars but that is a bit heavy handed. I will work on this then mark ready when this doesn't impact existing tests.

**Comment by jacobhinkle** [comment]
> I converted this back to draft since the current method is including more scalars than needed. Any root domain extent does not need to be included if it is exact mapped to an extent that is already computable. We could temporarily bind inputs to an `ExpressionEvaluator` and find `InputsOf` uncomputable scalars but that is a bit heavy handed. I will work on this then mark ready when this doesn't impact existing tests.

http://nv/e5M/nvfuser_github_ci/codegen_diff_p11175548_j76052171_1701449937649638555_codediff_a693a66_bdd502e_custom_command_20231201_164454.html
The differing test there shows this issue. The first kernel there has inputs `T0` and `T4`, so we should not also need to bind `i0, i1, i2, i3` which are the dimensions of `T0`, but we do after the change in this PR. This is because we are adding purely scalar expressions in `resolveScalarsInGroup` which then lead to adding their inputs in `resolveInputsInGroup`.

**Comment by jacobhinkle** [comment]
!build --diff

**Comment by jacobhinkle** [comment]
!build --diff

**Comment by jacobhinkle** [comment]
!build --diff

**Comment by jacobhinkle** [comment]
!build --diff

**Comment by jacobhinkle** [comment]
!build --diff

**Comment by jacobhinkle** [comment]
!build --diff

**Comment by jacobhinkle** [comment]
No test failures, and finally verified that this is never increasing the number of kernel args. Merging.
