### PR TITLE
Prevent self mapping in the AlmostExact graph

### LINKED ISSUE #3919: Test failed with  `Error replaying transforms in contiguous ID checker, expected iS10{9} to be in the active ID set.`
Repro:
```python
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id5(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[1, 1], contiguity=[None, None], dtype=DataType.Int, is_cpu=False, stride_order=[1, 0])
    S1 = fd.define_scalar(-2, dtype=DataType.Int)
    T7 = fd.ops.pad(T0, [0, 2, 0, 2], S1)
    fd.add_output(T7)

with FusionDefinition() as fd:
    nvfuser_fusion_id5(fd)

inputs = [
    torch.testing.make_tensor((1, 1), dtype=torch.int64, device='cuda:0'),
]
fd.execute(inputs)
```

Stacktrace:
```
Error replaying transforms in contiguous ID checker, expected iS10{9} to be in the active ID set.
Exception raised from checkExclusivelyConsumesAllocs at /opt/pytorch/nvfuser/csrc/contiguity.cpp:51 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x103 (0x7f3d6bb6010f in /opt/pytorch/nvfuser/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #1: nvfuser::nvfErrorFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x62 (0x7f3d6bf9fea2 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #2: <unknown function> + 0x3dd516 (0x7f3d6bdc0516 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
```

Env:
- pjnl-20250218 
- H100

This also caused thunder test to fail
```
pytest -vsx thunder/tests/test_ops.py -k test_core_vs_jax_consistency_pad_nvfuser_cuda_thunder
```

### PR DESCRIPTION
**Pull request by naoyam**
Fixes #3919 

The root cause of #3919 is there's a tensor that has a self mapping loop domain. Specifically:

```
// [1, 1]
tv0: [b1, b2]
// [3,3]
tv1 = pad(tv0, {1, 1, 1, 1});

tv0->merge(0, 1);
```

In this case, because the tv0 merge just uses broadcast IDs, all of the two input IDs and the output ID are mapped in the AlmostExact graph (see [here](https://github.com/NVIDIA/Fuser/blob/main/csrc/id_model/id_model.cpp#L435-L440)). That is also the case with [ComputeAtMap](https://github.com/NVIDIA/Fuser/blob/main/csrc/compute_at_map.cpp#L738-L748). That means `b1` and `b2` are mapped, which in turn means the two logical IDs of tv1 are also mapped since they use the same resize op.

While the mapping of `b1` and `b2` may not have any actual effect as they are just broadcast IDs, the mapping of the logical IDs of tv1 is problematic since they are concrete IDs. In the case of #3919, that manifests as the error in the contiguity analysis since it assumes no self mapping.

The fix in this PR is simply avoiding mapping `b1` and `b2`. More specifically, I extended `ValGraph` to exclude certain Vals from mapping. In the case of the AlmostExact graph, even when two IDs are trivially mapped, we no longer map them if they can result in self mapping. It may not sound ideal as they do have the same extent, but until we address the self mapping limitation, I think this is a reasonable workaround.

Note: I am not 100% confident if this might have any negative side effect. That is, the AlmostExact graph now lacks some mappings that do have the same extent. However, self mapping would certainly break TensorIndexer, so I think this is still reasonable.

### CODE REVIEW

**Comment by naoyam** [comment]
!test --diff

**Comment by naoyam** [comment]
!test --diff

**Comment by naoyam** [comment]
!test --diff

**Comment by naoyam** [comment]
!test --diff

File: csrc/id_model/id_model.cpp [hunk 1]
```diff
@@ -413,6 +415,12 @@ ValGraph& IdModel::buildExactGraph() {
 
   graph.validateConsistency();
 
+  // Make sure there's no self mapping in the Exact graph as that
+  // would invalidate lowering assumptions.
+  if (!allow_self_mapping_) {
+    assertNoSelfMapping(graph);
```
Comment (naoyam) [inline csrc/id_model/id_model.cpp:421]: Moved this check to `buildExactGraph`

File: csrc/id_model/id_model.h [hunk 2]
```diff
@@ -116,7 +116,7 @@ class IdModel : public PolymorphicBase {
       const std::vector<Expr*>& exprs,
       const std::vector<TensorView*>& additional_tvs = {},
       bool build_graphs = false,
-      bool allow_self_mapping = false,
+      bool allow_self_mapping = true,
```
Comment (naoyam) [inline csrc/id_model/id_model.h:119]: Changed to not check self mapping by default since that restriction only matters for indexing.

**Comment by naoyam** [comment]
!test --diff

**Comment by naoyam** [comment]
!test --diff

**Comment by xwang233** [comment]
!test --dev

**Comment by xwang233** [comment]
!test --dev

**Comment by naoyam** [comment]
!test --diff

**Review by zasdfgbnm — APPROVED** [review]
I don't like this approach, but I don't have better suggestions either.
