### PR TITLE
Explicitly mutate either Expr inputs or outputs in OptOutMutator

### LINKED ISSUE #852: Unexpected behavior in `OptOutMutator`
Simple usage patterns of `OptOutMutator` give confusing behavior; I have run into these while exploring concretization of symbolic fusions. We should more clearly express any limitations on the expected usage of the class.

# Scope

`OptOutMutator` is the only friend class of `IrContainer` and it is a `friend` to `TensorView` and so it's one of a handful of classes that can modify the `TensorDomain` of a tensor.  `OptOutMutator` is currently used as a parent class for
- `ValReplacementMutator` : used by `replaceValue`
- `ValReplacement::SubstituteInExpr` : used by `ir_utils::replaceValInExpr(Expr* expr, Val* reference, Val* substitute)` which substitutes replaces the given expression if any of its inputs, outputs, or attributes is `reference`, replacing it with `substitute`.
- `DynamicTransformConcretizer` : used to concretize symbolic fusions by traversing and mutating `TensorView`s and their associated `IterDomain`s.

# Example of confusing behavior

Here is the current docstring for `OptOutMutator`:
```c++
// Class to perform mutations on Fusion IR. Exprs can simply be redefined, but
// when mutating values they have to be registered through registerMutation so
// that exprs can detect there's been a muatation and know to modify all
// instances of that Val. This means each Val should be mutated "consistently".
// Otherwise behavior may be difficult to understand as it depends on which
// order mutate is called in. This class expects user to topologically call the
// statments of interest so inputs are called and mutated before exprs depending
// on them.
//
// Warning: TensorViews need to be treated carefully. As we don't generally
// register their mutation when their tensor domains only change. If a TV needs
// to be swapped out, it needs to be registered as a "proper" mutation like
// other vals, on top of TensorDomain being updated in the mutated TensorView.
```
Here is one use case from `TensorView::cacheBefore` where an output (`this`) of an expression is mutated using `ir_utils::replaceValInExpr`:
```c++
  // Insert producer - Cache_Before (CB) - before this TV.
  // Before: Prev TV -> [Definition Op] -> This TV
  // After:  Prev TV -> [Definition Op] -> New CB TV -> [Set Op] -> This TV

  // Get inputs for origin expression
  auto expr_inputs = definition()->inputs();
  // Expr* producer_definition =
  ir_utils::replaceValInExpr(definition(), this, producer);
```
This seems to work, since we use `cacheBefore` heavily and we do not see any errors. However, consider the following simple example:
```c++
// Test that OptOutMutator mutates expressions in a predictable way
TEST_F(NVFuserTest, OptOutMutatorMutatedOutput) {
  std::unique_ptr<Fusion> fusion_ptr = std::make_unique<Fusion>();
  Fusion* fusion = fusion_ptr.get();
  FusionGuard fg(fusion);

  TensorView* tv0 = makeSymbolicTensor(1);
  fusion->addInput(tv0);

  auto tv1 = neg(tv0);

  auto tv2 = set(tv1);
  fusion->addOutput(tv2);

  auto tv3 = set(tv0);

  fusion->printMath(/*from_outputs_only*/ false);
/*
Inputs:
  T0_g[ iS0{i0} ], float
Outputs:
  T2_g[ iS2{i0} ], float

%kernel_math {
T1_l[ iS1{i0} ]
   = -T0_g[ iS0{i0} ];
T2_g[ iS2{i0} ]
   = Set( T1_l[ iS1{i0} ] )
T3_l[ iS3{i0} ]
   = Set( T0_g[ iS0{i0} ] )
}
*/

  OptOutMutator mut;
  mut.registerMutation(tv1, tv3);
  mut.mutate(tv1->definition());

  fusion->printMath(/*from_outputs_only*/ false);
/*
Inputs:
  T0_g[ iS0{i0} ], float
Outputs:
  T2_g[ iS2{i0} ], float

%kernel_math {
T2_g[ iS2{i0} ]
   = Set( T1_l[ iS1{i0} ] )
T3_l[ iS3{i0} ]
   = -T0_g[ iS0{i0} ];
}
*/

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor t0 = at::randn({3}, options);

  FusionExecutor fe;
  fe.compileFusion(fusion);
/*
unknown file: Failure
C++ exception with description "thread_predicates_.find(tv_inp) != thread_predicates_.end() INTERNAL ASSERT FAILED at "/opt/pytor
ch/nvfuser/csrc/device_lower/analysis/thread_predicate.cpp":255, please report a bug with repro script to NVFuser at https://gith
ub.com/NVIDIA/Fuser/issues. Thread predicate map was not initialized, couldn't find T1_l[ iS5{( (( (( getMetaData(T0) )).logical_
size ))[0] )} ]
Exception raised from updateBitSet at /opt/pytorch/nvfuser/csrc/device_lower/analysis/thread_predicate.cpp:255 (most recent call
first):
*/

  auto outputs = fe.runFusion({t0});

  testValidate(fusion, outputs, {t0}, {t0}, __LINE__, __FILE__);
}
```
The `neg` op node was mutated, and its output `tv1` had been registered for mutation to `tv3`. When that happened, the definition was _transferred_ to `tv3`, which has the effect of redefining `tv3` to the original definition of `tv1`!

Compilation fails here; it seems that `T1` is removed from the fusion, and we were perhaps just lucky to avoid a segfault when printing the second time. In any event I would have expected to see the following mutated fusion:
```
Inputs:
  T0_g[ iS0{i0} ], float
Outputs:
  T2_g[ iS2{i0} ], float

%kernel_math {
T2_g[ iS2{i0} ]
   = Set( T3_l[ iS3{i0} ] )
T3_l[ iS3{i0} ]
   = Set( T0_g[ iS0{i0} ] )
}
```

# Suggested approach

I originally thought that we should just avoid mutating `Expr`s if only their outputs are registered for mutation, since this can have the effect of redefining the very `Val`s we had previously registered. However, the `cacheBefore` use case breaks in that case. We could salvage that by modifying `cacheBefore` to call `replaceValInExpr` on all uses of `this` instead. That is a typical pattern I use: replacing input and attribute vals in exprs, but not outputs. There may be other issues with this approach. I'm starting this issue to track this until we have a well-understood set of "guard rails" for mutating fusions.

### PR DESCRIPTION
**Pull request by jacobhinkle**
Fixes #852.

This PR:
- Changes `OptOutMutator::mutate(Expr* expr)` such that registered mutations of outputs of `expr` are not processed in that method. This means that if we register a `Val` for mutation then call `mutate` only on its definition, we will not wind up redefining that `Val` or its replacement.
- Adds `OptOutMutator::mutateExprOutputsOnly(Expr* expr)`, which does not replace any inputs or attributes to `expr`, but does replace outputs to the expression with registered mutations. This has the effect of transferring the definitions of those original outputs onto their registered replacements.
- Removes `ir_utils::replaceValInExpr`.
- Adds `ir_utils::replaceValInExprInputs`, which works similarly to the original `replaceValInExpr` but does not include the confusing output-mutating behavior. Most uses of `replaceValInExpr` are converted to use this directly.
- Adds `ir_utils::transferDefinitionToNewOutputs(Expr* expr, const std::vector<Val*>& new_outputs)`. Like `OptOutMutator::mutateExprOutputsOnly`, this does not replace inputs or attributes of `expr`, but creates a new `Expr` which serves as the definition of all members of `new_outputs`.

With these changes, registering a `Val` for mutation, then calling `OptOutMutator::dispatchMutate(stmt)` on all `Statement`s in topological order will produce the expected output and avoid strange cases like those outlined in #852.

Note that there is still one location that depends on the original behavior of `replaceValInExpr`: dynamic Fusion concretization. Currently, when propagating concretized `IterDomain`s from root to rfactor, we process `IterDomain` expressions in topological order then call `mutate(expr)`, which alters not only the inputs of each expression but also transfers that expression as the new definition for previously-undefined `IterDomain`s that were registered as mutations of the lhs of those expressions. In this PR, now we simply do this with two separate function calls, explaining that we need to transfer the expression as the new definition of the replacements, then we use the new `Expr` created in that step and mutate it so that its inputs are updated.

### CODE REVIEW

File: csrc/tensor_view.cpp [hunk 1]
```diff
@@ -1114,29 +1114,15 @@ TensorView* TensorView::cacheBefore(LoadStoreOpType cache_op) {
...
-         ir_utils::filterByType<TensorView>(definition()->inputs())) {
-      NVF_CHECK(
-          !producer_of_producer->hasComputeAt(),
-          "Potentially invalid computeAt and caching detected. Apply caching before computeAt.");
-    }
+  for (TensorView* producer_of_producer :
+       ir_utils::filterByType<TensorView>(definition()->inputs())) {
+    NVF_CHECK(
+        !producer_of_producer->hasComputeAt(),
+        "Potentially invalid computeAt and caching detected. Apply caching before computeAt.");
```
Comment (jacobhinkle) [inline csrc/tensor_view.cpp:1121]: If block was redundant with the above assertion.

File: csrc/ir/iostream.cpp [hunk 2]
```diff
@@ -92,6 +92,13 @@ void IrTransformPrinter::printTransforms(TensorView* tv) {
   auto root_domain = tv->getRootDomain();
   os() << " root domain : (" << toDelimitedString(root_domain) << ")\n";
 
+  if (tv->hasAllocation()) {
+    auto alloc_domain = tv->getAllocationDomain();
+
+    os() << " allocation domain : (" << toDelimitedString(alloc_domain)
+         << ")\n";
+  }
+
```
Comment (jacobhinkle) [inline csrc/ir/iostream.cpp:101]: Unrelated to this PR but helped debugging `test_allocation_domain.cpp` tests.

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

File: csrc/dispatch.h [hunk 3]
```diff
@@ -355,6 +355,9 @@ class TORCH_CUDA_CU_API OptOutMutator : public PolymorphicBase {
     if (mutations_.find(val) == mutations_.end()) {
       return val;
     }
+    // TODO: Check whether val is further mutated and throw error if so. This is
+    // to prevent errors where we depend on recursive mutation, which can be
+    // confusion/ambiguous to support.
```
Comment (jacobhinkle) [inline csrc/dispatch.h:360]: Not strictly necessary for this PR, but might be a good check to add?

File: csrc/ir/iostream.cpp [hunk 4]
```diff
@@ -89,17 +89,24 @@ void IrTransformPrinter::handle(Fusion* f) {
 }
 
 void IrTransformPrinter::printTransforms(TensorView* tv) {
-  auto root_domain = tv->getRootDomain();
+  const auto& root_domain = tv->getRootDomain();
   os() << " root domain : (" << toDelimitedString(root_domain) << ")\n";
 
+  if (tv->hasAllocation()) {
```
Comment (naoyam) [inline csrc/ir/iostream.cpp:95]: This seems fine but I wonder what the print out of a tensor should like. Should we also print the transformations between the allocation domain and the rfactor domain?

File: csrc/ir/utils.cpp [hunk 5]
```diff
@@ -191,12 +191,47 @@ struct SubstituteInExpr : public OptOutMutator {
...
+      new_outputs.size() == expr->outputs().size(),
+      "Number of new outputs must match old outputs");
+  OptOutMutator mutator;
+  for (const auto i : c10::irange(new_outputs.size())) {
+    auto old_output = expr->outputs().at(i);
+    auto new_output = new_outputs.at(i);
+    if (new_output == old_output) {
+      continue;
+    }
+    NVF_ERROR(
```
Comment (naoyam) [inline csrc/ir/utils.cpp:213]: Should we also assert that the new outputs are not like `3`?

File: csrc/mutator.cpp [hunk 6]
```diff
@@ -188,15 +194,18 @@ void OptOutMutator::mutate(Expr* op) {
   }
 
   if (all_same) {
-    return;
+    return op;
   }
 
   auto container = op->container();
   auto newObjectFunc = op->newObjectFunc();
+  const auto op_outputs = op->outputs();
```
Comment (naoyam) [inline csrc/mutator.cpp:202]: Unused?

File: test/test_dynamic_transform.cpp [hunk 7]
```diff
@@ -1188,4 +1188,76 @@ TEST_F(NVFuserTest, Issue249InputNegative1_CUDA) {
...
+
+  auto tv3 = set(tv0);
+
+  OptOutMutator mut;
+  mut.registerMutation(tv1, tv3);
+
+  for (auto stmt : StmtSort::getStmts(fusion)) {
+    mut.dispatchMutate(stmt);
+  }
+
```
Comment (naoyam) [inline test/test_dynamic_transform.cpp:1214]: Could you do some structural validation of the fusion? `tv3` should still be defined with the set op, not the neg op, and `tv2` should now has `tv3` as the input to its set op.

File: test/test_dynamic_transform.cpp [hunk 8]
```diff
@@ -1188,4 +1188,76 @@ TEST_F(NVFuserTest, Issue249InputNegative1_CUDA) {
...
+  // After the following mutation, it's reasonable to expect the input scalar s0
+  // to be ignored, and the output to just be ones.
+  OptOutMutator mut;
+  mut.registerMutation(s1, fusion->oneVal(DataType::Int));
+
+  for (auto stmt : StmtSort::getStmts(fusion)) {
+    mut.dispatchMutate(stmt);
+  }
+
```
Comment (naoyam) [inline test/test_dynamic_transform.cpp:1249]: Ditto

File: csrc/dynamic_transform.cpp [hunk 9]
```diff
@@ -668,9 +672,10 @@ void DynamicTransformConcretizer::mutate(TensorView* tv) {
         registerConcretization(out_id, concretized_out_id);
       }
 
-      // expr must be mutated in order to set it as the definition for the
-      // concretized outputs.
-      OptOutMutator::mutate(expr);
+      // Set expr as the definition for concretized outputs
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:675]: Please leave some more detailed comments why this needs to be done in this order.

File: csrc/dynamic_transform.cpp [hunk 10]
```diff
@@ -457,8 +457,12 @@ void DynamicTransformConcretizer::concretize() {
       /*traverse_members*/ true,
       /*traverse_attributes*/ true,
       /*traverse_siblings*/ true);
-  for (auto tv : ir_utils::filterByType<TensorView>(all_stmts)) {
-    mutate(tv);
+  for (auto stmt : all_stmts) {
+    if (const auto op = dynamic_cast<Expr*>(stmt); stmt->isA<IterDomain>() ||
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:461]: Please comment which types of statements should be visited and why.

File: csrc/dynamic_transform.cpp [hunk 11]
```diff
@@ -772,7 +777,8 @@ bool DynamicTransformConcretizer::propagateFromProducerToConsumer(
 
       auto input_id = c2p.at(root_id);
       NVF_ERROR(
-          input_id->getIterType() != IterType::Symbolic,
+          input_id == maybeMutated(input_id) &&
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:780]: I'd like to see more descriptive error message if this isn't the case. For example, I'd like to see what `maybeMutated(input_id)` would look like. 

Shouldn't this assertion and the one below about itertype separated?

**Review by naoyam — COMMENTED** [review]
Looks good overall. Just some minor comments.

**Comment by naoyam** [comment]
@jacobhinkle Could you also add assertions somewhere that expr outputs shouldn't be static constant values like `3`. Doesn't need to be in this PR.

**Review by zasdfgbnm — COMMENTED** [review]
Can this be cleaned up now, or it is unrelated to this PR?

https://github.com/NVIDIA/Fuser/blob/178ed873baed1ad9b8e9bc2070551f0bb1f23f1f/csrc/device_lower/utils.cpp#L460-L581

File: csrc/ir/utils.h [hunk 12]
```diff
@@ -164,20 +164,31 @@ std::vector<int> normalizeOld2New(
...
-// Warning: Invalidates provided Expr.
-// Warning: Removes connection of reference through provided Expr.
-// Warning: Creates new Expr connecting substitue.
-// Reference is found through direct pointer comparison.
-TORCH_CUDA_CU_API Expr* replaceValInExpr(
+//! Replaces reference Val with substitute in all Expr inputs and attributes.
+//! Warning: Invalidates provided Expr.
+//! Warning: Removes connection of reference through provided Expr.
+//! Warning: Creates new Expr defining substitute.
+TORCH_CUDA_CU_API Expr* replaceValInExprInputs(
```
Comment (zasdfgbnm) [inline csrc/ir/utils.h:171]: How is this different from https://github.com/NVIDIA/Fuser/blob/178ed873baed1ad9b8e9bc2070551f0bb1f23f1f/csrc/device_lower/utils.h#L168-L176? Can we unify them?

File: csrc/dispatch.h (hunk 3 above)
Comment (jacobhinkle) [reply csrc/dispatch.h:360]: Yes exactly. I didn't do it yet since I wanted to verify that two-hop mutations wouldn't make sense in any of the current use cases. I believe that's true. I will add an assertion with a note that if that's needed in the future we should add an explicit interface for it then.

File: csrc/ir/iostream.cpp (hunk 4 above)
Comment (jacobhinkle) [reply csrc/ir/iostream.cpp:95]: Yeah, I was wondering how best to print it. Since allocation to rfactor will commonly not have any transforms, it's probably best to print them, so that they jump out at us. If allocation domain is just a permutation of rfactor then it will be more subtle, but the information is still there. I'll add the alloc->rfactor transforms.

File: csrc/ir/utils.cpp (hunk 5 above)
Comment (jacobhinkle) [reply csrc/ir/utils.cpp:213]: Oh very good idea. This would've helped me find bugs in concretization code sooner.

File: csrc/ir/utils.h (hunk 12 above)
Comment (jacobhinkle) [reply csrc/ir/utils.h:171]: Yeah that is the kernel version of this. The `ReplaceExprInput` class is a `kir::ExprMutator` that behaves pretty  similarly to what `OptOutMutator` does now, but since it is expression tree-based it keeps track of scopes, positions, and predicates of replaced expressions. Currently it has a separate `handle()` override for each handled expression type; we could probably just compose this class with `OptOutMutator` and call `OptOutMutator::mutate` to create replacements. That might simplify the `ReplaceExprInput` class a bit.

File: csrc/dynamic_transform.cpp (hunk 11 above)
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp]: Indeed. Done.

**Review by naoyam — APPROVED** [review]
LGTM. 

I agree with @zasdfgbnm that there's something we should clean up regarding the two mutator classes. That should be a separate PR, I think.
