### PR TITLE
Issue 4086

### LINKED ISSUE #4086: TestNvFuserFrontend::test_broadcast_mixing corrupts memory.
This was detected by asan. However, it can be reproduced without it if you apply the following change: 

```diff
diff --git a/csrc/preseg_passes/allocation_order_inference.cpp b/csrc/preseg_passes/allocation_order_inference.cpp
index f7ab6dda..b56a08e2 100644
--- a/csrc/preseg_passes/allocation_order_inference.cpp
+++ b/csrc/preseg_passes/allocation_order_inference.cpp
@@ -314,8 +314,8 @@ void inferenceAllocationOrder(
         // allocation domain
         for (auto i : c10::irange(ref->nDims())) {
           if (!val_sets.permissiveAreMapped(
-                  ref->getMaybeAllocationDomain()[i],
-                  tv->getMaybeAllocationDomain()[i])) {
+                  ref->getMaybeAllocationDomain().at(i),
+                  tv->getMaybeAllocationDomain().at(i))) {
             // reset ref to nullptr, while keeping the iterdomain count high
             // water mark. No propagation will occur unless we found another ref
             // candidate with a higher iterdomain count.
```

```
$ DEBUG_BUILD=1 _bn && DEBUG_SERDE=debug pytest tests/python/test_python_frontend.py -s -v -k test_broadcast_mixing

FAILED tests/python/test_python_frontend.py::TestNvFuserFrontend::test_broadcast_mixing - IndexError: vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
```

### PR DESCRIPTION
**Pull request by jjsjann123**
Fixes #4086 

The old code comparing the permissive mapping among reference candidates in allocation domain inference needs to compare only non-trivial allocation domain.
The existing code compares their allocation domain directly and there's no guarantee that those are of the same rank, hence triggering out of bound access.

Instead of adding a new test, I switched to bound-check access instead.

### CODE REVIEW

**Comment by jjsjann123** [comment]
!test

File: csrc/preseg_passes/allocation_order_inference.cpp [hunk 1]
```diff
@@ -309,13 +316,16 @@ void inferenceAllocationOrder(
       // found multiple candidate with the same iterdomain count
       if (non_trivial_iter_count[tv] == non_bc_high_water_mark &&
           ref != nullptr) {
+        std::vector<IterDomain*> ref_alloc_non_trivial =
+            nonTrivialIterDomains(ref);
+        std::vector<IterDomain*> tv_alloc_non_trivial =
+            nonTrivialIterDomains(tv);
```
Comment (wujingyue) [inline csrc/preseg_passes/allocation_order_inference.cpp:322]: Should we NVF_ERROR they are the same size?

File: csrc/preseg_passes/allocation_order_inference.cpp [hunk 2]
```diff
@@ -309,13 +316,16 @@ void inferenceAllocationOrder(
...
         // ensure that there's no ambiguity on permutation mapping from multiple
         // references. we need both ref candidates to have the same mapping on
         // allocation domain
-        for (auto i : c10::irange(ref->nDims())) {
+        for (auto i : c10::irange(ref_alloc_non_trivial.size())) {
```
Comment (wujingyue) [inline csrc/preseg_passes/allocation_order_inference.cpp:326]: If you NVF_ERROR same size as suggested above, consider `zip` to simplify the code

File: csrc/preseg_passes/allocation_order_inference.cpp [hunk 3]
```diff
@@ -16,6 +16,13 @@ namespace nvfuser::preseg_passes {
 
 namespace {
 
+// returning non-broadcast & non-reduction iter domains in tv's allocation
```
Comment (wujingyue) [inline csrc/preseg_passes/allocation_order_inference.cpp:19]:
```suggestion
// Returns non-broadcast & non-reduction iter domains in tv's allocation
```

**Review by wujingyue — APPROVED** [review]

**Comment by jjsjann123** [comment]
!test

**Comment by jjsjann123** [comment]
!test

**Comment by jjsjann123** [comment]
!test

**Comment by jjsjann123** [comment]
failure are in thunder sdpa. merging this PR as-is.
