### PR TITLE
Fix a segmentation bug with input forwarding. 

### LINKED ISSUE #1541: Simple slice fusion fails to segment
Minimal repro:
```python
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id1(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[-1], contiguity=[True], dtype=DataType.BFloat16)
    T1 = fd.ops.neg(T0)
    T2 = fd.ops.slice(T1, start_indices=[0], end_indices=[5])
    fd.add_output(T2)

with FusionDefinition() as fd:
    nvfuser_fusion_id1(fd)

inputs = [
    torch.randn((10,), dtype=torch.bfloat16, device='cuda:0')
]
fd.execute(inputs)
```
This fails with `Can not find a scheduler to schedule fusion segment`. `NVFUSER_DUMP=segmenter_logging` shows:
```
***Runtime***: Try to schedule fusion un-segmented:

Scheduler _no_op_ ***rejected*** because : output has a concrete dimension
Scheduler _reduction_ ***rejected*** because : No reduction op to schedule
Scheduler _transpose_ ***rejected*** because : First input of SliceOp must be fusion input.
Scheduler _pointwise_ ***rejected*** because : First input of SliceOp must be fusion input.
Scheduler _inner_persistent_ ***rejected*** because : needs a reduction op
Scheduler _outer_persistent_ ***rejected*** because : needs a reduction op
Scheduler _inner_outer_persistent_ ***rejected*** because : needs a reduction op
Scheduler _matmul_ ***rejected*** because : Matmul scheduler supports fusions only with a single MMA op, got: 0

**Segmenter** Considering fusion:
i13 = fmin(i0, 5);
i15 = fmax(0, i13);
T2_g[ iS4{( i0 + ( ( fmax(0, ( fmin(i0, 5) )) ) + ( -i0 ) ) )}rf ]
   = slice( T1_g[ iS1{i0} ], { {0, i15, 1} } )

Scheduler _no_op_ ***rejected*** because : output has a concrete dimension
Scheduler _reduction_ ***rejected*** because : No reduction op to schedule
Scheduler _transpose_ ***rejected*** because : cannot find two mismatching inner most dimensions
Scheduler _transpose_ ***rejected*** because : cannot find two mismatching inner most dimensions
***Accepted*** as: pointwise

**Segmenter** Considering fusion:
T1_g[ iS1{i0} ]
   = -T0_g[ iS0{i0} ];
i13 = fmin(i0, 5);
i15 = fmax(0, i13);
T2_g[ iS4{( i0 + ( ( fmax(0, ( fmin(i0, 5) )) ) + ( -i0 ) ) )}rf ]
   = slice( T1_g[ iS1{i0} ], { {0, i15, 1} } )

Scheduler _no_op_ ***rejected*** because : output has a concrete dimension
Scheduler _reduction_ ***rejected*** because : No reduction op to schedule
Scheduler _transpose_ ***rejected*** because : First input of SliceOp must be fusion input.
Scheduler _pointwise_ ***rejected*** because : First input of SliceOp must be fusion input.
Scheduler _inner_persistent_ ***rejected*** because : needs a reduction op
Scheduler _outer_persistent_ ***rejected*** because : needs a reduction op
Scheduler _inner_outer_persistent_ ***rejected*** because : needs a reduction op
Scheduler _matmul_ ***rejected*** because : Matmul scheduler supports fusions only with a single MMA op, got: 0
An error occurred while executing nvFuser FusionDefinition 1.
```

### PR DESCRIPTION
**Pull request by wujingyue**
This PR takes code from @naoyam's #1559 and restructures it. 

Before this PR, nvFuser resolves forwarded inputs by unconditionally pulling in their dependencies into the group. This was problematic (#1541) because a group may require a resize op to only appear as an input. This PR fixes #1541 by checking the dependencies are indeed mergeable before pulling them in.

### CODE REVIEW

**Comment by wujingyue** [comment]
I saw several unit tests failing, e.g., FusionExpand_CUDA. Investigating...

**Comment by wujingyue** [comment]
!build

File: csrc/fusion_segmenter.cpp [hunk 1]
```diff
@@ -3848,14 +3850,54 @@ void SegmentCandidateFinder::findSegments() {
...
+      // Will be resolved after this loop.
+      continue;
+    }
+
+    resolveInputGroup(aux_group, forwarded_input);
+    // aux_group will be removed from segmented_fusion_ by
+    // cleanupForwardedInputs.
+  }
+
+  // Un-forward scalar inputs unconditionally. The loop above doesn't resolve
```
Comment (naoyam) [inline csrc/fusion_segmenter.cpp:3870]: Is this necessary? After this part, there's a call to `finalize`, which calles `resolveScalarsInGroup`. All necessary scalars included forwarded ones are resolved there.

**Comment by naoyam** [comment]
Thanks for finishing up the fix!

File: csrc/fusion_segmenter.cpp (hunk 1 above)
Comment (wujingyue) [reply csrc/fusion_segmenter.cpp:3870]: That's what I initially thought but FusionExpand_CUDA (and some others) failed without this. The failure was around https://github.com/NVIDIA/Fuser/blob/925acc63e5870718ab83de911ec7f85d6126f729/csrc/kernel_cache.cpp#L400-L404. I saw a scalar group input was never ready because it wasn't a fusion input. If you believe resolveScalarsInGroup should forward scalar inputs, then it must be a bug there.

Comment (naoyam) [reply csrc/fusion_segmenter.cpp:3870]: Ahh, makes sense. It was previously done in `resolveInputsInGroup` together with tensor inputs.

**Review by naoyam — APPROVED** [review]
The fix makes sense. Feel free to merge it whenever ready.

**Comment by wujingyue** [comment]
Some python tests are failing, e.g., `pytest python_tests/test_python_frontend.py -k 1706 -v -s `. It may be related to serialization, so cc @rdspring1. Indicators are:
1. Removing `@serde_check` before `exec_nvfuser` makes the test pass. 
2. Even with `@serde_check` removed, I sometimes see warnings such as the following. 

```
python_tests/test_python_frontend.py::TestNvFuserFrontend::test_issue1706 Warning: Failed to deserialize common workspace.
A new workspace will be saved upon program exit after deleting incompatible workspace.
toUnderlying(heuristic) == buffer->heuristic() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/executor.cpp":2239, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. 
Exception raised from deserialize at /opt/pytorch/nvfuser/csrc/executor.cpp:2239 (most recent call first):
```

**Comment by wujingyue** [comment]
I narrowed down the problem to `test_issue1706`, because `_bn && pytest python_tests/test_python_frontend.py -k 'not 1706' -v -s` is able to pass. 

(The only potential concern was the following warning, which however appears in TOT as well)

```
======================================================== warnings summary ========================================================
python_tests/test_python_frontend.py::TestNvFuserFrontend::test_var_correction
  /opt/pytorch/nvfuser/python_tests/test_python_frontend.py:1357: UserWarning: var(): degrees of freedom is <= 0. Correction should be strictly less than the reduction factor (input numel divided by output numel). (Triggered internally at /opt/pytorch/pytorch/aten/src/ATen/native/ReduceOps.cpp:1776.)
    torch_result = torch.var(inputs[0], [-1], correction=correction)

python_tests/test_python_frontend.py::TestNvFuserFrontend::test_var_mean_correction
  /opt/pytorch/nvfuser/python_tests/test_python_frontend.py:1341: UserWarning: var_mean(): degrees of freedom is <= 0. Correction should be strictly less than the reduction factor (input numel divided by output numel). (Triggered internally at /opt/pytorch/pytorch/aten/src/ATen/native/ReduceOps.cpp:1776.)
    torch_result = torch.var_mean(inputs[0], [-1], correction=correction)

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=============================== 88 passed, 1 skipped, 1 deselected, 2 warnings in 97.93s (0:01:37) ===============================
```

**Comment by wujingyue** [comment]
The interesting part: when I ran just that test (`pytest python_tests/test_python_frontend.py -k '1706' -v -s`), the result was non-deterministic, one of the following: 
1. passing. 
2. number mismatch. 
    ```
    E           AssertionError: Tensor-likes are not close!
    E           
    E           Mismatched elements: 16777216 / 16777216 (100.0%)
    E           Greatest absolute difference: nan at index (0, 0, 0) (up to 1e-05 allowed)
    E           Greatest relative difference: nan at index (0, 0, 0) (up to 0.016 allowed)
    E           
    E           To execute this test, run the following from the base repo dir:
    E                python test_python_frontend.py -k test_issue1706
    E           
    E           This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
    
    python_tests/test_python_frontend.py:146: AssertionError
    ```
3. Failed to serialize
    ```
    RuntimeError: compiled_kernel_ != nullptr && (!compiled_kernel->cubin.empty() || !compiled_kernel->ptx.empty()) INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/executor.cpp":2102, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Expected compiled cuda kernel before serializing FusionExecutor.
    ```
4. Failed to deserialize. 
    ```
    python_tests/test_python_frontend.py::TestNvFuserFrontend::test_issue1706 Warning: Failed to deserialize common workspace.
    A new workspace will be saved upon program exit after deleting incompatible workspace.
    toUnderlying(heuristic) == buffer->heuristic() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/executor.cpp":2239, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. 
    ```

**Comment by wujingyue** [comment]
Regarding the deserialization failure (the fourth outcome), apparently, `runtime_workspace_.group_run_order` and the executor order in `serde::FusionKernelRuntime::executors` are different. In this particular case, there are two segments, one using PointWise and the other using InnerOuterPersisitent. In `group_run_order`, the InnerOuterPersistent segment appears first. In `serde::FusionKernelRuntime`, the PointWise segment appears first. 

```
(gdb) f 4 
#4  0x00007ffedf15c8e7 in nvfuser::FusionKernelRuntime::deserialize (this=0x7fff4efb5e00, buffer=0x7ffef26ebf10, 
    device_index=0 '\000') at /opt/pytorch/nvfuser/csrc/kernel_cache.cpp:1148
1148        executors_.at(group_id).deserialize(
(gdb) l 
1143            "Heuristics do not match.");
1144        std::unique_ptr<Fusion> fusion_to_run = segmented_fusion_->makeFusion(sg);
1145        FusionGuard fg(fusion_to_run.get());
1146        scheduler_entry->schedule(fusion_to_run.get());
1147
1148        executors_.at(group_id).deserialize(
1149            buffer->executors()->Get(group_id),
1150            fusion_to_run.get(),
1151            device_index,
1152            scheduler_entry->params()->cparams,
(gdb) p buffer->executors()->Get(0)->heuristic() 
$12 = 2
(gdb) p buffer->executors()->Get(1)->heuristic() 
$13 = 6
(gdb) p runtime_workspace_.group_run_order.at(0)->heuristic() 
$14 = nvfuser::ScheduleHeuristic::InnerOuterPersistent
(gdb) p runtime_workspace_.group_run_order.at(1)->heuristic() 
$15 = nvfuser::ScheduleHeuristic::PointWise
```

Note: toUnderlying(PointWise) = 2 and toUnderlying(InnerOuterPersistent) == 6.

**Comment by wujingyue** [comment]
I'm not 100% sure about this but here's my theory: 

Serialization assumes a deterministic ID assignment and therefore assumes `SegmentedFusion::groups()` to follow a deterministic order: https://github.com/NVIDIA/Fuser/blob/417ec4b4bd7f2020b11388ce7d6ba0ae3cc40b6b/csrc/fusion_segmenter.cpp#L4235-L4238

This assumption is broken by this PR at https://github.com/NVIDIA/Fuser/pull/1825/files#diff-e2f2ad44a6dc03e4ad8e5f0f047be25eb1c142add431d48c1e046c968a577f3bR3854. Iterating through an unordered_map has a non-deterministic order. Therefore, in a non-deterministic order, the input groups are added and merged.

**Comment by wujingyue** [comment]
!build

**Comment by rdspring1** [comment]
Yes, serialization expects segmentation to be deterministic for the same fusion, input arguments, etc. There isn't O(1) time function to reconcile segmented groups to their fusions. You'd have to check the segmented fusions directly to find a match.

**Comment by wujingyue** [comment]
Unit tests are passing: https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/pipelines/13097732. The failed ones are pre-existing.

File: test/test_segmentation.cpp [hunk 2]
```diff
@@ -282,4 +291,42 @@ TEST_F(SegmentationTest, InputForwardingUntilOutput) {
       fec.fusion(), out_tensors, {in_tensor, in_tensor}, __LINE__, __FILE__);
 }
 
+TEST_F(SegmentationTest, ForwardedExprsAreNotMergeable) {
+  auto fusion = std::make_unique<Fusion>();
+  FusionGuard fg(fusion.get());
+
+  auto tv0 = makeSymbolicTensor(1);
```
Comment (jacobhinkle) [inline test/test_segmentation.cpp:298]: Sorry, I missed this on first review. This does not repro #1541 exactly since that issue used half precision inputs, which will behave differently in segmentation due to `castInputOutputToLowerPrecision()`.
