### PR TITLE
Fix max logical domain propagation with resize

### LINKED ISSUE #3801: Inconsistent parallelization found with cat, slice, matmul, linear in the fusion definition
When I enabled sending linears and matmuls to the nvFuser executor in Thunder by default I got several test failures. Here's one of them:
```py
RuntimeError:  INTERNAL ASSERT FAILED at "/home/iyashchuk/dev/Fuser/csrc/runtime/fusion_kernel_runtime.cpp":407
```
Here's a script to reproduce the error:
```python
# CUDA devices:
#  0: NVIDIA RTX 6000 Ada Generation
#  1: NVIDIA RTX 6000 Ada Generation
# torch version: 2.7.0a0+git1335882
# cuda version: 12.8
# nvfuser version: 0.2.25+git6b0b17e
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id0(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[1, 4, 3, 16], contiguity=[None, True, True, True], dtype=DataType.Float, is_cpu=False, stride_order=[3, 2, 1, 0])
    T1 = fd.define_tensor(shape=[1, 4, 3, 16], contiguity=[None, True, True, True], dtype=DataType.Float, is_cpu=False, stride_order=[3, 2, 1, 0])
    T2 = fd.define_tensor(shape=[1, 4, 3, 16], contiguity=[None, True, True, True], dtype=DataType.Float, is_cpu=False, stride_order=[3, 2, 1, 0])
    T3 = fd.define_tensor(shape=[1, 4, 3, 16], contiguity=[None, True, True, True], dtype=DataType.Float, is_cpu=False, stride_order=[3, 2, 1, 0])
    T4 = fd.define_tensor(shape=[1, 4, 1, 16], contiguity=[None, None, True, True], dtype=DataType.Float, is_cpu=False, stride_order=[3, 1, 2, 0])
    T5 = fd.define_tensor(shape=[64, 64], contiguity=[True, True], dtype=DataType.Float, is_cpu=False, stride_order=[1, 0])
    T6 = fd.define_tensor(shape=[1, 1, 64], contiguity=[None, None, True], dtype=DataType.Float, is_cpu=False, stride_order=[2, 1, 0])
    T7 = fd.define_tensor(shape=[64], contiguity=[True], dtype=DataType.Float, is_cpu=False, stride_order=[0])
    T8 = fd.define_tensor(shape=[1376, 64], contiguity=[True, True], dtype=DataType.Float, is_cpu=False, stride_order=[1, 0])
    T9 = fd.define_tensor(shape=[1376, 64], contiguity=[True, True], dtype=DataType.Float, is_cpu=False, stride_order=[1, 0])
    T10 = fd.define_tensor(shape=[64, 1376], contiguity=[True, True], dtype=DataType.Float, is_cpu=False, stride_order=[1, 0])
    T11 = fd.define_tensor(shape=[64], contiguity=[True], dtype=DataType.Float, is_cpu=False, stride_order=[0])
    T12 = fd.define_tensor(shape=[192, 64], contiguity=[True, True], dtype=DataType.Float, is_cpu=False, stride_order=[1, 0])
    T13 = fd.define_tensor(shape=[1, 16], contiguity=[None, True], dtype=DataType.Float, is_cpu=False, stride_order=[1, 0])
    T14 = fd.define_tensor(shape=[1, 16], contiguity=[None, True], dtype=DataType.Float, is_cpu=False, stride_order=[1, 0])
    T15 = fd.ops.set(T0)
    fd.add_output(T15, T1)
    T16 = fd.ops.set(T2)
    fd.add_output(T16, T3)
    T17 = fd.ops.permute(T4, dims=[0, 2, 1, 3])
    T22 = fd.ops.reshape(T17, new_shape=[1, 1, 64])
    T23 = fd.ops.linear(T22, T5)
    T24 = fd.ops.add(T23, T6)
    T25 = fd.ops.mul(T24, T24)
    T26 = fd.ops.sum(T25, dims=[2], keepdim=False, dtype=DataType.Null)
    T31 = fd.ops.broadcast_in_dim(T26, shape=[1, 1, 1], broadcast_dims=[0, 1])
    S32 = fd.define_scalar(64.0000, dtype=DataType.Double)
    S33 = fd.ops.reciprocal(S32)
    T34 = fd.ops.mul(T31, S33)
    S35 = fd.define_scalar(1.00000e-05, dtype=DataType.Double)
    T36 = fd.ops.add(T34, S35)
    T37 = fd.ops.rsqrt(T36)
    T42 = fd.ops.broadcast_in_dim(T37, shape=[1, 1, 64], broadcast_dims=[0, 1, 2])
    T43 = fd.ops.mul(T24, T42)
    T48 = fd.ops.broadcast_in_dim(T7, shape=[1, 1, 64], broadcast_dims=[2])
    T49 = fd.ops.mul(T43, T48)
    T50 = fd.ops.linear(T49, T8)
    T51 = fd.ops.linear(T49, T9)
    T52 = fd.ops.neg(T50)
    T53 = fd.ops.exp(T52)
    S54 = fd.define_scalar(1.00000, dtype=DataType.Double)
    T55 = fd.ops.add(S54, T53)
    T56 = fd.ops.reciprocal(T55)
    T57 = fd.ops.mul(T50, T56)
    T58 = fd.ops.mul(T57, T51)
    T59 = fd.ops.linear(T58, T10)
    T60 = fd.ops.add(T59, T24)
    T61 = fd.ops.mul(T60, T60)
    T62 = fd.ops.sum(T61, dims=[2], keepdim=False, dtype=DataType.Null)
    T67 = fd.ops.broadcast_in_dim(T62, shape=[1, 1, 1], broadcast_dims=[0, 1])
    S68 = fd.define_scalar(64.0000, dtype=DataType.Double)
    S69 = fd.ops.reciprocal(S68)
    T70 = fd.ops.mul(T67, S69)
    S71 = fd.define_scalar(1.00000e-05, dtype=DataType.Double)
    T72 = fd.ops.add(T70, S71)
    T73 = fd.ops.rsqrt(T72)
    T78 = fd.ops.broadcast_in_dim(T73, shape=[1, 1, 64], broadcast_dims=[0, 1, 2])
    T79 = fd.ops.mul(T60, T78)
    T84 = fd.ops.broadcast_in_dim(T11, shape=[1, 1, 64], broadcast_dims=[2])
    T85 = fd.ops.mul(T79, T84)
    T86 = fd.ops.linear(T85, T12)
    T93 = fd.ops.reshape(T86, new_shape=[1, 1, 4, 3, 16])
    T94 = fd.ops.permute(T93, dims=[0, 2, 3, 1, 4])
    T113 = fd.ops.slice(T94, start_indices=[0, 0, 0, 0, 0], end_indices=[1, 4, 1, 1, 16], strides=[1, 1, 1, 1, 1], manual_normalization=0)
    T132 = fd.ops.slice(T94, start_indices=[0, 0, 1, 0, 0], end_indices=[1, 4, 2, 1, 16], strides=[1, 1, 1, 1, 1], manual_normalization=0)
    T151 = fd.ops.slice(T94, start_indices=[0, 0, 2, 0, 0], end_indices=[1, 4, 3, 1, 16], strides=[1, 1, 1, 1, 1], manual_normalization=0)
    T157 = fd.ops.reshape(T113, new_shape=[1, 4, 1, 16])
    T163 = fd.ops.reshape(T132, new_shape=[1, 4, 1, 16])
    T169 = fd.ops.reshape(T151, new_shape=[1, 4, 1, 16])
    T185 = fd.ops.slice(T157, start_indices=[0, 0, 0, 0], end_indices=[1, 4, 1, 8], strides=[1, 1, 1, 1], manual_normalization=0)
    T201 = fd.ops.slice(T157, start_indices=[0, 0, 0, 8], end_indices=[1, 4, 1, 16], strides=[1, 1, 1, 1], manual_normalization=0)
    T202 = fd.ops.neg(T201)
    T203 = fd.ops.cat([T202, T185], dim=-1, manual_padding=0)
    T208 = fd.ops.broadcast_in_dim(T13, shape=[1, 1, 16], broadcast_dims=[1, 2])
    T213 = fd.ops.broadcast_in_dim(T14, shape=[1, 1, 16], broadcast_dims=[1, 2])
    T219 = fd.ops.broadcast_in_dim(T208, shape=[1, 4, 1, 16], broadcast_dims=[1, 2, 3])
    T220 = fd.ops.mul(T157, T219)
    T226 = fd.ops.broadcast_in_dim(T213, shape=[1, 4, 1, 16], broadcast_dims=[1, 2, 3])
    T227 = fd.ops.mul(T203, T226)
    T228 = fd.ops.add(T220, T227)
    T244 = fd.ops.slice(T163, start_indices=[0, 0, 0, 0], end_indices=[1, 4, 1, 8], strides=[1, 1, 1, 1], manual_normalization=0)
    T260 = fd.ops.slice(T163, start_indices=[0, 0, 0, 8], end_indices=[1, 4, 1, 16], strides=[1, 1, 1, 1], manual_normalization=0)
    T261 = fd.ops.neg(T260)
    T262 = fd.ops.cat([T261, T244], dim=-1, manual_padding=0)
    T263 = fd.ops.mul(T163, T219)
    T264 = fd.ops.mul(T262, T226)
    T265 = fd.ops.add(T263, T264)
    T281 = fd.ops.slice(T157, start_indices=[0, 0, 0, 0], end_indices=[1, 4, 1, 0], strides=[1, 1, 1, 1], manual_normalization=0)
    T282 = fd.ops.cat([T228, T281], dim=-1, manual_padding=0)
    T298 = fd.ops.slice(T163, start_indices=[0, 0, 0, 0], end_indices=[1, 4, 1, 0], strides=[1, 1, 1, 1], manual_normalization=0)
    T299 = fd.ops.cat([T265, T298], dim=-1, manual_padding=0)
    fd.add_output(T3)
    fd.add_output(T60)
    fd.add_output(T169)
    fd.add_output(T282)
    fd.add_output(T299)

with FusionDefinition() as fd:
    nvfuser_fusion_id0(fd)

inputs = [
    torch.testing.make_tensor((1, 4, 3, 16), dtype=torch.float32, device='cuda:0'),
    torch.testing.make_tensor((1, 4, 3, 16), dtype=torch.float32, device='cuda:0'),
    torch.testing.make_tensor((1, 4, 3, 16), dtype=torch.float32, device='cuda:0'),
    torch.testing.make_tensor((1, 4, 3, 16), dtype=torch.float32, device='cuda:0'),
    torch.testing.make_tensor((1, 4, 1, 16), dtype=torch.float32, device='cuda:0'),
    torch.testing.make_tensor((64, 64), dtype=torch.float32, device='cuda:0'),
    torch.testing.make_tensor((1, 1, 64), dtype=torch.float32, device='cuda:0'),
    torch.testing.make_tensor((64,), dtype=torch.float32, device='cuda:0'),
    torch.testing.make_tensor((1376, 64), dtype=torch.float32, device='cuda:0'),
    torch.testing.make_tensor((1376, 64), dtype=torch.float32, device='cuda:0'),
    torch.testing.make_tensor((64, 1376), dtype=torch.float32, device='cuda:0'),
    torch.testing.make_tensor((64,), dtype=torch.float32, device='cuda:0'),
    torch.testing.make_tensor((192, 64), dtype=torch.float32, device='cuda:0'),
    torch.testing.make_tensor((1, 16), dtype=torch.float32, device='cuda:0'),
    torch.testing.make_tensor((1, 16), dtype=torch.float32, device='cuda:0'),
]
fd.execute(inputs)
```
In Thunder, it can be reproduced with
git fetch origin pull/1371/head && git checkout FETCH_HEAD
pytest thunder/tests/test_jit_general.py::test_litgpt_variants_kvcache[cuda-llama2-like]
```

### PR DESCRIPTION
**Pull request by naoyam**
Fixes #3801.

Please see the repro of #3801: https://github.com/NVIDIA/Fuser/issues/3801#issuecomment-2638101547

Here's how the fusion looks like:

repro3801_fusion

The issue with the repro is that T10 is not inlined at all. The sync error is a side effect of the lack of inling.

The reason T10 isn't inlined at all is because `getPositionsMappedTo` of inlining.cpp returns 0 for T10, which is because the spanning tree traversal comes from the reference tensor of T11 through T1, which means `FindMappedPositions` is computed through the Resize exprs for the slice ops. Since inlining is not allowed across resized IDs, the resulting position is propagated as 0.

However, in this case, we can actually inline T10 safely. The inlining position returned by the analysis is not correct. In fact, there's a traversal path that doesn't go through the resize ops, i.e., from T11 through T3 and T13 then T10. If this path were taken, the analysis would have allowed inlining of T10.

To fix the issue, for inlining, we should prefer paths that don't involve Resize exprs. I thought we should always do this, but I realized that for the sake of transform propagation we don't want to deprioritize Resize, since we are currently propagating slice and merge ops across resized IDs rather permissively. I consider this behavior is a technical debt and we should take care of resize ops more explicitly as is done by the resize scheduler. For the time being, to keep the current behavior as is, `MaxLogicalDomainInfoSpanningTree` should not propagate through Resize exprs for inlining only.

To change the behavior of `MaxLogicalDomainInfoSpanningTree`, I added a flag, `propagate_through_resize_`, to `MaxLogicalDomainInfoSpanningTree`. I don't like the idea of adding a flag since it feels like an ad-hoc fix, but I couldn't find any other reasonable alternative.

### CODE REVIEW

**Comment by naoyam** [comment]
!test

File: csrc/ir/nodes.cpp [hunk 1]
```diff
@@ -1377,7 +1377,17 @@ SqueezeOp::SqueezeOp(
 std::string SqueezeOp::toString(int indent_size) const {
   std::stringstream ss;
   indent(ss, indent_size) << out()->toString() << "\n";
-  indent(ss, indent_size) << "   = squeeze( " << in()->toString() << " )\n";
+  indent(ss, indent_size) << "   = squeeze( " << in()->toString()
```
Comment (naoyam) [inline csrc/ir/nodes.cpp:1380]: Not related. Just printing squeeze flags too

**Comment by naoyam** [comment]
!test

File: csrc/scheduler/tools/inlining.cpp [hunk 2]
```diff
@@ -507,7 +507,14 @@ std::unordered_map<TensorView*, int64_t> getPositionsMappedTo(
     TensorView* reference_tv,
     int64_t reference_pos) {
   std::unordered_map<TensorView*, int64_t> mapped_positions;
-  MaxLogicalDomainInfoSpanningTree tree(reference_tv, reference_pos);
+  // Spanning tree traversal should not propagate across Resize ops
+  // since inlining should not be done across resized IDs. See
+  // ResizeTest.TraversalForInliningPosition for a concrete example.
+  MaxLogicalDomainInfoSpanningTree tree(
```
Comment (zasdfgbnm) [inline csrc/scheduler/tools/inlining.cpp:513]: Can the spanning tree traversal be replaced with IdModel?

Comment (naoyam) [reply csrc/scheduler/tools/inlining.cpp:513]: I believe so, but before that, we would at least need to solve the cycle issue (#3072).

**Review by zasdfgbnm — APPROVED** [review]
