### PR TITLE
Fixing `DomainMap::areAllTargetIdsCoveredBy` to handle broadcast to non-root IDs 

### LINKED ISSUE #3653: Reference tensor not found due to DomainMap::areAllTargetIdsCoveredBy
This simple fusion is segmented:

```
TEST_F(NVFuserTest, TMP) {
  auto fusion_ptr = std::make_unique<Fusion>();
  FusionGuard fg(fusion_ptr.get());
  Fusion& fusion = *fusion_ptr;

  auto tv0 = makeConcreteTensor({2, 4, 8});
  fusion.addInput(tv0);
  auto tv1 = makeConcreteTensor({2});
  fusion.addInput(tv1);

  auto tv2 = reshape(tv0, {2, 4, 8}, {2, 32});
  auto tv3 = broadcast(tv1, {false, true});
  auto tv4 = add(tv2, tv3);

  fusion.addOutput(tv4);
  fusion.addOutput(tv3);

  fusion.printMath();

  auto options =
      at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  auto t0 = at::randn({2, 4, 8}, options);
  auto t1 = at::randn({2}, options);
  std::vector<c10::IValue> inputs({t0, t1});

  FusionExecutorCache executor_cache(std::move(fusion_ptr));
  auto out_tensors = executor_cache.runFusionWithInputs(inputs);
  testValidate(
      executor_cache.fusion(), out_tensors, inputs, __LINE__, __FILE__);
}
```

```
Inputs:
  T0_g_float[iS0{2}, iS1{4}, iS2{8}]
  T1_g_float[iS3{2}]
Outputs:
  T4_g_float[iS12{2}, iS13{32}]
  T3_g_float[iS10{2}, bS11{1}]

%kernel_math {
T2_l_float[iS4{2}, iS9{32}rf] = view( T0_g_float[iS0{2}, iS1{4}, iS2{8}] )
T3_g_float[iS10{2}, bS11{1}]
   = broadcast( T1_g_float[iS3{2}], flags = {false, true} )
T4_g_float[iS12{2}, iS13{32}]
   = T2_l_float[iS4{2}, iS9{32}rf]
   + T3_g_float[iS10{2}, bS11{1}];
} // %kernel_math

***Runtime***: Try to schedule fusion un-segmented:

Scheduler _expr_eval_ ***rejected*** because : Fusion must contain only a single expression.
Scheduler _no_op_ ***rejected*** because : output has a concrete dimension
Scheduler _matmul_ ***rejected*** because : No matmul patterns were found
Scheduler _reduction_ ***rejected*** because : No reduction op to schedule
Scheduler _resize_ ***rejected*** because : No resize op to schedule
Scheduler _transpose_ ***rejected*** because : cannot find two mismatching inner most dimensions
Scheduler _pointwise_ ***rejected*** because : cannot find reference tensor
Scheduler _inner_persistent_ ***rejected*** because : needs a reduction op
Scheduler _outer_persistent_ ***rejected*** because : needs a reduction op
Scheduler _inner_outer_persistent_ ***rejected*** because : needs a reduction op
```

I don't see any reason this should be segmented. It should be scheduled as a pointwise kernel with `T4` as the reference, but `DomainMap` rejects it likely because of the use of the permissive map at [here](https://github.com/NVIDIA/Fuser/blob/main/csrc/scheduler/tools/domain_map.cpp#L259-L260).

### PR DESCRIPTION
**Pull request by jjsjann123**
Fixes #3653

This PR adds another projection to source ID after permissive mapping. This allows us to correctly identify coverage when the broadcast IDs are not source ID directly.

### CODE REVIEW

**Comment by jjsjann123** [comment]
!test

File: csrc/scheduler/tools/domain_map.cpp [hunk 1]
```diff
@@ -248,21 +247,30 @@ bool DomainMap::areAllTargetIdsCoveredBy(
...
-    auto concrete_source_id_out =
+    auto concrete_id_out =
         ca_map_.getConcreteMappedID(source_id_out, IdMappingMode::PERMISSIVE);
-    // if we find any source_id_out that's not contained, it's possible our
-    // propagation would fail since transformation involving this iter domain
-    // can't be resolved.
-    if (!getMappedInputConcreteID(covered_source_ids, concrete_source_id_out)) {
-      return false;
+
+    // After mapping with PERMISSIVE map, `concrete_id_out` might no longer be a
```
Comment (jjsjann123) [inline csrc/scheduler/tools/domain_map.cpp:262]: This is the patch. I added another call to `get_source_iter_domain({concrete_id_out})`

Comment (naoyam) [reply csrc/scheduler/tools/domain_map.cpp:262]: So, for a given logical ID, we take its source IDs, then for each source ID, take the source IDs of its concrete ID. I understand it would work for the repro, but I wonder why it would need to take source IDs twice. For example, would it work if we took first the concrete ID of a logical ID and then its source IDs.

Comment (jjsjann123) [reply csrc/scheduler/tools/domain_map.cpp:262]: I need to take the first `source ID` of the logical ID for the pad example to work, i.e. in the comment above from line 252 - 258.

```
T2[i0, i1] = T0[i0, b0] + T1[i0, i1]
T3[i0, i9] = pad(T0[i0, b0])
```

We want to have T2 as the reference TV and we want to be able to map T3 to T2. For i9 in T3. I wanted to first map to source ID, so it can be map to b0, which would concretize to i1.

So my naive justification of going through source IDs twice is that: the first source ID call allows us to trace back to broadcast IDs that went through a resize; while the second source ID calls allow us to resolve transformations on the concrete IDs.

Comment (naoyam) [reply csrc/scheduler/tools/domain_map.cpp:262]: I'm fine with this PR as long as #3653 is fixed, but I'm feeling there's something not quite right here, probably because `T2` and `T3` shouldn't be actually mapped. They could have completely different sizes, and neither `T2` nor `T3` should not be considered representative.

Comment (naoyam) [reply csrc/scheduler/tools/domain_map.cpp:262]: https://github.com/NVIDIA/Fuser/issues/3576#issuecomment-2540643470

**Review by naoyam — APPROVED** [review]
Thanks for fixing the issue. Could you add some more notes about the logic as you mentioned here: https://github.com/NVIDIA/Fuser/pull/3655#discussion_r1899863643

File: csrc/scheduler/tools/domain_map.cpp (hunk 1 above)
Comment (jjsjann123) [reply csrc/scheduler/tools/domain_map.cpp:262]: I agree with you.

We have some existing tests that asserts the behavior, which might not be what we would want to support moving forward.

I'll update the comment here per suggestion and merge this PR as-is just so we can patch the issue.

Meanwhile, I think the case where you are making is that, we shouldn't map through PERMISSIVE mapping in the first place here. I'll start a draft PR with that to see how many tests are affected. We can discuss what's the next step then.

Comment (naoyam) [reply csrc/scheduler/tools/domain_map.cpp:262]: I'm not sure if it's something we should worry about at this moment. No test should fail functionally since it's a segmentation issue. It would be just a performance difference, but unless we have a benchmark that has this particular pattern, it doesn't make much sense to discuss what we should do.

**Comment by jjsjann123** [comment]
!test
