### PR TITLE
MarkAliasesPrepare attempts to put segment_set after intermediate tensors.

### LINKED ISSUE #2599: Suboptimal segmentation for RoPE
# TL;DR

the RoPE module in Llama-2 (and possibly other configs as well) is over-segmented into six pointwise kernels. Two should suffice. This issue blocks https://github.com/Lightning-AI/lightning-thunder/pull/731, although we don't necessarily have to reach two to unblock. 

# To reproduce

```
$ pwd
/opt/pytorch/lightning-thunder
$ git checkout wjy/bookend
$ NVFUSER_DUMP=segmented_fusion pytest thunder/benchmarks/targets.py -k test_litgpt_qkv_split_rope[Llama-2-13b-hf-forward-bs2-thunder] -s | grep 'g{(pointwise' | wc -l
6
```

# Problem

The following figure shows the current suboptimal segmentation

RoPE

The highlighted ops form the three pointwise kernels for Q. There's a similar pattern for K that's omitted for simplicity, so there are in total six pointwise kernels. The remaining, meta ops are expectedly segmented out as "no-op" regions. 

Note: For now, I omitted the `Pad`s before a `Cat` for simplicity. Soonish, https://github.com/NVIDIA/Fuser/pull/2373, pending, may move `Pad`s upstream, affecting segmentation. 

There are two main reasons we reached this state. 
1. The segmenter enforces a segment boundary before `Slice` and `Pad` (and thus before `Cat`). 
2. The `Squeeze` and the red `ToFloat` were merged too early. This made it impossible to keep merging the red and the green segment, because `Squeeze` is a transitive input to the `Cat` and the merge would lead to a cycle. Several sub-reasons contributed to that order: 
   - The merging runs [in topological order](https://github.com/NVIDIA/Fuser/blob/83e6de805e42b3063adc20eefcd02cfd5e8c1959/csrc/fusion_segmenter.cpp#L3733-L3734). 
   - The segmenter merges one edge at a time. When attempting to merge into the green `+` its operands, the segmenter only merged the right operand instead of both. 
   - A newly merged segment is pushed to [the end](https://github.com/NVIDIA/Fuser/blob/83e6de805e42b3063adc20eefcd02cfd5e8c1959/csrc/fusion_segmenter.cpp#L745) of the worklist.

### PR DESCRIPTION
**Pull request by wujingyue**
# Summary

This PR improves segmentation around meta ops for #2599. It mimics Thunder's bookend optimization, although only the output end is implemented at this moment. Although the implementation isn't complete, I believe it's an improvement overall. It segments out meta ops more aggressively than before, making non-meta ops easier to schedule. 

# Potential problems

1. `segment_set` enforces the segmenter to give up scheduling the complete fusion and instead trying to merge from singletons. In theory, merging should be able to reach a "local maxima". But in practice it's not always as powerful as expected, e.g., https://github.com/NVIDIA/Fuser/pull/2639/files#diff-cf6d314e82c49485e9039e700a04a678904e5c669abcd1610ade897ca8f57c78R1472. 
2. MarkAliasesPreparePass may set an suboptimal layout, because it runs before `AllocationDomainPass` and reasons about only meta ops. For example, 
   ```
   // `in` has a column-major input matrix. 
   x = PointwiseUnary(in);
   out = Transpose(x);
   ```
   MarkAliasesPreparePass will make `x` row-major, the default layout, and `out` column-major. Although `Transpose` is made no-op, `PointwiseUnary` becomes a pointwise kernel with transposition rather than a streamline pointwise kernel. I think this can be fixed by combining the allocation-domain part of MarkAliasesPreparePass into AllocationDomainPass and of course running AllocationDomainPass before. 

# Performance comparison with TOT

https://gist.github.com/wujingyue/afdc3e89e693ff6bbc18271c96409b94 is the performance comparison before the PR and after. This is collected by running the following commands. 

```
$ python tools/benchmark_thunder.py --storage ~/workspace --filter='test_litgpt_qkv_split_rope[phi-2-backward-bs1-thunder] or test_litgpt_gelu[phi-2-backward-bs1-thunder] or test_batch_norm[backward-thunder]' main:main main:bug2599
$ pytest-benchmark --storage=$HOME/workspace compare 0011 0012 --group-by=name
```

Most benchmarks are neutral, which is as expected because bookend is still on. Several benchmarks (namely, `test_litgpt_qkv_split_rope[phi-2-backward-bs1-thunder]`, `test_litgpt_gelu[phi-2-backward-bs1-thunder]` and `test_batch_norm[backward-thunder]`) showed some regression. However, the regression disappeared the second time I ran the benchmarks, so it's likely a noise.

### CODE REVIEW

**Comment by wujingyue** [comment]
!build

**Comment by jjsjann123** [comment]
it's conflicting with @liqiangxl 's earlier PR :stuck_out_tongue: 

Do you mind a rebase :bow:

**Comment by wujingyue** [comment]
!build

**Comment by wujingyue** [comment]
> Do you mind a rebase 🙇

Done! cc @jjsjann123

**Comment by wujingyue** [comment]
!build

**Comment by wujingyue** [comment]
!build

File: tests/cpp/test_gpu_view.cpp [hunk 1]
```diff
@@ -2379,6 +2398,63 @@ TEST_F(GpuViewTest, SplitMergePointwiseSplitMerge) {
   testValidate(executor_cache.fusion(), {cg_outputs}, {t0}, __LINE__, __FILE__);
 }
 
+// segmented into 2 kernels: pointwise and reduction
+TEST_F(GpuViewTest, GroupNormOriginal) {
```
Comment (wujingyue) [inline tests/cpp/test_gpu_view.cpp:2402]: Copied from https://github.com/NVIDIA/Fuser/pull/2405.

File: tests/cpp/test_gpu_view.cpp [hunk 2]
```diff
@@ -1447,61 +1447,77 @@ TEST_F(GpuViewTest, FusionSumViewSchedule) {
 
 // Make sure matching reshapes are segmented into the same kernel
 TEST_F(GpuViewTest, FusionReshapeMagicSchedule1) {
-  auto fusion_ptr = std::make_unique<Fusion>();
-  Fusion& fusion = *fusion_ptr.get();
-  FusionGuard fg(&fusion);
+  auto fusion = std::make_unique<Fusion>();
+  FusionGuard fg(fusion.get());
```
Comment (wujingyue) [inline tests/cpp/test_gpu_view.cpp:1451]: Sorry for mixing in some cosmetic changes like this. Happy to revert if they are annoying enough.

File: tests/cpp/test_resize.cpp [hunk 3]
```diff
@@ -2000,7 +2001,8 @@ TEST_F(ResizeTest, ResizeReshapeAndSlice) {
       tv1,
       {{IrBuilder::create<Val>(0L), IrBuilder::create<Val>(2L)},
        {IrBuilder::create<Val>(0L), IrBuilder::create<Val>(2L)}});
-  fusion->addOutput(tv2);
+  auto tv3 = add(tv2, tv2);
```
Comment (wujingyue) [inline tests/cpp/test_resize.cpp:2004]: So MarkAliasesPreparePass doesn't kick in. Other changes in the file are minor cleanups.

File: tests/cpp/test_remove_bcast_squeeze.cpp [hunk 4]
```diff
@@ -78,7 +78,7 @@ TEST_F(RemoveBcastSqueezeTest, BcastSqueezeMultipleUses) {
   auto tv1 = set(tv0);
   auto tv2 = broadcast(tv1, is_broadcast_dim);
   auto tv3 = squeeze(tv2, is_broadcast_dim);
-  auto tv4 = set(tv3);
+  auto tv4 = add(tv3, tv3);
```
Comment (wujingyue) [inline tests/cpp/test_remove_bcast_squeeze.cpp:81]: Without this change, `squeeze` will be bookend'ed.

**Comment by liqiangxl** [comment]
Can we do a `--diff` to check generated code change?

File: benchmarks/cpp/matmul.cpp [hunk 5]
```diff
@@ -61,6 +61,7 @@ void setupMatmul(Fusion* fusion, MmaLayout layout, MatmulParams params) {
 
   fusion->addOutput(d);
 
+  preseg_passes::OptimizationPass<preseg_passes::PreSegmenter>::runPass(fusion);
```
Comment (wujingyue) [inline benchmarks/cpp/matmul.cpp:64]: This change has been submitted separately as https://github.com/NVIDIA/Fuser/pull/2680.

Comment (jjsjann123) [reply benchmarks/cpp/matmul.cpp:64]: should we change base to main? since #2680 is merged.

surprisingly that didn't happen automatically.

Comment (jjsjann123) [reply benchmarks/cpp/matmul.cpp:64]: wait. I was mistaken. The base of this PR is on the revert.... NVM

File: csrc/preseg_passes/mark_aliases_prepare.cpp [hunk 6]
```diff
@@ -50,86 +110,100 @@ void MarkAliasesPreparePass::runPass(Fusion* fusion) {
...
-        // A `segment_set` before a fusion input is useless.
-        continue;
-      }
-      // Rarely, if `aliased_io` is already defined by `segment_set`, don't
-      // create another `segment_set`.
-      if (LoadStoreOp* def =
-              dynamic_cast<LoadStoreOp*>(aliased_io->definition())) {
-        if (def->opType() == LoadStoreOpType::SegmenterSet) {
-          continue;
+    auto insert_segment_set = [&]() {
```
Comment (jjsjann123) [inline csrc/preseg_passes/mark_aliases_prepare.cpp:163]: dumb question, this lambda is not used anywhere else. Does lambda bring anything to the table?

File: csrc/preseg_passes/mark_aliases_prepare.cpp [hunk 7]
```diff
@@ -50,86 +110,100 @@ void MarkAliasesPreparePass::runPass(Fusion* fusion) {
...
-    for (Expr* e : users_used_only_by_aliases) {
-      ir_utils::replaceValInExprInputs(e, aliased_io, copy);
-    }
-    if (aliased_io->isFusionOutput()) {
-      fusion->replaceOutput(aliased_io, copy);
-    }
+      // If all aliasing users are `segment_set`, don't create another
+      // `segment_set`.
+      if (std::all_of(
+              i, j, [](const Use& use) { return isSegmentSet(use.user); })) {
```
Comment (jjsjann123) [inline csrc/preseg_passes/mark_aliases_prepare.cpp:186]: this condition is `all_of`. which means, if there's only a subset of `use.user` being segmenter_set, we are still going to put another segmenter_set before them.

**Review by jjsjann123 — COMMENTED** [review]
haven't finished the code yet. Some preliminary comment.

File: csrc/scheduler/mark_aliases.cpp [hunk 8]
```diff
@@ -33,21 +33,22 @@ void markAliases(Fusion* fusion) {
 
   for (TensorView* out :
        ir_utils::filterByType<TensorView>(fusion->outputs())) {
-    if (fusion->getOutputAlias(out).type != AllocationType::New) {
+    // AllocationType::ReuseBuffer requires the output to be updated in place
+    // so it can't be computed as an alias.
+    if (fusion->getOutputAlias(out).type == AllocationType::ReuseBuffer) {
```
[the remark this answers is not in the document]
Comment (wujingyue) [reply csrc/scheduler/mark_aliases.cpp:38]: Probably doesn't make a difference in practice. AllocationType::Evaluate is used for either aliases or ATen fallback. The latter is picked up by the ExprEvalScheduler, which doesn't call this function. I made the change only because it's easier to explain why we should skip ReuseBuffer.

File: csrc/preseg_passes/mark_aliases_prepare.cpp (hunk 6 above)
Comment (wujingyue) [reply csrc/preseg_passes/mark_aliases_prepare.cpp:154]: So I can early-return inside the lambda without exiting MarkAliasesPreparePass::runPass, the outer function. Alternatively, I could use nested ifs or say
```
if (...) {
  i = j;
  continue;
}
```
which I'm not a big fan of.

File: csrc/preseg_passes/mark_aliases_prepare.cpp (hunk 7 above)
Comment (wujingyue) [reply csrc/preseg_passes/mark_aliases_prepare.cpp]: Yes and that's suboptimal. I think the best fix to that is: still create another segment_set here but short circuit the double segment-set in the following std::for_each. I'll give it a shot tomorrow.

File: tests/cpp/test_alias.cpp [hunk 9]
```diff
@@ -1391,26 +1484,176 @@ TEST_F(AliasTest, SegmentMetaOps) {
...
+  for (int i = 0; i < 3; i++) {
+    in_tensors.push_back(at::randn({b, s, h * f}).cuda());
+  }
+  std::vector<at::Tensor> out_tensors = fec.runFusionWithInputs(in_tensors);
+  testValidate(fec.fusion(), out_tensors, in_tensors, __LINE__, __FILE__);
+
+  EXPECT_TRUE(out_tensors[2].is_alias_of(out_tensors[1]));
+}
+
+TEST_F(AliasTest, Bookend_Issue2375) {
```
Comment (jjsjann123) [inline tests/cpp/test_alias.cpp:1624]: cc'ing @liqiangxl

**Review by jjsjann123 — APPROVED** [review]
LGTM.

Thanks for modifying existing tests to work with the new analysis. That looked painful to go over each.

File: csrc/preseg_passes/mark_aliases_prepare.cpp [hunk 10]
```diff
@@ -7,13 +7,64 @@
...
+std::unordered_set<Expr*> exprsUsedByNonAliases(
+    const AliasAnalysisResult& analysis,
+    Fusion* fusion) {
+  std::vector<Val*> non_aliases;
+  for (TensorView* tv : ir_utils::allTvs(fusion)) {
+    if (analysis.getRoot(tv) == nullptr) {
+      non_aliases.push_back(tv);
+    }
+  }
+  std::vector<Expr*> used_by_non_aliases = StmtSort::getExprsTo(non_aliases);
```
Comment (liqiangxl) [inline csrc/preseg_passes/mark_aliases_prepare.cpp:62]: IIUC, this `used_by_non_aliases` means `exprs_producing_non_alias`.

File: csrc/preseg_passes/mark_aliases_prepare.cpp [hunk 11]
```diff
@@ -50,86 +101,101 @@ void MarkAliasesPreparePass::runPass(Fusion* fusion) {
...
-      if (used_by_non_aliases.count(e)) {
-        users_used_by_non_aliases.push_back(e);
-      } else {
-        users_used_only_by_aliases.push_back(e);
-      }
+  // The remaining are optimizations to reduce the number of `segment_set`s
+  // inserted.
+  //
+  // Group `uses_to_segment` by `use_of` and remove duplicates.
+  std::sort(uses_to_segment.begin(), uses_to_segment.end());
```
Comment (liqiangxl) [inline csrc/preseg_passes/mark_aliases_prepare.cpp:135]: we usually use `stable_sort` in nvFuser for reproductivity.

File: csrc/preseg_passes/mark_aliases_prepare.cpp [hunk 12]
```diff
@@ -50,86 +101,101 @@ void MarkAliasesPreparePass::runPass(Fusion* fusion) {
...
+  }
 
-    // If all users are used by non-alias outputs, do nothing. Adding
-    // segment_set around unlikely creates more no-op regions.
-    if (users_used_only_by_aliases.empty()) {
-      continue;
+  auto i = uses_to_segment.begin();
+  while (i != uses_to_segment.end()) {
+    TensorView* use_of = i->use_of;
+    auto j = i;
```
Comment (liqiangxl) [inline csrc/preseg_passes/mark_aliases_prepare.cpp:149]: I feel we can start from `j = i + 1`

File: csrc/preseg_passes/mark_aliases_prepare.cpp [hunk 13]
```diff
@@ -50,86 +101,101 @@ void MarkAliasesPreparePass::runPass(Fusion* fusion) {
...
+    for (const auto& use : uses_to_segment) {
+      debug() << "Will put a segment_set at " << use.user << std::endl;
     }
+  }
 
-    // If all users are used by non-alias outputs, do nothing. Adding
-    // segment_set around unlikely creates more no-op regions.
-    if (users_used_only_by_aliases.empty()) {
-      continue;
+  auto i = uses_to_segment.begin();
```
Comment (liqiangxl) [inline csrc/preseg_passes/mark_aliases_prepare.cpp:146]: can we change `i` and `j` to more meaningful names? and add comments to these two while loops.

File: tests/cpp/test_gather.cpp [hunk 14]
```diff
@@ -1101,6 +1102,9 @@ TEST_F(ScatterGatherTest, TakeAlongAxisIntermediateTensorTranspose2) {
 // transpose the dimension produced by take_along_axis. Currently not
 // supported by the transpose scheduler
 TEST_F(ScatterGatherTest, TakeAlongAxisIntermediateTensorTranspose3) {
+  preseg_passes::OptimizationPassGuard<preseg_passes::MarkAliasesPreparePass>
+      optimization_guard(false);
```
Comment (liqiangxl) [inline tests/cpp/test_gather.cpp:1106]: can we add a comment about why disabling?

File: tests/cpp/test_resize.cpp (hunk 3 above)
Comment (liqiangxl) [reply tests/cpp/test_resize.cpp:2004]: can we add this comment to the code?

**Review by liqiangxl — APPROVED** [review]
LGTM. Thanks for adding this powerful feature!

**Comment by liqiangxl** [comment]
(1) We may need to check the influence on the CPU overhead of segmenter since `segment_set enforces the segmenter to give up scheduling the complete fusion and instead trying to merge from singletons.`
(2) When merged into main branch, needs to check code diff to avoid over segmentation similar to several tests modified in this PR.

File: csrc/preseg_passes/mark_aliases_prepare.cpp (hunk 10 above)
Comment (wujingyue) [reply csrc/preseg_passes/mark_aliases_prepare.cpp:62]: I'll rename this to `depended_by_non_aliases`. I wanted to emphasize on transitivity, because it's not only the direct user that I care about.

File: csrc/preseg_passes/mark_aliases_prepare.cpp (hunk 11 above)
Comment (wujingyue) [reply csrc/preseg_passes/mark_aliases_prepare.cpp:135]: It makes no difference because the pairs `<use_of,user>` in `uses_to_segment` are distinct after the call to `std::unique`. 

But I got your concern on non-determinism, of which the root cause is sorting by pointer values. What sort keys would you use? Names?

File: csrc/preseg_passes/mark_aliases_prepare.cpp (hunk 12 above)
Comment (wujingyue) [reply csrc/preseg_passes/mark_aliases_prepare.cpp:149]: Got it. Will change the loop from while-do to do-while, which achieves the same effect of one less iteration.

File: csrc/preseg_passes/mark_aliases_prepare.cpp (hunk 6 above)
Comment (wujingyue) [reply csrc/preseg_passes/mark_aliases_prepare.cpp:154]: FYI, I'll make insert_segment_set a real function. The capture list is much shorter than I expected.

File: csrc/preseg_passes/mark_aliases_prepare.cpp (hunk 7 above)
Comment (wujingyue) [reply csrc/preseg_passes/mark_aliases_prepare.cpp]: After thinking more about this, the logic as is is probably correct because `segment_set` is supposed to block merging the edges. Consider
```
in -> (add) -> t0 -> (segment_set) -> t1 -> (reshape) -> out0
               |
               +--> (permute) -> out1
               +--> (permute) -> out2
```

IIUC, it's incorrect to redirect the `permutes` to `t1` like the following. 
```
in -> (add) -> t0 -> (segment_set) -> t1 -> (reshape) -> out0
                                      |
                                      +--> (permute) -> out1
                                      +--> (permute) -> out2
```
This is because the original `segment_set` intends to separate the `reshape` and the two `permute`s, but the new `segment_set` doesn't enforce that intention. Instead, the correct outcome should be
```
in -> (add) -> t0 -> (segment_set) -> t2 -> (segment_set) -> t1 -> (reshape) -> out0
                                      |
                                      +--> (permute) -> out1
                                      +--> (permute) -> out2
```

File: csrc/preseg_passes/mark_aliases_prepare.cpp (hunk 11 above)
Comment (liqiangxl) [reply csrc/preseg_passes/mark_aliases_prepare.cpp:135]: I think `name()` should work.

File: tests/cpp/test_alias.cpp [hunk 15]
```diff
@@ -964,6 +1008,42 @@ TEST_F(AliasTest, DoNotOverSegment) {
 
   FusionKernelRuntime* runtime = fec.getMostRecentKernelRuntime();
   EXPECT_FALSE(runtime->isSegmented());
+
+  // permute_out should be recognized as an alias of add_out. However, the
+  // pointwise scheduler `cacheFork`s outputs
+  // (https://github.com/NVIDIA/Fuser/blob/de488172d280d033511dfc0939e2207f87c1b1cb/csrc/scheduler/pointwise.cpp#L540),
+  // making permute_out no longer a transitive user of add_out.
+  // EXPECT_TRUE(out_tensors[1].is_alias_of(out_tensors[0]));
```
[the remark this answers is not in the document]
Comment (wujingyue) [reply tests/cpp/test_alias.cpp:1016]: That's right...

**Comment by wujingyue** [comment]
!build --diff

**Comment by wujingyue** [comment]
> When merged into main branch, needs to check code diff to avoid over segmentation similar to several tests modified in this PR.

I don't understand the result of codegen_diff any more. E.g., https://gitlab-master.nvidia.com/dl/pytorch/fuser-gh-mirror/-/jobs/103497030/viewer failed but I couldn't find which test case failed and what was the diff.

**Comment by wujingyue** [comment]
!build --diff
