### PR TITLE
Propagate modified reshape extents at concretization

### LINKED ISSUE #418: `ops.reshape` errors with `!fusion->hasDynamicTransform()`
Error:

```
Traceback (most recent call last):
  File "/workspace/simple_dl_models/repro.py", line 22, in <module>
    out = fd.execute(inputs)
  File "/opt/pytorch/nvfuser/nvfuser/__init__.py", line 76, in execute
    result = self._execute(inputs, override_user_schedule)
RuntimeError: !fusion->hasDynamicTransform() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/kernel_cache.cpp":619, please report a bug to PyTorch. Fusion must be concretized before constructing FusionKernelRuntime
```

This is a pattern we will find in the `GroupNorm` operation where the input tensors is reshaped.  I am not quite sure what the error indicates since this pattern will have a dynamic transform.

This repro is looking into a future that uses a branch: `add_new_reshape`.  This branch has some new operations not found in TOT in the Python API.

Repro:
```
import torch
from nvfuser import FusionDefinition, DataType

inputs = [
    torch.randn(256, 128, 28, 28, device='cuda'),
    32 
]

def func(fd: FusionDefinition) :
    T0 = fd.from_pytorch(inputs[0])
    S0 = fd.define_scalar(dtype=DataType.Int)
    V0 = T0.shape()
    T1 = fd.ops.reshape(T0, [V0[0], V0[1] / S0, S0, V0[2], V0[3]])
    var, mean = fd.ops.var_mean(T1, axes=[2, 3, 4], correction=0, keepdim=True)
    fd.add_output(var)
    fd.add_output(mean)

with FusionDefinition() as fd:
    func(fd)

for _ in range(5):
    out = fd.execute(inputs)
```

### LINKED ISSUE #629: Extent root scalars can get lost during segmentation
In fixing #418 I encountered this segmentation error. First, the offending test
```c++
TEST_F(NVFuserTest, DynamicTransformIssue418_CUDA) {
  auto fusion = std::make_unique<Fusion>();
  FusionGuard fg(fusion.get());

  auto tv0 = makeSymbolicTensor(4);
  fusion->addInput(tv0);
  auto s0 = IrBuilder::create<Val>(DataType::Int);
  fusion->addInput(s0);

  auto sh = tensor_sizes(tv0);
  auto tv1 = reshape(tv0, {sh[0], div(sh[1], s0), s0, sh[2], sh[3]});
  // Reducing along axis 2 in tv1 is equivalent to a partial reduction across
  // axis 1 of tv0.
  auto vm = variance_mean(tv1, {2, 3, 4}, 0, true);
  fusion->addOutput(vm.mean);
  fusion->addOutput(vm.var);

  FusionExecutorCache fusion_executor_cache(std::move(fusion));

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor at0 = at::randn({256, 128, 28, 28}, options);
  std::vector<c10::IValue> aten_inputs = {at0, 32};
  auto outputs = fusion_executor_cache.runFusionWithInputs(aten_inputs);
  /*
Concretized Fusion:
Inputs:
  T0_g[ iS0{i0}, iS1{i2}, iS2{i3}, iS3{i4} ], float
  i5, int64_t
Outputs:
  T7_g[ iS49{i0}, iS50{( i2 / i5 )}, bS37{1}, bS38{1}, bS39{1} ], float
  T6_g[ iS55{i0}, iS56{( i2 / i5 )}, bS32{1}, bS33{1}, bS34{1} ], float
%kernel_math {
T8_l[ iS40{i0}, iS45{4}rf, iS46{( ceilDiv(i2, 4) )}rf, iS42{i3}, iS43{i4} ]
  = view( T0_g[ iS0{i0}, iS1{i2}, iS2{i3}, iS3{i4} ] )
T2_l[ iS47{i0}, iS48{( i2 / i5 )}, rS15{i5}, rS16{i3}, rS17{i4} ](Avg),
T3_l[ iS51{i0}, iS52{( i2 / i5 )}, rS20{i5}, rS21{i3}, rS22{i4} ](Var),
T4_l[ iS57{i0}, iS58{( i2 / i5 )}, rS25{i5}, rS26{i3}, rS27{i4} ](Count)
 = Welford ( T8_l[ iS40{i0}, iS45{4}rf, iS46{( ceilDiv(i2, 4) )}rf, iS42{i3}, iS43{i4} ](Avg),
  allreduce = false )
T7_g[ iS49{i0}, iS50{( i2 / i5 )}, bS37{1}, bS38{1}, bS39{1} ]
  = broadcast( T2_l[ iS47{i0}, iS48{( i2 / i5 )}, rS15{i5}, rS16{i3}, rS17{i4} ] )
d17 = (double)(i5);
d19 = double(1) * d17;
d21 = (double)(i3);
d23 = d19 * d21;
d25 = (double)(i4);
d27 = d23 * d25;
d33 = reciprocal(d27);
T5_l[ iS53{i0}, iS54{( i2 / i5 )} ]
  = T3_l[ iS51{i0}, iS52{( i2 / i5 )}, rS20{i5}, rS21{i3}, rS22{i4} ]
  * d33;
T6_g[ iS55{i0}, iS56{( i2 / i5 )}, bS32{1}, bS33{1}, bS34{1} ]
  = broadcast( T5_l[ iS53{i0}, iS54{( i2 / i5 )} ] )
}
  */
  /*
  what():  inferred_val.hasValue() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/executor.cpp":477,
 please report a bug to PyTorch. Could not launch kernel as program could not infer
 ( i2 / i5 )(i6) for the buffer T7_g[ iS49{i0}, iS50{( i2 / i5 )}, bS37{1}, bS38{1}, bS39{1} ]
Exception raised from inferShape at /opt/pytorch/nvfuser/csrc/executor.cpp:477 (most recent call first):
  */
  auto at1 = at0.reshape({256, 4, 32, 28, 28});
  auto atmean = at1.mean({2, 3, 4});
  auto atvar = at1.var({2, 3, 4});
  testValidate(
      fusion_executor_cache.fusion(),
      outputs,
      aten_inputs,
      {atmean, atvar},
      __LINE__,
      __FILE__);
}
```
This error occurs because the Fusion is segmented at `tv1` (printed as `T8_l[ iS40{i0}, iS45{4}rf, iS46{( ceilDiv(i2, 4) )}rf, iS42{i3}, iS43{i4} ]`), since there is a split axis with a reduction along only one branch of the split. In the second segment, that tensor is an input, along with the scalars used to compute T5: `i3, i4, i5`. However, `i2` is not an input so it can't evaluate the extent, even though it is actually provided as an input.

We could either attempt to add missing input scalars to fusion segments so that each segment will have all inputs necessary to compute any extent expressions contained in that segment, or we could modify `bindInputs` to be able to bind values to derived extents like `i2 / i5`, so that that extent would be available directly in the `ExpressionEvaluator`.

### PR DESCRIPTION
**Pull request by jacobhinkle**
This PR propagates extent scalars after concretizing reshape. Previously the following fusion
```c++
  auto tv0 = makeSymbolicTensor(4);
  fusion->addInput(tv0);
  auto s0 = IrBuilder::create<Val>(DataType::Int);
  fusion->addInput(s0);

  auto sh = tensor_sizes(tv0);
  auto tv1 = reshape(tv0, {sh[0], div(sh[1], s0), s0, sh[2], sh[3]});
  // Reducing along axis 2 in tv1 is equivalent to a partial reduction across
  // axis 1 of tv0.
  auto vm = variance_mean(tv1, {2, 3, 4}, 0, true);
  fusion->addOutput(vm.mean);
  fusion->addOutput(vm.var);
```
would be concretized like this:
```
Inputs:
  T0_g[ iS0{i0}, iS1{i2}, iS2{i3}, iS3{i4} ], float
  i5, int64_t
Outputs:
  T7_g[ iS49{i0}, iS50{( i2 / i5 )}, bS37{1}, bS38{1}, bS39{1} ], float
  T6_g[ iS55{i0}, iS56{( i2 / i5 )}, bS32{1}, bS33{1}, bS34{1} ], float

%kernel_math {
T8_l[ iS40{i0}, iS45{4}rf, iS46{( ceilDiv(i2, 4) )}rf, iS42{i3}, iS43{i4} ] = view( T0_g[ iS0{i0}, iS1{i2}, iS2{i3}, iS3{i4} ] )
T2_l[ iS47{i0}, iS48{( i2 / i5 )}, rS15{i5}, rS16{i3}, rS17{i4} ](Avg),
T3_l[ iS51{i0}, iS52{( i2 / i5 )}, rS20{i5}, rS21{i3}, rS22{i4} ](Var),
T4_l[ iS57{i0}, iS58{( i2 / i5 )}, rS25{i5}, rS26{i3}, rS27{i4} ](Count)
 = Welford ( T8_l[ iS40{i0}, iS45{4}rf, iS46{( ceilDiv(i2, 4) )}rf, iS42{i3}, iS43{i4} ](Avg),
  allreduce = false )
T7_g[ iS49{i0}, iS50{( i2 / i5 )}, bS37{1}, bS38{1}, bS39{1} ]
   = broadcast( T2_l[ iS47{i0}, iS48{( i2 / i5 )}, rS15{i5}, rS16{i3}, rS17{i4} ] )
d17 = (double)(i5);
d19 = double(1) * d17;
d21 = (double)(i3);
d23 = d19 * d21;
d25 = (double)(i4);
d27 = d23 * d25;
d33 = reciprocal(d27);
T5_l[ iS53{i0}, iS54{( i2 / i5 )} ]
   = T3_l[ iS51{i0}, iS52{( i2 / i5 )}, rS20{i5}, rS21{i3}, rS22{i4} ]
   * d33;
T6_g[ iS55{i0}, iS56{( i2 / i5 )}, bS32{1}, bS33{1}, bS34{1} ]
   = broadcast( T5_l[ iS53{i0}, iS54{( i2 / i5 )} ] )
}
```

Now this concretizes as
```
Inputs:
  T0_g[ iS0{i0}, iS1{i2}, iS2{i3}, iS3{i4} ], float
  i5, int64_t
Outputs:
  T7_g[ iS52{i0}, iS53{4}, bS37{1}, bS38{1}, bS39{1} ], float
  T6_g[ iS62{i0}, iS63{4}, bS32{1}, bS33{1}, bS34{1} ], float

%kernel_math {
T8_l[ iS40{i0}, iS45{4}rf, iS46{( ceilDiv(i2, 4) )}rf, iS42{i3}, iS43{i4} ] = view( T0_g[ iS0{i0}, iS1{i2}, iS2{i3}, iS3{i4} ] )
T2_l[ iS49{i0}, iS50{4}, rS48{( ceilDiv(i2, 4) )}, rS16{i3}, rS17{i4} ](Avg),
T3_l[ iS56{i0}, iS57{4}, rS55{( ceilDiv(i2, 4) )}, rS21{i3}, rS22{i4} ](Var),
T4_l[ iS66{i0}, iS67{4}, rS65{( ceilDiv(i2, 4) )}, rS26{i3}, rS27{i4} ](Count)
 = Welford ( T8_l[ iS40{i0}, iS45{4}rf, iS46{( ceilDiv(i2, 4) )}rf, iS42{i3}, iS43{i4} ](Avg),
  allreduce = false )
T7_g[ iS52{i0}, iS53{4}, bS37{1}, bS38{1}, bS39{1} ]
   = broadcast( T2_l[ iS49{i0}, iS50{4}, rS48{( ceilDiv(i2, 4) )}, rS16{i3}, rS17{i4} ] )
d17 = (double)(i5);
d19 = double(1) * d17;
d21 = (double)(i3);
d23 = d19 * d21;
d25 = (double)(i4);
d27 = d23 * d25;
d33 = reciprocal(d27);
T5_l[ iS59{i0}, iS60{4} ]
   = T3_l[ iS56{i0}, iS57{4}, rS55{( ceilDiv(i2, 4) )}, rS21{i3}, rS22{i4} ]
   * d33;
T6_g[ iS62{i0}, iS63{4}, bS32{1}, bS33{1}, bS34{1} ]
   = broadcast( T5_l[ iS59{i0}, iS60{4} ] )
}
```
This helps ensure that no scalars get lost during segmentation, which could previously occur if the reshape output became a segmentation edge (see #629).

I also took this opportunity to remove `TensorView::convertRfactorToRootDomain()`. It was only used at segmentation and did a traversal for each segment input TV. Now, we call it once and that replaces all extents for all input TVs using a single traversal.

Fixes #629 and fixes #418.

### CODE REVIEW

File: csrc/tensor_view.cpp [hunk 1]
```diff
@@ -240,69 +240,6 @@ std::string TensorView::toInlineString(int indent_size) const {
...
-  };
-
-  // Create a new root domain and replacement TensorDomain.
-  // Given an rfactor domain, create a new IterDomain.
-  // Otherwise, clone the previous IterDomain
-  auto createReplacementDomain =
-      [this](const std::vector<Val*>& replacement_extents) {
-        TORCH_INTERNAL_ASSERT(
-            !replacement_extents.empty() &&
-            getMaybeRFactorDomain().size() == replacement_extents.size());
```
Comment (jacobhinkle) [inline csrc/tensor_view.cpp:262]: I omitted the check that `replacement_extents` is not empty since it did not seem necessary.

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

File: csrc/dynamic_transform.cpp [hunk 2]
```diff
@@ -454,8 +454,8 @@ void DynamicTransformConcretizer::concretize() {
   // Finally, propagate concretized domains
   auto all_stmts = StmtSort::getStmts(
       info_->fusion(),
-      /*traverse_members*/ false,
-      /*traverse_attributes*/ false,
+      /*traverse_members*/ true,
+      /*traverse_attributes*/ true,
```
Comment (jacobhinkle) [inline csrc/dynamic_transform.cpp:458]: Since we propagate scalars, we should do this anywhere they might occur; namely in members and attributes. This was not necessary when we were only replacing `IterType`s since `IterDomain`s are traversed regardless of these settings.

File: csrc/tensor_view.cpp [hunk 3]
```diff
@@ -240,69 +240,6 @@ std::string TensorView::toInlineString(int indent_size) const {
   return toString(indent_size);
 }
 
-void TensorView::convertRfactorToRootDomain() {
```
Comment (naoyam) [inline csrc/tensor_view.cpp:243]: Is this change completely unrelated with the propagation of concretized vals?

Comment (jacobhinkle) [reply csrc/tensor_view.cpp:243]: Yes. At first I thought it was going to be necessary. I realized it was not necessary for this PR, but it is a little faster and reduces the TensorView interface so I figured I would keep it. I can split it into another PR if you prefer.

**Comment by jacobhinkle** [comment]
!build

File: csrc/dynamic_transform.cpp (hunk 2 above)
Comment (naoyam) [reply csrc/dynamic_transform.cpp:458]: Didn't we discuss duplicated replacements if members were also traversed? Would it be a concern?

File: csrc/fusion_segmenter.cpp [hunk 4]
```diff
@@ -1437,6 +1437,62 @@ std::string toString(const SegmentedFusion* segmented_fusion) {
...
+      if (!id->extent()->isConstScalar()) {
+        tv_is_concrete = false;
+        break;
+      }
+    }
+
+    for (const auto& id : rfactor) {
+      if (id->isRFactorProduct()) {
+        // Create new symbolic extents for rfactor iterDomains
+        auto domain_extent = (!tv_is_concrete)
```
Comment (naoyam) [inline csrc/fusion_segmenter.cpp:1471]: I think this function is fine as it's mostly just copied from tensor_view.cpp. However, I don't know why we do use all symbolic extents if `tv_is_concrete`. It seems this means that if there's any IterDomain with a symbolic extent, all IterDomains would have symbolic extents. 

This is not about this PR itself, but does it make sense?

**Review by naoyam — APPROVED** [review]
The PR looks good to me, but I have one question on the rfactor-root replacement

File: csrc/fusion_segmenter.cpp (hunk 4 above)
Comment (jacobhinkle) [reply csrc/fusion_segmenter.cpp:1471]: > Didn't we discuss duplicated replacements if members were also traversed? Would it be a concern?

This is an important point since it could lead to us concretizing one aspect of a Val but losing a previously concretized aspect (for example losing the concretized extent when we later concretize IterType). But I think we are OK if we are careful to use `maybeMutated` when creating replacements. In one case we do already do multiple mutations; we call `OptOutMutator::mutate(id)` at the beginning of our `mutate(IterDomain* id)` override.

Comment (jacobhinkle) [reply csrc/fusion_segmenter.cpp:1471]: > It seems this means that if there's any IterDomain with a symbolic extent, all IterDomains would have symbolic extents.

Yeah that is strange. All IterDomains in the rfactor domain are checked to determine concreteness, but then the condition is only applied to rfactor products. The purpose of this function is to make the root a "standalone" domain so that we can bind input shapes to it, so it seems like all extents regardless of if they were already rfactor products should be either constant ints or pure symbolic.

We always need to create a new `IterDomain` for rfactor products in order to cut the connection to the root domain. It seems like a simpler condition would be
```c++
auto domain_extent = id->extent()->isConstScalar()
    ? id->extent()
    : IrBuilder::create<Val>(DataType::Int);
```
And in light of the above, we could move this outside of the `id->isRFactorProduct()` check, so that we would replace IDs that are not rfactor products if they have non-constant derived extents.

Comment (naoyam) [reply csrc/fusion_segmenter.cpp]: Please create a separate issue for this. Let's merge this PR as is.

Comment (jacobhinkle) [reply csrc/fusion_segmenter.cpp:1471]: Sounds good. Merging without that change. I will do that in another PR.
