### PR TITLE
Set extents of empty tensors to zeroVal() during concretization

### LINKED ISSUE #264: Floating-point exception scheduling reduction of zero-element tensor
Currently, scheduling a reduction with a tensor having zero size results in an unhandled SIGFPE due to 0/0 at https://github.com/NVIDIA/Fuser/blob/main/csrc/scheduler/reduction.cpp#L558 (`n_elems=target_blocks=0`).

Here is a minimal reproduction:
```c++
// Test that 0-dimensional tensors do not break reduction scheduler
TEST_F(NVFuserTest, FusionReduceZeroElementTensor_CUDA) {
  auto fusion = std::make_unique<Fusion>();
  FusionGuard fg(fusion.get());

  std::vector<int64_t> input_shape{3, 4, 0, 5};
  auto tv0 = makeSymbolicTensor(4);
  fusion->addInput(tv0);
  auto tv1 = sum(tv0, {1});
  fusion->addOutput(tv1);

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor at_x = at::randn(input_shape, options);
  FusionExecutorCache executor_cache(std::move(fusion));
  auto outputs = executor_cache.runFusionWithInputs({at_x});
  auto t2 = at_x.sum({2});

  auto reduction_params = getReductionHeuristics(fusion.get(), {at_x});
  TORCH_CHECK(reduction_params, "Reduction schedule was not generated!");
  scheduleReduction(fusion.get(), *reduction_params);

  testValidate(
      executor_cache.fusion(), outputs, {at_x}, {t2}, __LINE__, __FILE__);
}
```
Note that the reduction does not need to be along the 0 dimension to trigger the crash. We have a test for zero-dim tensors in the presence of reductions, but it is not actually reducing the zero-dim tensor: https://github.com/NVIDIA/Fuser/blob/13a90b6d18273acc6977269d90cfc28cb5e1c8b0/test/test_gpu2.cpp#L5984.

I tried guarding a few of the `ceilDiv`s in `outerReductionHeuristic` which can avoid the SIGFPE but lead to a kernel segfault, so I'm posting this issue for a little discussion before I try a fix. We may just need to check numel at the beginning of that function and short-circuit there if it's zero.

### LINKED ISSUE #365: Multiple slices with one of them zero-length fails assertion
We are hitting a failed assertion in the following test:
```c++
TEST_F(NVFuserTest, FusionResizeMultiSliceEmpty_CUDA) {
  auto fusion = std::make_unique<Fusion>();
  FusionGuard fg(fusion.get());

  std::vector<int64_t> shape({9});
  // concrete shapes to avoid dynamic Fusion
  auto tv0 = makeConcreteTensor(shape);
  fusion->addInput(tv0);

  // Perform a size-1 slice and a size-0 slice on tv0. The size-1 slice
  // could be size >1 with no change in the error. The order does not
  // matter. Performing only one of these slices does not trigger the
  // error and the output is correct in that case. If there are
  // multiple size-0 slices the error is not triggered. It only seems
  // to appear when there are both size-0 and size non-zero slices of
  // the same tensor.
  auto tv1 = slice(
      tv0,
      {{IrBuilder::create<Int>(0),
        IrBuilder::create<Int>(1),
        IrBuilder::create<Int>(1)}});
  fusion->addOutput(tv1);
  auto tv2 = slice(
      tv0,
      {{IrBuilder::create<Int>(0),
        IrBuilder::create<Int>(0),
        IrBuilder::create<Int>(1)}});
  fusion->addOutput(tv2);

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::manual_seed(0);

  auto t0 = at::randn(shape, options);
  std::vector<c10::IValue> aten_inputs({t0});

  FusionExecutorCache executor_cache(std::move(fusion));
  auto cg_outputs = executor_cache.runFusionWithInputs(aten_inputs);

  auto ref0 = t0.index({at::indexing::Slice(0, 1)});
  auto ref1 = t0.index({at::indexing::Slice(0, 0)});

  TORCH_CHECK(ref0.equal(cg_outputs[0]));
  TORCH_CHECK(ref1.equal(cg_outputs[1]));
}
```
This gives an error during scheduling:
> C++ exception with description "!new_numerator_val->isZeroInt() && (!new_numerator_val->isConstInt() || new_numerator_val->evaluateInt() > 0) INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/scheduler/vectorize_helper.h":74, please report a bug to PyTorch. Adding numerator value of zero not supported in ProjectedExtent.

This is coming from `getPointwiseHeuristics` calling `getAllVectorizedMapsOf`->`ContiguousInnerDimensionsMapper::map`. My naive thought is to just extent `ProjectedExtent` to handle size-0 dimensions, but I want to be sure that doesn't violate any assumptions in uses of that class first.

### PR DESCRIPTION
**Pull request by jacobhinkle**
A number of issues have come up when trying to process empty tensors (i.e. ones with at least one non-reduction axis with extent of zero) during scheduling and lowering. See: #264 #369 #269. Additionally, we now assume extents are positive (#440). Along with #543, this PR makes that a reality by removing all intermediate empty tensors.

This PR:
- Marks a `Fusion` as dynamic if dynamic reshapes/resizes exist or if _any_ alive `TensorView` has a static size-zero extent or a dynamic extent, since it might be empty. **This is means only Fusions with nothing but concrete non-zero sizes are static now.** That is, even if all static shapes are provided, it will be marked as a dynamic Fusion and those `TensorView`s will be modified during concretization.
- Adds a pass done during `getConcretizationInfo()` that collects a vector of empty tensors which are not fusion inputs. It does not traverse their definitions, since there is nothing to compute for an empty tensor.
- During concretization, sets the size-0 extents of identified empty tensors to constant 0.

When encountering a new set of input sizes/scalars, we evaluate a minimal set of `Val`s (those that appear in dynamic extents), and only proceed with removing branches if any of these are zero. So there is a rather quick path to re-using concretizations in the common case where none of the extents are zero.

Even after #543, this PR does not guarantee that all tensors present in the Fusion during scheduling have non-zero extent. It does guarantee that any remaining empty tensors are either fusion inputs or outputs, and that empty tensors will have constant 0 extents in any empty dimensions.  Stripping empty inputs and outputs from the Fusion could potentially be done at segmentation, but should only be done if it does not result in additional kernels being launched; that is left for another PR (see #448).

Fixes #365 and fixes #264. This replaces PRs #369 and #269.

### CODE REVIEW

**Comment by jacobhinkle** [comment]
In this approach, I've replaced extents that concretize to zero with `fusion->zeroVal()`, which we could use as a stand-in for having a new `IterType` for empty extents. Using the check for constant zero means we could avoid needing a separate `IterType` for size-0 reduction axes.

File: test/test_gpu1.cpp [hunk 1]
```diff
@@ -8106,8 +8106,8 @@ TEST_F(NVFuserTest, FusionMagicSchedulerInstanceNormalizationBackward_CUDA) {
       at_input_nvfuser,
       at_grad_nvfuser,
       at_weight_nvfuser,
-      at::empty({}),
-      at::empty({}),
+      at::empty({}, options),
+      at::empty({}, options),
```
Comment (jacobhinkle) [inline test/test_gpu1.cpp:8110]: Fixed a transient bug where these tensors were not technically set as CUDA tensors.

File: test/test_dynamic_transform.cpp [hunk 2]
```diff
@@ -1001,6 +1007,135 @@ TEST_F(NVFuserTest, DynamicPadShmoo_CUDA) {
...
+    auto initial_info = DynamicTransform::getInitialInfo(&fusion);
+    auto info = DynamicTransform::getConcretizationInfo(
+        &fusion, &initial_info, &expr_eval);
+    for (const auto& empty_desc : info.getEmptyTensors()) {
+      TORCH_CHECK(
+          y != empty_desc.tv,
+          "Expected ",
+          y->toString(),
+          " to not be marked empty as it is on a dead branch: ",
+          info.toString());
```
Comment (jacobhinkle) [inline test/test_dynamic_transform.cpp:1134]: This currently fails since I have not yet figured out how to conditionally stop traversing in `BackwardVisitor`, so all active empty tensors are added. Once we see a zero tensor, we should not process its definition. This may be easier to do without using `BackwardVisitor`, using a queue and `unordered_set`.

File: test/test_dynamic_transform.cpp [hunk 3]
```diff
@@ -1001,6 +1007,135 @@ TEST_F(NVFuserTest, DynamicPadShmoo_CUDA) {
...
+  // Fusion output should have hardcoded zero extent after concretization
+  auto output_extent = tv_output->axis(0)->extent();
+  EXPECT_TRUE(output_extent->isConstInt());
+  EXPECT_EQ(output_extent->getInt(), 0);
+
+  // Fusion input should have hardcoded zero extent after concretization
+  auto input_extent =
+      runtime_fusion->inputs().at(0)->as<TensorView>()->axis(0)->extent();
+  EXPECT_TRUE(input_extent->isConstInt());
+  EXPECT_EQ(input_extent->getInt(), 0);
```
Comment (jacobhinkle) [inline test/test_dynamic_transform.cpp:1100]: This currently fails since I have not yet figured out how to replace inputs to a `Fusion`. Outputs are easy to replace using `replaceOutput`. We probably just need to add a simple `replaceInput` method.

**Comment by jacobhinkle** [comment]
Currently, I am replacing inputs so that I can hardcode their extents as zero. This can cause problems since it replaces an input extent, meaning that extent `Val` can no longer be bound, and if it is used in further expressions directly (i.e. not related through exact maps), then we have no way to infer it later. This happens in the PadShmoo test. I would prefer to not overwrite the extent expressions at all, but we would still potentially want a way to infer that they are zero later (at least when we are doing `addAxioms`). This is only an issue for input tensors, so we could skip input tensors when adding axioms. Or we could imagine more powerful (invasive) solutions like #382 for tracking `Val`s that are equivalent to `zeroVal`, instead of using `isConstInt` and `evaluateInt`.

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
> Currently, I am replacing inputs so that I can hardcode their extents as zero. 

This introduced headaches since the `Val`s corresponding to these extents will need to be bound and propagated properly, which is difficult if we replace them with constants ahead of time. Instead, we can add an axiom that they are equal to zero, or we could instead move the positive-extent axioms to concretization instead of having it further down the pipeline where it no longer has access to concretization info.

**Review by naoyam — COMMENTED** [review]
Some preliminary comments

File: csrc/dynamic_transform.cpp [hunk 4]
```diff
@@ -385,6 +541,222 @@ void DynamicTransformConcretizer::concretize() {
   }
 }
 
+void DynamicTransformConcretizer::removeEmptyBranches() {
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:544]: Can you please add some example cases as a comment?

File: csrc/dynamic_transform.cpp [hunk 5]
```diff
@@ -385,6 +541,222 @@ void DynamicTransformConcretizer::concretize() {
...
+    auto hasEmptyRootReductionAxis = [&empty_tv_descr](TensorView* out_tv) {
+      return std::any_of(
+          empty_tv_descr.empty_axes.begin(),
+          empty_tv_descr.empty_axes.end(),
+          [&out_tv](size_t ax) {
+            return out_tv->getRootDomain().at(ax)->isReduction();
+          });
+    };
+
+    // Given a TensorView, get a shape with hard-coded zeroes
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:570]: Does it really hard-code zeros? Looks like it just fills with `getMaybeExpandedExtent()`.

File: csrc/dynamic_transform.cpp [hunk 6]
```diff
@@ -385,6 +541,222 @@ void DynamicTransformConcretizer::concretize() {
...
+        }
+      }
+    }
+    if (!tv->isFusionInput()) {
+      replaced[tv] = replaceWithFull(tv, new_shape);
+    }
+  }
+}
+
+TensorView* DynamicTransformConcretizer::replaceWithFull(
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:704]: Same here. Please add an example as a comment

File: csrc/dynamic_transform.cpp [hunk 7]
```diff
@@ -385,6 +541,222 @@ void DynamicTransformConcretizer::concretize() {
...
+    // particularly pad, cat, and reduction ops. These ops might have
+    // non-empty outputs so in order to guarantee that all (non- input or
+    // output) tensors are removed, we need to replace those ops with an
+    // equivalent that does not have any empty inputs.
+    for (auto use : tv->uses()) {
+      // If use is a ReductionOp or WelfordOp over some empty axes, replace it
+      // with a call to full().
+      if (auto rop = dynamic_cast<ReductionOp*>(use)) {
+        auto out = maybeReplaced(rop->out()->as<TensorView>());
+        if (hasEmptyRootReductionAxis(out)) {
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:612]: What happens if only some of zero domains are reduced? Should it be converted to a full op?

File: csrc/dynamic_transform.cpp [hunk 8]
```diff
@@ -385,6 +541,222 @@ void DynamicTransformConcretizer::concretize() {
...
+        return tv;
+      }
+      return it->second;
+    };
+
+    // Replace uses whose outputs might not be empty. Many expressions are
+    // guaranteed to have empty outputs if any of the inputs are empty; for
+    // example simple unary or binary ops. In those cases, we don't need to
+    // doctor the Fusion since they will have an empty tensor downstream which
+    // will cut off their dependence, resulting in those uses becoming dead
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:599]: How does that become dead code? Can you show an example?

**Review by naoyam — COMMENTED** [review]
Some more comments

File: csrc/dynamic_transform.cpp [hunk 9]
```diff
@@ -154,6 +181,97 @@ class DynamicTransformInitialInfoBuilder : public IterVisitor {
   std::vector<Val*> leaf_dynamic_vals_;
 };
 
+//! This performs a depth-first search from outputs toward inputs for empty
+//! tensors. It does not traverse past any zero tensors it finds; this is why
+//! this is implemented as a single function instead of with BackwardVisitor.
```
[the remark this answers is not in the document]
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:186]: Originally I used `BackwardVisitor`, but when we encounter an empty tensor, we want to DCE its upstream branch at concretization. That means we should not continue processing it, because any dynamic transforms in the dead branches will lead to spurious concretization info that might cause cache misses due to different concretization of the dead branches. So I just process it with a stack instead so I can skip those branches easily.

File: csrc/dynamic_transform.cpp (hunk 7 above)
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:616]: In that case, the output will have some zero dims, so this reduction will be dead code.

File: csrc/dynamic_transform.cpp [hunk 10]
```diff
@@ -154,6 +181,97 @@ class DynamicTransformInitialInfoBuilder : public IterVisitor {
...
+      continue;
+    }
+    auto tv = val->as<TensorView>();
+    if (visited.find(tv) != visited.end()) {
+      continue;
+    }
+    visited.insert(tv);
+
+    std::vector<size_t> empty_axes;
+    auto rfactor = TensorDomain::noReductions(tv->getMaybeRFactorDomain());
```
[the remark this answers is not in the document]
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:212]: Suppose a tensor has some size-zero dimensions. If any of those are not reduced, then the output will have some zero dimensions. In that case, the backward pass to find empty tensors will identify them, or their uses and the reduction will become dead code.

If all empty dimensions are reduced, then the output will not be empty, so this will be the furthest downstream empty tensor, meaning we're handling it directly. In `DynamicTransformConcretizer::removeEmptyBranches()`, we replace the tensor with a `full()`, then we look at its `uses()`. There we handle reductions, Welfords, pads, and cats. In the case of a reduction, we replace the reduction with a `full(init_value)`.

File: csrc/dynamic_transform.cpp (hunk 5 above)
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp]: Changed the comment to more accurately reflect that this just gets a shape.

File: csrc/dynamic_transform.cpp (hunk 9 above)
[the remark this answers is not in the document]
Comment (naoyam) [reply csrc/dynamic_transform.cpp:188]: I'm fine with it as is, but sounds like you could do so by extending the `next` method. See https://github.com/NVIDIA/Fuser/blob/main/csrc/iter_visitor.cpp#L308-L313, for example.

[the remark this answers is not in the document]
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:188]: The problem is that `next` works in the forward direction: it tells you the next downstream statements to process. In `BackwardVisitor`, this is used in a forward traversal from `InputsOf(outputs)` to outputs to build a stack of statements, then the statements are handled by popping from the stack, which reverses the handling. https://github.com/NVIDIA/Fuser/blob/e2bc9f39fc22afeb76e7ba1f652b78728851c447/csrc/iter_visitor.cpp#L460-L480. The original `InputsOf` is determining the roots to flow forward from. Instead, I just build the stack during a single backward pass that finds terminates at empty tensors, which would otherwise require modifying the behavior of `Inputs` inside `BackwardVisitor`.

File: csrc/dynamic_transform.cpp (hunk 4 above)
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:626]: Added an example and expanded comment in header.

File: csrc/dynamic_transform.cpp (hunk 8 above)
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:668]: Updated this comment with binary op example.

File: csrc/dynamic_transform.cpp [hunk 11]
```diff
@@ -385,6 +648,219 @@ void DynamicTransformConcretizer::concretize() {
...
+      registerConcretization(new_shape[ax], fusion->zeroVal());
+      new_shape[ax] = fusion->zeroVal();
+    }
+
+    auto hasEmptyRootReductionAxis = [&empty_tv_descr](TensorView* out_tv) {
+      return std::any_of(
+          empty_tv_descr.empty_axes.begin(),
+          empty_tv_descr.empty_axes.end(),
+          [&out_tv](size_t ax) {
+            return out_tv->getRootDomain().at(ax)->isReduction();
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:673]: Isn't `ax` an offset within the rfactor no-reduction domain?

File: csrc/dynamic_transform.cpp (hunk 7 above)
Comment (naoyam) [reply csrc/dynamic_transform.cpp:721]: But the reduction itself is still replaced, and it's just it's going to be dead code eventually, right?

File: csrc/dynamic_transform.cpp [hunk 12]
```diff
@@ -385,6 +648,219 @@ void DynamicTransformConcretizer::concretize() {
...
+    };
+
+    // Given a TensorView get a vector of its maybeRFactor maybeExpandedExtents
+    auto orig_shape = [](TensorView* out_tv) -> std::vector<Val*> {
+      const auto& rfactor =
+          TensorDomain::noReductions(out_tv->getMaybeRFactorDomain());
+      std::vector<Val*> out_shape;
+      out_shape.reserve(rfactor.size());
+      for (const auto id : rfactor) {
+        out_shape.push_back(id->getMaybeExpandedExtent());
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:684]: Why is a domain expanded? Can we create a tensor with an expanded domain with a full op?

File: csrc/dynamic_transform.cpp [hunk 13]
```diff
@@ -385,6 +648,219 @@ void DynamicTransformConcretizer::concretize() {
...
+          auto out_shape = orig_shape(out);
+          replaceWithFull(out, out_shape);
+        }
+      } else if (auto wop = dynamic_cast<WelfordOp*>(use)) {
+        auto avg = maybeReplaced(wop->outAvg()->as<TensorView>());
+        auto var = maybeReplaced(wop->outVar()->as<TensorView>());
+        auto N = maybeReplaced(wop->outN()->as<TensorView>());
+        if (hasEmptyRootReductionAxis(avg)) {
+          auto out_shape = orig_shape(avg);
+          auto nan = IrBuilder::create<Double>(0.0 / 0.0);
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:731]: Can't we just use something `NAN` instead of actually doing a zero division? Is this a standard convention?

File: csrc/dynamic_transform.cpp [hunk 14]
```diff
@@ -385,6 +648,219 @@ void DynamicTransformConcretizer::concretize() {
...
+    // Then the tensors tv2 and tv3 will become dead code if they have no other
+    // live uses. In this case tv4 is an output tensor, so we must keep it in
+    // the Fusion.
+    //
+    // Some special expressions can convert an empty tensor into a non-empty
+    // tensor; particularly pad, cat, and reduction ops. These ops might have
+    // non-empty outputs so in order to guarantee that all non- input or
+    // output tensors are removed, we need to replace those ops with an
+    // equivalent that does not have any empty inputs. For example
+    for (auto use : tv->uses()) {
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:716]: The control flow below looks a little convoluted. Given that in the future there could be other additional patterns where zero domains would need to be handled, I'd suggest to refactor below and make each part a separate function.

File: csrc/dynamic_transform.cpp (hunk 7 above)
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:721]: Yes. I think I see what you're saying. It's unnecessary to replace the reduction if we know it's dead code. I can add a check for empty unreduced dims.

File: csrc/dynamic_transform.cpp (hunk 11 above)
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:674]: Right. This is a little confusing. I will change this to refer to rfactor domain instead. In this case, we know there's not an rfactor domain since the op is a reduction, but it will be much clearer to have the descriptor always refer to the maybeRFactor domain.

File: csrc/dynamic_transform.cpp (hunk 13 above)
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp]: Changed to use `std::numeric_limits<double>::quiet_NaN()`.

File: csrc/dynamic_transform.cpp (hunk 12 above)
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:685]: This lambda is applied to outputs from reductions, Welfords, and pads. If those have inputs with non-reduced and non-padded dimensions that are expanded, they'll be preserved as expanded in the output. We could instead replace with a full followed by an expand, but I figured we could just go ahead and realize the expand on an empty tensor instead for simplicity.

File: csrc/dynamic_transform.cpp (hunk 14 above)
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:717]: I agree this is a good idea; I'm refactoring into an overloaded function to handle these ops....

File: csrc/dynamic_transform.cpp [hunk 15]
```diff
@@ -385,6 +648,219 @@ void DynamicTransformConcretizer::concretize() {
...
+
+  for (auto use : old_tv->uses()) {
+    ir_utils::replaceValInExpr(use, old_tv, new_tv);
+  }
+
+  if (old_tv->isFusionOutput()) {
+    old_tv->fusion()->replaceOutput(old_tv, new_tv);
+  }
+
+  replaced_tvs_[old_tv] = new_tv;
```
[the remark this answers is not in the document]
Comment (naoyam) [reply csrc/dynamic_transform.cpp:907]: Sorry, what do you mean by "only mutates and does not replace it"? Is this a generic issue with the mutator interface? If so, does it make sense to have a generic fix?

File: csrc/dynamic_transform.cpp [hunk 16]
```diff
@@ -385,6 +689,224 @@ void DynamicTransformConcretizer::concretize() {
...
+    shape.push_back(id->getMaybeExpandedExtent());
+  }
+  return shape;
+}
+
+//! Return whether or not we should replace a reduction or Welford op that is
+//! given an empty input tensor. Returns false if any non-reduction axes are
+//! empty, and otherwise return true if any reduction axis is empty.
+bool reductionOutputShouldBeReplaced(
+    TensorView* out,
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:710]: Is `out` assumed to be an output of a reduction op? Should we assert that?

File: csrc/dynamic_transform.cpp [hunk 17]
```diff
@@ -385,6 +689,224 @@ void DynamicTransformConcretizer::concretize() {
...
+    const std::vector<size_t>& empty_axes) {
+  bool has_empty_reduction = false;
+  bool has_empty_nonreduction = false;
+  // A reduction op itself should not generate an R-Factor domain anyway, but
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:714]: Please also mention that reduction rfactor should not be used at this point (if so, a reduction output can have an rfactor domain).

Should we assert that `out` doesn't have an rfactor domain?

File: csrc/dynamic_transform.cpp [hunk 18]
```diff
@@ -385,6 +689,224 @@ void DynamicTransformConcretizer::concretize() {
...
+  // note that we use the root domain explicitly here for clarity. This is
+  // because empty_axes refers to the _input_ of the reduction op we are
+  // considering, so it maps to the root domain of the TensorView "out" in this
+  // function.
+  auto dom = out->getRootDomain();
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:719]: nit:
```suggestion
  const auto& dom = out->getRootDomain();
```

File: csrc/dynamic_transform.cpp (hunk 16 above)
Comment (naoyam) [reply csrc/dynamic_transform.cpp:710]: I realized it's rather clear as indicated by the function name.

File: csrc/dynamic_transform.cpp [hunk 19]
```diff
@@ -385,6 +689,224 @@ void DynamicTransformConcretizer::concretize() {
...
+        : cat(nonempty_inputs, cop->concatenatedDim());
+    replaceTV(old_cat, new_cat);
+  } else { // Replace pads that are not part of CatOps with full()
+    auto out_shape = tensor_shape(out);
+    // Wherever there is a zero in the input, we will replace the original
+    // output extent so that we no longer reference the now-zero input
+    // extent
+    for (auto ax : empty_axes) {
+      auto pad_widths = pop->getPadWidths((int)ax);
+      out_shape[ax] = add(pad_widths.first, pad_widths.second);
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:840]: What happens if `pad_widths` are also zero?

File: csrc/dynamic_transform.cpp (hunk 10 above)
[the remark this answers is not in the document]
Comment (naoyam) [reply csrc/dynamic_transform.cpp:213]: I was a little confused here because I considered `tv` as a reduction output, so ignoring reduction domains didn't make sense. Looks like we are using the axis information collected from reduction inputs, so doing `noReductions` makes sense.

File: csrc/dynamic_transform.cpp [hunk 20]
```diff
@@ -385,6 +689,224 @@ void DynamicTransformConcretizer::concretize() {
...
+      // and output tensors during scheduling/execution.
+      registerConcretization(new_shape[ax], fusion->zeroVal());
+      new_shape[ax] = fusion->zeroVal();
+    }
+
+    for (auto use : tv->uses()) {
+      replaceEmptyUse(use, empty_tv_descr.empty_axes);
+    }
+    if (!tv->isFusionInput()) {
+      replaceWithFull(tv, new_shape);
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:867]: If all uses of `tv` is replaced by `replaceEmptyUse`, is this `replaceWithFull` necessary? I think not, but it would just become a dead full op, right?

File: csrc/dynamic_transform.cpp [hunk 21]
```diff
@@ -385,6 +689,224 @@ void DynamicTransformConcretizer::concretize() {
...
+  }
+}
+
+TensorView* DynamicTransformConcretizer::replaceWithFull(
+    TensorView* tv,
+    std::vector<Val*>& new_shape,
+    Val* fill_value) {
+  TensorView* mut_tv = nullptr;
+  if (!tv->definition()) {
+    return tv;
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:878]: Can we just assert `tv->definition() != nullptr`?

File: csrc/dynamic_transform.cpp [hunk 22]
```diff
@@ -385,6 +689,224 @@ void DynamicTransformConcretizer::concretize() {
...
+  }
+  if (!fill_value) {
+    fill_value = tv->fusion()->zeroVal();
+  }
+  if (fill_value->getDataType().value() != tv->getDataType().value()) {
+    fill_value = castOp(tv->getDataType().value(), fill_value);
+  }
+  mut_tv = full(new_shape, fill_value, tv->getDataType().value());
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:886]: nit: 
```suggestion
  auto mut_tv = full(new_shape, fill_value, tv->getDataType().value());
```

And remove line 876.

File: test/test_resize.cpp [hunk 23]
```diff
@@ -2168,6 +2168,52 @@ TEST_F(NVFuserTest, FusionSqueezeSymbolic_CUDA) {
...
+  auto tv0 = makeConcreteTensor(shape);
+  fusion->addInput(tv0);
+
+  // Perform a size-1 slice and a size-0 slice on tv0. The size-1 slice
+  // could be size >1 with no change in the error. The order does not
+  // matter. Performing only one of these slices does not trigger the
+  // error and the output is correct in that case. If there are
+  // multiple size-0 slices the error is not triggered. It only seems
+  // to appear when there are both size-0 and size non-zero slices of
+  // the same tensor.
```
Comment (naoyam) [inline test/test_resize.cpp:2187]: This comment sounds like there's still an error. Can you update what the issue was and clarify that it's now fixed?

File: test/test_resize.cpp [hunk 24]
```diff
@@ -2168,6 +2168,52 @@ TEST_F(NVFuserTest, FusionSqueezeSymbolic_CUDA) {
...
+  std::vector<c10::IValue> aten_inputs({t0});
+
+  FusionExecutorCache executor_cache(std::move(fusion));
+  auto cg_outputs = executor_cache.runFusionWithInputs(aten_inputs);
+
+  auto ref0 = t0.index({at::indexing::Slice(0, 1)});
+  auto ref1 = t0.index({at::indexing::Slice(0, 0)});
+
+  TORCH_CHECK(ref0.equal(cg_outputs[0]));
+  TORCH_CHECK(ref1.equal(cg_outputs[1]));
```
Comment (naoyam) [inline test/test_resize.cpp:2214]: Can you also verify the post-removal fusion more explicitly? In this case, IIUC, `tv2` should be just replaced with a full op output. `tv1` doesn't seem to have anything to do with the zero-dim processing.

**Comment by naoyam** [comment]
Added some more remaining comments, which are mostly just minor clarifications.

I think we should expand tests. For example, do we have a test of just reducing zero-dim domains?

File: csrc/dynamic_transform.cpp (hunk 15 above)
[the remark this answers is not in the document]
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:907]: In concretization, we have so far not wanted to replace `TensorView`s, but with this PR (and #511) we have started rewriting the `TensorView` graph instead of just updating the `TensorDomain`s, like we do for `resize` and `reshape`. 

Instead of changing `OptOutMutator`, I think I just need to fix how we are using it. I had a misunderstanding about how it was meant to be used and thought that if we did not want to directly replace an expression, that registering the input or output `Val`s would be enough. This is not true since `OptOutMutator::mutate(Expr*)` is actually the thing that does val replacement. So one needs to traverse the graph in topological order and call `mutate(stmt)` for each `Expr` as well as any `Val`s that might need to be changed (including `TensorView`s and `TensorDomain`s if they contain `IterDomain`s that have been changed). Note that replacing inputs or outputs would need to be done manually and can be done at any point. I think currently we are not calling `mutate` on exprs during the concretization loop, but if we do that (and also call `replaceOutput` when needed) then marking vals for replacement should work fine.

I will try this and report back.

[the remark this answers is not in the document]
Comment (naoyam) [reply csrc/dynamic_transform.cpp:907]: >In concretization, we have so far not wanted to replace TensorViews, but with this PR (and https://github.com/NVIDIA/Fuser/pull/511) we have started rewriting the TensorView graph instead of just updating the TensorDomains, like we do for resize and reshape.

Right, that's true.

[the remark this answers is not in the document]
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:907]: I've almost converted the code but it is fragile and it is starting to feel like this doesn't actually belong in concretization. Really, this is an optimization that we could do as an optimization pass if we set enough information at concretization. The reason I put it here originally was that we need the change to be reflected in concretization info since it depends on input sizes. But altering the `TensorView` graph is really what the optimization passes are for.

Instead, we could do the following at concretization without ever replacing one `TensorView` with another:

- Concretize `reshape` as we do now: by replacing the rfactor domain with the transforms found in `analyzeView`.
- Set constant extents of `zeroVal()` wherever we find empty tensors (replaces this PR).
- Concretize `slice` by setting the output extents according to the concrete branch (replaces #511). We would skip replacing the output with `full` (for empty slices) and `set` (trivial slices), but we would set the output extents to either `zeroVal()` or the input extent in those cases so that we can detect them in an optimization pass.
- Propagate concretized extents and `IterType`s as we do now.

Then, we would add optimization passes to do the following rewriting of the graph:

- Detect empty tensors by looking for constant zero extents in a backward traversal pass. Replace them with `full` if they are outputs, otherwise replace their reduction/pad/cat uses as appropriate (replaces this PR).
- Detect size-1 extents in outputs from operations like pad or slice. Currently we set the output `IterType` to broadcast at concretization, but we could additionally translate them into more meaningful and possibly simpler operations. For example, if we pad with non-positive pad widths and the result has size 1, it is actually a `select`+`broadcast`. In order to determine if the pad widths are non-positive, we could use axioms (#440). We could additionally check that the broadcast is resolved here since that may help simplify the graph as well (see #340).
- Detect trivial `slice` outputs by checking whether their slice `start`, `stop`, `step` are `sameAs` 0, `input->extent()`, and 1; if so we would replace the `slice` with `set`.

[the remark this answers is not in the document]
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:907]: I have opened #543 which addresses this much more cleanly I think. In this new approach we will only modify `TensorDomain`s during concretization, and we will leave rewriting the `TensorView`s for the pre-segmentation passes. I am now working on simplifying the present PR so that we just set extents to zero in the concretization pass.

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

File: csrc/dynamic_transform.cpp [hunk 25]
```diff
@@ -370,18 +447,34 @@ class DynamicTransformConcretizer : public OptOutMutator {
...
 
+  // Registers replacement of all empty extents with zeroVal()
+  concretizeEmptyExtents();
+
   // Finally, propagate concretized domains
-  auto all_stmts = StmtSort::getStmts(info_->fusion(), true);
-  for (auto stmt : all_stmts) {
-    if (stmt->isA<Val>()) {
-      mutate(stmt);
+  auto all_stmts = StmtSort::getStmts(info_->fusion());
```
Comment (jacobhinkle) [inline csrc/dynamic_transform.cpp:460]: Note we no longer traverse into members.

File: csrc/ops/alias.h [hunk 26]
```diff
@@ -97,12 +97,14 @@ TORCH_CUDA_CU_API TensorView* transpose(TensorView* x);
...
-    Val* value = nullptr);
+    Val* value = nullptr,
+    std::optional<IterType> iter_type_opt = std::nullopt);
 
 //! Concatenate tensors in the given dimension
 TORCH_CUDA_CU_API TensorView* cat(
     const std::vector<TensorView*>& inputs,
-    int64_t dim);
+    int64_t dim,
+    std::optional<IterType> iter_type_opt = std::nullopt);
```
Comment (jacobhinkle) [inline csrc/ops/alias.h:107]: These options let us pipe through an optional IterType to avoid symbolic IterTypes popping up during the RemoveEmptyPass. This is a bug that was exposed by the dynamic empty cat tests.

File: csrc/fusion_segmenter.cpp [hunk 27]
```diff
@@ -3399,13 +3399,24 @@ void SegmentCandidateFinder::forwardInputs() {
...
       }
 
-      if (expr->output(0)->uses().size() > 1) {
+      // expr is a unary op so there is a single output. Here we look at that
+      // output's further uses
+      auto output_uses = expr->output(0)->uses();
+      if (output_uses.size() == 0) {
+        // Unused outputs terminate here
+        continue;
+      }
```
Comment (jacobhinkle) [inline csrc/fusion_segmenter.cpp:3408]: This fixes a segfault that popped up in the `Standalone*` tests in `test_tensor_factories.cpp`. These tests have scalar inputs which are used in `FullOp`s as fill values. When the extents are zero, concretization replaces those `FullOps` with others so that the output size is hardcoded. This means the original fill value (which is now irrelevant since the output is empty) has no uses. The cast to target dtype before the `full` means we have `input -> cast -> (no uses)`, which caused a segfault here. We now just check that there's at least one use to avoid a segfault.

**Comment by jacobhinkle** [comment]
!build

File: test/test_resize.cpp (hunk 24 above)
Comment (jacobhinkle) [reply test/test_resize.cpp:2194]: Done below

**Comment by jacobhinkle** [comment]
!build

File: csrc/fusion_segmenter.cpp [hunk 28]
```diff
@@ -3399,13 +3399,24 @@ void SegmentCandidateFinder::forwardInputs() {
         continue;
       }
 
-      if (expr->output(0)->uses().size() > 1) {
+      // expr is a unary op so there is a single output. Here we look at that
```
Comment (naoyam) [inline csrc/fusion_segmenter.cpp:3402]: Is this a general bug fix or specific to the replacement of size-zero extents?

File: csrc/dynamic_transform.cpp [hunk 29]
```diff
@@ -141,6 +161,16 @@ class DynamicTransformInitialInfoBuilder : public IterVisitor {
     }
   }
 
+  //! Convert maybe_zero_extents_set_ to a vector so we can index it reliably
+  void finalizeMaybeEmptyExtents() {
+    info_.maybe_zero_extents_.reserve(info_.maybe_zero_extents_set_.size());
+    for (auto val : info_.maybe_zero_extents_set_) {
+      info_.maybe_zero_extents_.push_back(val);
+    }
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:169]: nit:
```suggestion
    info_.maybe_zero_extents_ = std::vector<IterDomain*>(info_.maybe_zero_extents_set_.begin(), info_.maybe_zero_extents_set_.end());
```

File: csrc/dynamic_transform.cpp [hunk 30]
```diff
@@ -370,18 +447,34 @@ class DynamicTransformConcretizer : public OptOutMutator {
...
+  auto fusion = FusionGuard::getCurFusion();
+  for (const auto& ext_index : info_->getEmptyExtents()) {
+    auto ext = info_->initialInfo()->getMaybeZeroExtents().at(ext_index);
+    auto zero = fusion->zeroVal(ext->getDataType().value());
+    auto uses = ext->uses();
+    for (auto use : uses) {
+      ir_utils::replaceValInExpr(use, ext, zero);
     }
+    // Register the concretization of this scalar, which allows us to replace it
+    // whenever it is used as an extent member of an IterDomain.
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:476]: This is because `ext` is "used" by an IterDomain but it isn't part of `uses()`, correct?

File: csrc/dynamic_transform.cpp (hunk 25 above)
Comment (naoyam) [reply csrc/dynamic_transform.cpp:460]: Don't remember why it did

File: csrc/dynamic_transform.cpp [hunk 31]
```diff
@@ -656,7 +754,9 @@ bool DynamicTransformConcretizer::propagateFromProducerToConsumer(
         consumer->toString());
 
     auto concretized_id =
-        IterDomainBuilder(root_id).iter_type(*id_type).build();
+        IterDomainBuilder(maybeMutated(root_id)->as<IterDomain>())
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:757]: Is this change because the extent of `root_id` may be changed to 0?

File: csrc/dynamic_transform.cpp [hunk 32]
```diff
@@ -446,8 +540,10 @@ void DynamicTransformConcretizer::checkConcretizedUses(
 // concretized. Since symbolic IDs may be propagated down to
 // consumers, those domains need to be concretized accordingly.
 void DynamicTransformConcretizer::mutate(TensorView* tv) {
-  if (!tv->domain()->hasSymbolicAxis()) {
-    return;
+  for (auto root_id : tv->getRootDomain()) {
```
Comment (naoyam) [inline csrc/dynamic_transform.cpp:543]: This looks a bit confusing. A root ID may be mutated here, but there's also `propagateFromProducerToConsumer` below, which may also mutate a root ID. Is there any concern of conflicts?

File: csrc/optimization/remove_empty.cpp [hunk 33]
```diff
@@ -260,8 +260,16 @@ class EmptyTensorRemover : public DeadCodeRemover {
     if (non_empty_inputs.size() != cop->inputs().size()) {
       // Replace this op with a new cat op
       auto old_tv = cop->outputs()[0]->as<TensorView>();
-      // NOTE: cat() will translate to set() if non_empty_inputs.size() == 1
-      auto new_tv = cat(non_empty_inputs, dim);
+      // NOTE: cat() will translate to set() if non_empty_inputs.size() == 1.
+      // Also note that unless we're careful this call to cat() might result in
+      // symbolic axis, since the inputs have potentially symbolic extents in
+      // the cat dimension. However, since we have already undergone
+      // concretization at this point, we can trust that the original IterType,
```
[the remark this answers is not in the document]
Comment (jacobhinkle) [reply csrc/optimization/remove_empty.cpp:267]: The input extents are symbolic (e.g. `i0`) or they are `zeroVal()`, but since we use the `cat` command here to do the replacement, we need some way to tell it to not use `IterType::Symbolic` and trust us at this point that the output will be `Iteration`.

File: csrc/dynamic_transform.cpp (hunk 30 above)
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:473]: Yes exactly. When we replace in `uses()` we update things like `i0 + 1`, but `iS2{i0}` would remain unless registered for mutation.

File: csrc/dynamic_transform.cpp (hunk 31 above)
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:754]: Yes exactly, when we call `OptOutMutator::mutate(root_id)` it will register it for mutation if any of its members are mutated, including the extent. Since we are going to register another mutation here, we don't want to lose those changes, so we base `concretized_id` on the mutated ID.

File: csrc/dynamic_transform.cpp (hunk 32 above)
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:540]: At line 659 in `propagateFromProducerToConsumer`, we reflect the earlier mutation by basing the new mutated ID on `maybeMutated(root_id)`. That way we compose both mutations.

File: csrc/dynamic_transform.cpp (hunk 25 above)
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:457]: I changed it to `true` in #258 so that the traversal would handle `IterDomain`s, but I didn't have a clear enough picture of how that should work at that time.

Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:457]: Now we explicitly are only traversing the `TensorView` graph, and we only handle `IterDomain` members manually.

File: csrc/dynamic_transform.cpp (hunk 32 above)
Comment (naoyam) [reply csrc/dynamic_transform.cpp:542]: Well, what happens if the same root ID is mutated both at line 546 and within line 551? Doesn't the latter just overwrite the mutation at line 546?

Comment (naoyam) [reply csrc/dynamic_transform.cpp:542]: Oh, are you referring to line 659 before this PR?

File: csrc/optimization/remove_empty.cpp (hunk 33 above)
[the remark this answers is not in the document]
Comment (jacobhinkle) [reply csrc/optimization/remove_empty.cpp:267]: Yes exactly. It should be more clear in the comment probably.

File: csrc/dynamic_transform.cpp (hunk 32 above)
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:542]: It will overwrite the mutation, but since we using `IterDomainBuilder(maybeMutated(root_id)->as<IterDomain>())` as the basis of the new mutation lets us update the `IterType` without changing other mutations like the extent.

File: csrc/dynamic_transform.cpp (hunk 30 above)
Comment (jacobhinkle) [reply csrc/dynamic_transform.cpp:475]: Done

File: csrc/dynamic_transform.cpp (hunk 32 above)
Comment (naoyam) [reply csrc/dynamic_transform.cpp:548]: OK, I see it now. Maybe it'd be helpful to add that to the code comment too.

File: csrc/optimization/remove_empty.cpp (hunk 33 above)
[the remark this answers is not in the document]
Comment (jacobhinkle) [reply csrc/optimization/remove_empty.cpp]: Updated the comment.

**Review by naoyam — APPROVED** [review]
I'm approving this now, but let me review the segmentation change separately before merging this

**Comment by jacobhinkle** [comment]
> I'm approving this now, but let me review the segmentation change separately before merging this

Sounds good. The current fix in the segmentation PR is slightly different from what is here. I think that one makes more sense and is a bit simpler so if approved, I'll just revert the one here before merging main.

**Comment by naoyam** [comment]
Approved the other PR as well
