### PR TITLE
Fix sharding decomposition for biased row-parallel linear. 

### LINKED ISSUE #4363: Biased row-parallel linear generates wrong numbers.
See https://github.com/NVIDIA/Fuser/pull/4362 for the repro

### PR DESCRIPTION
**Pull request by wujingyue**
Fixes #4363

### CODE REVIEW

File: csrc/transform_replay.cpp [hunk 1]
```diff
@@ -155,9 +155,9 @@ class ReplaySelf : public ReplayTransformations {
 
  public:
   ReplaySelf(
-      const std::vector<IterDomain*>& _target_domain,
-      IterDomainMap _id_map)
-      : ReplayTransformations(_target_domain, std::move(_id_map)) {
+      const std::vector<IterDomain*>& target_domain,
+      IterDomainMap id_map)
+      : ReplayTransformations(target_domain, std::move(id_map)) {
```
Comment (wujingyue) [inline csrc/transform_replay.cpp:160]: Naming nits

File: csrc/transform_replay.cpp [hunk 2]
```diff
@@ -299,17 +293,20 @@ void TransformReplay::selfReplay(
...
+          // NOLINTNEXTLINE(modernize-use-emplace)
+          new_contiguity.push_back(std::nullopt);
+        }
       }
     }
 
     // Pushing the mapped IDs and corresponding contiguity flags
     for (size_t i : arange(self_allocation.size())) {
       IterDomain* id = self_allocation[i];
+      // FIXME: this is wrong when ignore_reductions=false.
```
Comment (wujingyue) [inline csrc/transform_replay.cpp:309]: I'll fix this before merging.

File: csrc/transform_replay.cpp [hunk 3]
```diff
@@ -240,24 +240,18 @@ TensorDomain* TransformReplay::fullSelfReplay(
...
+    TensorDomain* new_self,
+    bool ignore_reductions) {
   FUSER_PERF_SCOPE("TransformReplay::selfReplay");
 
-  // NOTE: We could also have reduction IDs involved in transformation that
-  // leads to allocation domain, so technically we should have included
-  // reduction IDs in the replay as well. The reason that we skipped them here
-  // is because this function is used by `RemoveBcastSqueeze`, where we could
-  // have mismatch reduction IDs on the logical between `self` and
-  // `new_self`.
```
Comment (wujingyue) [inline csrc/transform_replay.cpp:251]: I added some comments in the header file, which hopefully explain the idea better.

**Comment by wujingyue** [comment]
!test

File: csrc/ops/composite.cpp [hunk 4]
```diff
@@ -161,7 +163,9 @@ TensorView* newForLinear(
   TensorDomain* td = IrBuilder::create<TensorDomain>(
       out_domain, TensorDomain::getContiguityFilledWith(out_domain, true));
 
-  return IrBuilder::create<TensorView>(td, input->dtype());
```
Comment (Priya2698) [inline csrc/ops/composite.cpp:164]: Can we set it in the decomposition instead?

**Comment by Priya2698** [comment]
To The changes to `selfReplay` seem independent to sharding decomposition.
Can we make these two separate PRs -- or is that too much effort?

File: csrc/ops/composite.cpp (hunk 4 above)
Comment (wujingyue) [reply csrc/ops/composite.cpp:164]: (I assume you are referring to calling setDeviceMesh in InsertReshardingsPass.)

I'd love to understand why you prefer one way to the other. 

I think this is part of https://github.com/NVIDIA/Fuser/issues/4336, and I'm sure I haven't thought about where to setDeviceMesh as much as you have. 

I chose to setDeviceMesh in newForLinear because
1. I followed the convention of other new-a-TV methods, which could for sure be wrong in the first place. 
2. Propagating meshes is trivial and I don't mind having to do it in multiple places.

**Comment by wujingyue** [comment]
> The changes to `selfReplay` seem independent to sharding decomposition. Can we make these two separate PRs -- or is that too much effort?

Sure! If this PR looks good to you, I'll make a smaller PR with only the selfReplay changes and a new unit test in
https://github.com/NVIDIA/Fuser/blob/413f992f439e09e8488e28a7a41a68deae9efc24/tests/cpp/test_replay.cpp#L4.

File: csrc/preseg_passes/insert_reshardings.cpp [hunk 5]
```diff
@@ -129,6 +133,39 @@ void insertReshardingSetsAfter(Fusion* fusion) {
...
+              return id->isReduction() && id->isParallelized();
+            })) {
+      continue;
+    }
+
+    auto* without_bias = linear(linear_op->inA(), linear_op->inB());
+    TransformReplay::selfReplay(out->domain(), without_bias->domain());
+
+    TensorView* broadcasted_bias =
+        broadcast(linear_op->bias(), {true, true, false});
```
Comment (Priya2698) [inline csrc/preseg_passes/insert_reshardings.cpp]: `without_bias` can be higher dimensional based on the dimensionality of `inA()`.

Comment (Priya2698) [reply csrc/preseg_passes/insert_reshardings.cpp]: https://github.com/NVIDIA/Fuser/blob/e0d5928ffaf2cd6bcf196076dbb075b1e8900e01/csrc/ops/composite.cpp#L169-L172

The inputs can be n-D whereas weights can only be 2D.

File: csrc/ops/composite.cpp (hunk 4 above)
Comment (Priya2698) [reply csrc/ops/composite.cpp:164]: I don't mind setting device meshes in the ops-- I agree it is trivial to set / unset it.
I do prefer propagating transforms explicitly as required outside of the new-TV and ops methods. Since that will also have to parallelize the new loop domain and set device mesh as required, this would be unnecessary but I am onboard with it at the current stage while #4336 is pending.

While propagating withing ops API, has the advantage of avoiding additional code in other preseg passes / segmentation, I have the following reasons to prefer the former approach from my initial investigation of this task:

1. Less unexpected: Outside multi-device new tensorviews usually have a trivial loop domain. An explicit call on propagating transforms makes it more upfront when this changes and describes how/why. 
2. Tests: When implementing tests, if I propagate transforms within the ops API, the order where I transform inputs becomes important. In some cases, I might have to roll back certain transforms which is non-trivial or be careful about where the tensorviews are transformed (before / after declaring ops).
3. Reuse of already existing replay: Several instances where new Tvs are created are already using TransformReplay (for instance: when inserting `segment_set` in MarkAliasesPreparePass). If done within ops API, we will be calling replay twice. This can be avoided by reusing the replay output and parallelizing as required for preserving sharding annotations. Other examples are cacheBefore/cacheAfter.

Comment (wujingyue) [reply csrc/ops/composite.cpp:164]: Your thought process makes sense and the rationales are well established. I'll leave setDeviceMesh here for now just so it's consistent with the other new* methods. Feel free to revert it when working on #4336.

**Comment by wujingyue** [comment]
!test
