### PR TITLE
Fix several problems related to perf_debug_verbose.

### LINKED ISSUE #1943: Some tests crash with `NVFUSER_DUMP=perf_debug_verbose`.
For example, 
```
$ NVFUSER_DUMP=perf_debug_verbose bin/nvfuser_tests --gtest_filter=NVFuserTest.CombinedSchedulerSharedProducer_CUDA
```

```
C++ exception with description "bytes_processed_per_input_ is not defined!
Exception raised from bytesInputsProcessed at /opt/pytorch/nvfuser/csrc/executor.h:260 (most recent call first):
frame #0: <unknown function> + 0x117855 (0x55d3ee5fc855 in bin/nvfuser_tests)
frame #1: <unknown function> + 0x4d097d (0x55d3ee9b597d in bin/nvfuser_tests)
frame #2: <unknown function> + 0x4d0c19 (0x55d3ee9b5c19 in bin/nvfuser_tests)
frame #3: <unknown function> + 0x4da84e (0x55d3ee9bf84e in bin/nvfuser_tests)
frame #4: <unknown function> + 0x8900f0 (0x55d3eed750f0 in bin/nvfuser_tests)
frame #5: <unknown function> + 0x8911e6 (0x55d3eed761e6 in bin/nvfuser_tests)
frame #6: <unknown function> + 0xd31c11 (0x55d3ef216c11 in bin/nvfuser_tests)
frame #7: <unknown function> + 0xd1e855 (0x55d3ef203855 in bin/nvfuser_tests)
frame #8: <unknown function> + 0xd1efe2 (0x55d3ef203fe2 in bin/nvfuser_tests)
frame #9: <unknown function> + 0xd1fb6b (0x55d3ef204b6b in bin/nvfuser_tests)
frame #10: <unknown function> + 0xd281c4 (0x55d3ef20d1c4 in bin/nvfuser_tests)
frame #11: <unknown function> + 0xd1f1c5 (0x55d3ef2041c5 in bin/nvfuser_tests)
frame #12: <unknown function> + 0x2a0384 (0x55d3ee785384 in bin/nvfuser_tests)
frame #13: <unknown function> + 0x29d90 (0x7f47bb1d4d90 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #14: __libc_start_main + 0x80 (0x7f47bb1d4e40 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #15: <unknown function> + 0x2a0995 (0x55d3ee785995 in bin/nvfuser_tests)
```

### PR DESCRIPTION
**Pull request by wujingyue**
1. The name group_id is overloaded. Sometimes it refers to the index in run order, sometimes SegmentedGroup::groupId(). That indeed confused [this code](https://github.com/NVIDIA/Fuser/blob/cccfa1fb578022ea6a3866c30256cad5071a03ca/csrc/kernel_cache.cpp#L1460), partially causing the bug. I cleaned up the naming so it's less likely to make such bugs. 
2. The number of output bytes processed is only [written](https://github.com/NVIDIA/Fuser/blob/cccfa1fb578022ea6a3866c30256cad5071a03ca/csrc/executor.cpp#L1945) under `execute_kernel_`, but is read ([e.g.](https://github.com/NVIDIA/Fuser/blob/cccfa1fb578022ea6a3866c30256cad5071a03ca/csrc/kernel_cache.cpp#L1225)) even when the kernel is not executed. So I hoisted `outputBytesProcessed` out of `if execute_kernel_`. 

Fixes #1943.

### CODE REVIEW

**Comment by wujingyue** [comment]
!build

**Comment by wujingyue** [comment]
!build

File: csrc/kernel_cache.cpp [hunk 1]
```diff
@@ -1453,11 +1455,11 @@ std::unordered_map<Val*, const PolymorphicValue*> FusionKernelRuntime::
     std::vector<at::Tensor> group_runtime_outputs =
         runKernelWithInput(group_runtime_inputs, group_to_run);
     args_manager.updateWithSegmentOutputs(
-        group_to_run->outputs(), group_runtime_outputs, group_id);
+        group_to_run->outputs(), group_runtime_outputs, run_order_id);
     num_live_args_after_segment_runs_.push_back((int64_t)args.size());
 
     if (compute_overall_bw) {
-      const auto& executor = executors_.at(group_id);
+      const auto& executor = executors_.at(group_to_run->groupId());
```
Comment (jacobhinkle) [inline csrc/kernel_cache.cpp:1462]: Sorry I am a little bit slow today, but why would `run_order_id` not be equal to `group-to_run->groupId()`? I thought that was how groupId was defined.

File: csrc/executor.cpp [hunk 2]
```diff
@@ -1864,11 +1864,11 @@ std::vector<at::Tensor> FusionExecutor::runFusion(
 
   executor_utils::CudaKernelTimer timer(stream);
 
-  if (measure_kernel_time) {
-    timer.init();
-  }
-
   if (execute_kernel_ && !kernel()->topLevelExprs().empty()) {
```
Comment (jacobhinkle) [inline csrc/executor.cpp:1867]: Good idea to move the timer here.

File: csrc/executor.cpp [hunk 3]
```diff
@@ -1941,17 +1941,19 @@ std::vector<at::Tensor> FusionExecutor::runFusion(
...
-        debug() << "kernel" << kernel_id_ << " run in " << kernel_time_ms_
-                << " ms, achieved: " << gb_per_s << " GB/s" << std::endl;
-      }
+    if (isDebugDumpEnabled(DebugDumpOption::EffectiveBandwidth) ||
+        isDebugDumpEnabled(DebugDumpOption::PerfDebugVerbose)) {
+      double gb_per_s =
+          ((double)bytesProcessed() / ((double)kernel_time_ms_ / 1000)) /
+          (double)1.0e9;
+      debug() << "kernel" << kernel_id_ << " run in " << kernel_time_ms_
+              << " ms, achieved: " << gb_per_s << " GB/s" << std::endl;
```
Comment (jacobhinkle) [inline csrc/executor.cpp:1956]: This change means that we print bytes processed even when we do not execute the kernel, correct?

File: csrc/kernel_cache.cpp (hunk 1 above)
Comment (wujingyue) [reply csrc/kernel_cache.cpp:1462]: groupId is set [here](https://github.com/NVIDIA/Fuser/blob/6c066c0c1f01ae984bdb6adf51f5edc4c529c023/csrc/fusion_segmenter.cpp#L4308). `groups()` is not sorted in run order.  

(I did verify this by putting a `NVF_ERROR(group_to_run->groupId() == run_order_id)` and saw many tests fail.)

File: csrc/executor.cpp (hunk 3 above)
Comment (wujingyue) [reply csrc/executor.cpp:1956]: Correct -- I do see `gb_per_s=inf` printed, which is the right answer. 

I believe this will change again with https://github.com/NVIDIA/Fuser/pull/1930. This printing will have to be skipped because `kernel_id_` won't even exist.

File: test/test_alias.cpp [hunk 4]
```diff
@@ -1146,4 +1146,28 @@ TEST_F(AliasTest, AliasOnlyKernelsAreNotLaunched) {
...
+TEST_F(AliasTest, PerfDebugVerboseWhenSomeKernelsNotLaunched) {
+  // A reproducer for #1943.
+  DebugDumpOptionsGuard options_guard;
+  DebugDumpOptionsGuard::getCurOptions().set(DebugDumpOption::PerfDebugVerbose);
+
+  auto fusion = std::make_unique<Fusion>();
+  FusionGuard fg(fusion.get());
+
+  // The segment between `add_out` and `permute_out` is meta-op only and
+  // turned into a no-op kernel.
```
Comment (jacobhinkle) [inline test/test_alias.cpp:1158]: Is it easy to test that there are two segments and that one is NoOp?

**Review by jacobhinkle — APPROVED** [review]
LGTM

**Comment by wujingyue** [comment]
!build

**Comment by wujingyue** [comment]
!build

**Comment by wujingyue** [comment]
!build
