### PR TITLE
Fix issue 4929

### LINKED ISSUE #4929: Missing sync when scatter logical domain happens to be mapped with loop domain
Follow-up issue from #4742 (https://github.com/NVIDIA/Fuser/pull/4742#discussion_r2245883319)

Repro:

```
TEST_F(ScatterTest, MappedLogicalAndLoop) {
  auto fusion_ptr = std::make_unique<Fusion>();
  Fusion& fusion = *fusion_ptr.get();
  FusionGuard fg(&fusion);

  const int64_t m = 8;

  auto tv0 = makeContigConcreteTensor({m}, DataType::Int);
  fusion.addInput(tv0);
  auto tv1 = makeContigConcreteTensor({m}, DataType::Int);
  fusion.addInput(tv1);

  auto tv2 = set(tv1);
  auto tv3 = arange(IrBuilder::create<Val>(8));
  auto tv4 = scatter(tv2, 0, tv0, tv3);
  auto tv5 = set(tv4);
  fusion.addOutput(tv5);

  // Maps the iter domains of tv0 and tv1, which in turn maps the loop
  // domain of tv4 with its logical domain
  if (getenv("MAP")) {
    auto tv6 = add(tv0, tv1);
    fusion.addOutput(tv6);
  }

  for (auto tv : fusion.allTvs()) {
    tv->axis(0)->parallelize(ParallelType::TIDx);
  }

  tv2->setMemoryType(MemoryType::Shared);
  tv2->setAllocationDomain(tv2->getLogicalDomain(), true);
  tv4->setMemoryType(MemoryType::Shared);
  tv4->setAllocationDomain(tv4->getLogicalDomain(), true);

  auto options = at::TensorOptions().dtype(at::kLong).device(at::kCUDA, 0);
  auto t0 = at::randperm(m, options);
  auto t1 = at::zeros({m}, options);

  KernelExecutor ke;
  ke.compile(&fusion, {t0, t1});
  auto outputs = ke.run({t0, t1});

  testValidate(&fusion, outputs, {t0, t1}, __LINE__, __FILE__);
}
```

If `tv0` and `tv1` are used together, it will end up mapping the logical and loop domains of `tv4`, which means no sync is inserted.

Withtout mapping:
```
__global__ void nvfuser_none_f0_c0_r0_g0(Tensor<int64_t, 1, 1> T0, Tensor<int64_t, 1, 1> T1, Tensor<int64_t, 1, 1> T5) {
  alignas(16) extern __shared__ char array[];
  const unsigned smem_offset = 0;
  int64_t* T2 = reinterpret_cast<int64_t*>(array + smem_offset + 0);
  // Alias Allocation - shared
  auto& T4 = T2;
  int64_t i0;
  i0 = 8LL - 0LL;
  int64_t i1;
  i1 = abs(i0);
  int64_t i2;
  i2 = abs(1LL);
  int64_t i3;
  i3 = ceilDiv(i1, i2);
  T2[((nvfuser_index_t)threadIdx.x)]
     = T1[((nvfuser_index_t)threadIdx.x)];
  Array<int64_t, 1, 1> T3;
  T3[0] = ((nvfuser_index_t)threadIdx.x);
  __syncthreads();
  T4[__to_index(T0[((nvfuser_index_t)threadIdx.x)])] = T3[0];
  __syncthreads();
  T5[((nvfuser_index_t)threadIdx.x)]
     = T4[((nvfuser_index_t)threadIdx.x)];
}
```

With mapping:
```
// Codegen generated code
__global__ void nvfuser_none_f0_c0_r0_g0(Tensor<int64_t, 1, 1> T0, Tensor<int64_t, 1, 1> T1, Tensor<int64_t, 1, 1> T5, Tensor<int64_t, 1, 1> T6) {
  alignas(16) extern __shared__ char array[];
  const unsigned smem_offset = 0;
  int64_t* T2 = reinterpret_cast<int64_t*>(array + smem_offset + 0);
  // Alias Allocation - shared
  auto& T4 = T2;
  int64_t i0;
  i0 = 8LL - 0LL;
  int64_t i1;
  i1 = abs(i0);
  int64_t i2;
  i2 = abs(1LL);
  int64_t i3;
  i3 = ceilDiv(i1, i2);
  T6[((nvfuser_index_t)threadIdx.x)]
    = T0[((nvfuser_index_t)threadIdx.x)]
    + T1[((nvfuser_index_t)threadIdx.x)];
  T2[((nvfuser_index_t)threadIdx.x)]
     = T1[((nvfuser_index_t)threadIdx.x)];
  Array<int64_t, 1, 1> T3;
  T3[0] = ((nvfuser_index_t)threadIdx.x);
  T4[((nvfuser_index_t)threadIdx.x)] = T3[0];
  T5[((nvfuser_index_t)threadIdx.x)]
     = T4[((nvfuser_index_t)threadIdx.x)];
}
```

Notice the lack of the syncthreads.

The indexing of `T4` is also wrong. Not sure why yet.
```
T4[((nvfuser_index_t)threadIdx.x)] = T3[0];
```

### PR DESCRIPTION
**Pull request by naoyam**
Fixes #4929. 

This is a follow-up bug fix (https://github.com/NVIDIA/Fuser/pull/4742#discussion_r2259275612). 

There are actually two bugs. One is index overriding, which caused the overriding replacement to fail:

Wrong: `T4[((nvfuser_index_t)threadIdx.x)] = T3[0];`
Correct: `T4[__to_index(T0[((nvfuser_index_t)threadIdx.x)])] = T3[0];`

Another bug is missing RAW syncs. The sync analysis needed to be extended to consider indirect indexing.

### CODE REVIEW

**Comment by naoyam** [comment]
!test --diff

File: csrc/id_model/indexing.cpp [hunk 1]
```diff
@@ -971,7 +971,7 @@ std::pair<std::vector<Val*>, std::vector<Val*>> TensorIndexer::
   auto index_info = computeIndex(
       expr, indexed_ids, for_loops, isSharedMemoryTvForLdStMatrix(tv, expr));
   for (const auto& [indexed_id, index] : override_index) {
-    index_info.index_map.emplace(traversalGraph().toGroup(indexed_id), index);
+    index_info.index_map[traversalGraph().toGroup(indexed_id)] = index;
```
Comment (naoyam) [inline csrc/id_model/indexing.cpp:974]: This is a trivial bug fix. `override_index` didn't actually override existing mappings because of the use of `emplace`.

**Comment by naoyam** [comment]
!test

File: csrc/device_lower/analysis/sync_information.cpp [hunk 2]
```diff
@@ -91,6 +91,34 @@ bool allowIncoherentDependency(
...
+// op. Specifically, if the given expr is a scatter op using the given
+// tensor as its input, returns true if the given iter domain is
+// derived from the scattered logical iter domain.
+bool isConsumedByScatter(TensorView* tv, IterDomain* id, Expr* consumer_expr) {
+  auto scatter = dynamic_cast<ScatterOp*>(consumer_expr);
+  if (scatter == nullptr || scatter->in() != tv) {
+    return false;
+  }
+
+  auto logical_scatter_dim = tv->domain()->noReductions().at(scatter->dim());
```
Comment (jjsjann123) [inline csrc/device_lower/analysis/sync_information.cpp]: I'm not following here how we are using `tv->domain()->noReductions()` along with `scatter->dim()`.
Wasn't the first one the loop domain, while that scatter->dim() gives us index to the logical domain?

File: tests/cpp/test_scatter.cpp [hunk 3]
```diff
@@ -269,4 +269,89 @@ TEST_F(ScatterTest, CacheAfter) {
...
+  auto tv2 = set(tv1);
+  auto tv3 = arange(IrBuilder::create<Val>(8));
+  auto tv4 = scatter(tv2, 0, tv0, tv3);
+  auto tv5 = set(tv4);
+  fusion.addOutput(tv5);
+
+  // At this point, tv4's loop ID is not mapped with its sole logical
+  // ID but mapped with tv0's logical ID. This means that the loop
+  // ID is not mapped with the loop ID of the input of the op,
+  // tv2. When parallelized, this differene of the loop IDs should
```
Comment (jjsjann123) [inline tests/cpp/test_scatter.cpp]:
```suggestion
  // tv2. When parallelized, this difference of the loop IDs should
```

File: csrc/device_lower/analysis/sync_information.cpp (hunk 2 above)
Comment (naoyam) [reply csrc/device_lower/analysis/sync_information.cpp]: Thanks! You're completely right. Not sure why I did this...

File: tests/cpp/test_scatter.cpp [hunk 4]
```diff
@@ -269,4 +269,89 @@ TEST_F(ScatterTest, CacheAfter) {
...
+  }
+
+  tv2->setMemoryType(MemoryType::Shared);
+  tv2->setAllocationDomain(tv2->getLogicalDomain(), true);
+  tv4->setMemoryType(MemoryType::Shared);
+  tv4->setAllocationDomain(tv4->getLogicalDomain(), true);
+
+  auto options = at::TensorOptions().dtype(at::kLong).device(at::kCUDA, 0);
+  auto t0 = at::randperm(m, options);
+  auto t1 = at::zeros({m}, options);
```
Comment (jjsjann123) [inline tests/cpp/test_scatter.cpp]: nitpick: I don't see the reason for a zero-init t1. randn should work as well.

**Comment by naoyam** [comment]
68c955b revealed a bug with `isProducedByScatter`. It should be fixed by the last commit.

**Comment by naoyam** [comment]
!test
