### PR TITLE
don't cache slice input tv

### LINKED ISSUE #1697: !detect_exception_in_thread_pool.load() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/kernel_cache.cpp":1307
### environment
- nvfuser: 0.1.5+gitd8589a4
- gpu: H100 80GB HBM3
- PyTorch: 2.3.0a0+git42062e2
- CUDA: 12.3

### error
```
Traceback (most recent call last):
  File "/opt/pytorch/nvfuser/nvfuser/__init__.py", line 137, in execute
    result = self._execute(
RuntimeError: !detect_exception_in_thread_pool.load() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/kernel_cache.cpp":1307, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Detected exception while compiling fusion segments in parallel.
Use NVFUSER_DISABLE=parallel_compile to print exception message.
Exception raised from compileFusionParallel at /opt/pytorch/nvfuser/csrc/kernel_cache.cpp:1307 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf3 (0x7f1a32f4ce09 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #1: nvfuser::nvfErrorFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x53 (0x7f1a330a18a3 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #2: nvfuser::FusionKernelRuntime::compileFusionParallel(nvfuser::KernelArgumentHolder) + 0x118f (0x7f1a332107df in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #3: nvfuser::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&, std::optional<nvfuser::PrimDataType>, std::optional<signed char>) + 0xa33 (0x7f1a3321b3c3 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #4: nvfuser::python_frontend::FusionDefinition::execute(c10::ArrayRef<c10::IValue> const&, bool, bool, std::optional<signed char>) const + 0x16c (0x7f1a33535cec in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #5: <unknown function> + 0xf151e (0x7f1a3388751e in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x177458 (0x7f1a3390d458 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
<omitting python frames>
frame #22: <unknown function> + 0x29d90 (0x7f1c5d63ad90 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #23: __libc_start_main + 0x80 (0x7f1c5d63ae40 in /usr/lib/x86_64-linux-gnu/libc.so.6)

Traceback (most recent call last):
  File "/opt/pytorch//nvfuser_failure_in_Llama-2-7b-hf.py", line 102, in <module>
    fd.execute(inputs)
  File "/opt/pytorch/nvfuser/nvfuser/__init__.py", line 137, in execute
    result = self._execute(
RuntimeError: !detect_exception_in_thread_pool.load() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/kernel_cache.cpp":1307, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Detected exception while compiling fusion segments in parallel.
Use NVFUSER_DISABLE=parallel_compile to print exception message.
Exception raised from compileFusionParallel at /opt/pytorch/nvfuser/csrc/kernel_cache.cpp:1307 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf3 (0x7f1a32f4ce09 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #1: nvfuser::nvfErrorFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x53 (0x7f1a330a18a3 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #2: nvfuser::FusionKernelRuntime::compileFusionParallel(nvfuser::KernelArgumentHolder) + 0x118f (0x7f1a332107df in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #3: nvfuser::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&, std::optional<nvfuser::PrimDataType>, std::optional<signed char>) + 0xa33 (0x7f1a3321b3c3 in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #4: nvfuser::python_frontend::FusionDefinition::execute(c10::ArrayRef<c10::IValue> const&, bool, bool, std::optional<signed char>) const + 0x16c (0x7f1a33535cec in /opt/pytorch/nvfuser/nvfuser/lib/libnvfuser_codegen.so)
frame #5: <unknown function> + 0xf151e (0x7f1a3388751e in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x177458 (0x7f1a3390d458 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
<omitting python frames>
frame #22: <unknown function> + 0x29d90 (0x7f1c5d63ad90 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #23: __libc_start_main + 0x80 (0x7f1c5d63ae40 in /usr/lib/x86_64-linux-gnu/libc.so.6)
```

### script to reproduce
```python
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id15(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[1, -1, -1], contiguity=[None, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[2, 1, 0])
    T1 = fd.define_tensor(shape=[1, -1, -1], contiguity=[None, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[2, 1, 0])
    T2 = fd.define_tensor(shape=[-1], contiguity=[True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[0])
    T3 = fd.ops.cast(T0, dtype=DataType.Float)
    T4 = fd.ops.cast(T1, dtype=DataType.Float)
    T5 = fd.ops.add(T4, T3)
    T6 = fd.ops.cast(T5, dtype=DataType.BFloat16)
    T7 = fd.ops.mul(T5, T5)
    T8 = fd.ops.sum(T7, axes=[2], keepdim=False, dtype=DataType.Null)
    S9 = fd.define_scalar(1, dtype=DataType.Int)
    S10 = fd.define_scalar(4096, dtype=DataType.Int)
    S11 = fd.define_scalar(1, dtype=DataType.Int)
    V12 = fd.define_vector([S9, S10, S11], dtype=DataType.Int)
    T13 = fd.ops.broadcast_in_dim(T8, shape=V12, broadcast_dims=[0, 1])
    S14 = fd.define_scalar(4096.00, dtype=DataType.Double)
    S15 = fd.ops.reciprocal(S14)
    T16 = fd.ops.mul(T13, S15)
    S17 = fd.define_scalar(1.00000e-05, dtype=DataType.Double)
    T18 = fd.ops.add(T16, S17)
    T19 = fd.ops.rsqrt(T18)
    T20 = fd.ops.cast(T19, dtype=DataType.BFloat16)
    S21 = fd.define_scalar(1, dtype=DataType.Int)
    S22 = fd.define_scalar(4096, dtype=DataType.Int)
    S23 = fd.define_scalar(4096, dtype=DataType.Int)
    V24 = fd.define_vector([S21, S22, S23], dtype=DataType.Int)
    T25 = fd.ops.broadcast_in_dim(T20, shape=V24, broadcast_dims=[0, 1, 2])
    T26 = fd.ops.cast(T25, dtype=DataType.Float)
    T27 = fd.ops.mul(T5, T26)
    S28 = fd.define_scalar(8, dtype=DataType.Int)
    S29 = fd.define_scalar(25297920, dtype=DataType.Int)
    V30 = fd.define_vector([S28, S29], dtype=DataType.Int)
    T31 = fd.ops.reshape(T2, new_shape=V30)
    T32 = fd.ops.slice(T31, start_indices=[0, 0], end_indices=[8, 512], strides=[1, 1])
    S33 = fd.define_scalar(4096, dtype=DataType.Int)
    V34 = fd.define_vector([S33], dtype=DataType.Int)
    T35 = fd.ops.reshape(T32, new_shape=V34)
    T36 = fd.ops.slice(T31, start_indices=[0, 512], end_indices=[8, 6291968], strides=[1, 1])
    S37 = fd.define_scalar(12288, dtype=DataType.Int)
    S38 = fd.define_scalar(4096, dtype=DataType.Int)
    V39 = fd.define_vector([S37, S38], dtype=DataType.Int)
    T40 = fd.ops.reshape(T36, new_shape=V39)
    T41 = fd.ops.slice(T31, start_indices=[0, 6291968], end_indices=[8, 8389120], strides=[1, 1])
    S42 = fd.define_scalar(4096, dtype=DataType.Int)
    S43 = fd.define_scalar(4096, dtype=DataType.Int)
    V44 = fd.define_vector([S42, S43], dtype=DataType.Int)
    T45 = fd.ops.reshape(T41, new_shape=V44)
    T46 = fd.ops.slice(T31, start_indices=[0, 8389120], end_indices=[8, 8389632], strides=[1, 1])
    S47 = fd.define_scalar(4096, dtype=DataType.Int)
    V48 = fd.define_vector([S47], dtype=DataType.Int)
    T49 = fd.ops.reshape(T46, new_shape=V48)
    T50 = fd.ops.slice(T31, start_indices=[0, 8389632], end_indices=[8, 14025728], strides=[1, 1])
    S51 = fd.define_scalar(11008, dtype=DataType.Int)
    S52 = fd.define_scalar(4096, dtype=DataType.Int)
    V53 = fd.define_vector([S51, S52], dtype=DataType.Int)
    T54 = fd.ops.reshape(T50, new_shape=V53)
    T55 = fd.ops.slice(T31, start_indices=[0, 14025728], end_indices=[8, 19661824], strides=[1, 1])
    S56 = fd.define_scalar(11008, dtype=DataType.Int)
    S57 = fd.define_scalar(4096, dtype=DataType.Int)
    V58 = fd.define_vector([S56, S57], dtype=DataType.Int)
    T59 = fd.ops.reshape(T55, new_shape=V58)
    T60 = fd.ops.slice(T31, start_indices=[0, 19661824], end_indices=[8, 25297920], strides=[1, 1])
    S61 = fd.define_scalar(4096, dtype=DataType.Int)
    S62 = fd.define_scalar(11008, dtype=DataType.Int)
    V63 = fd.define_vector([S61, S62], dtype=DataType.Int)
    T64 = fd.ops.reshape(T60, new_shape=V63)
    S65 = fd.define_scalar(1, dtype=DataType.Int)
    S66 = fd.define_scalar(4096, dtype=DataType.Int)
    S67 = fd.define_scalar(4096, dtype=DataType.Int)
    V68 = fd.define_vector([S65, S66, S67], dtype=DataType.Int)
    T69 = fd.ops.broadcast_in_dim(T35, shape=V68, broadcast_dims=[2])
    T70 = fd.ops.cast(T69, dtype=DataType.Float)
    T71 = fd.ops.mul(T70, T27)
    T72 = fd.ops.cast(T71, dtype=DataType.BFloat16)
    S73 = fd.define_scalar(1, dtype=DataType.Int)
    S74 = fd.define_scalar(4096, dtype=DataType.Int)
    S75 = fd.define_scalar(4096, dtype=DataType.Int)
    V76 = fd.define_vector([S73, S74, S75], dtype=DataType.Int)
    T77 = fd.ops.broadcast_in_dim(T49, shape=V76, broadcast_dims=[2])
    T78 = fd.ops.cast(T77, dtype=DataType.Float)
    fd.add_output(T78)
    fd.add_output(T6)
    fd.add_output(T19)
    fd.add_output(T40)
    fd.add_output(T45)
    fd.add_output(T54)
    fd.add_output(T59)
    fd.add_output(T64)
    fd.add_output(T72)

with FusionDefinition() as fd:
    nvfuser_fusion_id15(fd)

inputs = [
    torch.randn((16777216,), dtype=torch.bfloat16, device='cuda:0').as_strided((1, 4096, 4096), (16777216, 4096, 1)),
    torch.randn((16777216,), dtype=torch.bfloat16, device='cuda:0').as_strided((1, 4096, 4096), (16777216, 4096, 1)),
    torch.randn((202383360,), dtype=torch.bfloat16, device='cuda:0').as_strided((202383360,), (1,)),
]
fd.execute(inputs)
```

### PR DESCRIPTION
**Pull request by liqiangxl**
Fix #1697

### CODE REVIEW

File: test/test_gpu3.cpp [hunk 1]
```diff
@@ -8716,6 +8716,91 @@ TEST_F(NVFuserTest, Reduction3DConstantIterationDomain) {
...
+  auto tv11 = castOp(DataType::Float, tv10);
+  fusion->addOutput(tv11);
+
+  // slice-2  reshape to hidden size and link with inner persistent
+  auto tv12 = slice(tv7, {0, fiveTwelve * 3}, {eight, fiveTwelve * 4});
+  auto tv13 = reshape(
+      tv12,
+      {castOp(
+          DataType::Index,
+          IrBuilder::create<Val>(hidden_size, DataType::Int))});
```
Comment (jacobhinkle) [inline test/test_gpu3.cpp:8771]:
```suggestion
      {IrBuilder::create<Val>(hidden_size, DataType::Index)});
```

File: csrc/scheduler/utils.cpp [hunk 2]
```diff
@@ -1123,7 +1123,8 @@ std::vector<TensorView*> cacheInputs(Fusion* fusion, bool unroll) {
   auto in_tvs = ir_utils::filterByType<TensorView>(fusion->inputs());
   for (auto tv : in_tvs) {
     if (tv->uses().empty() || ir_utils::isTorchGatherLookupTv(tv) ||
-        ir_utils::isSelectInput(tv) || ir_utils::isIndexSelectLookupTv(tv)) {
+        ir_utils::isSelectInput(tv) || ir_utils::isIndexSelectLookupTv(tv) ||
+        ir_utils::isSliceInput(tv)) {
```
Comment (jacobhinkle) [inline csrc/scheduler/utils.cpp:1127]: Maybe we could make this a templated utility function like `ir_utils::isOpInput<Slice, PadOp, ...>(tv)`?

File: csrc/ir/utils.cpp [hunk 3]
```diff
@@ -752,6 +752,15 @@ bool isSelectInput(TensorView* tv) {
   return false;
 }
 
+bool isSliceInput(TensorView* tv) {
+  for (auto expr : tv->uses()) {
+    if (expr->isA<SliceOp>()) {
```
[the remark this answers is not in the document]
Comment (naoyam) [reply csrc/ir/utils.cpp:757]: I don't think padding inputs would have the same issue (unless doing something crazy like padding with negative widths). I think the problem here happens because in the original fusion a reduction tensor was picked as the reference, so its shape determined the thread block size, but that resulted in an invalid block size for the input. Avoiding caching the input would prevent the error from happening, but the underlying issue is what I initially did for these schedulers to (appear to) work with resize ops. 

Specifically, the assumption we have here is that all the other tensors are either the same shape as the reference or lack some domains due to broadcasting. This is not the case with IterDomain resizing, but initially I just patched the schedulers to ignore the extent differences so that everything just work. In this case, the number of threads was determined based on the post-slice tensor, but that resulted in too large for the pre-resize tensor. 

Padding an input believe should be fine as the input should be smaller than the padding output (unless it's negative padding).

More generally, this problem would happen when a reference tensor is smaller than tensors before slicing or after padding and boils down to the question of what the effective scheduling should look like for fusions with different shapes.

File: csrc/ir/utils.cpp [hunk 4]
```diff
@@ -752,6 +752,15 @@ bool isSelectInput(TensorView* tv) {
   return false;
 }
 
+bool isSliceInput(TensorView* tv) {
```
Comment (naoyam) [inline csrc/ir/utils.cpp:755]: Let's not add a trivial function like this.

File: csrc/ir/utils.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (naoyam) [reply csrc/ir/utils.cpp:757]: Since slice inputs must be a segment input, disabling caching should work around the problem, so I think this fix is a reasonable WAR for now. Thanks @liqiangxl.

File: csrc/scheduler/utils.cpp (hunk 2 above)
Comment (liqiangxl) [reply csrc/scheduler/utils.cpp]: (1) `isSelectInput` and `isSliceInput` can be merged into a variadic template function.
(2) `IndexSelectOp` and `TorchGatherOp`, they have two inputs: `lookupTv` and `indexTv`, but here we only check the `lookupTv`, if we merge them into the template then we need to add special code for these ops and someone may use it in a wrong way e.g. when checking for the `indexTv`.
so we keep `isIndexSelectLookupTv` and `isIndexSelectLookupTv`? or merge them into another variadic template function?

File: csrc/ir/utils.cpp (hunk 4 above)
Comment (liqiangxl) [reply csrc/ir/utils.cpp]: merged with `isSelectInput` into a variadic template function.

File: test/test_gpu3.cpp (hunk 1 above)
Comment (liqiangxl) [reply test/test_gpu3.cpp:8769]: They are not important. Let me remove all of them.

File: csrc/ir/utils.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (liqiangxl) [reply csrc/ir/utils.cpp]: Thanks for the background info.
Here what I observed is: the launch parameter is based on the maximum dim. 
For example, TIDx is used to parallel
`ithreadIdx.x190{( ceilDiv(( ceilDiv(( ceilDiv(( i246 * i247 ), 4) ), 8) ), 1) )}_p` in the slice tv
 and
`rthreadIdx.x106{( ceilDiv(( ceilDiv(( ceilDiv(4096, 4) ), 8) ), 1) )}_p ` in the reduction tv. 
The value of bdimx = max(4096/4/8, ( i246 * i247 )/4/8).
When `( i246 * i247 )/4/8` is less than 1024, the kernel runs without error, just not efficient. This is why I need to set ` i246 * i247` to a large value to trigger the original error.

**Comment by liqiangxl** [comment]
!build

File: csrc/ir/utils.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (jacobhinkle) [reply csrc/ir/utils.cpp]: > something crazy like padding with negative widths

That's what I had in mind since one can effectively do a slice this way, but you're right it's probably rare and could possibly separated/translated in integration, so I agree it's probably fine to ignore `PadOp` here.

**Comment by liqiangxl** [comment]
Failed internal tests are due to `RuntimeError: The number of fusions in nvfuser has exceeded 8192fusions`, not related to this work.

File: csrc/ir/utils.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (liqiangxl) [reply csrc/ir/utils.cpp]: `PadOp` is added to the skip list.

**Comment by liqiangxl** [comment]
!build

File: csrc/scheduler/utils.cpp [hunk 5]
```diff
@@ -1123,7 +1123,8 @@ std::vector<TensorView*> cacheInputs(Fusion* fusion, bool unroll) {
   auto in_tvs = ir_utils::filterByType<TensorView>(fusion->inputs());
   for (auto tv : in_tvs) {
     if (tv->uses().empty() || ir_utils::isTorchGatherLookupTv(tv) ||
-        ir_utils::isSelectInput(tv) || ir_utils::isIndexSelectLookupTv(tv)) {
+        ir_utils::isIndexSelectLookupTv(tv) ||
+        ir_utils::isTvUsedByOpsOfType<SliceOp, SelectOp, PadOp>(tv)) {
       // Right now, tensors that are input to the select op can't be cached as
```
Comment (jacobhinkle) [inline csrc/scheduler/utils.cpp:1128]: Could you update this comment to indicate the problem with slice and pad?

**Review by jacobhinkle — APPROVED** [review]
LGTM. Just one suggestion.

File: csrc/scheduler/utils.cpp (hunk 5 above)
Comment (liqiangxl) [reply csrc/scheduler/utils.cpp]: added

**Comment by liqiangxl** [comment]
!build

**Comment by liqiangxl** [comment]
!build

**Comment by liqiangxl** [comment]
The failed case is a known issue.
