### PR TITLE
IdModel: Fix invalid promotion selection

### LINKED ISSUE #3702: `hf_llama` model error
This impacts taking more ops in the forward pass to reduce CPU overhead.

Error:
```bash
Error from segmentation group 14:  INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/bfs.h":241, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. BFS traversal could no
t visit some nodes:  idg{108 503 510} (from:  idg{600 602 607 609 614 616 621 623 628 630 641 643 647 649 653 655 659 661 677 679 683 685 689 691 695 697 701 703 707 709 713 715 719 721 725 727 731 733 753 755 757
759} idg{603 610 617 624 631 644 650 656 662 680 686 692 698 704 710 716 722 728 734 758} idg{601 608 615 622 629 642 648 654 660 678 684 690 696 702 708 714 720 726 732 754 756 760}), visited: ( idg{665 667 671 67
3 737 739 743 745 749 751} idg{389 393} idg{668 674 740 746 752} idg{663 664 669 670 735 736 741 742 747 748} idg{1 14 390 394 398 506 535 536} idg{666 672 738 744 750} idg{2 15 28 31 34 37 40 43 106 112 137 145 15
7 161 165 169 213 221 241 297 305 388 392 396 502 507 509 513 517 521 525 529 533} idg{603 610 617 624 631 644 650 656 662 680 686 692 698 704 710 716 722 728 734 758} idg{601 608 615 622 629 642 648 654 660 678 68
4 690 696 702 708 714 720 726 732 754 756 760} idg{397} idg{541 548 555 562 569 576 583 590 597 598 599 604 605 606 611 612 613 618 619 620 625 626 627 632 639 640 645 646 651 652 657 658 675 676 681 682 687 688 69
3 694 699 700 705 706 711 712 717 718 723 724 729 730} idg{600 602 607 609 614 616 621 623 628 630 641 643 647 649 653 655 659 661 677 679 683 685 689 691 695 697 701 703 707 709 713 715 719 721 725 727 731 733 753
 755 757 759} idg{29 32 35 38 41 44 110 114 138 146 158 162 166 170 214 222 242 298 306 399 514 518 522 526 530 534 538 540} idg{0 13 27 30 33 36 39 42 105 111 135 136 143 155 156 159 163 164 167 211 219 239 240 29
5 303 387 391 395 501 505 508 511 515 516 519 523 527 531})
```

Repro:

```python
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id3(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[1, 32, 6], contiguity=[None, True, True], dtype=DataType.Float, is_cpu=False, stride_order=[2, 1, 0])
    T1 = fd.define_tensor(shape=[1, 6, 2048], contiguity=[None, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[2, 1, 0])
    T2 = fd.define_tensor(shape=[2048], contiguity=[True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[0])
    T3 = fd.define_tensor(shape=[2048, 2048], contiguity=[True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[1, 0])
    T4 = fd.define_tensor(shape=[512, 2048], contiguity=[True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[1, 0])
    T5 = fd.define_tensor(shape=[512, 2048], contiguity=[True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[1, 0])
    T6 = fd.ops.permute(T0, dims=[0, 2, 1])
    T7 = fd.ops.cat([T6, T6], dim=-1, manual_padding=0)
    T8 = fd.ops.cos(T7)
    T9 = fd.ops.sin(T7)
    S10 = fd.define_scalar(1.00000, dtype=DataType.Double)
    T11 = fd.ops.mul(T8, S10)
    S12 = fd.define_scalar(1.00000, dtype=DataType.Double)
    T13 = fd.ops.mul(T9, S12)
    T14 = fd.ops.cast(T11, dtype=DataType.BFloat16)
    T15 = fd.ops.cast(T13, dtype=DataType.BFloat16)
    T16 = fd.ops.cast(T1, dtype=DataType.Float)
    S17 = fd.define_scalar(2.00000, dtype=DataType.Double)
    T18 = fd.ops.pow(T16, S17)
    T19 = fd.ops.sum(T18, dims=[2], keepdim=False, dtype=DataType.Null)
    T24 = fd.ops.broadcast_in_dim(T19, shape=[1, 6, 1], broadcast_dims=[0, 1])
    S25 = fd.define_scalar(2048.00, dtype=DataType.Double)
    S26 = fd.ops.reciprocal(S25)
    T27 = fd.ops.mul(T24, S26)
    S28 = fd.define_scalar(1.00000e-05, dtype=DataType.Double)
    T29 = fd.ops.add(T27, S28)
    T30 = fd.ops.rsqrt(T29)
    T35 = fd.ops.broadcast_in_dim(T30, shape=[1, 6, 2048], broadcast_dims=[0, 1, 2])
    T36 = fd.ops.mul(T16, T35)
    T41 = fd.ops.broadcast_in_dim(T2, shape=[1, 6, 2048], broadcast_dims=[2])
    T42 = fd.ops.cast(T41, dtype=DataType.Float)
    T43 = fd.ops.mul(T42, T36)
    T44 = fd.ops.cast(T43, dtype=DataType.BFloat16)
    T45 = fd.ops.linear(T44, T3)
    T46 = fd.ops.linear(T44, T4)
    T47 = fd.ops.linear(T44, T5)
    T53 = fd.ops.reshape(T45, new_shape=[1, 6, 32, 64])
    T54 = fd.ops.permute(T53, dims=[0, 2, 1, 3])
    T60 = fd.ops.reshape(T46, new_shape=[1, 6, 8, 64])
    T61 = fd.ops.permute(T60, dims=[0, 2, 1, 3])
    T67 = fd.ops.reshape(T47, new_shape=[1, 6, 8, 64])
    T68 = fd.ops.permute(T67, dims=[0, 2, 1, 3])
    T74 = fd.ops.broadcast_in_dim(T14, shape=[1, 1, 6, 64], broadcast_dims=[0, 2, 3])
    T80 = fd.ops.broadcast_in_dim(T15, shape=[1, 1, 6, 64], broadcast_dims=[0, 2, 3])
    T86 = fd.ops.broadcast_in_dim(T74, shape=[1, 32, 6, 64], broadcast_dims=[0, 1, 2, 3])
    T87 = fd.ops.cast(T54, dtype=DataType.Float)
    T88 = fd.ops.cast(T86, dtype=DataType.Float)
    T89 = fd.ops.mul(T87, T88)
    T105 = fd.ops.slice(T54, start_indices=[0, 0, 0, 0], end_indices=[1, 32, 6, 32], strides=[1, 1, 1, 1], manual_normalization=0)
    T121 = fd.ops.slice(T54, start_indices=[0, 0, 0, 32], end_indices=[1, 32, 6, 64], strides=[1, 1, 1, 1], manual_normalization=0)
    T122 = fd.ops.cast(T121, dtype=DataType.Float)
    T123 = fd.ops.neg(T122)
    T124 = fd.ops.cast(T123, dtype=DataType.BFloat16)
    T125 = fd.ops.cat([T124, T105], dim=-1, manual_padding=0)
    T131 = fd.ops.broadcast_in_dim(T80, shape=[1, 32, 6, 64], broadcast_dims=[0, 1, 2, 3])
    T132 = fd.ops.cast(T125, dtype=DataType.Float)
    T133 = fd.ops.cast(T131, dtype=DataType.Float)
    T134 = fd.ops.mul(T132, T133)
    T135 = fd.ops.add(T89, T134)
    T136 = fd.ops.cast(T135, dtype=DataType.BFloat16)
    T142 = fd.ops.broadcast_in_dim(T74, shape=[1, 8, 6, 64], broadcast_dims=[0, 1, 2, 3])
    T143 = fd.ops.cast(T61, dtype=DataType.Float)
    T144 = fd.ops.cast(T142, dtype=DataType.Float)
    T145 = fd.ops.mul(T143, T144)
    T161 = fd.ops.slice(T61, start_indices=[0, 0, 0, 0], end_indices=[1, 8, 6, 32], strides=[1, 1, 1, 1], manual_normalization=0)
    T177 = fd.ops.slice(T61, start_indices=[0, 0, 0, 32], end_indices=[1, 8, 6, 64], strides=[1, 1, 1, 1], manual_normalization=0)
    T178 = fd.ops.cast(T177, dtype=DataType.Float)
    T179 = fd.ops.neg(T178)
    T180 = fd.ops.cast(T179, dtype=DataType.BFloat16)
    T181 = fd.ops.cat([T180, T161], dim=-1, manual_padding=0)
    T187 = fd.ops.broadcast_in_dim(T80, shape=[1, 8, 6, 64], broadcast_dims=[0, 1, 2, 3])
    T188 = fd.ops.cast(T181, dtype=DataType.Float)
    T189 = fd.ops.cast(T187, dtype=DataType.Float)
    T190 = fd.ops.mul(T188, T189)
    T191 = fd.ops.add(T145, T190)
    T192 = fd.ops.cast(T191, dtype=DataType.BFloat16)
    T199 = fd.ops.broadcast_in_dim(T192, shape=[1, 8, 1, 6, 64], broadcast_dims=[0, 1, 3, 4])
    T206 = fd.ops.broadcast_in_dim(T199, shape=[1, 8, 4, 6, 64], broadcast_dims=[0, 1, 2, 3, 4])
    T212 = fd.ops.reshape(T206, new_shape=[1, 32, 6, 64])
    T219 = fd.ops.broadcast_in_dim(T68, shape=[1, 8, 1, 6, 64], broadcast_dims=[0, 1, 3, 4])
    T226 = fd.ops.broadcast_in_dim(T219, shape=[1, 8, 4, 6, 64], broadcast_dims=[0, 1, 2, 3, 4])
    T232 = fd.ops.reshape(T226, new_shape=[1, 32, 6, 64])
    T233 = fd.ops.stride_order(T136, stride_order=[3, 2, 1, 0])
    T234 = fd.ops.stride_order(T212, stride_order=[3, 2, 1, 0])
    T235 = fd.ops.stride_order(T232, stride_order=[3, 2, 1, 0])
    fd.add_output(T68)
    fd.add_output(T192)
    fd.add_output(T233)
    fd.add_output(T234)
    fd.add_output(T235)

with FusionDefinition() as fd:
    nvfuser_fusion_id3(fd)

inputs = [
    torch.testing.make_tensor((1, 32, 6), dtype=torch.float32, device='cuda:0'),
    torch.testing.make_tensor((1, 6, 2048), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((2048,), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((2048, 2048), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((512, 2048), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((512, 2048), dtype=torch.bfloat16, device='cuda:0'),
]
fd.execute(inputs)
```

### PR DESCRIPTION
**Pull request by naoyam**
Fixes #3702 

`computeCoveredGroups` is used in the loop promotion analysis to find a promotion ID that has dependencies to all input exact groups. Specifically, it traverses the exact graph in a topological order and it assigns for each exact group a set of dependent input exact groups. This information is used to find promotion IDs since a promotion ID of a loop group needs to have all dependent input groups for all IDs of the given loop group.

Here's a simple example. Suppose there are two 2D input tensors, `t0` and `t1`, and they are added together as follows:

```
t0: [i0, b1]
t1: [i2, i3]

t2 = t0 + t1
// t2: [i4, i5]

flatten_all_tensors();
inlineMost();
```

The resulting tensors and IDs look like below:

Scratch-37

Specifically, `i6, i7 and i8` form a loop group with `i8` (or `i7`) being its promotion ID. The dependent input exact groups of `i8` are `{i0, i2, i4}` and `{i3, i5}`. Note that broadcast IDs are ignored. Notice that the set covers all of the dependent groups of the member IDs of the loop group. That's true obviously for `i7` as it's exact mapped with `i8`. It's also true for `i6`, which only has `{i0, i2, i4}` as its dependent group (the dependency to `b1` is ignored as its a broadcast ID).

This `computeCoveredGroups` just works fine in common transformation patters, where we tend to first do all merges and then splits. However, it has a problem when there's some split followed by a merge. Consider a fusion with 2 input tensors, `t0` and `t1` as shown below:

```
t0: [i0, b1]
t1: [i2]

t2 = reshape(t1, {i4, i5});
t3 = t0 + t2
// t3: [i6, i7]

flatten_all_tensors();
inlineMost();
```
Scratch-36

Similar to the previous case, the final merged IDs form a loop group of `{i8, i9, i10}`. In this case, it should be promoted to `i9` or `i10` (they are exact mapped and it doesn't matter which one is picked). However, `computeCoveredGroups` assigns the exact group of `{i2, i3}` not just to the exact group of `{i9, i10}` but also to the exact groups of `{i0, i4, i6}`, `{i5, i7}` and as well as `{i8}` since all of them have dependencies to `{i2, i3}`. This is problematic since then `findPromotionfOfLoopGroup` [may incorrectly choose](https://github.com/NVIDIA/Fuser/blob/main/csrc/id_model/loop_promotion.cpp#L926-L934), e.g., `i8` as the promotion of the loop group.

The root cause of the issue lies in `[computeCoveredGroups](https://github.com/NVIDIA/Fuser/blob/main/csrc/id_model/loop_promotion.cpp#L779-L822)`. It just propagates input exact groups down to consumer exact groups through exact expr groups, no matter what actual expr a group represents. Specifically, when it's a split, the input groups covered by the split input ID are just propagated to the split output groups, but the output groups do not actually cover the entire input groups but they should be considered to cover only the split portion of the input groups. In the above example case, `{i0, i4, i6}` and `{i5, i7}` should cover only the outer and inner split of `{i2, i3}`, respectively. Therefore, `{i8}` only inherits the outer split of `{i0, i4, i6}`, whereas `{i9, i10}` gets both the outer and inner split groups, which allows `findPromotionOfLoopGroup` to correctly identify `{i9, i10}` as the promotion of the loop group.

Previously, the coverage information is just a map from each exact `ValGroup` to a `ValGroups` of dependent input groups. Since that is not enough to represent the coverage information as precisely as discussed above, this PR introduces an additional data structure, `CoveredGroup`, which represents a covered exact group of an exact group. Since each exact group may cover multiple groups, `std::unordered_set<CoveredGroup>` is used to represent all covered groups for an exact group.

`CoveredGroup` optionally encodes the split of a covered group, like the above `{i0, i4, i6}` case. The `CoveredGroup` of `{i0, i4, i6}` would have `{i0, i4, i6}` as `group_` and also the covered groups of its split input group, `{i2, i3}`, as `split_in` with `is_inner_` being false. Similarly, `{i5, i7}` would have `{i5, i7}` as its `group_` and `{i2, i3}` as its `split_in_` but `is_inner_` being true. Therefore, `{i8}` would just get the same coverage info propagated from `{i0, i4, i6}`, whereas `{i9, i10}` would get that as well as the one from `{i5, i7}`, effectively gathering both the outer and inner output groups of the split. This way, we avoid losing information of covered input groups when propagating the information through split exprs.

### CODE REVIEW

**Comment by naoyam** [comment]
!test

File: tests/cpp/test_tutorial.cpp [hunk 1]
```diff
@@ -654,7 +654,7 @@ TEST_F(Tutorial, IdModelReshapeAnalysis) {
   fusion.addOutput(tv3);
 
   IdModel id_model(&fusion);
-  ValGraph& exact_graph = id_model.idGraph(IdMappingMode::EXACT);
+  ValGraph& exact_graph = id_model.buildExactGraph();
```
Comment (naoyam) [inline tests/cpp/test_tutorial.cpp:657]: Unrelated fix

**Comment by naoyam** [comment]
!test

**Comment by naoyam** [comment]
!test

**Comment by naoyam** [comment]
CI systems seem unstable now. Confirmed `manual_ci.sh` pass on an H100 system.

File: csrc/id_model/loop_promotion.h [hunk 2]
```diff
@@ -14,6 +14,78 @@ namespace nvfuser {
...
+
+using CoveredGroups = std::unordered_set<CoveredGroup>;
+
+std::string toString(const CoveredGroups& covered_groups);
+
+// Represents an input (or split output) ID group that an exact group
+// depends on (i.e., covers). If an input ID group is split, split_in_
+// refers to the covered groups of the input ID group, and group_
+// refers to either inner or outer output group.
+struct CoveredGroup {
```
Comment (zasdfgbnm) [inline csrc/id_model/loop_promotion.h:27]: Does `CoveredGroup` defines a language to say things like: the inner of the outer of the inner of x, y and z?

File: csrc/id_model/loop_promotion.cpp [hunk 3]
```diff
@@ -16,6 +16,184 @@
...
+            other_split_in.end(),
+            [&](const CoveredGroup& other_split_in_group) {
+              return std::any_of(
+                  split_in.begin(),
+                  split_in.end(),
+                  [&](const CoveredGroup& split_in_group) {
+                    return split_in_group.isEqualToOrSuperSetOf(
+                        other_split_in_group);
+                  });
+            })) {
```
Comment (zasdfgbnm) [inline csrc/id_model/loop_promotion.cpp:88]: Can this  be simplified as the following?

```C++
if (isEqualToOrSuperSetOf(*split_in, *other_split_in)) {
```

Comment (naoyam) [reply csrc/id_model/loop_promotion.cpp:88]: Yes, thanks for pointing it out. Will update.

Comment (naoyam) [reply csrc/id_model/loop_promotion.cpp]: Updated

**Comment by naoyam** [comment]
!test --diff
