### PR TITLE
fixing a typo in macro usage

### LINKED ISSUE #4340: Should this `NVFUSER_EXPLICIT_CHECK` be renamed `NVFUSER_EXPLICIT_ERROR_CHECK` for consistency?
NVFUSER_EXPLICIT_CHECK:
https://github.com/NVIDIA/Fuser/blob/85726a85186922354d3f3438a9f44d8382dc6a40/csrc/disjoint_set.h#L156

NVFUSER_EXPLICIT_ERROR_CHECK:
https://github.com/NVIDIA/Fuser/blob/85726a85186922354d3f3438a9f44d8382dc6a40/csrc/utils.h#L121

and cmake
https://github.com/NVIDIA/Fuser/blob/85726a85186922354d3f3438a9f44d8382dc6a40/CMakeLists.txt#L17-L21

re: #3371

### PR DESCRIPTION
**Pull request by jjsjann123**
Fixes #4340

### CODE REVIEW

**Comment by jjsjann123** [comment]
!build

File: csrc/disjoint_set.h [hunk 1]
```diff
@@ -153,25 +153,25 @@ class VectorOfUniqueEntries {
 
   // Returns first element in vector
   T front() const {
-#if defined(NDEBUG) && !defined(NVFUSER_EXPLICIT_CHECK)
+#if defined(NDEBUG) && !defined(NVFUSER_EXPLICIT_ERROR_CHECK)
```
Comment (naoyam) [inline csrc/disjoint_set.h:156]: This still seems off to me. I think we want to do this assertion when debugging or the explicit check is required. So, shouldn't this be `not defined(NDEBUG) || defined(NVFUSER_EXPLICIT_ERROR_CHECK)`?

Comment (jjsjann123) [reply csrc/disjoint_set.h:156]: good catch. You are totally right.
I think this was copied from the static_dynamic check earlier and I didn't notice it's originally calling `#ifndef` :face_holding_back_tears: 

https://github.com/NVIDIA/Fuser/commit/5a603dbf2ec01d503f41f93d1b9690eec70ee190

Comment (naoyam) [reply csrc/disjoint_set.h]: Thanks for the fix. I really don't like `not defined(NDEBUG)` as the double negative is just confusing.

**Review by naoyam — APPROVED** [review]
LGTM

**Review by xwang233 — APPROVED** [review]
