### PR TITLE
Avoid DCE in fuseWarpReduce when no rewrites happened

### LINKED ISSUE #151: Compilation error using `torch_gather` with broadcasted index dimension
This may be the same underlying issue as #93 but it manifests in a different way. The following example results in an error when compiling kernel:
```c++
// Test unsqueezing the an index vector before gathering, as is done for
// cross_entropy_loss.
TEST_F(NVFuserTest, FusionTorchGatherUnsqueezed_CUDA) {
  int64_t N = 16384;
  int64_t num_classes = 60;
  std::vector<int64_t> input_dims{N, num_classes};
  std::vector<int64_t> index_dims{N};

  at::manual_seed(0);

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  auto options_i = at::TensorOptions().dtype(at::kLong).device(at::kCUDA, 0);

  auto fusion_ptr = std::make_unique<Fusion>();
  Fusion& fusion = *fusion_ptr.get();
  FusionGuard fg(&fusion);

  TensorView* tv_in1 = makeConcreteTensor(input_dims);
  TensorView* tv_idx = makeConcreteTensor(index_dims, DataType::Int);
  fusion.addInput(tv_in1);
  fusion.addInput(tv_idx);

  auto tv_idx_unsqueeze = broadcast(tv_idx, {false, true});
  auto tv_gather = torch_gather(tv_in1, 1, tv_idx_unsqueeze);
  auto tv_gather_squeeze = reshape(tv_gather, {N, 1}, {N});

  fusion.addOutput(tv_gather_squeeze);

  at::Tensor input_1 = at::randn(input_dims, options);
  at::Tensor input_2 = at::randn(index_dims, options);
  at::Tensor input_idx =
      at::randint(0, num_classes, index_dims, options_i);

  auto t_gather = at::gather(input_1, 1, input_idx.unsqueeze(1)).squeeze();

  std::vector<c10::IValue> aten_inputs = {input_1, input_idx};

  FusionExecutorCache executor_cache(std::move(fusion_ptr));
  auto cg_outputs = executor_cache.runFusionWithInputs(aten_inputs);
  testValidate(
      &fusion, cg_outputs, aten_inputs, {t_gather}, __LINE__, __FILE__);
}
```
The generated kernel is
```c++
__global__ void kernel1(Tensor<float, 2> T0, Tensor<int64_t, 1> T1, Tensor<float, 1> T4) {                                               
  NVFUSER_DEFINE_MAGIC_ZERO                                                                                                              
  int i318;                                                                                                                              
  i318 = ((T1.stride[0] * 2) * ((nvfuser_index_t)threadIdx.x)) + ((T1.stride[0] * 256) * ((nvfuser_index_t)blockIdx.x));                 
  int i614;                                                                                                                              
  i614 = ((T0.stride[0] * 2) * ((nvfuser_index_t)threadIdx.x)) + ((T0.stride[0] * 256) * ((nvfuser_index_t)blockIdx.x));                 
  int i802;                                                                                                                              
  i802 = 2 * ((nvfuser_index_t)threadIdx.x);                                                                                             
  int i803;                                                                                                                              
  i803 = 256 * ((nvfuser_index_t)blockIdx.x);                                                                                            
  int i804;                                                                                                                              
  i804 = i802 + i803;                                                                                                                    
  bool b1981;                                                                                                                            
  b1981 = ((1 + i802) + i803) < 16384;                                                                                                   
  if ((((i802 + 1) + i803) < 16384)) {                                                                                                   
    int64_t T5[2];                                                                                                                       
    #pragma unroll                                                                                                                           for(nvfuser_index_t i111 = 0; i111 < 2; ++i111) {                                                                                    
      T5[i111] = 0;                                                                                                                      
    }                                                                                                                                        NVFUSER_UPDATE_MAGIC_ZERO                                                                                                                #pragma unroll                                                                                                                           for(nvfuser_index_t i111 = 0; i111 < 2; ++i111) {                                                                                    
      T5[i111]                                                                                                                                    = T1[(i318 + (T1.stride[0] * (i111 + nvfuser_zero)))];                                                                          
    }                                                                                                                                        NVFUSER_UPDATE_MAGIC_ZERO                                                                                                            
    Array<float, 2, 2> T6;                                                                                                                   #pragma unroll                                                                                                                       
    for(nvfuser_index_t i112 = 0; i112 < 2; ++i112) {                                                                                          float T3[1];                                                                                                                       
      T3[0] = 0;                                                                                                                               T3[0]                                                                                                                              
         = T0[((i614 + (T0.stride[0] * (i112 + nvfuser_zero))) + (T0.stride[1] * T2[0]))];                                                     T6[i112]                                                                                                                           
         = T3[0];                                                                                                                        
    }                                                                                                                                    
    NVFUSER_UPDATE_MAGIC_ZERO                                                                                                            
    loadLocalToGlobal<float, 2, false>( &T4[i804], &T6[0]);                                                                              
  } else {                                                                                                                               
    int64_t T5[2];                                                                                                                       
    #pragma unroll                                                                                                                       
    for(nvfuser_index_t i111 = 0; i111 < 2; ++i111) {                                                                                    
      T5[i111] = 0;                                                                                                                      
    }
    }
    NVFUSER_UPDATE_MAGIC_ZERO
    Array<float, 2, 2> T6;
    #pragma unroll
    for(nvfuser_index_t i112 = 0; i112 < 2; ++i112) {
      float T3[1];
      T3[0] = 0;
      if (b1981) {
        T3[0]
           = T0[((i614 + (T0.stride[0] * (i112 + nvfuser_zero))) + (T0.stride[1] * T2[0]))];
      }
      T6[i112]
         = T3[0];
    }
    NVFUSER_UPDATE_MAGIC_ZERO
    if (b1981) {                                     
      loadLocalToGlobal<float, 2, false>( &T4[i804], &T6[0]);                                                                            
    }                                                
  }                                                  
}                                                    
}                                                    
  /*           
CUDA NVRTC compile error: __tmp_kernel1.cu(9404): error: identifier "T2" is undefined                     
           = T0[((i614 + (T0.stride[0] * (i112 + nvfuser_zero))) + (T0.stride[1] * T2[0]))];              
                                                                                   ^                      
                                                     
__tmp_kernel1.cu(9386): warning #550-D: variable "T5" was set but never used                              
      int64_t T5[2];                                 
              ^                                      
                                                     
Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"
*/
```
Removing the reshape does not change the error.

### PR DESCRIPTION
**Pull request by jacobhinkle**
The `fuseWarpReduce` call in lowering rewrites single-warp reductions with broadcast consumers as allreduces. After that, it runs a custom DCE pass that aims to remove any replaced broadcasts and associated allocations. This DCE pass was actually removing an allocation in the example from #151 where the only use for the allocation is in an index expression, causing a compilation error.

The current approach is just to short-circuit this function if no broadcasts are removed. However, as noted in the previously-existing comments, rewriting and DCE passes like this are better done prior to this point, on the Fusion graph.

Also note that in debugging this, I realized it is quite hard to measure the effect of `fuseWarpReduce`. I tried commenting the function and I think all our tests still ran. It may be the case that we do not explicitly test rewrites of single-warp reductions, or that single-warp reductions are already being covered by the previous Fusion-based rewriting pass called `fuseReductionsAndBroadcasts` which covers grid reductions. A more detailed look at refactoring these two passes and potentially removing `fuseWarpReduce` will be left to another PR.

Fixes #151

### CODE REVIEW

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
Failing test is `FusionBiasGeluBwd_CUDA`:
https://gitlab-master.nvidia.com/dl/pytorch/update-scripts/-/jobs/58565720

**Comment by naoyam** [comment]
!build

File: csrc/lower_warp_reduce.cpp [hunk 1]
```diff
@@ -148,6 +148,10 @@ class FuseBroadcastWithWarpReduce : private kir::IrVisitor {
  public:
   static std::vector<Expr*> fuse(const std::vector<Expr*>& exprs) {
     FuseBroadcastWithWarpReduce fuse_broadcast_map(exprs);
+    if (fuse_broadcast_map.val_replacement_map_.empty()) {
```
Comment (naoyam) [inline csrc/lower_warp_reduce.cpp:151]: Is the issue the broadcast elimination pass incorrectly eliminates broadcast ops used for gather ops? If so, what happens if the warp fusion indeed happens?

Comment (jacobhinkle) [reply csrc/lower_warp_reduce.cpp:151]: `EliminateDeadBroadcastAndAllocate` looks for any local memory `Allocate`s whose buffers are broadcast outputs and which are not the inputs to an expression. It then marks any of these that are inputs to an expression in the kernel expression tree as "live", and removes any of the others. The thing is that a gather op actually looks like a `Set` op where the only input is the tensor being indexed, and the index expression itself is an attribute instead of an input. A more complete fix may be to check attributes in the Expr list as well, and look at those recursively, but I thought that may be too intrusive.

Comment (jacobhinkle) [reply csrc/lower_warp_reduce.cpp:151]: I also considered special casing for set ops. But I'm currently just looking at what is the actual difference between this pass and the earlier grid reduce fusion pass. In this pass, we check that the scopes are the same between the reduction and broadcast. In a graph-based pass, we could check that they are inlined at the same level instead I think? Otherwise, there is an assumption for fused warp reduce that the input is in register/local mem; I'm not sure if that also holds for grid reduce.

**Comment by jacobhinkle** [comment]
> The failing test should already be fixed in main.

Yeah, but even locally after merge I am seeing that test fail (3090Ti).

File: csrc/lower_warp_reduce.cpp (hunk 1 above)
Comment (naoyam) [reply csrc/lower_warp_reduce.cpp:151]: Hmm, maybe I'm missing something, but if we update this part: 

https://github.com/NVIDIA/Fuser/blob/main/csrc/lower_warp_reduce.cpp#L97-L103

to include the use by `gather`, isn't the problem gone?

Comment (jacobhinkle) [reply csrc/lower_warp_reduce.cpp:151]: Yeah I think we should be able to detect it, but I think it needs a bit of traversal. The reason is that in this case, the missing allocation is only used inside a somewhat deep indexing expression. That expression is a `TensorIndex` that's the input to a `LoadStoreOp` that we could detect there where you pointed. However, we'd then need to traverse to find the actual tensor we need to mark as live (by finding any root TVs of the `index()` I suppose). I can take a crack at it.

Comment (jacobhinkle) [reply csrc/lower_warp_reduce.cpp]: Latest push removes the empty check and adds all TV inputs of TensorIndex index() as live TVs. Note that it doesn't recurse further, since IterVisitor doesn't currently pass through `.index()` of a `TensorIndex` either. If this is the only case, we could add that level to IterVisitor. This is where Attributes on Vals might be nice, but Attributes are themselves Vals so it may not be so easy to add.

**Review by naoyam — APPROVED** [review]
LGTM. Thanks for the fix.

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
!build

**Comment by naoyam** [comment]
!build
