### PR TITLE
Fix domain validation

### LINKED ISSUE #3502: compareDomain fails to recognize additional IDs when those IDs are transformed
Repro:

```
  Fusion fusion;
  FusionGuard fg(&fusion);

  // [i0]
  auto tv0 = makeSymbolicTensor(1);
  fusion.addInput(tv0);
  // [i1, i0]
  auto tv1 = makeSymbolicTensor(2);
  fusion.addInput(tv1);

  // [i0]
  auto tv2 = set(tv0);
  // [b2, i0]
  auto tv3 = broadcast(tv2, {true, false});
  // [i1, i0]
  auto tv4 = add(tv1, tv3);
  fusion.addOutput(tv4);

  // [i3]
  tv4->merge(0);

  // Set the loop domain of tv2 as the same as tv4 loop domain. Note that tv4 loop domain is already different from its logical domain because of its merge op

  // tv2
  {
    // tv2 is missing the first logical ID of tv4, i.e., i1. Use a clone of i1.
    auto missing_id = tv4->getLogicalDomain().at(0)->cloneWithoutRFactor();
    std::vector<IterDomain*> new_loop_domain{IterDomain::merge(missing_id, tv2->getLogicalDomain().at(0))};
    tv2->setLoopDomain(new_loop_domain);
  }
```

It's such a simple pattern but the current `compareDomain` falsely reports there's a redundant ID because of this assertion: https://github.com/NVIDIA/Fuser/blob/main/csrc/ir/utils.cpp#L931-L937.

```
iS3{i0} is redundant in iS10{( i2 * i0 )}
```

`iS3` is the logical ID of `tv2`, which is obviously not redundant.

### PR DESCRIPTION
**Pull request by naoyam**
Fixes #3502 

To fix #3502, I revisited `compareDomains` and decided to start from scratch. `compareDomainWithReference` is the new function to verify the validity of a domain.

As the name suggests, this new function assumes one of the input domains is known to be a domain consisting of independent non-overlapped iter domains. That makes the analysis much simpler and less expensive. The assumption should be fine as we can always use the logical domain as a reference.

I initially attempted to just fix `compareDomains` with no particular assumption like having a reference (https://github.com/NVIDIA/Fuser/pull/3514/commits/46089ef306a1b6da6e7d63d1962dedc4679d81e3), but it turned out to be a very expensive analysis, so I scrapped it.

### CODE REVIEW

**Comment by naoyam** [comment]
!test

**Comment by naoyam** [comment]
!test

**Comment by naoyam** [comment]
!test

**Comment by naoyam** [comment]
!test

File: csrc/ir/utils.cpp [hunk 1]
```diff
@@ -801,6 +801,166 @@ std::vector<TensorView*> getTVsWithDynamicTransform(Fusion* fusion) {
...
+
+  // If there're unused IDs, they may be redundant or additional
+  // IDs. The latter means the ID has no overlap with any other
+  // ID. This could happen, for example, when we use a concrete loop
+  // ID for a broadcast logical ID.
+  //
+  // If there's unreachable reference IDs, however, the unused IDs may have
+  // been unused because of missing dependencies, which should not be
+  // considered redundant or additional. Different analysis would be
+  // required in that case, which is not imlemented since error
```
Comment (zasdfgbnm) [inline csrc/ir/utils.cpp:915]:
```suggestion
  // required in that case, which is not implemented since error
```

File: csrc/ir/utils.cpp [hunk 2]
```diff
@@ -801,6 +801,166 @@ std::vector<TensorView*> getTVsWithDynamicTransform(Fusion* fusion) {
...
+          additional_ids.push_back(unused_id);
+        }
+      }
+    }
+  }
+
+  // If an output of the path is not used, i.e., not part of the
+  // reference domain, it's considered an additional ID. For example,
+  // if we have `split i0 -> i1, i2`, and the reference only includes
+  // i1, i2 is considered an additional ID
```
Comment (zasdfgbnm) [inline csrc/ir/utils.cpp:953]: For clarity:
```suggestion
  // i1, then i2 is considered an additional ID
```
So that we now it is not "includes both i1 and i2"

File: csrc/iter_visitor.h [hunk 3]
```diff
@@ -604,4 +604,63 @@ class IRBFS
...
+      Direction allowed_direction = Direction::Undefined)
+      : IRBFS(
+            {from_ids.begin(), from_ids.end()},
+            {to_ids.begin(), to_ids.end()},
+            require_all_to_visited,
+            allowed_direction) {}
+
+  std::optional<std::pair<Direction, std::vector<NodeType>>> isReady(
+      const ExprType& expr) const override {
+    // Either all inputs or all outputs must have been visited
```
Comment (zasdfgbnm) [inline csrc/iter_visitor.h:632]:
```suggestion
    // Either any inputs or any outputs must have been visited
```

File: tests/cpp/test_inlining.cpp
Comment (zasdfgbnm) [inline tests/cpp/test_inlining.cpp:1]: Why does this file change?

**Review by zasdfgbnm — COMMENTED** [review]
Haven't finish reading yet

File: tests/cpp/test_gpu3.cpp [hunk 4]
```diff
@@ -6463,6 +6463,208 @@ TEST_F(NVFuserTest, CompareLogicalAndLoopDomains) {
...
+  const auto& reference = tv1->getLogicalDomain();
+
+  tv1->merge(0);
+  auto domain = tv1->getLoopDomain();
+  EXPECT_TRUE(ir_utils::compareDomainWithReference(domain, reference).empty());
+
+  // Adding one of the logical domain, which is redundant.
+  domain.push_back(tv1->getLogicalDomain().at(0));
+  auto x = ir_utils::compareDomainWithReference(domain, reference);
+  std::cerr << x.toString() << "\n";
```
Comment (zasdfgbnm) [inline tests/cpp/test_gpu3.cpp:6484]: remove debug print

**Review by zasdfgbnm — APPROVED** [review]

File: tests/cpp/test_inlining.cpp
Comment (naoyam) [reply tests/cpp/test_inlining.cpp:1]: Oh, sorry, I should have mentioned this before, but I actually found a bug with the new domain checker. In this test, the outermost dimension doesn't need to change at all, so we should just use `tv3->getLogicalDomain().at(0)` for `tv3`, for example. The inner 2 IDs are just extra IDs for `tv3` and `tv4`.

File: csrc/ir/utils.cpp [hunk 5]
```diff
@@ -801,6 +801,166 @@ std::vector<TensorView*> getTVsWithDynamicTransform(Fusion* fusion) {
   return dynamic_tvs;
 }
 
+CompareDomainWithReferenceResult compareDomainWithReference(
+    const std::vector<IterDomain*>& domain,
+    const std::vector<IterDomain*>& reference) {
+  if (domain.empty()) {
+    return {};
+  }
```
[the remark this answers is not in the document]
Comment (naoyam) [reply csrc/ir/utils.cpp:809]: Yeah, that makes more sense.

**Comment by naoyam** [comment]
!build
