### PR TITLE
Fix indexing traversal for vectorization validation

### LINKED ISSUE #5377: Failed to find a corresponding innermost allocation running HF Llama 4.
I get the following error (with a specific branch of thunder and running vanilla hf llama 4 from 4.55.4)

Error:
```
RuntimeError:  INTERNAL ASSERT FAILED at /workspace/Fuser/csrc/runtime/fusion_kernel_runtime.cpp:459, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. 
Expected thread_pool_error_message.empty() . Detected exception while compiling fusion segments in parallel. Error messages from all threads are printed below.

Error from segmentation group 9:  INTERNAL ASSERT FAILED at /workspace/Fuser/csrc/device_lower/validation.cpp:675, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. 
Failed to find a corresponding innermost allocation ID of T62_l___bfloat[iblockIdx.x235{( ceilDiv(640, blockDim.x) )}, iV234{8}, ithreadIdx.x236{blockDim.x}, bS158{1}] ca_pos( 1 ) with vectorized ID of iV234{8}
Vectorized load-store: T62_l___bfloat[iblockIdx.x235{( ceilDiv(640, blockDim.x) )}, iV234{8}, ithreadIdx.x236{blockDim.x}, bS158{1}] ca_pos( 1 )
   = Set( T2_g___bfloat[iS239{( ceilDiv(640, blockDim.x) )}, iS238{8}, iS240{blockDim.x}, bS4{1}], cache_op=AllLevels )
Allocation domain: bS158{1}, iS159{5120}
Loop domain: iblockIdx.x181{( ceilDiv(640, blockDim.x) )}, iV234{8}, ithreadIdx.x296{blockDim.x}, bS158{1}
Current visited group: idg{180 186 210 216 222 228 234 238 266 268 270 278 280 282 284 286 294} (iS180{8})
Split: iS159{5120} by factor 8 -> iS233{640}, iV234{8}
Split: iS233{640} by factor blockDim.x -> iblockIdx.x235{( ceilDiv(640, blockDim.x) )}, ithreadIdx.x236{blockDim.x}
```

Repro:
```python
# CUDA devices:
#  0: NVIDIA H200
# torch version: 2.8.0+cu128
# cuda version: 12.8
import torch
from nvfuser_direct import FusionDefinition, DataType
def nvfuser_fusion(fd : FusionDefinition) -> None :
    tv0 = fd.define_tensor(shape=[1, 16], contiguity=[None, True], dtype=DataType.BFloat16, is_cpu=False)
    tv1 = fd.define_tensor(shape=[1, 16], contiguity=[None, True], dtype=DataType.BFloat16, is_cpu=False)
    tv2 = fd.define_tensor(shape=[1, 5120], contiguity=[None, True], dtype=DataType.BFloat16, is_cpu=False)
    tv3 = fd.define_tensor(shape=[16, 5120, 16384], contiguity=[True, True, True], dtype=DataType.BFloat16, is_cpu=False)
    tv4 = fd.define_tensor(shape=[16, 8192, 5120], contiguity=[True, True, True], dtype=DataType.BFloat16, is_cpu=False)
    tv5 = fd.define_tensor(shape=[8192, 5120], contiguity=[True, True], dtype=DataType.BFloat16, is_cpu=False)
    tv6 = fd.define_tensor(shape=[8192, 5120], contiguity=[True, True], dtype=DataType.BFloat16, is_cpu=False)
    tv7 = fd.define_tensor(shape=[5120, 8192], contiguity=[True, True], dtype=DataType.BFloat16, is_cpu=False)
    tv41 = fd.ops.linear(tv2, tv5)
    tv42 = fd.ops.cast(tv41, dtype=DataType.Float)
    tv43 = fd.ops.neg(tv42)
    tv44 = fd.ops.exp(tv43)
    tv45 = fd.ops.add(1.00000, tv44)
    tv46 = fd.ops.reciprocal(tv45)
    tv47 = fd.ops.mul(tv42, tv46)
    tv48 = fd.ops.linear(tv2, tv6)
    tv49 = fd.ops.cast(tv48, dtype=DataType.Float)
    tv50 = fd.ops.mul(tv47, tv49)
    tv51 = fd.ops.cast(tv50, dtype=DataType.BFloat16)
    tv52 = fd.ops.linear(tv51, tv7)
    tv15 = fd.ops.broadcast(tv2, is_broadcast_dim=[True, False, True, False])
    tv16 = fd.ops.expand(tv15, shape=[16, 1, 1, 5120])
    tv17 = fd.ops.squeeze(tv16, dims=[1, 2])
    tv22 = fd.ops.cast(tv17, dtype=DataType.Float)
    tv8 = fd.ops.cast(tv0, dtype=DataType.BFloat16)
    tv9 = fd.ops.cast(tv8, dtype=DataType.Float)
    tv10 = fd.ops.neg(tv9)
    tv11 = fd.ops.exp(tv10)
    tv12 = fd.ops.add(1.00000, tv11)
    tv13 = fd.ops.reciprocal(tv12)
    tv14 = fd.ops.cast(tv13, dtype=DataType.BFloat16)
    tv18 = fd.ops.squeeze(tv14, dims=[0])
    tv19 = fd.ops.broadcast(tv18, is_broadcast_dim=[False, True])
    tv20 = fd.ops.cast(tv19, dtype=DataType.BFloat16)
    tv21 = fd.ops.expand(tv20, shape=[16, 5120])
    tv23 = fd.ops.cast(tv21, dtype=DataType.Float)
    tv24 = fd.ops.mul(tv22, tv23)
    tv25 = fd.ops.cast(tv24, dtype=DataType.BFloat16)
    tv26 = fd.ops.broadcast(tv25, is_broadcast_dim=[False, True, False])
    tv27 = fd.ops.matmul(tv26, tv3)
    tv29 = fd.ops.slice(tv27, start_indices=[0, 0, 8192], end_indices=[16, 1, 16384], strides=[1, 1, 1], manual_normalization=True)
    tv36 = fd.ops.cast(tv29, dtype=DataType.Float)
    tv28 = fd.ops.slice(tv27, start_indices=[0, 0, 0], end_indices=[16, 1, 8192], strides=[1, 1, 1], manual_normalization=True)
    tv30 = fd.ops.cast(tv28, dtype=DataType.Float)
    tv31 = fd.ops.neg(tv30)
    tv32 = fd.ops.exp(tv31)
    tv33 = fd.ops.add(1.00000, tv32)
    tv34 = fd.ops.reciprocal(tv33)
    tv35 = fd.ops.mul(tv30, tv34)
    tv37 = fd.ops.mul(tv36, tv35)
    tv38 = fd.ops.cast(tv37, dtype=DataType.BFloat16)
    tv39 = fd.ops.matmul(tv38, tv4)
    tv40 = fd.ops.squeeze(tv39, dims=[1])
    tv53 = fd.ops.broadcast(tv40, is_broadcast_dim=[False, True, False])
    tv54 = fd.ops.cast(tv53, dtype=DataType.Float)
    tv55 = fd.ops.sum(tv54, dims=[0], dtype=DataType.Float)
    tv56 = fd.ops.cast(tv55, dtype=DataType.BFloat16)
    fd.add_output(tv8, tv1)
    fd.add_output(tv52)
    fd.add_output(tv56)
with FusionDefinition() as fd:
    nvfuser_fusion(fd)

inputs = [
    torch.testing.make_tensor((1, 16), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((1, 16), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((1, 5120), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((16, 5120, 16384), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((16, 8192, 5120), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((8192, 5120), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((8192, 5120), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((5120, 8192), dtype=torch.bfloat16, device='cuda:0'),
]
fd.execute(inputs)
```

### PR DESCRIPTION
**Pull request by naoyam**
Fixes #5377

The issue happened while traversing a loop domain to an allocation domain in the *Exact* graph. This is done to find a corresponding allocation ID of a vectorized loop ID for validating the vectorization. The problem was the promoted loop domain was used with the Exact graph. This isn't guaranteed to work as loop promotion may pick, for example, `i0` over `i0 * 1`, and in some other cases `i0 * 1` instead of `i0`. Because of the inconsistency, traversing the Exact graph may not work and the AlmostExact graph needs to be used.

For this traversal, the simplest fix is not using loop promotion as it shouldn't be necessary.

### CODE REVIEW

**Comment by naoyam** [comment]
!test --diff

**Comment by naoyam** [comment]
!test --diff

**Comment by naoyam** [comment]
!test --diff

**Comment by naoyam** [comment]
!test --diff

**Comment by naoyam** [comment]
!test

**Comment by naoyam** [comment]
!test

**Comment by naoyam** [comment]
!test

**Comment by naoyam** [comment]
!test --diff

File: csrc/device_lower/validation.cpp [hunk 1]
```diff
@@ -672,6 +673,7 @@ class VectorizeValidator : public OptInDispatch {
       for (auto expr : tv->domain()->allExprs()) {
         ss << expr->toString();
       }
+      graph.dumpGraphvizDotGraph("validation_graph.dot");
```
Comment (jacobhinkle) [inline csrc/device_lower/validation.cpp]:
```suggestion
```

**Comment by naoyam** [comment]
!build
