### PR TITLE
Re-write replaceSymbolicSizes using IdModel

### LINKED ISSUE #2702: Codegen error: `have dynamic allocations but are placed in local memory.` coming from qkv_split_rope backwards
Seems to be a functional regression. A new failure show up from disabling bookend in the qkv_split_rope backward.

Error message:
```
Traceback (most recent call last):
  File "/opt/pytorch/nvfuser/nvfuser/__init__.py", line 210, in execute
    result = self._execute(
RuntimeError: false INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/executor.cpp":492, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Allocations must be based on constant integers for local memory. However, found: T74_l[ iblockIdx.x515{( ceilDiv(( ceilDiv(( ceilDiv(( 8 * ( 8192 * 128 ) ), 8) ), blockDim.x) ), 1) )}, ithreadIdx.x514{blockDim.x}, iUS516{1}, iV512{8}, iS519{( ceilDiv(( ceilDiv(( ceilDiv(( (( (( getMetaData(T4) )).logical_size ))[1] ), 8) ), 2) ), 1) )}, iUS520{1}, iUR518{2}, bS420{1} ] ca_pos( 3 ), T74_l[ iblockIdx.x515{( ceilDiv(( ceilDiv(( ceilDiv(( 8 * ( 8192 * 128 ) ), 8) ), blockDim.x) ), 1) )}, ithreadIdx.x514{blockDim.x}, iUS516{1}, iV512{8}, iS519{( ceilDiv(( ceilDiv(( ceilDiv(( (( (( getMetaData(T4) )).logical_size ))[1] ), 8) ), 2) ), 1) )}, iUS520{1}, iUR518{2}, bS420{1} ] ca_pos( 3 ),  have dynamic allocations but are placed in local memory.
Exception raised from compileFusion at /opt/pytorch/nvfuser/csrc/executor.cpp:492 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf3 (0x7f3e15150829 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #1: nvfuser::nvfErrorFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x53 (0x7f3e154ad263 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #2: nvfuser::FusionExecutor::compileFusion(nvfuser::Fusion*, nvfuser::KernelArgumentHolder const&, nvfuser::LaunchParams const&, nvfuser::CompileParams, nvfuser::ScheduleHeuristic, long, long, long, long) + 0x1fe7 (0x7f3e154c7257 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x6ab5d5 (0x7f3e156cc5d5 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #4: nvfuser::FusionKernelRuntime::compileFusionParallel(nvfuser::KernelArgumentHolder) + 0x492 (0x7f3e156d4622 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #5: nvfuser::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&, std::optional<nvfuser::PrimDataType>, std::optional<signed char>) + 0xab3 (0x7f3e156df4a3 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #6: nvfuser::python_frontend::FusionDefinition::execute(c10::ArrayRef<c10::IValue> const&, std::optional<signed char>, bool, bool, bool) const + 0x394 (0x7f3e158d0a24 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #7: <unknown function> + 0x1ad1be (0x7f3e151ce1be in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #8: <unknown function> + 0x22452f (0x7f3e1524552f in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #9: <unknown function> + 0x2ba5f0 (0x7f3e152db5f0 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
<omitting python frames>
frame #25: <unknown function> + 0x29d90 (0x7f4057536d90 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #26: __libc_start_main + 0x80 (0x7f4057536e40 in /usr/lib/x86_64-linux-gnu/libc.so.6)
```

vvv

```
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id1(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[-1, -1], contiguity=[True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[1, 0])
    T1 = fd.define_tensor(shape=[-1, -1], contiguity=[True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[1, 0])
    T2 = fd.define_tensor(shape=[1, -1, -1, -1], contiguity=[None, True, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[3, 2, 1, 0])
    T3 = fd.define_tensor(shape=[1, -1, -1, -1], contiguity=[None, True, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[3, 2, 1, 0])
    T4 = fd.define_tensor(shape=[1, -1, -1, -1], contiguity=[None, True, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[3, 2, 1, 0])
    S5 = fd.define_scalar(1, dtype=DataType.Int)
    S6 = fd.define_scalar(32, dtype=DataType.Int)
    S7 = fd.define_scalar(8192, dtype=DataType.Int)
    S8 = fd.define_scalar(128, dtype=DataType.Int)
    V9 = fd.define_vector([S5, S6, S7, S8], dtype=DataType.Int)
    T10 = fd.ops.broadcast_in_dim(T0, shape=V9, broadcast_dims=[2, 3])
    T11 = fd.ops.cast(T10, dtype=DataType.Float)
    S12 = fd.define_scalar(1, dtype=DataType.Int)
    S13 = fd.define_scalar(32, dtype=DataType.Int)
    S14 = fd.define_scalar(8192, dtype=DataType.Int)
    S15 = fd.define_scalar(128, dtype=DataType.Int)
    V16 = fd.define_vector([S12, S13, S14, S15], dtype=DataType.Int)
    T17 = fd.ops.broadcast_in_dim(T1, shape=V16, broadcast_dims=[2, 3])
    T18 = fd.ops.cast(T17, dtype=DataType.Float)
    T19 = fd.ops.slice(T3, start_indices=[0, 0, 0, 0], end_indices=[1, 32, 8192, 128], strides=[1, 1, 1, 1])
    S20 = fd.define_scalar(0, dtype=DataType.Int)
    S21 = fd.define_scalar(1, dtype=DataType.Int)
    S22 = fd.define_scalar(32, dtype=DataType.Int)
    S23 = fd.define_scalar(8192, dtype=DataType.Int)
    S24 = fd.define_scalar(0, dtype=DataType.Int)
    V25 = fd.define_vector([S21, S22, S23, S24], dtype=DataType.Int)
    T26 = fd.ops.full(shape=V25, fill_value=S20, dtype=DataType.BFloat16)
    S27 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T28 = fd.ops.pad(T26, [0, 128, 0, 0, 0, 0, 0, 0], S27)
    T29 = fd.ops.slice(T2, start_indices=[0, 0, 0, 0], end_indices=[1, 32, 8192, 128], strides=[1, 1, 1, 1])
    T30 = fd.ops.cast(T19, dtype=DataType.Float)
    T31 = fd.ops.mul(T18, T30)
    T32 = fd.ops.cast(T31, dtype=DataType.BFloat16)
    T33 = fd.ops.mul(T11, T30)
    T34 = fd.ops.cast(T28, dtype=DataType.Float)
    T35 = fd.ops.add(T34, T33)
    T36 = fd.ops.slice(T32, start_indices=[0, 0, 0, 0], end_indices=[1, 32, 8192, 64], strides=[1, 1, 1, 1])
    T37 = fd.ops.slice(T32, start_indices=[0, 0, 0, 64], end_indices=[1, 32, 8192, 128], strides=[1, 1, 1, 1])
    T38 = fd.ops.cast(T36, dtype=DataType.Float)
    T39 = fd.ops.neg(T38)
    T40 = fd.ops.cast(T39, dtype=DataType.BFloat16)
    S41 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T42 = fd.ops.pad(T40, [64, 0, 0, 0, 0, 0, 0, 0], S41)
    T43 = fd.ops.cast(T42, dtype=DataType.Float)
    T44 = fd.ops.add(T35, T43)
    S45 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T46 = fd.ops.pad(T37, [0, 64, 0, 0, 0, 0, 0, 0], S45)
    T47 = fd.ops.cast(T46, dtype=DataType.Float)
    T48 = fd.ops.add(T44, T47)
    T49 = fd.ops.cast(T48, dtype=DataType.BFloat16)
    T50 = fd.ops.cast(T29, dtype=DataType.Float)
    T51 = fd.ops.mul(T18, T50)
    T52 = fd.ops.cast(T51, dtype=DataType.BFloat16)
    T53 = fd.ops.mul(T11, T50)
    T54 = fd.ops.add(T34, T53)
    T55 = fd.ops.slice(T52, start_indices=[0, 0, 0, 0], end_indices=[1, 32, 8192, 64], strides=[1, 1, 1, 1])
    T56 = fd.ops.slice(T52, start_indices=[0, 0, 0, 64], end_indices=[1, 32, 8192, 128], strides=[1, 1, 1, 1])
    T57 = fd.ops.cast(T55, dtype=DataType.Float)
    T58 = fd.ops.neg(T57)
    T59 = fd.ops.cast(T58, dtype=DataType.BFloat16)
    S60 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T61 = fd.ops.pad(T59, [64, 0, 0, 0, 0, 0, 0, 0], S60)
    T62 = fd.ops.cast(T61, dtype=DataType.Float)
    T63 = fd.ops.add(T54, T62)
    S64 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T65 = fd.ops.pad(T56, [0, 64, 0, 0, 0, 0, 0, 0], S64)
    T66 = fd.ops.cast(T65, dtype=DataType.Float)
    T67 = fd.ops.add(T63, T66)
    T68 = fd.ops.cast(T67, dtype=DataType.BFloat16)
    S69 = fd.define_scalar(1, dtype=DataType.Int)
    S70 = fd.define_scalar(8, dtype=DataType.Int)
    S71 = fd.define_scalar(4, dtype=DataType.Int)
    S72 = fd.define_scalar(8192, dtype=DataType.Int)
    S73 = fd.define_scalar(128, dtype=DataType.Int)
    V74 = fd.define_vector([S69, S70, S71, S72, S73], dtype=DataType.Int)
    T75 = fd.ops.reshape(T4, new_shape=V74)
    S76 = fd.define_scalar(1, dtype=DataType.Int)
    S77 = fd.define_scalar(8, dtype=DataType.Int)
    S78 = fd.define_scalar(4, dtype=DataType.Int)
    S79 = fd.define_scalar(8192, dtype=DataType.Int)
    S80 = fd.define_scalar(128, dtype=DataType.Int)
    V81 = fd.define_vector([S76, S77, S78, S79, S80], dtype=DataType.Int)
    T82 = fd.ops.reshape(T49, new_shape=V81)
    S83 = fd.define_scalar(1, dtype=DataType.Int)
    S84 = fd.define_scalar(8, dtype=DataType.Int)
    S85 = fd.define_scalar(4, dtype=DataType.Int)
    S86 = fd.define_scalar(8192, dtype=DataType.Int)
    S87 = fd.define_scalar(128, dtype=DataType.Int)
    V88 = fd.define_vector([S83, S84, S85, S86, S87], dtype=DataType.Int)
    T89 = fd.ops.reshape(T68, new_shape=V88)
    T90 = fd.ops.cast(T75, dtype=DataType.Float)
    T91 = fd.ops.sum(T90, dims=[0, 2], keepdim=False, dtype=DataType.Null)
    T92 = fd.ops.cast(T91, dtype=DataType.BFloat16)
    S93 = fd.define_scalar(1, dtype=DataType.Int)
    S94 = fd.define_scalar(8, dtype=DataType.Int)
    S95 = fd.define_scalar(1, dtype=DataType.Int)
    S96 = fd.define_scalar(8192, dtype=DataType.Int)
    S97 = fd.define_scalar(128, dtype=DataType.Int)
    V98 = fd.define_vector([S93, S94, S95, S96, S97], dtype=DataType.Int)
    T99 = fd.ops.broadcast_in_dim(T92, shape=V98, broadcast_dims=[1, 3, 4])
    T100 = fd.ops.cast(T82, dtype=DataType.Float)
    T101 = fd.ops.sum(T100, dims=[0, 2], keepdim=False, dtype=DataType.Null)
    T102 = fd.ops.cast(T101, dtype=DataType.BFloat16)
    S103 = fd.define_scalar(1, dtype=DataType.Int)
    S104 = fd.define_scalar(8, dtype=DataType.Int)
    S105 = fd.define_scalar(1, dtype=DataType.Int)
    S106 = fd.define_scalar(8192, dtype=DataType.Int)
    S107 = fd.define_scalar(128, dtype=DataType.Int)
    V108 = fd.define_vector([S103, S104, S105, S106, S107], dtype=DataType.Int)
    T109 = fd.ops.broadcast_in_dim(T102, shape=V108, broadcast_dims=[1, 3, 4])
    T110 = fd.ops.cat([T89, T109, T99], dim=2)
    T111 = fd.ops.permute(T110, dims=[0, 3, 1, 2, 4])
    S112 = fd.define_scalar(1, dtype=DataType.Int)
    S113 = fd.define_scalar(8192, dtype=DataType.Int)
    S114 = fd.define_scalar(6144, dtype=DataType.Int)
    V115 = fd.define_vector([S112, S113, S114], dtype=DataType.Int)
    T116 = fd.ops.reshape(T111, new_shape=V115)
    fd.add_output(T116)

with FusionDefinition() as fd:
    nvfuser_fusion_id1(fd)

inputs = [
    torch.randn((1048576,), dtype=torch.bfloat16, device='cuda:0').as_strided((8192, 128), (128, 1)),
    torch.randn((1048576,), dtype=torch.bfloat16, device='cuda:0').as_strided((8192, 128), (128, 1)),
    torch.randn((33554432,), dtype=torch.bfloat16, device='cuda:0').as_strided((1, 32, 8192, 128), (33554432, 1048576, 128, 1)),
    torch.randn((33554432,), dtype=torch.bfloat16, device='cuda:0').as_strided((1, 32, 8192, 128), (33554432, 1048576, 128, 1)),
    torch.randn((33554432,), dtype=torch.bfloat16, device='cuda:0').as_strided((1, 32, 8192, 128), (33554432, 1048576, 128, 1)),
]
fd.execute(inputs)

```

### LINKED ISSUE #2766: Allocs must be based on constant integers
This comes out of the proxy model, after #2765 lands.

```
RuntimeError: false INTERNAL ASSERT FAILED at "/tmp/pip-req-build-9g58foxe/csrc/executor.cpp":437, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Allocations must be based on constant integers for local memory. However, found: T108_l[ iblockIdx.x751{( ceilDiv(( ceilDiv(( ceilDiv(( 22 * ( 96 * ( 60 * ( 80 * ( ceilDiv(( (( (( getMetaData(T5) )).logical_size ))[3] ), 80) ) ) ) ) ), 4) ), blockDim.x) ), 1) )}, ithreadIdx.x750{blockDim.x}, iUS752{1}, iV748{4}, iS755{( ceilDiv(( ceilDiv(( ceilDiv(( (( (( getMetaData(T5) )).logical_size ))[2] ), 60) ), 2) ), 1) )}, iUS756{1}, iUR754{2} ] ca_pos( 3 ), T108_l[ iblockIdx.x751{( ceilDiv(( ceilDiv(( ceilDiv(( 22 * ( 96 * ( 60 * ( 80 * ( ceilDiv(( (( (( getMetaData(T5) )).logical_size ))[3] ), 80) ) ) ) ) ), 4) ), blockDim.x) ), 1) )}, ithreadIdx.x750{blockDim.x}, iUS752{1}, iV748{4}, iS755{( ceilDiv(( ceilDiv(( ceilDiv(( (( (( getMetaData(T5) )).logical_size ))[2] ), 60) ), 2)), 1) )}, iUS756{1}, iUR754{2} ] ca_pos( 3 ),  have dynamic allocations but are placed in local memory.
Exception raised from compileFusion at /tmp/pip-req-build-9g58foxe/csrc/executor.cpp:437 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf8 (0xffd476098154 in /home/tfogal/env/lib/python3.10/site-packages/nvfuser/_C.cpython-310-aarch64-linux-gnu.so)
frame #1: nvfuser::nvfErrorFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x5c (0xffd47637a48c in /home/tfogal/env/lib/python3.10/site-packages/nvfuser/_C.cpython-310-aarch64-linux-gnu.so)
frame #2: nvfuser::FusionExecutor::compileFusion(nvfuser::Fusion*, nvfuser::KernelArgumentHolder const&, nvfuser::LaunchParams const&, nvfuser::CompileParams, nvfuser::ScheduleHeuristic, long, long, long, long) + 0x1738 (0xffd47639172c in /home/tfogal/env/lib/python3.10/site-packages/nvfuser/_C.cpython-310-aarch64-linux-gnu.so)
frame #3: <unknown function> + 0x5c16e8 (0xffd4765816e8 in /home/tfogal/env/lib/python3.10/site-packages/nvfuser/_C.cpython-310-aarch64-linux-gnu.so)
frame #4: nvfuser::FusionKernelRuntime::compileFusionParallel(nvfuser::KernelArgumentHolder) + 0x348 (0xffd476589048 in /home/tfogal/env/lib/python3.10/site-packages/nvfuser/_C.cpython-310-aarch64-linux-gnu.so)
frame #5: nvfuser::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&, std::optional<nvfuser::PrimDataType>, std::optional<signed char>) + 0x50c (0xffd47659284c in /home/tfogal/env/lib/python3.10/site-packages/nvfuser/_C.cpython-310-aarch64-linux-gnu.so)
frame #6: nvfuser::python_frontend::FusionDefinition::execute(c10::ArrayRef<c10::IValue> const&, std::optional<sign
ed char>, bool, bool, bool) const + 0x304 (0xffd476772864 in /home/tfogal/env/lib/python3.10/site-packages/nvfuser/
_C.cpython-310-aarch64-linux-gnu.so)
frame #7: <unknown function> + 0xed32c (0xffd4760ad32c in /home/tfogal/env/lib/python3.10/site-packages/nvfuser/_C.
cpython-310-aarch64-linux-gnu.so)
frame #8: <unknown function> + 0x1644e0 (0xffd4761244e0 in /home/tfogal/env/lib/python3.10/site-packages/nvfuser/_C
.cpython-310-aarch64-linux-gnu.so)
frame #9: <unknown function> + 0x1fda30 (0xffd4761bda30 in /home/tfogal/env/lib/python3.10/site-packages/nvfuser/_C
.cpython-310-aarch64-linux-gnu.so)
<omitting python frames>
frame #25: <unknown function> + 0x273fc (0xffd733d373fc in /usr/lib/aarch64-linux-gnu/libc.so.6)
frame #26: __libc_start_main + 0x98 (0xffd733d374cc in /usr/lib/aarch64-linux-gnu/libc.so.6)
```

[nvf-alloc.py](https://github.com/user-attachments/files/16516447/nvf-alloc.py.txt)

### PR DESCRIPTION
**Pull request by jacobhinkle**
This uses IdModel to implement `replaceSymbolicSizes`. Extents are replaced with a single representative from their exact graph ValGroup with the following precedence:
1. Constants are preferred
2. If no constants exist, prefer the extents of fusion inputs.
3. Ties are broken by choosing the scalar with the smallest `name()`.

Fixes #2702. Fixes #2766

### CODE REVIEW

**Comment by jacobhinkle** [comment]
!build --diff

**Comment by jacobhinkle** [comment]
!build --diff

**Comment by jacobhinkle** [comment]
!build --diff-bench

**Comment by jacobhinkle** [comment]
!build --diff-bench

File: csrc/device_lower/pass/replace_size.cpp [hunk 1]
```diff
@@ -35,131 +37,68 @@ namespace {
...
-
-  auto map_root_ids = [&disjoint_root_sets, &id_to_disjoint_root_set](
-                          IterDomain* id0, IterDomain* id1) {
-    if (id0->isBroadcast() || id1->isBroadcast()) {
-      return;
-    }
-
-    if (id0->isGatherScatter() || id1->isGatherScatter()) {
-      return;
-    }
```
Comment (jacobhinkle) [inline csrc/device_lower/pass/replace_size.cpp:50]: Wondering if there was a reason for special-casing for these cases. Instead I am just using `getMaybeExpandedExtent()` now.

**Comment by jacobhinkle** [comment]
!build --diff-bench

**Comment by jacobhinkle** [comment]
Marking as draft while I investigate some test failures

**Comment by jacobhinkle** [comment]
!build --diff-bench

**Comment by jacobhinkle** [comment]
!build --diff-bench

**Comment by naoyam** [comment]
This also fixes #2766.

@jacobhinkle, please add this as a test as well. This is based on the repro of #2766.

```
// Repro of #2766 
TEST_F(NVFuserTest, SmallOuterBlockReductionRepro) {
  std::unique_ptr<Fusion> fusion_ptr = std::make_unique<Fusion>();
  auto& fusion = *fusion_ptr;
  FusionGuard fg(&fusion);

  std::vector<int64_t> shape{100, 2, 128};

  auto tv0 = makeContigTensor(2);
  fusion.addInput(tv0);

  auto tv1 = reshape(
      tv0,
      {IrBuilder::create<Val>(shape[0]),
       IrBuilder::create<Val>(shape[1]),
       IrBuilder::create<Val>(shape[2])});
  auto tv2 = sum(tv1, {1});
  fusion.addOutput(tv2);

  // Previously, after the extent replacement of the lowering, the reduction reference tensor got a reduction domain of a static size, which is just 1, but the pre-reshape tensors still kept using symbolic extents. Before #2771, the scheduler decided to not use TIDy because the reference tensor has a static size of 1, but since the other tensors still had dynamic sizes, it resulted in the dynamic allocation error.

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  auto t0 = at::randn({shape[0] * shape[1], shape[2]}, options);
  std::vector<c10::IValue> inputs({t0});

  FusionExecutorCache fec(std::move(fusion_ptr));
  auto outputs = fec.runFusionWithInputs(inputs);

  testValidate(fec.fusion(), outputs, inputs, __LINE__, __FILE__);
}
```

**Comment by jacobhinkle** [comment]
!build --diff-bench

File: tests/python/test_python_frontend.py [hunk 2]
```diff
@@ -4584,6 +4584,55 @@ def fusion_func(
                     )
                 torch.testing.assert_close(nvf_out[0], ref_out)
 
+    # Test that replaced sizes using input tensor metadata are successfully computed
+    # See https://github.com/NVIDIA/Fuser/pull/2714 which surfaced this in
+    # failing thunder test
+    # thunder.tests.test_core.test_bsym_toposort_nvfuser_cuda_thunder.dtypes.float32
+    def test_replaced_sizes_pr2714(self):
```
Comment (jacobhinkle) [inline tests/python/test_python_frontend.py:4591]: This test fails currently. We wind up needing to compute metadata for T0 at runtime, but we can't because we never actually _bind_ `GetMetadata` to `PrecomputedValues`.  It looks at a glance like this line is enough:https://github.com/NVIDIA/Fuser/blob/862dfd18a03b48617c4789b7507455eb996fb5d3/csrc/evaluator_common.cpp#L373
However, `bindValue` requires `evaluatorIndex()` to be set on the `Val` for it to have any effect: https://github.com/NVIDIA/Fuser/blob/862dfd18a03b48617c4789b7507455eb996fb5d3/csrc/evaluator_common.h#L208-L211. The only `Val`s that have evaluator indices are those found in `collectRuntimeUsedValues`: https://github.com/NVIDIA/Fuser/blob/862dfd18a03b48617c4789b7507455eb996fb5d3/csrc/evaluator_common.cpp#L93
This function doesn't currently look for `metadataOf(tv)` and simply adding that line doesn't seem to be enough. I will investigate this more; it seems like a more general bug but I haven't yet isolated a simpler repro for just this particular failure.

Comment (jacobhinkle) [reply tests/python/test_python_frontend.py:4591]: With latest commit c423854 this gets closer, but still fails in `PrecomputedValues::validate` at this check: https://github.com/NVIDIA/Fuser/blob/5326aff33d3078f03a103d2486a672ba3b6ea1d6/csrc/evaluator_common.cpp#L317
The `TensorMetaData` is held in a `PolymorphicValue` that is a `StructHandle` and `isSame` just checks that the pointer is equal. https://github.com/NVIDIA/Fuser/blob/5326aff33d3078f03a103d2486a672ba3b6ea1d6/csrc/polymorphic_value.h#L279 We might be creating metadata multiple times for some reason. I am not sure. However, if I just insert
```c++
if (a.is<StructHandle>()) {
  return b.is<StructHandle>();
}
```
then this test passes. That weakens the validation of course. A proper fix would do a deep equality check, probably by special casing for known `Struct`s like `TensorMetaData`. For now, maybe we can avoid this pointer check for `Struct`s? What do you think, @zasdfgbnm ?

**Comment by jacobhinkle** [comment]
!build

File: tests/python/test_python_frontend.py (hunk 2 above)
Comment (jacobhinkle) [reply tests/python/test_python_frontend.py:4288]: Current status: the deep validation check was merged (#2811), but there are still some CI errors blocking #2812 which actually binds the tensor metadata. Once that is figured out this PR should be ready to go.

Comment (jacobhinkle) [reply tests/python/test_python_frontend.py:4288]: This now passes.

**Comment by jacobhinkle** [comment]
!build --diff-bench

**Comment by jacobhinkle** [comment]
!build --diff-bench

**Comment by jacobhinkle** [comment]
The only test failures are known H100 thunder SDPA failures.

**Comment by liqiangxl** [comment]
@jacobhinkle I merged #2668 into main, updated this branch, and restarted CI. Just to make ensure this is no conflict.

**Comment by liqiangxl** [comment]
!build

**Comment by jacobhinkle** [comment]
> @jacobhinkle I merged #2668 into main, updated this branch, and restarted CI. Just to make ensure there is no conflict.

Good idea. Thanks.

File: csrc/device_lower/pass/replace_size.cpp [hunk 3]
```diff
@@ -230,20 +192,28 @@ void replaceSymbolicSizes(Fusion* fusion) {
...
     auto simplified_extent = extent_entry.second;
-    if (tensor_dim_map.count(orig_extent)) {
-      if (tensor_dim_map.count(simplified_extent)) {
-        tensor_dim_map[orig_extent] = tensor_dim_map[simplified_extent];
-      } else {
-        tensor_dim_map[orig_extent] = simplified_extent;
-      }
+    auto it = tensor_dim_map.find(simplified_extent);
+    if (it != tensor_dim_map.end()) {
+      extent_simplification_map[orig_extent] = it->second;
```
Comment (naoyam) [inline csrc/device_lower/pass/replace_size.cpp:204]: nit: I always feel a little nervous when I see a map is modified while iterating it. I think this should be fine, though.

File: csrc/device_lower/pass/replace_size.cpp [hunk 4]
```diff
@@ -230,20 +192,28 @@ void replaceSymbolicSizes(Fusion* fusion) {
...
     auto orig_extent = extent_entry.first;
     auto simplified_extent = extent_entry.second;
-    if (tensor_dim_map.count(orig_extent)) {
-      if (tensor_dim_map.count(simplified_extent)) {
-        tensor_dim_map[orig_extent] = tensor_dim_map[simplified_extent];
-      } else {
-        tensor_dim_map[orig_extent] = simplified_extent;
-      }
+    auto it = tensor_dim_map.find(simplified_extent);
+    if (it != tensor_dim_map.end()) {
```
Comment (naoyam) [inline csrc/device_lower/pass/replace_size.cpp:203]: Why are we doing this? Previously, there's `tensor_dim_map`, and we update it with `expr_simplification_map`. Now, it seems we are doing the opposite, which means if an extent is discovered to be a constant in `expr_simplification_map`, it would be overwritten by the symbolic representation. Am I understanding it correctly?

**Review by naoyam — COMMENTED** [review]
Do we have basic tests of the replacement? If not, please add some unit tests.

File: csrc/device_lower/pass/replace_size.cpp (hunk 4 above)
Comment (jacobhinkle) [reply csrc/device_lower/pass/replace_size.cpp:203]: Yes, we are now doing more replacements than previously. Previously we would only replace extents that are exact mapped to input extents. This was a problem in the motivating example from #2702: see https://github.com/NVIDIA/Fuser/issues/2702#issuecomment-2256920406. In that case it's "`ceilDiv`" extent of a reshaped tensor that needs to be mapped as constant and it's not actually exact mapped with an input.

Comment (naoyam) [reply csrc/device_lower/pass/replace_size.cpp:201]: I understand that, but what happens if an input domain is discovered to be a constant in `extent_simplification_map`. Wouldn't it be overwritten by the `getMetaData` expr even if it's constant?

File: tests/cpp/test_gpu3.cpp [hunk 5]
```diff
@@ -8770,6 +8771,56 @@ TEST_F(NVFuserTest, Issue2685Repro) {
   testValidate(&fusion_copy, outputs, inputs, __LINE__, __FILE__);
 }
 
+// Check that extents are properly replaced by replaceSymbolicSizes lowering
+// pass
+TEST_F(NVFuserTest, ReplaceSymbolicSizes) {
```
Comment (jacobhinkle) [inline tests/cpp/test_gpu3.cpp:8776]: Added this test which matches the behavior described in the comments of `replaceSymbolicSizes`.

File: csrc/device_lower/pass/replace_size.cpp (hunk 4 above)
Comment (naoyam) [reply csrc/device_lower/pass/replace_size.cpp:232]: Ah, I see.

Why is the previous code not enough?

Comment (naoyam) [reply csrc/device_lower/pass/replace_size.cpp:232]: Hmm, what about line 240 of the previous code? Doesn't it add a mapping that does not exist in `tensor_dim_map`?

Comment (naoyam) [reply csrc/device_lower/pass/replace_size.cpp:232]: Never mind, I misread the code. It's under the `if` branch starting at line 237, not 236.

**Review by naoyam — APPROVED** [review]
LGTM. Thanks!
