### PR TITLE
Fix resize scheduler with reshapes appearing after ref tensor

### LINKED ISSUE #4250: LitGPT based Llama backward error around RoPE
I am not sure what extra logic is here but there is something in the backward pass in the full model that is triggering an error.

Error:
```
Error from segmentation group 12:  INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/scheduler/tools/loop_domain_scheduler.cpp":436, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Trying to update the current loop domain but could not find a valid path from the referenc
e: T167_l___bfloat[bS490{1}, iS491{2048}, iS496{1024}rf]. Missing target ID groups: idg{496 660}
Exception raised from getReplayPath at /opt/pytorch/nvfuser/csrc/scheduler/tools/loop_domain_scheduler.cpp:436 (most recent call first):
```

Repro:
```
# torch version: 2.7.0a0+79aa17489c.nvInternal
# cuda version: 12.9
# nvfuser version: 0.2.27+git802f042
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id10(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[1, 2048, 128], contiguity=[None, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[2, 1, 0])
    T1 = fd.define_tensor(shape=[1, 8, 2048, 128], contiguity=[None, True, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[3, 2, 1, 0])
    T2 = fd.define_tensor(shape=[1, 32, 2048, 128], contiguity=[None, True, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[3, 2, 1, 0])
    T3 = fd.define_tensor(shape=[1, 2048, 6144], contiguity=[None, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[2, 1, 0])
    T4 = fd.define_tensor(shape=[1, 2048, 128], contiguity=[None, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[2, 1, 0])
    T5 = fd.define_tensor(shape=[1, 8, 2048, 128], contiguity=[None, True, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[3, 2, 1, 0])
    T6 = fd.define_tensor(shape=[1, 2048, 4096], contiguity=[None, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[2, 1, 0])
    T7 = fd.define_tensor(shape=[1, 2048, 4096], contiguity=[None, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[2, 1, 0])
    T8 = fd.define_tensor(shape=[1, 2048, 14336], contiguity=[None, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[2, 1, 0])
    T9 = fd.define_tensor(shape=[1, 2048, 4096], contiguity=[None, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[2, 1, 0])
    T15 = fd.ops.reshape(T0, new_shape=[1, 1, 2048, 128])
    T31 = fd.ops.slice(T1, start_indices=[0, 0, 0, 0], end_indices=[1, 8, 2048, 128], strides=[1, 1, 1, 1], manual_normalization=0)
    T37 = fd.ops.broadcast_in_dim(T15, shape=[1, 8, 2048, 128], broadcast_dims=[0, 1, 2, 3])
    T53 = fd.ops.slice(T2, start_indices=[0, 0, 0, 0], end_indices=[1, 32, 2048, 128], strides=[1, 1, 1, 1], manual_normalization=0)
    T59 = fd.ops.broadcast_in_dim(T15, shape=[1, 32, 2048, 128], broadcast_dims=[0, 1, 2, 3])
    T60 = fd.ops.cast(T31, dtype=DataType.Float)
    T61 = fd.ops.cast(T37, dtype=DataType.Float)
    T62 = fd.ops.cast(T53, dtype=DataType.Float)
    T63 = fd.ops.cast(T59, dtype=DataType.Float)
    T76 = fd.ops.slice(T3, start_indices=[0, 0, 0], end_indices=[1, 2048, 4096], strides=[1, 1, 1], manual_normalization=0)
    T89 = fd.ops.slice(T3, start_indices=[0, 0, 4096], end_indices=[1, 2048, 5120], strides=[1, 1, 1], manual_normalization=0)
    T90 = fd.ops.mul(T61, T60)
    T91 = fd.ops.mul(T63, T62)
    T97 = fd.ops.reshape(T76, new_shape=[1, 2048, 32, 128])
    T103 = fd.ops.reshape(T89, new_shape=[1, 2048, 8, 128])
    T104 = fd.ops.cast(T90, dtype=DataType.BFloat16)
    T105 = fd.ops.cast(T91, dtype=DataType.BFloat16)
    T106 = fd.ops.permute(T97, dims=[0, 2, 1, 3])
    T107 = fd.ops.permute(T103, dims=[0, 2, 1, 3])
    T123 = fd.ops.slice(T104, start_indices=[0, 0, 0, 0], end_indices=[1, 8, 2048, 64], strides=[1, 1, 1, 1], manual_normalization=0)
    T139 = fd.ops.slice(T105, start_indices=[0, 0, 0, 0], end_indices=[1, 32, 2048, 64], strides=[1, 1, 1, 1], manual_normalization=0)
    T155 = fd.ops.slice(T106, start_indices=[0, 0, 0, 64], end_indices=[1, 32, 2048, 128], strides=[1, 1, 1, 1], manual_normalization=0)
    T171 = fd.ops.slice(T107, start_indices=[0, 0, 0, 64], end_indices=[1, 8, 2048, 128], strides=[1, 1, 1, 1], manual_normalization=0)
    T172 = fd.ops.cast(T123, dtype=DataType.Float)
    T178 = fd.ops.reshape(T4, new_shape=[1, 1, 2048, 128])
    T179 = fd.ops.cast(T139, dtype=DataType.Float)
    T180 = fd.ops.cast(T155, dtype=DataType.Float)
    T181 = fd.ops.cast(T171, dtype=DataType.Float)
    T182 = fd.ops.neg(T172)
    T188 = fd.ops.broadcast_in_dim(T178, shape=[1, 8, 2048, 128], broadcast_dims=[0, 1, 2, 3])
    S189 = fd.define_scalar(0, dtype=DataType.Int)
    T195 = fd.ops.full(shape=[1, 8, 2048, 0], fill_value=S189, dtype=DataType.BFloat16)
    T196 = fd.ops.neg(T179)
    T202 = fd.ops.broadcast_in_dim(T178, shape=[1, 32, 2048, 128], broadcast_dims=[0, 1, 2, 3])
    S203 = fd.define_scalar(0, dtype=DataType.Int)
    T209 = fd.ops.full(shape=[1, 32, 2048, 0], fill_value=S203, dtype=DataType.BFloat16)
    T210 = fd.ops.neg(T180)
    T211 = fd.ops.neg(T181)
    T212 = fd.ops.cast(T182, dtype=DataType.BFloat16)
    T213 = fd.ops.cast(T188, dtype=DataType.Float)
    S214 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T224 = fd.ops.pad(T195, [0, 128, 0, 0, 0, 0, 0, 0], S214)
    T225 = fd.ops.cast(T196, dtype=DataType.BFloat16)
    T226 = fd.ops.cast(T202, dtype=DataType.Float)
    S227 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T237 = fd.ops.pad(T209, [0, 128, 0, 0, 0, 0, 0, 0], S227)
    T253 = fd.ops.slice(T106, start_indices=[0, 0, 0, 0], end_indices=[1, 32, 2048, 64], strides=[1, 1, 1, 1], manual_normalization=0)
    T254 = fd.ops.cast(T210, dtype=DataType.BFloat16)
    T270 = fd.ops.slice(T107, start_indices=[0, 0, 0, 0], end_indices=[1, 8, 2048, 64], strides=[1, 1, 1, 1], manual_normalization=0)
    T271 = fd.ops.cast(T211, dtype=DataType.BFloat16)
    T287 = fd.ops.slice(T104, start_indices=[0, 0, 0, 64], end_indices=[1, 8, 2048, 128], strides=[1, 1, 1, 1], manual_normalization=0)
    S288 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T298 = fd.ops.pad(T212, [64, 0, 0, 0, 0, 0, 0, 0], S288)
    T299 = fd.ops.mul(T213, T60)
    T300 = fd.ops.cast(T224, dtype=DataType.Float)
    T316 = fd.ops.slice(T105, start_indices=[0, 0, 0, 64], end_indices=[1, 32, 2048, 128], strides=[1, 1, 1, 1], manual_normalization=0)
    S317 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T327 = fd.ops.pad(T225, [64, 0, 0, 0, 0, 0, 0, 0], S317)
    T328 = fd.ops.mul(T226, T62)
    T329 = fd.ops.cast(T237, dtype=DataType.Float)
    T330 = fd.ops.cat([T254, T253], dim=-1, manual_padding=0)
    T331 = fd.ops.cat([T271, T270], dim=-1, manual_padding=0)
    S332 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T342 = fd.ops.pad(T287, [0, 64, 0, 0, 0, 0, 0, 0], S332)
    T343 = fd.ops.cast(T298, dtype=DataType.Float)
    T344 = fd.ops.add(T300, T299)
    S345 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T355 = fd.ops.pad(T316, [0, 64, 0, 0, 0, 0, 0, 0], S345)
    T356 = fd.ops.cast(T327, dtype=DataType.Float)
    T357 = fd.ops.add(T329, T328)
    T358 = fd.ops.cast(T106, dtype=DataType.Float)
    T359 = fd.ops.cast(T107, dtype=DataType.Float)
    T360 = fd.ops.cast(T330, dtype=DataType.Float)
    T361 = fd.ops.cast(T331, dtype=DataType.Float)
    T362 = fd.ops.cast(T342, dtype=DataType.Float)
    T363 = fd.ops.add(T344, T343)
    T364 = fd.ops.cast(T355, dtype=DataType.Float)
    T365 = fd.ops.add(T357, T356)
    T366 = fd.ops.mul(T358, T62)
    T367 = fd.ops.mul(T359, T60)
    T368 = fd.ops.mul(T360, T62)
    T369 = fd.ops.mul(T361, T60)
    T370 = fd.ops.add(T363, T362)
    T371 = fd.ops.add(T365, T364)
    T372 = fd.ops.sum(T366, dims=[0, 1], keepdim=False, dtype=DataType.Null)
    T373 = fd.ops.sum(T367, dims=[0, 1], keepdim=False, dtype=DataType.Null)
    T374 = fd.ops.sum(T368, dims=[0, 1], keepdim=False, dtype=DataType.Null)
    T375 = fd.ops.sum(T369, dims=[0, 1], keepdim=False, dtype=DataType.Null)
    T376 = fd.ops.cast(T370, dtype=DataType.BFloat16)
    T377 = fd.ops.cast(T371, dtype=DataType.BFloat16)
    T378 = fd.ops.cast(T372, dtype=DataType.BFloat16)
    T379 = fd.ops.cast(T373, dtype=DataType.BFloat16)
    T380 = fd.ops.cast(T374, dtype=DataType.BFloat16)
    T381 = fd.ops.cast(T375, dtype=DataType.BFloat16)
    T382 = fd.ops.permute(T5, dims=[0, 2, 1, 3])
    T383 = fd.ops.permute(T376, dims=[0, 2, 1, 3])
    T384 = fd.ops.permute(T377, dims=[0, 2, 1, 3])
    T390 = fd.ops.broadcast_in_dim(T378, shape=[1, 1, 2048, 128], broadcast_dims=[2, 3])
    T396 = fd.ops.broadcast_in_dim(T379, shape=[1, 1, 2048, 128], broadcast_dims=[2, 3])
    T402 = fd.ops.broadcast_in_dim(T380, shape=[1, 1, 2048, 128], broadcast_dims=[2, 3])
    T408 = fd.ops.broadcast_in_dim(T381, shape=[1, 1, 2048, 128], broadcast_dims=[2, 3])
    T413 = fd.ops.reshape(T382, new_shape=[1, 2048, 1024])
    T418 = fd.ops.reshape(T383, new_shape=[1, 2048, 1024])
    T423 = fd.ops.reshape(T384, new_shape=[1, 2048, 4096])
    T428 = fd.ops.reshape(T390, new_shape=[1, 2048, 128])
    T433 = fd.ops.reshape(T396, new_shape=[1, 2048, 128])
    T438 = fd.ops.reshape(T402, new_shape=[1, 2048, 128])
    T443 = fd.ops.reshape(T408, new_shape=[1, 2048, 128])
    T444 = fd.ops.cat([T423, T418, T413], dim=-1, manual_padding=0)
    T445 = fd.ops.cast(T428, dtype=DataType.Float)
    T446 = fd.ops.cast(T433, dtype=DataType.Float)
    T447 = fd.ops.cast(T438, dtype=DataType.Float)
    T448 = fd.ops.cast(T443, dtype=DataType.Float)
    T452 = fd.ops.reshape(T444, new_shape=[2048, 6144])
    T453 = fd.ops.add(T446, T445)
    T454 = fd.ops.add(T448, T447)
    T458 = fd.ops.reshape(T6, new_shape=[2048, 4096])
    T462 = fd.ops.reshape(T7, new_shape=[2048, 4096])
    T466 = fd.ops.reshape(T8, new_shape=[2048, 14336])
    T470 = fd.ops.reshape(T9, new_shape=[2048, 4096])
    T471 = fd.ops.permute(T452, dims=[1, 0])
    T472 = fd.ops.cast(T453, dtype=DataType.BFloat16)
    T473 = fd.ops.cast(T454, dtype=DataType.BFloat16)
    fd.add_output(T473)
    fd.add_output(T472)
    fd.add_output(T452)
    fd.add_output(T471)
    fd.add_output(T470)
    fd.add_output(T466)
    fd.add_output(T462)
    fd.add_output(T458)

with FusionDefinition() as fd:
    nvfuser_fusion_id10(fd)

inputs = [
    torch.testing.make_tensor((1, 2048, 128), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((1, 8, 2048, 128), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((1, 32, 2048, 128), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((1, 2048, 6144), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((1, 2048, 128), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((1, 8, 2048, 128), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((1, 2048, 4096), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((1, 2048, 4096), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((1, 2048, 14336), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((1, 2048, 4096), dtype=torch.bfloat16, device='cuda:0'),
]
fd.execute(inputs)
```

### PR DESCRIPTION
**Pull request by naoyam**
Fix #4250

In the resize scheduler, the scheduling applied to the reference tensor is propagated to all the other tensors by a backward traversal from the reference loop domain over the exact graph. This means that the loop domains of the other tensors need to be reachable from the reference. 

The requirement does not hold when, for example, there's a reshape after the reference. See the added test for a concrete example. More generally, if the logical domain of a tensor is not reachable by just traversing backward from the reference logical domain, there must be something that should prevent the transform propagation. Note that since the resize scheduler does not allow no additional `Resize` ops between the ref and outputs, these additional ops between the ref and other tensors must come from reshapes and should be "cancelable", i.e., setting the loop domain as the producer of the reshaped logical domain. `prepareForBackwardTransformPropagation`, which is called just before propagating ref transformations, searches for those tensors that have additional transformations and make their loop domains look like the reference logical domain.

### CODE REVIEW

**Comment by naoyam** [comment]
!test --diff

File: csrc/scheduler/resize.cpp [hunk 1]
```diff
@@ -254,12 +326,12 @@ void ResizeScheduler::schedule(Fusion* fusion, const HeuristicParams* params) {
 
   scheduler_utils::clearMemorySpace(fusion);
 
-  auto ref_tv = getReferenceTensor(fusion);
-  NVF_ERROR(ref_tv != nullptr);
-
   scheduler_utils::cacheInputs(fusion, true);
   scheduler_utils::cacheAndForkOutputs(fusion, true);
 
+  auto ref_tv = getReferenceTensor(fusion);
```
Comment (naoyam) [inline csrc/scheduler/resize.cpp:332]: This change is not strictly required, but just to pick a reference from fusion outputs. `cacheAndForkOutputs` may change output tensors.

File: csrc/scheduler/resize.cpp [hunk 2]
```diff
@@ -419,6 +491,10 @@ void ResizeScheduler::schedule(Fusion* fusion, const HeuristicParams* params) {
   // [..., I0/bdimx/max_gdimx, max_gdimx(BIDx), bdimx(TIDx), vec_factor] or
   // [..., I0/bdimx(BIDx), bdimx(TIDx), vec_factor]
 
+  // Before propagating the reference transformations, make sure all
+  // tensors are ready to get transformations from the ref
+  prepareForBackwardTransformPropagation(ref_tv);
```
Comment (jjsjann123) [inline csrc/scheduler/resize.cpp:496]: > // This may not work if there's a tensor that is reshaped
  // from the reference tensor, but that should not be the case as the
  // reference is picked by the same routine used for the pointwise
  // scheduler.

nitpick, the comment in the new line 500 - 503 reads a bit strange in the context of this PR.
Sounds like it is indeed happening and we are patching that now. Should we remove that comment?

File: csrc/scheduler/resize.cpp [hunk 3]
```diff
@@ -245,6 +245,78 @@ std::unique_ptr<HeuristicParams> ResizeScheduler::computeHeuristics(
...
+  }
+
+  if (tvs_with_extra_transforms.empty()) {
+    return;
+  }
+
+  // Make their loop domains look like the ref so that loop
+  // transformations of the ref can be propagated
+  scheduler_tools::scheduleLoopDomainsLike(
+      tvs_with_extra_transforms, ref_tv->getLogicalDomain());
```
Comment (jjsjann123) [inline csrc/scheduler/resize.cpp:315]: Out of curiosity. How do we know it's a safe to overwrite the loop domain here?

i.e. if the overwrite loop domain from ref_tv is *smaller* than the actual tv, we are effectively applying a false predicate here, which might lead to silent wrong results?

I'm assuming the resize scheduler has a check somewhere that ensures the coverage from ref to outputs?

Comment (naoyam) [reply csrc/scheduler/resize.cpp:315]: That's a good question. Since this is only for pointwise ops with no reduction, as long as the loop domain of the reference tensor is kept intact, all tensors should be also covered. If not, that seems to indicate the reference is not really a right reference. We found a couple of issues with finding right references, but as far as I can see, a reference tensor chosen by the current logic should guarantee all other tensors can be transformed to the same shape as the reference without losing any dimension.

That won't be the case with reductions, so that's one big difference when we extend this scheduling scheme to handle reductions.

**Comment by naoyam** [comment]
!test

File: csrc/scheduler/resize.cpp (hunk 3 above)
Comment (jjsjann123) [reply csrc/scheduler/resize.cpp:315]: nitpick: I wonder if we should add a check looking for reduction op and the reasoning as a comment in this function?
Not pushing strongly for that though.

**Review by jjsjann123 — APPROVED** [review]
LGTM

File: csrc/scheduler/resize.cpp (hunk 3 above)
Comment (naoyam) [reply csrc/scheduler/resize.cpp:315]: Thanks for the suggestion. Added a comment (not here, but the first place where potentially shrinking propagations happen).

**Comment by naoyam** [comment]
!build
