### PR TITLE
Preserve definition of IDs mutated because of mutated extents

### LINKED ISSUE #2671: why consumer's logical domain doesn't equal producer's logical domain after fusion concretization
Given the following fusion, save it as `bug.py`
```
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id0(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[-1], contiguity=[True], dtype=DataType.Half, is_cpu=False)
    T1 = fd.define_tensor(shape=[-1], contiguity=[True], dtype=DataType.Half, is_cpu=False)
    S2 = fd.define_scalar(32, dtype=DataType.Int)
    S3 = fd.ops.size(T0, dim=0)
    S4 = fd.ops.div(S3, S2)
    V5 = fd.define_vector([S2, S4], dtype=DataType.Int)
    T6 = fd.ops.reshape(T0, new_shape=V5)
    T7 = fd.ops.cast(T6, dtype=DataType.Float)
    T7 = fd.ops.segment_set(T7)
    T9 = fd.ops.reshape(T1, new_shape=V5)
    T10 = fd.ops.cast(T9, dtype=DataType.Float)
    T11 = fd.ops.mul(T7, T10)
    fd.add_output(T11)

with FusionDefinition() as fd:
    nvfuser_fusion_id0(fd)

inputs = [
    torch.randn((128,), dtype=torch.half, device='cuda:0').as_strided((128,), (1,)),
    torch.randn((128,), dtype=torch.half, device='cuda:0').as_strided((128,), (1,)),
]

fd.execute(inputs)

```
using the current main branch and run with `NVFUSER_DISABLE=parallel_compile NVFUSER_DUMP=fusion_ir_preseg,segmented_fusion,pre_segmenter_logging,fusion_ir_concretized python bug.py  2>&1 |tee bug.log`
The concretized Fusion is:
```
%kernel {
T8_l[ iS18{32}rf, iS19{( ceilDiv(i0, 32) )}rf ] = view( T0_g[ iS0{i0} ] )
T3_l[ iS25{32}, iS26{( ceilDiv(i2, 32) )} ]
   = __half2float(T8_l[ iS18{32}rf, iS19{( ceilDiv(i0, 32) )}rf ]);
T4_l[ iS28{32}, iS29{( ceilDiv(i2, 32) )} ]
   = SegmenterSet( T3_l[ iS25{32}, iS26{( ceilDiv(i2, 32) )} ] )
T9_l[ iS22{32}rf, iS23{( ceilDiv(i2, 32) )}rf ] = view( T1_g[ iS1{i2} ] )
T6_l[ iS31{32}, iS32{( ceilDiv(i2, 32) )} ]
   = __half2float(T9_l[ iS22{32}rf, iS23{( ceilDiv(i2, 32) )}rf ]);
T7_g[ iS34{32}, iS35{( ceilDiv(i2, 32) )} ]
   = T4_l[ iS28{32}, iS29{( ceilDiv(i2, 32) )} ]
   * T6_l[ iS31{32}, iS32{( ceilDiv(i2, 32) )} ];
```

**Why T3's logical domain has `iS26{( ceilDiv(i2, 32) )}` instead of `iS26{( ceilDiv(i0, 32) )}` since its producer's locial domain has `iS19{( ceilDiv(i0, 32) )}rf`, `i0` is somehow changed to `i2`?**
 
```
T8_l[ iS18{32}rf, iS19{( ceilDiv(i0, 32) )}rf ]
 root domain : (iS17{i0}rf)
  Outer split: iS17{i0}rf by factor 32 -> iS18{32}rf, iS19{( ceilDiv(i0, 32) )}rf
 logical domain : (iS18{32}rf, iS19{( ceilDiv(i0, 32) )}rf)
 contiguity: t t
 loop domain : (iS18{32}rf, iS19{( ceilDiv(i0, 32) )}rf)
T3_l[ iS25{32}, iS26{( ceilDiv(i2, 32) )} ]
 logical domain : (iS25{32}, iS26{( ceilDiv(i2, 32) )})
 contiguity: t t
 loop domain : (iS25{32}, iS26{( ceilDiv(i2, 32) )})
```

**It finally leads to the following error:**
```
RuntimeError: std::all_of( dom1.begin(), dom1.end(), [&](auto id) { return id->getIterType() == IterType::Symbolic || frontier.count(id); }) INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/ir/utils.cpp":894, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. dom0 and dom1 are not equal. dom0: iS22{32}rf, iS109{( (( (( getMetaData(T4) )).logical_size ))[1] )}rf. dom1: iS108{( (( (( getMetaData(T1) )).logical_size ))[0] )}rf
Exception raised from validateDomainEquivalence at /opt/pytorch/nvfuser/csrc/ir/utils.cpp:894 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf3 (0x7fb00e8575b3 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #1: nvfuser::nvfErrorFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x53 (0x7fb00ebb29e3 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #2: nvfuser::ir_utils::validateDomainEquivalence
```

### PR DESCRIPTION
**Pull request by jacobhinkle**
In #2671, the replaceSymbolicSizes lowering pass calls ir_utils::replaceValue with a seemingly benign list of scalar Val replacements. However, an error is encountered because in replacing IterDomains whose extents should be replaced, we wind up erasing the definition of a Split output. We should instead preserve these definitions and just replace the output of that expression.

Fixes #2671

### CODE REVIEW

**Comment by jacobhinkle** [comment]
!build

**Comment by jacobhinkle** [comment]
See #2711 for the binary test failure (unrelated); thunder failure is also unrelated.

File: tests/cpp/test_gpu_view.cpp [hunk 1]
```diff
@@ -2761,4 +2761,35 @@ TEST_F(GpuViewTest, FusionMismatchingReshape) {
   testValidate(&fusion, cg_outputs, {t0}, __LINE__, __FILE__);
 }
 
+// Test that replacement of a scalar in a reshaped ID that is a product of a
+// split gets replaced properly
```
Comment (naoyam) [inline tests/cpp/test_gpu_view.cpp:2765]: Can you please add more details about where the problem occurs and how it could manifest if not fixed? Is it also possible to do more explicit validation of the fix?

**Comment by naoyam** [comment]
The fix makes sense. Please run all the tests and benchmarks just in case.

File: csrc/mutator.cpp [hunk 2]
```diff
@@ -98,14 +98,25 @@ void OptOutMutator::mutate(IterDomain* id) {
...
+  // This guarantees we replace id in all downstream expressions
+  registerMutation(id, new_id);
+
+  // Preserve definition if it exists in id. This is important since otherwise
+  // we might disconnect the root to logical transform path. For example if id
+  // is one output of a Split operation and the other output is unmodified,
+  // then we must avoid replacing only one of the outputs with a new IterDomain
+  // with no definition. See https://github.com/NVIDIA/Fuser/issues/2671 for an
+  // example of this happening.
+  if (Expr* def = id->definition()) {
```
Comment (liqiangxl) [inline csrc/mutator.cpp:117]: More specific comments:
`T1.size(0) / 32` in `Outer split: T1.size(0) by factor 32 -> 32, T1.size(0) / 32` is replaced to `T4.size(1)`

File: tests/cpp/test_gpu_view.cpp [hunk 3]
```diff
@@ -2761,4 +2761,35 @@ TEST_F(GpuViewTest, FusionMismatchingReshape) {
...
+// See https://github.com/NVIDIA/Fuser/issues/2671
+TEST_F(NVFuserTest, ReplacedScalarInSplitOutput) {
```
Comment (liqiangxl) [inline tests/cpp/test_gpu_view.cpp:2767]: change to `GpuViewTest` or move to a different test file.

**Review by liqiangxl — APPROVED** [review]
LGTM. Thanks for the fix.

File: tests/cpp/test_gpu_view.cpp (hunk 1 above)
Comment (jacobhinkle) [reply tests/cpp/test_gpu_view.cpp]: I expanded this comment and also added a test where I explicitly do the replacement and check that it works as expected. I kept this original test since it is the repro for the bug.

**Comment by jacobhinkle** [comment]
!build --diff-bench

**Comment by jacobhinkle** [comment]
I believe the codediffs are false alarms, but I'll wait to merge until I can confirm that.

**Comment by jacobhinkle** [comment]
!build --diff-bench

**Comment by jacobhinkle** [comment]
Failures are unrelated, and no code diffs. Merging.
