### PR TITLE
Fix #3607

### LINKED ISSUE #3607: INTERNAL_ASSERT: Unable to find mapped root/logical domain
While working on https://github.com/Lightning-AI/lightning-thunder/pull/1560 the randomness tests seem to fail with the following repro.

```python
# CUDA devices:
#  0: NVIDIA GeForce RTX 3090
#  1: NVIDIA GeForce RTX 3090
# torch version: 2.6.0a0+gitc418a9a
# cuda version: 12.5
# nvfuser version: 0.2.23+git911d7bf
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id24(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[2, 24000], contiguity=[None, None], dtype=DataType.Double, is_cpu=False, stride_order=[1, 0])
    S1 = fd.define_scalar(None, dtype=DataType.Int)
    S2 = fd.define_scalar(None, dtype=DataType.Int)
    T3 = fd.define_tensor(shape=[24000], contiguity=[True], dtype=DataType.Double, is_cpu=False, stride_order=[0])
    T4 = fd.define_tensor(shape=[2, 24000], contiguity=[True, True], dtype=DataType.Double, is_cpu=False, stride_order=[1, 0])
    T5 = fd.define_tensor(shape=[2, 24000], contiguity=[True, True], dtype=DataType.Double, is_cpu=False, stride_order=[1, 0])
    S6 = fd.define_scalar(1.00000, dtype=DataType.Double)
    T7 = fd.ops.mul(S6, T0)
    S8 = fd.define_scalar(2.00000, dtype=DataType.Double)
    T9 = fd.ops.mul(S8, T7)
    S10 = fd.define_scalar(0.00000, dtype=DataType.Double)
    S11 = fd.define_scalar(1.00000, dtype=DataType.Double)
    S12 = fd.define_scalar(2, dtype=DataType.Int)
    S13 = fd.define_scalar(24000, dtype=DataType.Int)
    T15 = fd.ops.uniform(S10, S11, shape=[S12, S13], rng_seed=S2, rng_offset=S1, dtype=DataType.Double)
    S16 = fd.define_scalar(0.500000, dtype=DataType.Double)
    T17 = fd.ops.lt(T15, S16)
    T18 = fd.ops.cast(T17, dtype=DataType.Double)
    T19 = fd.ops.mul(T18, T9)
    T20 = fd.ops.sum(T19, dims=[0], keepdim=False, dtype=DataType.Null)
    T24 = fd.ops.broadcast_in_dim(T3, shape=[2, 24000], broadcast_dims=[1])
    T25 = fd.ops.mul(T24, T19)
    T26, T27 = fd.ops.var_mean(T4, dims=[1], correction=0, keepdim=False)
    T31 = fd.ops.broadcast_in_dim(T27, shape=[2, 1], broadcast_dims=[0])
    T35 = fd.ops.broadcast_in_dim(T31, shape=[2, 24000], broadcast_dims=[0, 1])
    T36 = fd.ops.sub(T4, T35)
    T40 = fd.ops.broadcast_in_dim(T26, shape=[2, 1], broadcast_dims=[0])
    S41 = fd.define_scalar(1.00000e-05, dtype=DataType.Double)
    T42 = fd.ops.add(T40, S41)
    T43 = fd.ops.rsqrt(T42)
    T47 = fd.ops.broadcast_in_dim(T43, shape=[2, 24000], broadcast_dims=[0, 1])
    T48 = fd.ops.mul(T36, T47)
    T49 = fd.ops.mul(T48, T19)
    T50 = fd.ops.sum(T49, dims=[0], keepdim=False, dtype=DataType.Null)
    T51 = fd.ops.mul(T47, T25)
    T52 = fd.ops.mul(T36, T25)
    T53 = fd.ops.sum(T52, dims=[1], keepdim=False, dtype=DataType.Null)
    T57 = fd.ops.broadcast_in_dim(T53, shape=[2, 1], broadcast_dims=[0])
    T58 = fd.ops.neg(T51)
    T59 = fd.ops.sum(T58, dims=[1], keepdim=False, dtype=DataType.Null)
    T63 = fd.ops.broadcast_in_dim(T59, shape=[2, 1], broadcast_dims=[0])
    S64 = fd.define_scalar(-0.500000, dtype=DataType.Double)
    T65 = fd.ops.mul(S64, T57)
    S66 = fd.define_scalar(3.00000, dtype=DataType.Double)
    T67 = fd.ops.pow(T43, S66)
    T68 = fd.ops.mul(T65, T67)
    T69 = fd.ops.sum(T63, dims=[1], keepdim=False, dtype=DataType.Null)
    T70 = fd.ops.sum(T68, dims=[1], keepdim=False, dtype=DataType.Null)
    T74 = fd.ops.broadcast_in_dim(T69, shape=[2, 1], broadcast_dims=[0])
    T78 = fd.ops.broadcast_in_dim(T74, shape=[2, 24000], broadcast_dims=[0, 1])
    S79 = fd.define_scalar(4.16667e-05, dtype=DataType.Double)
    T80 = fd.ops.mul(S79, T78)
    T84 = fd.ops.broadcast_in_dim(T70, shape=[2, 1], broadcast_dims=[0])
    T88 = fd.ops.broadcast_in_dim(T84, shape=[2, 24000], broadcast_dims=[0, 1])
    S89 = fd.define_scalar(2.00000, dtype=DataType.Double)
    T90 = fd.ops.mul(S89, T88)
    T91 = fd.ops.mul(T90, T36)
    S92 = fd.define_scalar(24000.0, dtype=DataType.Double)
    S93 = fd.ops.reciprocal(S92)
    T94 = fd.ops.mul(T91, S93)
    T95 = fd.ops.add(T80, T94)
    T96 = fd.ops.add(T51, T95)
    S97 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T98 = fd.ops.gt(T5, S97)
    S99 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T100 = fd.ops.where(T98, T96, S99)
    fd.add_output(T20)
    fd.add_output(T50)
    fd.add_output(T100)

with FusionDefinition() as fd:
    nvfuser_fusion_id24(fd)

inputs = [
    torch.randn(1, dtype=torch.float64, device='cuda:0').as_strided((2, 24000), (0, 0)),
    1,
    20,
    torch.testing.make_tensor((24000,), dtype=torch.float64, device='cuda:0'),
    torch.testing.make_tensor((2, 24000), dtype=torch.float64, device='cuda:0'),
    torch.testing.make_tensor((2, 24000), dtype=torch.float64, device='cuda:0'),
]
fd.execute(inputs)
```

Traceback:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/nvfuser/__init__.py", line 238, in execute
    results = self._execute(
              ^^^^^^^^^^^^^^
RuntimeError:  INTERNAL ASSERT FAILED at "/home/tv/data/firma/grid/thunder/Fuser/csrc/scheduler/utils.cpp":1476, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Unable to find mapped root/logical domain
Exception raised from propagateSibling at /home/tv/data/firma/grid/thunder/Fuser/csrc/scheduler/utils.cpp:1476 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xca (0x7f1841b1853a in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #1: nvfuser::nvfErrorFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x3e (0x7f1841ea6b4e in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #2: <unknown function> + 0x888bb8 (0x7f1842288bb8 in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #3: nvfuser::MaxInfoSpanningTree::traverse(nvfuser::MaxInfoSpanningTree::Propagator*) + 0x5a (0x7f184226da6a in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x890cff (0x7f1842290cff in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x875fae (0x7f1842275fae in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x879e49 (0x7f1842279e49 in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #7: <unknown function> + 0x87a962 (0x7f184227a962 in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #8: <unknown function> + 0x851760 (0x7f1842251760 in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #9: <unknown function> + 0x516635 (0x7f1841f16635 in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #10: <unknown function> + 0x5256bb (0x7f1841f256bb in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #11: <unknown function> + 0x526d29 (0x7f1841f26d29 in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #12: <unknown function> + 0x51de1e (0x7f1841f1de1e in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #13: nvfuser::SegmentCandidateFinder::SegmentCandidateFinder(std::unique_ptr<nvfuser::Fusion, std::default_delete<nvfuser::Fusion> >, nvfuser::KernelArgumentHolder const*, nvfuser::SegmentCandidateFinderOptions) + 0x3e2 (0x7f1841f1e5f2 in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #14: <unknown function> + 0x51e755 (0x7f1841f1e755 in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #15: <unknown function> + 0x51eb1c (0x7f1841f1eb1c in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #16: <unknown function> + 0x7bc6f8 (0x7f18421bc6f8 in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #17: <unknown function> + 0x7b2de7 (0x7f18421b2de7 in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #18: nvfuser::FusionExecutorCache::runFusionWithInputs(c10::ArrayRef<c10::IValue> const&, std::optional<nvfuser::PrimDataType>, std::optional<signed char>) + 0x9a (0x7f18421b385a in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #19: nvfuser::python_frontend::FusionDefinition::execute(c10::ArrayRef<c10::IValue> const&, std::optional<signed char>, bool, bool, bool, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >) const + 0xbb2 (0x7f1842346562 in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #20: <unknown function> + 0x1782ee (0x7f1841b782ee in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #21: <unknown function> + 0x238d0b (0x7f1841c38d0b in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #22: <unknown function> + 0x28a62c (0x7f1841c8a62c in /usr/local/lib/python3.12/dist-packages/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #23: /usr/bin/python3() [0x57b5ce]
frame #24: _PyObject_MakeTpCall + 0x123 (0x543f83 in /usr/bin/python3)
frame #25: _PyEval_EvalFrameDefault + 0x82c (0x5cfafc in /usr/bin/python3)
frame #26: /usr/bin/python3() [0x547527]
frame #27: PyObject_Call + 0x119 (0x545dc9 in /usr/bin/python3)
frame #28: _PyEval_EvalFrameDefault + 0x4204 (0x5d34d4 in /usr/bin/python3)
frame #29: _PyObject_Call_Prepend + 0xc2 (0x5454e2 in /usr/bin/python3)
frame #30: /usr/bin/python3() [0x59d434]
frame #31: _PyObject_MakeTpCall + 0x6f (0x543ecf in /usr/bin/python3)
frame #32: _PyEval_EvalFrameDefault + 0x82c (0x5cfafc in /usr/bin/python3)
frame #33: /usr/bin/python3() [0x547466]
frame #34: torch::autograd::PyNode::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x7e (0x7f18dd12f25e in /usr/local/lib/python3.12/dist-packages/torch/lib/libtorch_python.so)
frame #35: <unknown function> + 0x4e0bbab (0x7f18d440bbab in /usr/local/lib/python3.12/dist-packages/torch/lib/libtorch_cpu.so)
frame #36: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&, std::shared_ptr<torch::autograd::ReadyQueue> const&) + 0xde2 (0x7f18d4406c32 in /usr/local/lib/python3.12/dist-packages/torch/lib/libtorch_cpu.so)
frame #37: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&) + 0x4cf (0x7f18d4407abf in /usr/local/lib/python3.12/dist-packages/torch/lib/libtorch_cpu.so)
frame #38: torch::autograd::Engine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x32a (0x7f18d44000ea in /usr/local/lib/python3.12/dist-packages/torch/lib/libtorch_cpu.so)
frame #39: torch::autograd::python::PythonEngine::thread_init(int, std::shared_ptr<torch::autograd::ReadyQueue> const&, bool) + 0x62 (0x7f18dd129e42 in /usr/local/lib/python3.12/dist-packages/torch/lib/libtorch_python.so)
frame #40: <unknown function> + 0xe0ea4 (0x7f18ddee0ea4 in /lib/x86_64-linux-gnu/libstdc++.so.6)
frame #41: <unknown function> + 0x89dab (0x7f18e82e9dab in /lib/x86_64-linux-gnu/libc.so.6)
frame #42: <unknown function> + 0x10b9f8 (0x7f18e836b9f8 in /lib/x86_64-linux-gnu/libc.so.6)
```

### PR DESCRIPTION
**Pull request by naoyam**
Fixes #3607.

In the fusion reported in #3607, there's a proposed fusion segment as shown below:

```
**Segmenter** Considering fusion:
T14_g_double[iS27{2}, rS28{24000}](Avg),
T15_l_double[iS29{2}, rS30{24000}](Var),
T16_l_nvfuser_index_t[iS31{2}, rS32{24000}](Count)
 = Welford ( T2_g_double[iS3{2}, iS4{24000}](Avg),
  allreduce = false )
d59 = (double)(24000);
d61 = double(1) * d59;
d65 = (double)(0);
d67 = d61 - d65;
d69 = (double)(0);
b71 = d67 >= d69;
d73 = (double)(0);
d75 = where(b71, d67, d73);
d80 = reciprocal(d75);
T17_l_double[iS33{2}]
   = T15_l_double[iS29{2}, rS30{24000}]
   * d80;
T23_l_double[iS44{2}, bS45{1}]
   = broadcast( T17_l_double[iS33{2}] )
T25_l_double[iS48{2}, bS49{1}]
   = T23_l_double[iS44{2}, bS45{1}]
   + double(1.0000000000000001e-05);
T26_g_double[iS50{2}, bS51{1}]
   = rsqrt(T25_l_double[iS48{2}, bS49{1}]);
T27_l_double[iS52{2}, bS53{1}]
   = Set( T26_g_double[iS50{2}, bS51{1}], cache_op=Streaming )
T28_g_double[iS54{2}, bS55{1 ex 24000}] = expand( T27_l_double[iS52{2}, bS53{1}], {2, 24000} )
T32_g_double[iS62{2}, iS63{24000}]
   = T28_g_double[iS54{2}, bS55{1 ex 24000}]
   * T13_g_double[iS25{2}, iS26{24000}];
T37_l_double[iS72{2}, iS73{24000}]
   = -T32_g_double[iS62{2}, iS63{24000}];
T38_g_double[iS74{2}, rS75{24000}]
   = reduction( T37_l_double[iS72{2}, iS73{24000}], op = add, initial value = double(0), allreduce = false )
```

When `canScheduleCompileTime` of the transpose scheduler is called, `FindAllMappedDims` is used with `T32` as the reference. Since its innermost dimension is not connected with `T15` due to the reduction, `propagateSibling` hits the assertion at https://github.com/NVIDIA/Fuser/blob/main/csrc/scheduler/utils.cpp#L1476.

This PR avoids the assertion by checking the existence of reduction first. We may also want to remove the assertion.

### CODE REVIEW

**Comment by naoyam** [comment]
!test

File: csrc/scheduler/transpose.cpp [hunk 1]
```diff
@@ -87,6 +81,12 @@ bool TransposeScheduler::canScheduleCompileTime(Fusion* fusion) {
     return false;
   }
 
+  if (!hasAtLeastTwoValidGroups(fusion)) {
```
Comment (naoyam) [inline csrc/scheduler/transpose.cpp:84]: I moved this here because because it uses `getInputsOutputsWithInnerDim`, which uses `FindAllMappedDims`, which asserts the existence of mappings between sibling tensors.

https://github.com/NVIDIA/Fuser/blob/main/csrc/scheduler/utils.cpp#L1476

I'm not entirely sure why we should have an assertion there. If the `from` tensor has a mapping to `nullptr`, which is not asserted, but propagating that to a sibling is asserted. I think we can just remove the assertion, but not 100% sure.

Instead, we shouldn't do this level of analysis until the fusion is confirmed to consist of only pointwise ops with no reduction. This should avoid the issue and also would help reduce the segmentation cost.

**Review by zasdfgbnm — APPROVED** [review]

**Comment by t-vi** [comment]
Thank you for this, @naoyam ! 
I can confirm that this unblock https://github.com/Lightning-AI/lightning-thunder/pull/1560 .
