### PR TITLE
Fix a bug in logical mapping

### LINKED ISSUE #4729: [multi-gpu] INTERNAL ASSERT FAILED: Can not find a scheduler to schedule fusion segment
Repro
```python
# torchrun --local-ranks-filter=0 --nnodes 1 --nproc-per-node 2 test_nvfuser_fd_direct.py
import torch.nn as nn
import torch
from torch.distributed._tensor import DeviceMesh, Shard, distribute_tensor
from torch.distributed.tensor.placement_types import Placement, Shard, Replicate
import os
import torch.distributed as dist

import torch.distributed as dist
from collections.abc import Iterable
from torch.distributed.tensor import DTensor
from torch.distributed.tensor.placement_types import Placement, Shard, Replicate
from typing import Callable, cast, TypeAlias

import torch
from dataclasses import dataclass
from functools import partial
from torch.distributed.tensor import DTensor
from functools import lru_cache
from enum import auto, Enum

import nvfuser_direct as nvfd
from nvfuser_direct import FusionDefinition as DirectFusionDefinition
from nvfuser_direct import DataType


LOCAL_RANK = int(os.environ["LOCAL_RANK"])

device = torch.device("cuda", LOCAL_RANK)
torch.cuda.set_device(device)
num_devices = 2
mesh = DeviceMesh("cuda", list(range(num_devices)))

hidden_size = 16

class FusionDefinitionWrapper:
    def __init__(self, define_fusion: Callable[[DirectFusionDefinition], None]):
        """Wraps a function that defines a fusion without `multidevice_schedule`."""
        # The complete FusionDefinition (w/ multidevice_scheduler) will have to
        # be created at "call" time according to the input DTensors.
        self._define_fusion = define_fusion

    def _create_fusion_definition(
        self, in_dtensors: Iterable[DTensor]
    ) -> DirectFusionDefinition:
        def multidevice_schedule(fd: DirectFusionDefinition, in_dtensors: list[DTensor]) -> None:
            for in_tv, in_dtensor in zip(fd.fusion.inputs(), in_dtensors):
                assert isinstance(in_dtensor, DTensor)
                # Set the device mesh.
                assert (
                    in_dtensor.device_mesh.ndim == 1
                ), "nvFuser's Python API only supports 1D meshes."
                mesh = nvfd.multidevice.DeviceMesh(in_dtensor.device_mesh.mesh.tolist())

                in_tv.set_device_mesh(mesh)

                assert len(in_dtensor.placements) == 1, "Expect a 1D mesh"

                # Split and parallelize.
                # When the mesh is multi-dimensional, iterate through the
                # placements in descending order of Placement.dim.
                placement: Placement = in_dtensor.placements[0]
                if placement.is_shard():
                    dim = cast(Shard, placement).dim
                    in_tv.split(dim, mesh.size, inner_split=False)
                    in_tv.axis(dim).parallelize(nvfd.ParallelType.mesh_x)
                    in_tv.set_allocation_domain(in_tv.get_loop_domain(), new_contiguity=True)

        with DirectFusionDefinition() as fd:
            self._define_fusion(fd)
            multidevice_schedule(fd, in_dtensors)
        return fd

    def __call__(self, in_dtensors: Iterable[DTensor]) -> list[DTensor]:
        fusion_def = self._create_fusion_definition(in_dtensors)
        out_dtensors = nvfd.dtensor_execute(fusion_def, in_dtensors)
        return out_dtensors

def define_forward(fd: DirectFusionDefinition) -> None:
    tv0 = fd.define_tensor(shape=[1, 1, 16384], contiguity=[None, None, True], dtype=DataType.BFloat16, is_cpu=False)
    tv1 = fd.define_tensor(shape=[1, 1, 16384], contiguity=[None, None, True], dtype=DataType.BFloat16, is_cpu=False)
    tv2 = fd.define_tensor(shape=[5120, 16384], contiguity=[True, True], dtype=DataType.BFloat16, is_cpu=False)
    tv3 = fd.ops.cast(tv0, dtype=DataType.Float)
    tv4 = fd.ops.cast(tv1, dtype=DataType.Float)
    tv5 = fd.ops.mul(tv3, tv4)
    tv6 = fd.ops.cast(tv5, dtype=DataType.BFloat16)
    tv7 = fd.ops.linear(tv6, tv2)
    fd.add_output(tv7)

fd = FusionDefinitionWrapper(define_forward)

x = distribute_tensor(torch.randn(1, 1, 16384, device="cuda", dtype=torch.bfloat16), mesh, [Shard(2),])
y = distribute_tensor(torch.randn(1, 1, 16384, device="cuda", dtype=torch.bfloat16), mesh, [Shard(2),])
w = distribute_tensor(torch.randn(5120, 16384, device="cuda", dtype=torch.bfloat16), mesh, [Shard(1),])

def fn(x, y, w):
    return torch.nn.functional.linear(x * y, w)

expected = fn(x, y, w)

result = fd([x, y, w])

torch.testing.assert_close(result[0], expected)

```

Repro
```python
[rank0]: Traceback (most recent call last):
[rank0]:   File "/opt/pytorch/lightning-thunder/test_nvfuser_fd_direct.py", line 101, in <module>
[rank0]:     result = fd([x, y, w])
[rank0]:              ^^^^^^^^^^^^^
[rank0]:   File "/opt/pytorch/lightning-thunder/test_nvfuser_fd_direct.py", line 76, in __call__
[rank0]:     out_dtensors = nvfd.dtensor_execute(fusion_def, in_dtensors)
[rank0]:                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/pytorch/nvfuser/python/nvfuser_direct/__init__.py", line 48, in dtensor_execute
[rank0]:     out_tensors, out_shardings = fd.multigpu_execute(inputs)
[rank0]:                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/pytorch/nvfuser/python/nvfuser_direct/__init__.py", line 255, in multigpu_execute
[rank0]:     out_tensors = self.execute(inputs, auto_schedule=True)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/opt/pytorch/nvfuser/python/nvfuser_direct/__init__.py", line 235, in execute
[rank0]:     return self.fec.execute(inputs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError:  INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/fusion_segmenter.cpp":4058, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Can not find a scheduler to schedule fusion segment
```

### PR DESCRIPTION
**Pull request by wujingyue**
Fixes #4729

### CODE REVIEW

File: csrc/logical_domain_map.cpp [hunk 1]
```diff
@@ -272,27 +270,27 @@ std::unordered_map<IterDomain*, IterDomain*> PairwiseLogicalDomainMap::map(
...
       NVF_THROW("Producer did not match any LinearOp input.")
     }
 
-    bool k_bcast = op->inA()->as<TensorView>()->axis(-1)->isBroadcast();
     // LinearOp:
     // inputs (0) = {*, in_features}
     // weight (1) = {out_features, in_features} / {in_features}
     // bias (2) = {out_features} / {}
     // output = {*, out_features} / {*}
+    const bool k_bcast = op->inA()->getLogicalDomain().back()->isBroadcast();
```
Comment (wujingyue) [inline csrc/logical_domain_map.cpp:293]: This is the one-line fix. Other changes are cosmetic.

File: csrc/preseg_passes/propagate_shardings.cpp [hunk 2]
```diff
@@ -323,15 +323,7 @@ void PropagateShardingsPass::runPass(Fusion* fusion) {
     // Note: Tvs without a mesh are assumed to have no manual sharding
     // annotation and are sharded like the first producer Tv.
     const auto& outputs_without_mesh = getOutputsWithoutMesh(expr);
-    if (outputs_without_mesh.empty()) {
```
Comment (wujingyue) [inline csrc/preseg_passes/propagate_shardings.cpp]: Personal style again. I tend to remove `if`s aggressively.

**Comment by wujingyue** [comment]
!test

**Comment by wujingyue** [comment]
!test
