### PR TITLE
Fix incorrect DataType in allocGlobalBufferForGridComm

### LINKED ISSUE #2634: Cannot create an iter domain over an extent that is not an nvfuser_index_t but received int64_t
The following program crashes with the error message:

```
Traceback (most recent call last):
  File "/home/tfogal/env/lib/python3.10/site-packages/nvfuser/__init__.py", line 145, in execute
    result = self._execute(
RuntimeError: extent->dtype() == DataType::Index INTERNAL ASSERT FAILED at "/tmp/pip-req-build-fk_mwug5/csrc/ir/nodes.cpp":2408, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Cannot create an iter domain over an extent that is not an nvfuser_index_t but received int64_t .
Exception raised from IterDomain at /tmp/pip-req-build-fk_mwug5/csrc/ir/nodes.cpp:2408 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xf3 (0x7dad02992f9b in /home/tfogal/env/lib/python3.10/site-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #1: nvfuser::nvfErrorFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x53 (0x7dad02ce1473 in /home/tfogal/env/lib/python3.10/site-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #2: nvfuser::IterDomain::IterDomain(nvfuser::IrBuilderPasskey, nvfuser::Val*, nvfuser::Val*, nvfuser::Val*, nvfuser::Val*, nvfuser::ParallelType, nvfuser::IterType, bool, bool, std::optional<long>, bool) + 0x603 (0x7dad02e9ab33 in /home/tfogal/env/lib/python3.10/site-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
frame #3: nvfuser::IterDomain::IterDomain(nvfuser::IrBuilderPasskey, nvfuser::IterDomainBuilder const&) + 0x39 (0x7dad02e9ad89 in /home/tfogal/env/lib/python3.10/site-packages/nvfuser/_C.cpython-310-x86_64-linux-gnu.so)
```

This is with the environment variable `NVFUSER_DISABLE=parallel_compile` set.

# Program

The program is a particular fusion from a customer model.

```python
import torch
from nvfuser import FusionDefinition, DataType
def a(FusionDefinition) :
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    c = b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    d = b.define_scalar(DataType.Int)
    b.define_scalar(DataType.Int)
    b.define_tensor([], [], DataType.Half, stride_order=[3, 2, 1, 0])
    b.define_tensor([], stride_order=[0])
    aa = b.define_tensor([], stride_order=[0])
    b.define_tensor([-1, -1, -1, -1], [], DataType.Half)
    b.define_tensor([-1, -1, -1, -1], [], DataType.Half)
    b.define_tensor([-1, -1, -1, -1], [], DataType.Half)
    b.define_tensor([-1, -1, -1, -1], [], DataType.Half)
    b.define_tensor([], [], DataType.Half, stride_order=[3, 2, 1, 0])
    b.define_tensor([], stride_order=[0])
    b.define_tensor([], stride_order=[0])
    b.define_tensor([-1, -1, -1, -1], [], DataType.Half)
    b.define_tensor([-1, -1, -1, -1], [], DataType.Half)
    e = b.define_tensor([-1, -1, -1, -1], [], DataType.Half)
    b.define_tensor([], [], DataType.Half, stride_order=[3, 2, 1, 0])
    b.define_tensor([], stride_order=[0])
    f = b.define_tensor([], stride_order=[0])
    b.define_tensor([], [], DataType.Half, stride_order=[3, 2, 1, 0])
    b.define_tensor([], stride_order=[0])
    b.define_tensor([], stride_order=[0])
    g = b.define_tensor([], [], DataType.Half, stride_order=[0])
    h = b.define_tensor([], [], DataType.Half, stride_order=[0])
    b.define_tensor([], [], DataType.Half, stride_order=[0])
    b.define_tensor([], [], DataType.Half, stride_order=[0])
    b.define_tensor([], [], DataType.Half, stride_order=[0])
    b.define_tensor([], [], DataType.Half, stride_order=[0])
    b.define_tensor([], [], DataType.Half, stride_order=[0])
    b.define_tensor([], [], DataType.Half, stride_order=[0])
    i = 1
    ac = 96
    j = m = 1
    k = i, ac, j, m
    l = b.ops.reshape(aa, k)
    n = t = b.define_scalar(96)
    ab = ad = 320
    ae = t, d, ab, ad
    ag = b.ops.broadcast_in_dim(l, ae, [0, 1, 2, 3])
    af = b.ops.mul(n, ag)
    ah = b.ops.cast(h, DataType.Float)
    ai = 1
    aj = 96
    ak = al = 1
    am = ai, aj, ak, al
    an = b.ops.reshape(ah, am)
    ao = ap = 96
    aq = ar = 320
    at = ao, ap, aq, ar
    au = b.ops.broadcast_in_dim(an, at, [0, 1, 2, 3])
    av = b.ops.mul(af, au)
    aw = b.ops.cast(g, DataType.Float)
    ax = 1
    ay = 96
    az = ba = 1
    bb = ax, ay, az, ba
    bc = b.ops.reshape(aw, bb)
    bd = 96
    bf = bg = 320
    bh = bd, d, bf, bg
    bi = b.ops.broadcast_in_dim(bc, bh, [0, 1, 2, 3])
    bj = b.ops.add(av, bi)
    bk = b.ops.cast(bj, DataType.Half)
    bl = b.ops.ne(bk, bk)
    bm = b.define_scalar(0.00000)
    bn = b.ops.gt(bk, bm)
    bo = b.define_scalar(0.00000)
    bp = b.ops.where(bn, bk, bo)
    bq = b.ops.where(bl, bk, bp)
    br = b.ops.ne(bq, bq)
    bs = b.define_scalar(6.00000)
    bt = b.ops.lt(bq, bs
    )
    bv = 1
    bw = 192
    bx = by = 1
    bz = bv, bw, bx, by
    ca = b.ops.reshape(f, bz)
    co = cb = b.define_scalar(2)
    cd = ce = 20
    cf = cb, c, cd, ce
    cg = b.ops.broadcast_in_dim(ca, cf, [0, 1, 2, 3])
    ch = b.ops.mul(co, cg)
    dj = dl = dp = ee = b.ops.ne(c, c)
    dr = b.define_scalar(6.00000)
    ds = b.ops.lt(dp, dr
    )
    
    dt = e
    du = b.ops.cat([dt] )
    dv = b.ops.slice(du, [0, 0, 0, 0], [2, 6, 240, 3201])
    
    dw = b.ops.slice(du, [0, 2, 0, 0], [2, 4, 240, 201]
    )
    dx = b.define_scalar(0.00000)
    dy = b.ops.where(ee, dx, dw)
    dz = b.define_scalar(0.00000)
    fc = b.ops.where(ds, dy, dz)
    ec = b.ops.cast(fc, DataType.Float)
    ed = b.ops.add(c, ec)
    fg = b.ops.cast(ed, DataType.Half)
    ef = b.define_scalar(0.00000)
    eg = b.ops.where(dj, ef, fg)
    eh = b.define_scalar(0.00000)
    ei = b.ops.where(dl, eg, eh)
    ej = ek = b.ops.cast(ei, DataType.Float)
    el = b.ops.add(ej, ek)
    em = b.ops.mul(ch, el)
    en = b.ops.mul(co, em
     )
    eo = en
    ep = b.ops.sum(eo, [0, 2, 3])
    eq = 1
    er = 192
    es = eq, er
    et = b.ops.broadcast_in_dim(ep, es, [1])
    eu = 192
    ev = [eu]
    ew = b.ops.reshape(et, ev)
    ex = ey = 192
    ez = o = 1
    fa = ex, ey, ez, o
    fb = b.ops.broadcast_in_dim(ew, fa, [1])
    ge = 192
    fe = ff = 20
    gi = ge, c, fe, ff
    fh = b.ops.broadcast_in_dim(fb, gi, [0, 1, 2, 3])
    fi = b.define_scalar(6.51042e06)
    fj = b.ops.mul(fi, fh)
    fk = fm = f
    fn = b.ops.mul(fk, fm)
    fo = b.ops.add(fj, fn)
    fp = b.ops.add(en, fo)
    fq = b.ops.cast(fp, DataType.Half)
    fr = b.ops.pad(fq, []
    )
    fs = b.define_scalar(0.00000)
    ft = b.ops.where(br, fs, dv)
    fu = b.define_scalar(0.00000)
    fv = b.ops.where(bt, ft, fu)
    fw = fx = b.ops.cast(fv, DataType.Float)
    fy = b.ops.add(fw, fx)
    fz = b.ops.cast(fy, DataType.Half)
    ga = b.define_scalar(0.00000)
    gb = b.ops.where(bl, ga, fz)
    gc = b.define_scalar(0.00000)
    gd = b.ops.where(bn, gb, gc)
    hh = gf = b.ops.cast(gd, DataType.Float)
    gg = b.ops.add(hh, gf)
    p = b.ops.mul(af, gg)
    gh = b.ops.mul(n, p
     )
    q = gh
    u = b.ops.sum(q, [0, 2, 3])
    r = 1
    s = 96
    hm = r, s
    v = b.ops.broadcast_in_dim(u, hm, [1])
    gj = 96
    gk = [gj]
    gl = b.ops.reshape(v, gk)
    gm = gn = 96
    go = gp = 1
    gq = gm, gn, go, gp
    gr = b.ops.broadcast_in_dim(gl, gq, [1])
    gs = hx = 96
    gu = gv = 20
    gw = gs, hx, gu, gv
    gx = b.ops.broadcast_in_dim(gr, gw, [0, 1, 2, 3])
    gy = b.define_scalar(6.51042e06)
    gz = b.ops.mul(gy, gx)
    ha = hb = b.ops.cast(d, DataType.Double)
    hc = hb
    hd = b.ops.mul(ha, hc)
    he = b.ops.add(gz, hd)
    hf = b.ops.add(gh, he)
    hg = b.ops.cast(hf, DataType.Half)
    b.add_output(fr)
    b.add_output(hg)
with FusionDefinition() as b:
    a(b)
hi = [
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    1,
    torch.randn(0, dtype=torch.float16, device='cuda:0').as_strided((2, 6, 0, 0), (0, 0, 0, 1)),
    torch.randn(6, device='cuda:0'),
    torch.randn(96, device='cuda:0'),
    torch.randn(961408, dtype=torch.float16, device='cuda:0').as_strided((2, 6, 2, 2), (80704, 4, 2, 1)),
    torch.randn(961408, dtype=torch.float16, device='cuda:0').as_strided((2, 6, 2, 2), (80704, 4, 2, 1)),
    torch.randn(961408, dtype=torch.float16, device='cuda:0').as_strided((2, 6, 2, 2), (80704, 4, 2, 1)),
    torch.randn(961408, dtype=torch.float16, device='cuda:0').as_strided((2, 6, 2, 2), (80704, 4, 2, 1)),
    torch.randn(0, dtype=torch.float16, device='cuda:0').as_strided((2, 6, 0, 0), (0, 0, 0, 1)),
    torch.randn(6, device='cuda:0'),
    torch.randn(6, device='cuda:0'),
    torch.randn(961408, dtype=torch.float16, device='cuda:0').as_strided((2, 6, 2, 2), (80704, 4, 2, 1)),
    torch.randn(961408, dtype=torch.float16, device='cuda:0').as_strided((2, 6, 2, 2), (80704, 4, 2, 1)),
    torch.randn(961408, dtype=torch.float16, device='cuda:0').as_strided((2, 6, 242, 322), (80704, 4, 2, 1)),
    torch.randn(0, dtype=torch.float16, device='cuda:0').as_strided((2, 2, 0, 0), (0, 0, 0, 1)),
    torch.randn(2, device='cuda:0'),
    torch.randn(192, device='cuda:0'),
    torch.randn(0, dtype=torch.float16, device='cuda:0').as_strided((2, 8, 0, 0), (0, 0, 0, 1)),
    torch.randn(8, device='cuda:0'),
    torch.randn(8, device='cuda:0'),
    torch.randn(96, dtype=torch.float16, device='cuda:0'),
    torch.randn(96, dtype=torch.float16, device='cuda:0'),
    torch.randn(6, dtype=torch.float16, device='cuda:0'),
    torch.randn(6, dtype=torch.float16, device='cuda:0'),
    torch.randn(2, dtype=torch.float16, device='cuda:0'),
    torch.randn(2, dtype=torch.float16, device='cuda:0'),
    torch.randn(8, dtype=torch.float16, device='cuda:0'),
    torch.randn(8, dtype=torch.float16, device='cuda:0')]
b.execute(hi)
```

edit: replaced with a smaller program (albeit a bit of an odd one).
Attaching the original version for posterity: [original.txt](https://github.com/user-attachments/files/16301174/original.txt)

### PR DESCRIPTION
**Pull request by jacobhinkle**
In #2634, an `IterDomain` is created during lowering (in `allocGlobalBufferForGridComm`) using an extent that is derived from parallel extents. In this case the computation is done with `Int` scalars, and the constructor of `IterDomain` asserts that the extent should be `Index` instead. This PR casts the stop value to `Index` if necessary before creating the `IterDomain` in `allocGlobalBufferForGridComm`.

The reason we have an `Int` parallel dimension is that we compute `SimplifyExpr::maxExpr` with two constant `IterDomain` extents each of which is `DataType::Index` and should return `DataType::Index`. However, it currently returns `Int`. This is similar to the problem encountered in #2646. This PR fixes this by computing the proper output type for `maxExpr`, `minExpr`, `bitwiseAndExpr`, and `bitwiseOrExpr`.

Fixes #2634

### CODE REVIEW

File: csrc/device_lower/pass/index.cpp [hunk 1]
```diff
@@ -503,7 +503,7 @@ Val* getGridSyncBufferSize(
     const std::vector<ForLoop*>& for_loops,
     bool is_persistent) {
   // See the comment above for getGridCommWorkBufferSize.
-  Val* buffer_size = GpuLower::current()->kernel()->oneVal();
+  Val* buffer_size = GpuLower::current()->kernel()->oneVal(DataType::Index);
```
Comment (jacobhinkle) [inline csrc/device_lower/pass/index.cpp:506]: This attempts to avoid introducing an `Int` when we multiply by 1 in the first step. I believe it's possible `pt_dim` below might still be `Int` sometimes, which is why I still have the maybe cast in `device_lower/utils.cpp` also.

**Comment by naoyam** [comment]
Could you give more details about the issue? I'm not exactly sure what's the problem without this PR. We are using `oneVal()` and `zeroVal()` a lot. Are there any other use cases that need to be fixed?

**Comment by naoyam** [comment]
Oh, I thought the main changes are those `oneVal` and `zeroVal`, but it's actually the case of `buffer_size`, right?

**Review by naoyam — APPROVED** [review]
LGTM. Please add a unit test.

**Comment by jacobhinkle** [comment]
> LGTM. Please add a unit test.

Will do. I tried a bit to shrink the repro from #2634 but that has proven challenging so far. Still, it's worth understanding how these `Int` values get introduced.

**Comment by jacobhinkle** [comment]
I found the underlying cause of this. When building `ParallelDimensionMap`, this line calls `SimplifyingIrBuilder::maxExpr`:
https://github.com/NVIDIA/Fuser/blob/fa2bedc28e5ca4da461e92f468f814ab92fcc6f1/csrc/parallel_dimension_map.cpp#L65-L66 The inputs are two `Val`s whose dtype is `DataType::Index`, but they are both `isConst()`. That leads to this line: https://github.com/NVIDIA/Fuser/blob/fa2bedc28e5ca4da461e92f468f814ab92fcc6f1/csrc/ir/builder.cpp#L611 We should set the dtype of this new `Val` at this line by promoting the types of the two inputs.

To cause `Int` values in `ParallelDimensionMap`, all that's needed is for two `IterDomain`s with different const extents to both be mapped to the same parallel dimension.  In the original repro, there is also a grid reduction which needs to use that dimension map to compute the temporary buffer size, at which point we hit the error. I'll try and distill this into a small repro now, and fix the underlying cause by preserving dtype in `SimplifyingIrBuilder::maxExpr` (and `minExpr`).

**Comment by naoyam** [comment]
Glad you figured it out. I recently hit a similar problem: #2646. I looked at the file if there's any other places that need the same fix but couldn't spot them.

**Comment by jacobhinkle** [comment]
!build --diff

**Comment by jacobhinkle** [comment]
!build --diff

**Comment by jacobhinkle** [comment]
Diff looks as expected: changing things like `2LL` to `2` in cases where `nvfuser_index_t` is `int`. There was one test failure which is easily fixed by specifying the `DataType` in the reference scalar for `IndexingTest.ResizePath`. I will merge this soon.
