### PR TITLE
Validate all circular buffers at runtime

### LINKED ISSUE #2699: Add runtime check for circular buffer correctness
We generate incorrect results if the size of the pipeline is greater than the size of the circular buffering for-loop.

For example, say that the pipeline size is 4 and circular buffering loop size is 2.
prologue loop is (0, S-1) => (0, 3)
main loop is (0, N-(S-1)) => (0, -1)
epilogue loop is (N-(S-1), N) => (-1, 2)

The proposed fix is to have a runtime check to determine that the entire pipeline is filled at least once.

### PR DESCRIPTION
**Pull request by rdspring1**
This PR fixes #2699. It adds `validateCircularBuffering` to `FusionExecutor::initializeExecutorEntry`. The check ensures that every circular buffer TensorView is filled completely at least once.

Details:

- Add `CircularBufferInfo` from lowering analysis to `kir::KernelSummary`
- Create runtime check to guarantee that the entire pipelined is filled in `executor_utils.cpp`
- Use `limitCircularBufferingSmemOperands` to modify matmul heuristics so that the pipeline is always filled. In the matmul scheduler, the K dimension is the circular buffer axis for A and B operands. Therefore, the number of stages is `min(desired_stage, ceilDiv(ceilDiv(K, splitk_factor), cta_dim.k)`.

### CODE REVIEW

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

**Comment by rdspring1** [comment]
!build

File: csrc/device_lower/analysis/circular_buffer.h [hunk 1]
```diff
@@ -29,8 +31,13 @@ class CircularBufferInfo {
 
   void setCircularBufferAxis(const TensorView* tv, IterDomain* id);
 
+  IterDomain* getCircularBufferAxis(const TensorView* tv) const;
```
Comment (naoyam) [inline csrc/device_lower/analysis/circular_buffer.h:34]: Can we remove the non-const version? Looks like a duplication.

File: csrc/device_lower/analysis/circular_buffer.cpp [hunk 2]
```diff
@@ -59,19 +59,9 @@ int64_t getCircularBufferAxisPosition(const TensorView* tv) {
     }
   }
 
-  NVF_ERROR(
```
Comment (naoyam) [inline csrc/device_lower/analysis/circular_buffer.cpp:62]: Why is this removed?

**Review by naoyam — COMMENTED** [review]
LGTM. Just left a couple of minor comments.

@zasdfgbnm, please review the matmul scheduling part.

File: csrc/device_lower/analysis/circular_buffer.cpp (hunk 2 above)
Comment (rdspring1) [reply csrc/device_lower/analysis/circular_buffer.cpp:62]: I moved the `NVF_ERROR` to [validateCircularBufferedTensor](https://github.com/NVIDIA/Fuser/pull/2703/files#diff-189d7a00cf165617e4bf50aca92e4ab4db0d44213f349a3c4c90ab49f8581484R100-R104).

I was thinking that a user would call `getCircularBufferAxis` to evaluate its extent during scheduling. The user is evaluating if they should apply circular buffering, so we shouldn't throw an assertion in this case.

**Comment by rdspring1** [comment]
!build

File: csrc/device_lower/analysis/circular_buffer.cpp (hunk 2 above)
Comment (naoyam) [reply csrc/device_lower/analysis/circular_buffer.cpp:62]: Hmm, if `getCircularBufferAxisPosition` returns -1, doesn't it get interpreted as the innermost position?

**Comment by rdspring1** [comment]
!build

File: csrc/device_lower/analysis/circular_buffer.cpp (hunk 2 above)
Comment (rdspring1) [reply csrc/device_lower/analysis/circular_buffer.cpp:62]: Ah, I forgot about that. I changed `getCircularBufferAxisPosition` to return `getLoopDomain.size()`. `getCircularBufferAxis` will return `nullptr` if it sees `getLoopDomain.size()` as the axis position.

**Comment by rdspring1** [comment]
!build

File: csrc/scheduler/matmul.cpp [hunk 3]
```diff
@@ -1304,8 +1305,21 @@ void scheduleMatmul(Fusion* fusion, const MatmulParams& params) {
...
+        acr_axis->extent()->evaluate() >= number_of_stages) {
+      acr->circularBuffer(number_of_stages);
+    }
+
+    IterDomain* bcr_axis = getCircularBufferAxis(bcr);
+    NVF_ERROR(bcr_axis != nullptr);
+    if (bcr_axis->extent()->isConstScalar() &&
+        bcr_axis->extent()->evaluate() >= number_of_stages) {
+      bcr->circularBuffer(number_of_stages);
+    }
```
Comment (jacobhinkle) [inline csrc/scheduler/matmul.cpp:1322]: Nit: you could create a lambda to avoid repeating this part.

Comment (jacobhinkle) [reply csrc/scheduler/matmul.cpp:1322]: Instead of an if statement, should we just assert that these are constant? That could be done by just removing the `isConstScalar` check in the condition.

**Comment by rdspring1** [comment]
!build

File: csrc/scheduler/matmul_utils.cpp [hunk 4]
```diff
@@ -126,11 +126,19 @@ inline bool initCoreHeuristics(
...
-      constexpr int stages = 3;
-
-      params->circular_buffer_options.circular_buffer_smem_write = true;
+      // Find the number of circular buffer stages so that the entire pipeline
+      // is filled.
+      //
+      // The axes of the mma tensorviews are permuted to [B, M, N, K],
+      // so K / cta_tile_k is the circular buffer axis for both operands.
+      int64_t k_stages =
+          ceilDiv(problem_shape[(size_t)MatmulDimRole::K], cta_tile.k);
```
Comment (zasdfgbnm) [inline csrc/scheduler/matmul_utils.cpp:135]: @jacobhinkle Is this correct if we have split-k?

Comment (jacobhinkle) [reply csrc/scheduler/matmul_utils.cpp:135]: No, I believe the numerator should be `ceilDiv(problem_shape[(size_t)MatmulDimRole::K], params.splitk_factor)` here. Good catch.

**Comment by rdspring1** [comment]
!build

File: csrc/scheduler/matmul_utils.cpp (hunk 4 above)
Comment (rdspring1) [reply csrc/scheduler/matmul_utils.cpp]: I added this ^^^ to `limitCircularBufferingSmemOperands`, which updates the parameters from `matmul_heuristic_plugin` and `initCoreHeuristics`.

Can `splitk_factor > 1` in the `initCoreHeuristics`?

**Comment by rdspring1** [comment]
!build --matmul-bench

**Comment by rdspring1** [comment]
!build --matmul-bench

File: csrc/scheduler/matmul_utils.cpp (hunk 4 above)
Comment (jacobhinkle) [reply csrc/scheduler/matmul_utils.cpp]: It should not be `>1` in `initCoreHeuristics` at this time.

**Review by zasdfgbnm — APPROVED** [review]
LGTM now
