### PR TITLE
[WIP] Fixes #4202

### LINKED ISSUE #4202: Resize Scheduler bug with RoPE based fusion from Thunder
Error:
```
# error message
Traceback (most recent call last):
  File "/wayan/lightning-thunder/ttmp1.py", line 111, in <module>
    fd.execute(inputs)
  File "/opt/pytorch/nvfuser/nvfuser/__init__.py", line 317, in execute
    out_tensors, out_shardings = self._execute(
                                 ^^^^^^^^^^^^^^
RuntimeError:  INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/runtime/fusion_kernel_runtime.cpp":464, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Detected exception while compiling fusion segments in parallel. Error messages from all threads are printed below.
Error from segmentation group 1:  INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/scheduler/tools/loop_domain_scheduler.cpp":44, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Should not rewrite definition of iS2003{9216}. Existing definition: Resize: iS2004{3072} by 3072 and 3072 -> iS2003{9216}
New definition: Resize: iS314{3072}rf by 0 and 6144 -> iS315{9216}rf
Exception raised from LoopDomainSchedulerReplayTransform at /opt/pytorch/nvfuser/csrc/scheduler/tools/loop_domain_scheduler.cpp:44 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x103 (0x7da492e9d945 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #1: nvfuser::nvfErrorFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x62 (0x7da49330b882 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #2: <unknown function> + 0xa63529 (0x7da49378c529 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0xa6b325 (0x7da493794325 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0xa46597 (0x7da49376f597 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x98e5f7 (0x7da4936b75f7 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x98e904 (0x7da4936b7904 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #7: c10::ThreadPool::main_loop(unsigned long) + 0x29d (0x7da60d578d8d in /usr/local/lib/python3.12/dist-packages/torch/lib/libc10.so)
frame #8: <unknown function> + 0xecdb4 (0x7da59e014db4 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #9: <unknown function> + 0x9caa4 (0x7da60effcaa4 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #10: <unknown function> + 0x129c3c (0x7da60f089c3c in /usr/lib/x86_64-linux-gnu/libc.so.6)

Use NVFUSER_DISABLE=parallel_compile to simplify error message.
Exception raised from compileFusionParallel at /opt/pytorch/nvfuser/csrc/runtime/fusion_kernel_runtime.cpp:464 (most recent call first):
frame #0: nvfuser::nvfCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x103 (0x7da492e9d945 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #1: nvfuser::nvfErrorFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x62 (0x7da49330b882 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #2: nvfuser::FusionKernelRuntime::compileFusionParallel(nvfuser::KernelArgumentHolder) + 0x1f0a (0x7da4936bbd9a in /opt/pytorch/nvfuser/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #3: nvfuser::FusionExecutorCache::runFusionWithInputs(nvfuser::KernelArgumentHolder, std::optional<nvfuser::PrimDataType>, std::optional<signed char>) + 0x12c (0x7da4936af6ac in /opt/pytorch/nvfuser/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #4: nvfuser::python_frontend::FusionDefinition::execute(nvfuser::KernelArgumentHolder, std::optional<signed char>, bool, bool, bool, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >) const + 0xefc (0x7da4938a336c in /opt/pytorch/nvfuser/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #5: <unknown function> + 0x2180bd (0x7da492f410bd in /opt/pytorch/nvfuser/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x2e786d (0x7da49301086d in /opt/pytorch/nvfuser/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #7: <unknown function> + 0x205613 (0x7da492f2e613 in /opt/pytorch/nvfuser/nvfuser/_C.cpython-312-x86_64-linux-gnu.so)
frame #8: python() [0x58208f]
<omitting python frames>
frame #12: python() [0x608b42]
frame #13: python() [0x6b4e93]
frame #18: <unknown function> + 0x2a1ca (0x7da60ef8a1ca in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #19: __libc_start_main + 0x8b (0x7da60ef8a28b in /usr/lib/x86_64-linux-gnu/libc.so.6)
 
 
 
```

Repro:

```
# CUDA devices:
#  0: NVIDIA RTX 6000 Ada Generation
#  1: NVIDIA RTX 6000 Ada Generation
# torch version: 2.7.0a0+79aa17489c.nvInternal
# cuda version: 12.9
# nvfuser version: 0.2.27+gitd48f971
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id0(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[1, 32, 256, 96], contiguity=[None, True, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[3, 2, 1, 0])
    T1 = fd.define_tensor(shape=[1, 32, 256, 96], contiguity=[None, True, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[3, 2, 1, 0])
    T2 = fd.define_tensor(shape=[1, 256, 96], contiguity=[None, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[2, 1, 0])
    T3 = fd.define_tensor(shape=[1, 32, 256, 96], contiguity=[None, True, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[3, 2, 1, 0])
    T4 = fd.define_tensor(shape=[1, 256, 96], contiguity=[None, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[2, 1, 0])
    T5 = fd.define_tensor(shape=[1, 32, 256, 96], contiguity=[None, True, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[3, 2, 1, 0])
    T6 = fd.define_tensor(shape=[1, 32, 256, 96], contiguity=[None, True, True, True], dtype=DataType.BFloat16, is_cpu=False, stride_order=[3, 2, 1, 0])
    T7 = fd.ops.cast(T0, dtype=DataType.Float)
    T8 = fd.ops.cast(T1, dtype=DataType.Float)
    T9 = fd.ops.add(T8, T7)
    T10 = fd.ops.cast(T9, dtype=DataType.BFloat16)
    T16 = fd.ops.broadcast_in_dim(T2, shape=[1, 1, 256, 96], broadcast_dims=[0, 2, 3])
    T32 = fd.ops.slice(T10, start_indices=[0, 0, 0, 0], end_indices=[1, 32, 256, 96], strides=[1, 1, 1, 1], manual_normalization=0)
    T38 = fd.ops.broadcast_in_dim(T16, shape=[1, 32, 256, 96], broadcast_dims=[0, 1, 2, 3])
    T54 = fd.ops.slice(T3, start_indices=[0, 0, 0, 0], end_indices=[1, 32, 256, 96], strides=[1, 1, 1, 1], manual_normalization=0)
    T55 = fd.ops.cast(T32, dtype=DataType.Float)
    T56 = fd.ops.cast(T38, dtype=DataType.Float)
    T57 = fd.ops.cast(T54, dtype=DataType.Float)
    T58 = fd.ops.mul(T56, T55)
    T59 = fd.ops.mul(T56, T57)
    T60 = fd.ops.cast(T58, dtype=DataType.BFloat16)
    T61 = fd.ops.cast(T59, dtype=DataType.BFloat16)
    T77 = fd.ops.slice(T60, start_indices=[0, 0, 0, 0], end_indices=[1, 32, 256, 48], strides=[1, 1, 1, 1], manual_normalization=0)
    T93 = fd.ops.slice(T61, start_indices=[0, 0, 0, 0], end_indices=[1, 32, 256, 48], strides=[1, 1, 1, 1], manual_normalization=0)
    T94 = fd.ops.cast(T77, dtype=DataType.Float)
    T95 = fd.ops.cast(T93, dtype=DataType.Float)
    T96 = fd.ops.neg(T94)
    T97 = fd.ops.neg(T95)
    T103 = fd.ops.broadcast_in_dim(T4, shape=[1, 1, 256, 96], broadcast_dims=[0, 2, 3])
    T119 = fd.ops.slice(T60, start_indices=[0, 0, 0, 48], end_indices=[1, 32, 256, 96], strides=[1, 1, 1, 1], manual_normalization=0)
    T120 = fd.ops.cast(T96, dtype=DataType.BFloat16)
    T136 = fd.ops.slice(T61, start_indices=[0, 0, 0, 48], end_indices=[1, 32, 256, 96], strides=[1, 1, 1, 1], manual_normalization=0)
    T137 = fd.ops.cast(T97, dtype=DataType.BFloat16)
    T143 = fd.ops.broadcast_in_dim(T103, shape=[1, 32, 256, 96], broadcast_dims=[0, 1, 2, 3])
    S144 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T154 = fd.ops.pad(T119, [0, 48, 0, 0, 0, 0, 0, 0], S144)
    S155 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T165 = fd.ops.pad(T120, [48, 0, 0, 0, 0, 0, 0, 0], S155)
    S166 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T176 = fd.ops.pad(T136, [0, 48, 0, 0, 0, 0, 0, 0], S166)
    S177 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T187 = fd.ops.pad(T137, [48, 0, 0, 0, 0, 0, 0, 0], S177)
    S188 = fd.define_scalar(0, dtype=DataType.Int)
    T194 = fd.ops.full(shape=[1, 32, 256, 0], fill_value=S188, dtype=DataType.BFloat16)
    T195 = fd.ops.cast(T143, dtype=DataType.Float)
    T196 = fd.ops.cast(T154, dtype=DataType.Float)
    T197 = fd.ops.cast(T165, dtype=DataType.Float)
    T198 = fd.ops.cast(T176, dtype=DataType.Float)
    T199 = fd.ops.cast(T187, dtype=DataType.Float)
    S200 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T210 = fd.ops.pad(T194, [0, 96, 0, 0, 0, 0, 0, 0], S200)
    T211 = fd.ops.mul(T195, T55)
    T212 = fd.ops.add(T197, T196)
    T213 = fd.ops.mul(T195, T57)
    T214 = fd.ops.add(T199, T198)
    T215 = fd.ops.cast(T210, dtype=DataType.Float)
    T216 = fd.ops.add(T212, T211)
    T217 = fd.ops.cast(T5, dtype=DataType.Float)
    T218 = fd.ops.cast(T6, dtype=DataType.Float)
    T219 = fd.ops.add(T214, T213)
    T220 = fd.ops.add(T216, T215)
    T221 = fd.ops.add(T218, T217)
    T222 = fd.ops.add(T219, T215)
    T223 = fd.ops.cast(T220, dtype=DataType.BFloat16)
    T224 = fd.ops.cast(T221, dtype=DataType.BFloat16)
    T225 = fd.ops.cast(T222, dtype=DataType.BFloat16)
    T226 = fd.ops.permute(T223, dims=[0, 2, 1, 3])
    T227 = fd.ops.permute(T224, dims=[0, 2, 1, 3])
    T228 = fd.ops.permute(T225, dims=[0, 2, 1, 3])
    T233 = fd.ops.reshape(T226, new_shape=[1, 256, 3072])
    T238 = fd.ops.reshape(T227, new_shape=[1, 256, 3072])
    T243 = fd.ops.reshape(T228, new_shape=[1, 256, 3072])
    S244 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T252 = fd.ops.pad(T233, [3072, 3072, 0, 0, 0, 0], S244)
    S253 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T261 = fd.ops.pad(T238, [6144, 0, 0, 0, 0, 0], S253)
    S262 = fd.define_scalar(0.00000, dtype=DataType.Double)
    T270 = fd.ops.pad(T243, [0, 6144, 0, 0, 0, 0], S262)
    T271 = fd.ops.cast(T252, dtype=DataType.Float)
    T272 = fd.ops.cast(T261, dtype=DataType.Float)
    T273 = fd.ops.cast(T270, dtype=DataType.Float)
    T274 = fd.ops.add(T272, T271)
    T275 = fd.ops.add(T274, T273)
    T276 = fd.ops.cast(T275, dtype=DataType.BFloat16)
    T280 = fd.ops.reshape(T276, new_shape=[256, 9216])
    fd.add_output(T276)
    fd.add_output(T280)

with FusionDefinition() as fd:
    nvfuser_fusion_id0(fd)

inputs = [
    torch.testing.make_tensor((1, 32, 256, 96), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((1, 32, 256, 96), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((1, 256, 96), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((1, 32, 256, 96), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((1, 256, 96), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((1, 32, 256, 96), dtype=torch.bfloat16, device='cuda:0'),
    torch.testing.make_tensor((1, 32, 256, 96), dtype=torch.bfloat16, device='cuda:0'),
]
fd.execute(inputs)
```

### PR DESCRIPTION
**Pull request by naoyam**
Fixes #4202 

The resize scheduler is just using `fusion->inputs()` to find all tensors that appear before a certain tensor, which misses those created by factory methods such as `full`.

### CODE REVIEW

**Comment by naoyam** [comment]
!test --diff

**Comment by naoyam** [comment]
!test --diff

**Comment by naoyam** [comment]
!build

File: tests/cpp/test_resize.cpp [hunk 1]
```diff
@@ -6005,4 +6005,39 @@ TEST_F(ResizeTest, VectorizeSliceMultiplePaths) {
   EXPECT_EQ(tv6->getLoopDomain().back()->extent()->evaluate(), 2);
 }
 
+// Repro of issue #4202
```
Comment (jjsjann123) [inline tests/cpp/test_resize.cpp:6008]: nice repro~ much more concise than the original. :clap:

**Review by jjsjann123 — APPROVED** [review]
LGTM
