### PR TITLE
Safe resize vectorization

### LINKED ISSUE #3640: Vectorization analysis returns wrong Vectorization Factor
In vectorization analysis, we use MaxInfoSpanningTree to propagate the vectorization factor from reference TV to other TVs in the fusion. The issue is that, for each TV with multiple paths to the reference TV, only one path is traversed.

For the graph below where resize is involved, this approach runs into issue.

tv0 is being sliced twice producing tv1 / tv2, which were later added together as tv3 (reference TV).
We are taking a slice with an odd offset, `tv2 = tv0[3:-5]`, which wouldn't allow any vectorization.

But in our analysis, when we propagate the projected contiguous inner dimensions from tv3 to tv0:
1. if we go through `tv3 -> tv1 -> tv0`, the resize with resize extent `(-4, -4)` would give us a vectorization factor of `4`;
2. Meanwhile if we go along `tv3 -> tv2 -> tv0`, the other resize with resize extent `(-3, -5)` wouldn't allow any vectorization.

```
// Trivial slice
TEST_F(VectorizationAnalysisTest, ResizeFork) {
  Fusion fusion;
  FusionGuard fg(&fusion);
  std::vector<std::pair<TensorView*, int64_t>> expection_list;

  // concrete shapes to avoid dynamic Fusion
  auto tv0 = makeContigConcreteTensor({36});
  fusion.addInput(tv0);

  auto tv1 = slice(
      tv0,
      {{IrBuilder::create<Val>(4L),
        sub(tv0->axis(0)->extent(), IrBuilder::create<Val>(4L))}});
  auto tv2 = slice(
      tv0,
      {{IrBuilder::create<Val>(3L),
        sub(tv0->axis(0)->extent(), IrBuilder::create<Val>(5L))}});
  auto tv3 = add(tv1, tv2);
  fusion.addOutput(tv3);

  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  auto t0 = at::randn({36}, options);
  std::vector<c10::IValue> aten_inputs({t0});

  std::unordered_map<TensorView*, Val*> projected_extent_map_from_producer =
      vectorize_helper::ContiguousInnerDimensionsMapper::map(
          tv3, tv3->getLogicalDomain())
          .getTvToContigMergeOfInnerSizeMap();
  checkMappedVal(projected_extent_map_from_producer, tv0, 1);
}
```

### PR DESCRIPTION
**Pull request by naoyam**
Fixes #3640.

The current issue with resize vectorization is that because of the spanning tree based traversal, not all paths are taken into consideration when determining vectorization factors. This PR addresses the issue by finding all `Resize` ops that have dependencies with vectorized IDs. To do so, added a new graph traversal class, `FindAllExprs`, based on `BFS`. Note that `BFS` only finds shortest paths, so not suitable when, for example, `Resize` appears in a cycle, which is the case with RoPE.

I was also thinking about overhauling the vectorization analysis to be more ID traversal basis, but we would still need to look at each tensor's allocation domain, so I don't think we can completely move away from tensor op traversals.

### CODE REVIEW

**Comment by naoyam** [comment]
CC: @jjsjann123

**Comment by naoyam** [comment]
!test --diff

**Comment by naoyam** [comment]
!test --diff

**Comment by naoyam** [comment]
!test --diff

**Comment by naoyam** [comment]
!test --diff

**Comment by naoyam** [comment]
!test --diff

**Comment by naoyam** [comment]
!test --diff

**Comment by naoyam** [comment]
!test --diff

**Comment by naoyam** [comment]
!test

**Comment by naoyam** [comment]
!test

**Comment by naoyam** [comment]
!test

File: tests/cpp/test_host_irs.cpp [hunk 1]
```diff
@@ -888,6 +888,7 @@ TEST_F(LinearHostIrTest, HostIr) {
 }
 
 TEST_F(LinearHostIrTest, HostIrLinearOut) {
+  GTEST_SKIP();
```
Comment (naoyam) [inline tests/cpp/test_host_irs.cpp:891]: Temporarily disabled as it prevents the binary tests running on H100. 

Related: #3996

**Comment by naoyam** [comment]
!test

File: csrc/scheduler/vectorize_helper.cpp [hunk 2]
```diff
@@ -881,6 +971,15 @@ int64_t getVectorizationFactor(
     return 1;
   }
 
+  auto resize_factors_entry =
+      HeuristicDataCacheEntry<HeuristicCompileTime::ResizeVectorizationFactors>(
```
Comment (jjsjann123) [inline csrc/scheduler/vectorize_helper.cpp:975]: :clap:

File: csrc/scheduler/vectorize_helper.cpp [hunk 3]
```diff
@@ -843,6 +844,95 @@ std::vector<std::unordered_map<TensorView*, Val*>> getTvToContigInnerSizeMapsOf(
...
+  // tensor.
+  for (auto resize_based_op : resize_based_ops) {
+    auto resize_out = resize_based_op->output(0)->as<TensorView>();
+    NVF_ERROR(
+        resize_out->hasRoot(), "Unexpected op: ", resize_based_op->toString());
+    // To make sure the resize op of this resize_based_op tensor op,
+    // use both the root and logical domains as the traversal targets
+    ValGroups resize_inp_out;
+    resize_inp_out.pushBack(graph.toGroups(resize_out->getRootDomain()));
+    resize_inp_out.pushBack(graph.toGroups(resize_out->getLogicalDomain()));
```
Comment (jjsjann123) [inline csrc/scheduler/vectorize_helper.cpp:880]: Is the reason of pushing both root and logical because we could be traversing on both directions?

If so, I think the comment on line 876-877 isn't very clear about that.

File: csrc/scheduler/vectorize_helper.cpp [hunk 4]
```diff
@@ -843,6 +844,95 @@ std::vector<std::unordered_map<TensorView*, Val*>> getTvToContigInnerSizeMapsOf(
...
+         ++it) {
+      vectorized_groups.pushBack(graph.toGroup(*it));
+    }
+
+    // Find all resize exprs that appear in expr_path and depend on
+    // vectorized_groups. Since expr_path is not guaranteed to be
+    // topologically sorted, need to loop through the path until
+    // converged.
+
+    bool something_has_changed = true;
```
Comment (jjsjann123) [inline csrc/scheduler/vectorize_helper.cpp:901]: NOTE FOR MYSELF: go over this again later.

File: csrc/scheduler/vectorize_helper.cpp [hunk 5]
```diff
@@ -920,6 +1019,15 @@ int64_t getVectorizationFactor(
         max_vec_size);
   }
 
+  for (const auto resize_factor : resize_factors) {
+    auto inferred_val =
+        runtime_info.expressionEvaluator().evaluate(resize_factor);
+    if (!inferred_val.hasValue()) {
+      return 1;
+    }
+    max_vec_size = std::gcd(max_vec_size, inferred_val.as<int64_t>());
```
Comment (jjsjann123) [inline csrc/scheduler/vectorize_helper.cpp:1028]: One thing I think the WAR is different from how we are handling resize in `propagateRezie` is that: the WAR here doesn't consider the position of the ID where the resize is applying to.

Here we are taking gcd over each factor in the resize op. (left_extent & right_extent & (in|out extent)).
So if the resize is only applying on a middle dimension, I think we are not supposed to take the GCD of that resize on the overall `max_vec_size`.

Comment (jjsjann123) [reply csrc/scheduler/vectorize_helper.cpp:1028]: I think the approach taken here is that we are going to be more conservative on applying vectorization with resize.

For rope, since the resize is happening at the fastest dimension, it does seem to be doing the right thing. But this will be restrictive on more general cases.

**Review by jjsjann123 — COMMENTED** [review]
some quick comments.

I still need to go over `graph_traversal.h` and tests.

File: csrc/scheduler/vectorize_helper.cpp (hunk 5 above)
Comment (naoyam) [reply csrc/scheduler/vectorize_helper.cpp:1028]: You're right, that's a good point. I'd keep it as is since this is an immediate correctness issue. To make it more precise, it would need more significant changes.

File: csrc/scheduler/vectorize_helper.cpp (hunk 3 above)
Comment (naoyam) [reply csrc/scheduler/vectorize_helper.cpp:880]: That is correct. Updated the comment.

File: csrc/scheduler/vectorize_helper.cpp (hunk 5 above)
Comment (naoyam) [reply csrc/scheduler/vectorize_helper.cpp:1033]: Added a comment.

Comment (naoyam) [reply csrc/scheduler/vectorize_helper.cpp:1033]: If innermost two contiguous IDs looked like `{1024, 6}`, and the innermost ID were sliced as `[2:4]`, would our current analysis yield 4 as its vectorization factor instead of 2? Because of the innermost ID, it should be 2. However, its projected extent would be 2 but then the outer ID has a projected extent of 1024, so if two IDs were merged, wouldn't it (falsely) claim it should be vectorizable by a factor of 4?

Comment (jjsjann123) [reply csrc/scheduler/vectorize_helper.cpp:1033]: No. when we resize a ID, we excludes all its outer dimensions from the contiguous IDs. https://github.com/NVIDIA/Fuser/blob/b0bf8f39c9fe64db76983e74eae06aec03c3da5d/csrc/scheduler/vectorize_helper.cpp#L381-L384

Comment (jjsjann123) [reply csrc/scheduler/vectorize_helper.cpp:1033]: That sounds fair. Let me take another round at the graph_traversal stuff.

File: csrc/graph_traversal.h [hunk 6]
```diff
@@ -0,0 +1,598 @@
...
+    typename InputsT,
+    typename OutputsT>
+class FindAllExprs {
+ public:
+  using ExprType = ExprT;
+  using ValType = ValT;
+  using NodeType = std::variant<ExprT, ValT>;
+  using ExprPath = std::vector<std::pair<ExprT, Direction>>;
+  using InputsType = InputsT;
+  using OutputsType = OutputsT;
```
[the remark this answers is not in the document]
Comment (naoyam) [reply csrc/graph_traversal.h:62]: They can be removed. This class started by copying BFS`, so those were just copied from `BFS`.

File: csrc/graph_traversal.h [hunk 7]
```diff
@@ -0,0 +1,598 @@
...
+      while (!edges_to_visit.empty()) {
+        const auto edge_to_visit = edges_to_visit.front();
+        edges_to_visit.pop_front();
+
+        // Don't visit edges multiple times even when traversing all paths
+        if (isVisited(edge_to_visit)) {
+          continue;
+        }
+
+        auto prev_edges = isReady(edge_to_visit);
```
[the remark this answers is not in the document]
Comment (naoyam) [reply csrc/graph_traversal.h:153]: I think I was actually using that information in some of prior versions. I ended up not using it, but I'm not sure if that's always the case, so I'll keep it as is for now.

File: csrc/graph_traversal.h [hunk 8]
```diff
@@ -0,0 +1,598 @@
...
+      }
+      ss << ")";
+      NVF_THROW("BFS traversal could not visit some nodes: ", ss.str());
+    }
+  }
+
+  // Check if a node is ready to visit. If yes, return the direction
+  // and the prev nodes that should be visited before the given node
+  // is visited.
+  virtual std::optional<std::vector<Edge>> isReady(const Edge& edge) const {
```
[the remark this answers is not in the document]
Comment (naoyam) [reply csrc/graph_traversal.h:205]: Thanks. Yes, just an empty vector should be fine.

File: csrc/graph_traversal.h [hunk 9]
```diff
@@ -0,0 +1,598 @@
...
+              })) {
+        std::vector<Edge> prev_edges;
+        for (const ValT& output : outputs) {
+          prev_edges.push_back(Edge(output, from_expr));
+        }
+        return prev_edges;
+      }
+    }
+
+    return std::nullopt;
```
[the remark this answers is not in the document]
Comment (naoyam) [reply csrc/graph_traversal.h:264]: No, I don't think so since not all of the dependencies may be satisfied yet.

File: csrc/graph_traversal.h [hunk 10]
```diff
@@ -0,0 +1,598 @@
...
+        }
+        return prev_edges;
+      }
+    } else if (dir == Direction::Backward) {
+      decltype(auto) outputs = outputs_(from_expr);
+      if (std::all_of(
+              outputs.begin(), outputs.end(), [&](const ValT& output) -> bool {
+                return isVisited(Edge(output, from_expr));
+              })) {
+        std::vector<Edge> prev_edges;
```
[the remark this answers is not in the document]
Comment (naoyam) [reply csrc/graph_traversal.h:256]: Because those are the edges that should have been visited previously.

File: csrc/graph_traversal.h (hunk 6 above)
[the remark this answers is not in the document]
Comment (naoyam) [reply csrc/graph_traversal.h]: Removed

File: tests/cpp/test_bfs.cpp [hunk 11]
```diff
@@ -577,4 +574,359 @@ TEST_F(BFSTest, IRBFSPermissiveTraversal2) {
...
+
+    VALIDATE_EXPR_PATH(result, reference_path);
+  }
+}
+
+// Testing with a graph structure of
+//
+//  A ----> B ----> D
+//      ^       |
+//      +-- C <-+
```
Comment (jjsjann123) [inline tests/cpp/test_bfs.cpp:752]: nitpick: I struggle with mapping {tvX} into (A, B, C, D)

File: tests/cpp/test_bfs.cpp [hunk 12]
```diff
@@ -577,4 +574,359 @@ TEST_F(BFSTest, IRBFSPermissiveTraversal2) {
...
+  fusion.addInput(tv0);
+
+  auto tv1 = sin(tv0);
+
+  auto tv2 = slice(
+      tv1,
+      {{fusion.zeroVal(), tv1->getLogicalDomain().at(0)->extent()},
+       {fusion.zeroVal(), IrBuilder::create<Val>(shape[1] / 2)}});
+
+  auto tv3 = sin(tv0);
```
Comment (jjsjann123) [inline tests/cpp/test_bfs.cpp:878]: nitpick, this isn't really rope. But that doesn't matter.

another nitpick/question. Does the two `sin` function add anything to the test? I think we can directly slice on `tv0`, which would test the same pattern.

**Review by jjsjann123 — APPROVED** [review]
Thanks for addressing my nitpick and questions.

LGTM

File: tests/cpp/test_bfs.cpp [hunk 13]
```diff
@@ -577,4 +574,359 @@ TEST_F(BFSTest, IRBFSPermissiveTraversal2) {
...
+  Fusion& fusion = *fusion_ptr;
+
+  // Create an ID graph with two cycles
+  auto tv0 = makeConcreteTensor({10});
+  fusion.addInput(tv0);
+  // One cycle from tv0 to tv1 and then tv2
+  auto tv1 = reshape(tv0, {10}, {2, 5});
+  auto tv2 = reshape(tv1, {2, 5}, {10});
+  // Another cycle from tv0 to tv3 and then tv4
+  auto tv3 = reshape(tv0, {10}, {5, 2});
```
[the remark this answers is not in the document]
Comment (naoyam) [reply tests/cpp/test_bfs.cpp:653]: tv1's logical shape is `{2, 5}`, while `tv5` is `{5, 2}`, so they are not mapped.

File: tests/cpp/test_bfs.cpp [hunk 14]
```diff
@@ -577,4 +574,359 @@ TEST_F(BFSTest, IRBFSPermissiveTraversal2) {
...
+
+    ExprGroupPath reference_path{
+        {graph.toGroup(tv3->getLogicalDomain().at(0)->definition()),
+         Direction::Forward},
+        {graph.toGroup(tv1->getLogicalDomain().at(0)->definition()),
+         Direction::Forward},
+        {graph.toGroup(tv4->getLogicalDomain().at(0)->definition()),
+         Direction::Forward},
+        {graph.toGroup(tv2->getLogicalDomain().at(0)->definition()),
+         Direction::Forward}};
```
[the remark this answers is not in the document]
Comment (naoyam) [reply tests/cpp/test_bfs.cpp:692]: They are not mappable.

File: tests/cpp/test_bfs.cpp (hunk 12 above)
Comment (naoyam) [reply tests/cpp/test_bfs.cpp:878]: It is not the entire rope but just the rotation part, which is what tends to matter most.

`sin` is just to prevent the preseg passes to take over the `slice` ops.

**Comment by naoyam** [comment]
!build
