### PR TITLE
Handle constant -1 values in dynamic reshape at definition

### LINKED ISSUE #249: Support symbolic -1 output dimensions in reshape
As of #24 and #215 there is support for scheduling and running Fusions containing `reshape` ops whose output shape is a list of `Scalar`s. These scalars are typically the extents of the corresponding reshaped dimensions. If -1 is passed, it should be replaced by an integer that preserves the number of elements in the input. Currently, we are able to handle dynamic values of -1 during concretization, but scheduling fails while getting heuristics.
```c++
  std::unique_ptr<Fusion> fusion_ptr = std::make_unique<Fusion>();
  Fusion& fusion = *fusion_ptr.get();
  FusionGuard fg(&fusion);

  TensorView* tv0 = makeSymbolicTensor(4);
  fusion.addInput(tv0);

  auto tv1 = add(tv0, tv0);
  auto tv2 = reshape(tv1, {tv1->axis(0)->extent(), tv1->axis(2)->extent(), IrBuilder::create<Int>(-1)});
  auto tv3 = add(tv2, tv2);
  fusion.addOutput(tv3);

  FusionExecutorCache fusion_executor_cache(std::move(fusion_ptr));


  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
  at::Tensor at_x = at::randn({2,3,4,5}, options);

  auto outputs = fusion_executor_cache.runFusionWithInputs({at_x});
//C++ exception with description "extent_int >= 0 INTERNAL ASSERT FAILED at 
// "/opt/pytorch/nvfuser/csrc/scheduler/registry.cpp":807, please report a bug to PyTorch. 
// Unexpected size of axis: -1                                                                                                  
// Exception raised from getTensorIndexType at
// /opt/pytorch/nvfuser/csrc/scheduler/registry.cpp:807
```

### PR DESCRIPTION
**Pull request by jacobhinkle**
This replaces scalar new sizes that evaluate to `-1` at definition time in the `reshape()` op with a simplified expression for the new output extent. Previous to this change, the output shape would be set to the `Val*` that was provided, which evaluates to `-1`; after which it is difficult to reliably change even at concretization, since that scalar might have legitimate other uses.

Before this change:
```c++
auto tv0 = makeSymbolicTensor(4); // [ iS0{i0}, iS1{i2}, iS2{i3}, iS3{i4} ]
auto tv1 = reshape({tv0->axis(0)->extent(), tv0->axis(2)->extent(), IrBuilder::create<Scalar>(-1)});
// [ ?S4{i0}, ?S5{i3}, ?S6{-1} ]
```
After this change:
```c++
auto tv0 = makeSymbolicTensor(4); // [ iS0{i0}, iS1{i2}, iS2{i3}, iS3{i4} ]
auto tv1 = reshape({tv0->axis(0)->extent(), tv0->axis(2)->extent(), IrBuilder::create<Scalar>(-1)});
// [ iS4{i0}, iS5{i3}, ?S6{( i2 * i4 )} ]
```

In this PR we also introduce a check that only allows values of -1 when that value is known at compile time; for example passing an input scalar of -1 or an expression that evaluates to -1 to a dynamic reshape will result in an error at concretization.

Fixes #249

### CODE REVIEW

File: csrc/dynamic_transform.cpp [hunk 1]
```diff
@@ -277,18 +276,7 @@ void DynamicTransformConcretizationInfo::analyzeReshapes(
...
-      if (extent_int == -1) {
-        TORCH_INTERNAL_ASSERT(
-            !extent_m1_found,
-            "Multiple output domains of size -1 not allowed",
-            out_tv->toString());
-        extent_m1_found = true;
-      } else {
-        TORCH_INTERNAL_ASSERT(
-            extent_int > 0, "Invalid output domain extent: ", extent_int);
-      }
```
Comment (jacobhinkle) [inline csrc/dynamic_transform.cpp:290]: These checks are handled by `reshape()` and `analyzeView()` and are not needed here.

File: csrc/ops/alias.cpp [hunk 2]
```diff
@@ -121,12 +122,38 @@ TensorView* reshape(TensorView* inp_tv, const std::vector<Val*>& new_sizes) {
...
+        numel = mul(numel, inp_dom.at(j)->extent());
+      }
+      for (const auto j : c10::irange(new_sizes.size())) {
+        if (i == j) {
+          continue;
+        }
+        other_new_numel = mul(other_new_numel, new_sizes.at(j));
+      }
+      new_size = div(numel, other_new_numel);
+      new_size = simplifyExpr(new_size);
```
Comment (jacobhinkle) [inline csrc/ops/alias.cpp:150]: Note that `SimplifyingIrBuilder` evaluates constant subexpressions but does not simplify `(x * y) / y`, so I used `simplifyExpr` here.

**Comment by jacobhinkle** [comment]
!build

File: test/test_dynamic_transform.cpp [hunk 3]
```diff
@@ -1070,4 +1070,85 @@ TEST_F(NVFuserTest, FusionDynamicEmptyCat2_CUDA) {
...
+  auto options = at::TensorOptions().dtype(at::kFloat).device(at::kCUDA, 0);
+  at::Tensor at_x = at::randn({2, 3, 4, 5}, options);
+  auto at_y = (at_x + at_x).reshape({2, 4, -1});
+  auto at_z = at_y + at_y;
+
+  // Dynamic reshape sizes that are not constant at definition must be explicit:
+  // no -1 allowed
+  EXPECT_THROW(
+      fusion_executor_cache.runFusionWithInputs({at_x, 2, 4, -1}),
+      std::exception);
```
Comment (jacobhinkle) [inline test/test_dynamic_transform.cpp:1140]: Input scalars of -1 are not supported for dynamic reshape currently. Supporting this is not impossible, but would increase the complexity quite a bit. At first glance, it seems like we could just replace any `Val` that evaluates to -1 in a reshape output with the proper shape. However, that is not safe since we currently replace all uses of concretized scalars and we would run the risk of replacing actual values of -1 with the a positive integer. Instead, it's safer to just disallow this explicitly and require -1 to be a constant at definition.

File: csrc/ops/alias.cpp [hunk 4]
```diff
@@ -121,12 +122,38 @@ TensorView* reshape(TensorView* inp_tv, const std::vector<Val*>& new_sizes) {
...
+      TORCH_CHECK(
+          !found_neg_one,
+          "A maximum of one value of -1 can be provided to reshape.");
+      found_neg_one = true;
+
+      Val* numel = FusionGuard::getCurFusion()->oneVal();
+      Val* other_new_numel = FusionGuard::getCurFusion()->oneVal();
+      for (const auto j : c10::irange(inp_dom.size())) {
+        numel = mul(numel, inp_dom.at(j)->extent());
+      }
```
[the remark this answers is not in the document]
Comment (naoyam) [reply csrc/ops/alias.cpp:142]: Maybe in loewr_utils? I'd prefer minimalistic designs for the IR nodes themselves.

**Review by naoyam — APPROVED** [review]
LGTM.
