### PR TITLE
Fix invalid resource usage by dangling threads

### LINKED ISSUE #4372: Invalid resource usage due to dangling threads
@csarofeen reported a segfault in his branch (#4162). It was due to dangling threads using deallocated resources. It happened due to an exception thrown in the main thread [here](https://github.com/NVIDIA/Fuser/blob/main/csrc/runtime/fusion_kernel_runtime.cpp#L424), while the worker threads were still active, which means they were still using unique_ptr-backed resources such as `SegmentedGroup`.

ASan was pretty helpful to locate the error. For example:

```
==3773==ERROR: AddressSanitizer: heap-use-after-free on address 0x5120002db1a4 at pc 0x558c038420e2 bp 0x7f61a1ec6f20 sp 0x7f61a1ec6f10
READ of size 1 at 0x5120002db1a4 thread T7
    #0 0x558c038420e1 in std::_Optional_base_impl<nvfuser::PrimDataType, std::_Optional_base<nvfuser::PrimDataType, true, true> >::_M_is_engaged() const /usr/include/c++/13/optional:473
    #1 0x558c0383eb8b in std::optional<nvfuser::PrimDataType>::has_value() const /usr/include/c++/13/optional:990
    #2 0x558c04facd34 in nvfuser::FusionKernelRuntime::compileKernel(nvfuser::KernelArgumentHolder const&, nvfuser::SegmentedGroup*, nvfuser::hir::HostIrContainer*) /home/scratch.nmaruyama_ent/nvfuser/debug5/csrc/runtime/fusion_kernel_runtime.cpp:806
    #3 0x558c04fa5a67 in operator() /home/scratch.nmaruyama_ent/nvfuser/debug5/csrc/runtime/fusion_kernel_runtime.cpp:417
    #4 0x558c04fb0b11 in __invoke_impl<void, nvfuser::FusionKernelRuntime::compileFusionParallel(nvfuser::KernelArgumentHolder)::<lambda()>&> /usr/include/c++/13/bits/invoke.h:61
    #5 0x558c04fb0208 in __invoke_r<void, nvfuser::FusionKernelRuntime::compileFusionParallel(nvfuser::KernelArgumentHolder)::<lambda()>&> /usr/include/c++/13/bits/invoke.h:111
    #6 0x558c04fafa14 in _M_invoke /usr/include/c++/13/bits/std_function.h:290
    #7 0x7f64a338bdd2 in c10::ThreadPool::main_loop(unsigned long) (/opt/conda/pytorch/lib/python3.10/site-packages/torch/lib/libc10.so+0x7bdd2) (BuildId: dd360b5b1ea7b87b1629b4217f9cfb420b38b2ba)
    #8 0x7f64a338bf26 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<c10::ThreadPool::ThreadPool(int, int, std::function<void ()> const&)::{lambda()#1}> > >::_M_run() (/opt/conda/pytorch/lib/python3.10/site-packages/torch/lib/libc10.so+0x7
bf26) (BuildId: dd360b5b1ea7b87b1629b4217f9cfb420b38b2ba)
    #9 0x7f64a34465bf in execute_native_thread_routine (/opt/conda/pytorch/lib/python3.10/site-packages/torch/lib/libtorch.so+0x145bf) (BuildId: b170e144835ab80238a99a73fad98277f35d9563)
    #10 0x7f64a34b6a41 in asan_thread_start ../../../../src/libsanitizer/asan/asan_interceptors.cpp:234
    #11 0x7f645209eaa3 in start_thread nptl/pthread_create.c:447
    #12 0x7f645212bc3b in clone3 ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

which was deleted by:

```
0x5120002db1a4 is located 100 bytes inside of 288-byte region [0x5120002db140,0x5120002db260)
freed by thread T0 here:
    #0 0x7f64a35575e8 in operator delete(void*, unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:164
    #1 0x558c05208800 in nvfuser::ReductionParams::~ReductionParams() /home/scratch.nmaruyama_ent/nvfuser/debug5/csrc/scheduler/reduction_heuristic.h:22
    #2 0x558c041cc30a in std::default_delete<nvfuser::HeuristicParams>::operator()(nvfuser::HeuristicParams*) const /usr/include/c++/13/bits/unique_ptr.h:99
```

This deletion stack was quite deep, but the bottom few frames were:

```
  #29 0x558c042d6f9f in std::unordered_map<std::pair<signed char, nvfuser::DynamicTransformConcretizationInfo const*>, std::vector<std::unique_ptr<nvfuser::FusionKernelRuntime, std::default_delete<nvfuser::FusionKernelRuntime> >, std::allocator<std::unique_ptr<nvfuser::FusionKernelRuntime, std::default_delete<nvfuser::FusionKernelRuntime> > > >, nvfuser::PairPointerHash, nvfuser::PairPointerEquals, std::allocator<std::pair<std::pair<signed char, nvfuser::DynamicTransformConcretizationInfo const*> const, std::vector<std::unique_ptr<nvfuser::FusionKernelRuntime, std::default_delete<nvfuser::FusionKernelRuntime> >, std::allocator<std::unique_ptr<nvfuser::FusionKernelRuntime, std::default_delete<nvfuser::FusionKernelRuntime> > > > > > >::~unordered_map() /usr/include/c++/13/bits/unordered_map.h:109
    #30 0x558c042d70a3 in nvfuser::FusionExecutorCache::~FusionExecutorCache() /home/scratch.nmaruyama_ent/nvfuser/debug5/csrc/runtime/fusion_executor_cache.h:117
```

This suggested `FusionExecutorCache` was deleted, while the worker thread was still active.

Inserting a try-catch around the failing code (#4366) seems to remove the segfault.

### PR DESCRIPTION
**Pull request by naoyam**
With this change, segfault is no longer observed in #4162. The try-catch block looks rather ugly. Would be happy to have any feedback to make it more robust. Perhaps, we shouldn't let multiple threads share unique_ptr-backed resources.

Fixes #4372

### CODE REVIEW

**Comment by naoyam** [comment]
!test

File: csrc/runtime/fusion_kernel_runtime.cpp [hunk 1]
```diff
@@ -361,71 +361,89 @@ void FusionKernelRuntime::compileFusionParallel(KernelArgumentHolder args) {
...
   }
 
-  std::atomic<bool> detect_exception_in_thread_pool{false};
-  std::string thread_pool_error_message;
-  std::mutex thread_pool_error_message_mutex;
-  for (int64_t run_order_id = 0; run_order_id < num_groups; ++run_order_id) {
-    auto group_to_run = runtime_workspace_.group_run_order.at(run_order_id);
-
-    if (isDebugDumpEnabled(DebugDumpOption::PythonDefinitionSegments)) {
+  if (isDebugDumpEnabled(DebugDumpOption::PythonDefinitionSegments)) {
```
Comment (naoyam) [inline csrc/runtime/fusion_kernel_runtime.cpp:364]: Took this out of the compilation loop to reduce the complexity of the loop.

File: csrc/runtime/fusion_kernel_runtime.cpp [hunk 2]
```diff
@@ -361,71 +361,89 @@ void FusionKernelRuntime::compileFusionParallel(KernelArgumentHolder args) {
...
-        group_to_run->outputs(), group_runtime_outputs, run_order_id);
+      // map output args to tensor map
+      args_manager.updateWithSegmentOutputs(
+          group_to_run->outputs(), group_runtime_outputs, run_order_id);
+    }
+  } catch (const std::exception& e) {
+    // Before clearning up unique_ptr-backed resources such as
+    // SegmentedGroup, make sure all threads are done as they may
+    // be still using the resources.
+    getThreadPool()->waitWorkComplete();
```
Comment (wujingyue) [inline csrc/runtime/fusion_kernel_runtime.cpp:445]: How is this different from the waitWorkComplete on line 451?

File: csrc/runtime/fusion_kernel_runtime.cpp [hunk 3]
```diff
@@ -361,71 +361,89 @@ void FusionKernelRuntime::compileFusionParallel(KernelArgumentHolder args) {
...
 
-    // map output args to tensor map
-    args_manager.updateWithSegmentOutputs(
-        group_to_run->outputs(), group_runtime_outputs, run_order_id);
+      // map output args to tensor map
+      args_manager.updateWithSegmentOutputs(
+          group_to_run->outputs(), group_runtime_outputs, run_order_id);
+    }
+  } catch (const std::exception& e) {
+    // Before clearning up unique_ptr-backed resources such as
```
Comment (rdspring1) [inline csrc/runtime/fusion_kernel_runtime.cpp:442]:
```suggestion
    // Before cleaning up unique_ptr-backed resources such as
```

File: csrc/runtime/fusion_kernel_runtime.cpp (hunk 2 above)
Comment (naoyam) [reply csrc/runtime/fusion_kernel_runtime.cpp:445]: The main thread might exit before reaching that line. That was what's happening with Christian's WIP PR. Specifically, he had some changes that caused an exception at `inferOuputSizes` at line 435.

File: csrc/runtime/fusion_kernel_runtime.cpp [hunk 4]
```diff
@@ -361,71 +361,89 @@ void FusionKernelRuntime::compileFusionParallel(KernelArgumentHolder args) {
...
+    // SegmentedGroup, make sure all threads are done as they may
+    // be still using the resources.
+    getThreadPool()->waitWorkComplete();
+    throw;
```
Comment (jjsjann123) [inline csrc/runtime/fusion_kernel_runtime.cpp:446]: We are still throwing here. Which means the other seg-fault was only happening where we are testing a case where exception is expected?

File: csrc/runtime/fusion_kernel_runtime.cpp (hunk 2 above)
Comment (wujingyue) [reply csrc/runtime/fusion_kernel_runtime.cpp:445]: Got it! 

One simplification is to collect inputs and compile kernels in separate loops:
```
kernels_to_compile = []

for each segment in topological order:
  collect runtime inputs
  kernels_to_compile.append((segment ID, runtime inputs))
  infer output sizes
  update the Val-to-tensor map (aka args_manager)

parallel for each kernel in kernels_to_compile:
  compile the kernel using the recorded runtime inputs
```

IIUC, `group_runtime_inputs` are cheap, meta tensors, so keeping all of them alive won't be a problem.

File: csrc/runtime/fusion_kernel_runtime.cpp (hunk 4 above)
Comment (wujingyue) [reply csrc/runtime/fusion_kernel_runtime.cpp:446]: Could be that. Even if the exception wasn't expected, it's still good to catch it cleanly without an extra segfault which could corrupt downstream tests.

Comment (naoyam) [reply csrc/runtime/fusion_kernel_runtime.cpp:446]: Empirically yes. After this change, no segfault has been observed.

**Comment by naoyam** [comment]
!test

**Comment by naoyam** [comment]
!test

File: csrc/fusion_segmenter.cpp [hunk 5]
```diff
@@ -1871,7 +1871,7 @@ void eraseInputDistinctRootDomains(Fusion* fusion) {
 }
 
 std::pair<IrCloner, std::unique_ptr<Fusion>> SegmentedFusion::makeFusion(
-    SegmentedGroup* sg) {
+    SegmentedGroup* sg) const {
```
Comment (naoyam) [inline csrc/fusion_segmenter.cpp:1874]: Unrelated

File: csrc/fusion_segmenter.h [hunk 6]
```diff
@@ -300,7 +300,8 @@ class SegmentedFusion {
 
   //! Get the fusion for the segmented group and return the IrCloner used to
   //! clone the complete fusion
-  std::pair<IrCloner, std::unique_ptr<Fusion>> makeFusion(SegmentedGroup* sg);
+  std::pair<IrCloner, std::unique_ptr<Fusion>> makeFusion(
```
Comment (naoyam) [inline csrc/fusion_segmenter.h:303]: Unrelated

File: csrc/runtime/fusion_kernel_runtime.cpp [hunk 7]
```diff
@@ -330,6 +330,45 @@ KernelArgumentHolder FusionKernelRuntime::runWithInputs(
   return fusion_outputs;
 }
 
+std::vector<KernelArgumentHolder> FusionKernelRuntime::prepareInputs(
```
Comment (naoyam) [inline csrc/runtime/fusion_kernel_runtime.cpp:333]: Factored out the input preparation step as suggested by @wujingyue 

https://github.com/NVIDIA/Fuser/pull/4373/files#r2074246473

File: csrc/runtime/fusion_kernel_runtime.cpp [hunk 8]
```diff
@@ -756,6 +787,9 @@ void FusionKernelRuntime::compileKernel(
     SegmentedGroup* sg,
     hir::HostIrContainer* hic) {
   FUSER_PERF_SCOPE("FusionKernelRuntime::compileKernel");
+  c10::cuda::CUDAGuard dg(args.getDeviceIndex());
+  c10::Device device(c10::DeviceType::CUDA, args.getDeviceIndex());
```
Comment (naoyam) [inline csrc/runtime/fusion_kernel_runtime.cpp:791]: These two lines are moved from

https://github.com/NVIDIA/Fuser/pull/4373/files#diff-67ea17ca8b2cc538ed907fe9c9546fe45fe300237d1302379a14a0c0c0e79fcbL389

and 

https://github.com/NVIDIA/Fuser/pull/4373/files#diff-67ea17ca8b2cc538ed907fe9c9546fe45fe300237d1302379a14a0c0c0e79fcbL405-L406

I don't see any reason that they need to be done outside of `compileKernel`.

File: csrc/runtime/fusion_kernel_runtime.h [hunk 9]
```diff
@@ -174,6 +174,14 @@ class FusionKernelRuntime {
   NVF_API const std::vector<std::unique_ptr<HeuristicParams>>& schedulers()
       const;
 
+  // Create KernelArgumentHolders for all of the segments
```
Comment (wujingyue) [inline csrc/runtime/fusion_kernel_runtime.h:177]: Can you code-comment what are the indices? SegmentedGroup::groupId()?

File: csrc/runtime/fusion_kernel_runtime.cpp [hunk 10]
```diff
@@ -330,6 +330,45 @@ KernelArgumentHolder FusionKernelRuntime::runWithInputs(
...
+        args_manager.translateValsToArgs(group_to_run->inputs()));
+    auto& group_runtime_inputs = all_runtime_inputs.back();
+
+    group_runtime_inputs.setDeviceIndex(args.getDeviceIndex());
+    if (group_cache_id.has_value()) {
+      group_runtime_inputs.setCacheId(group_cache_id.value());
+    }
+
+    // A segment fusion is created again in compileKernel. Can be done
+    // just once?
```
Comment (wujingyue) [inline csrc/runtime/fusion_kernel_runtime.cpp:359]: (Can be done as a follow-up)

I don't think we even need to create a segment fusion here. https://github.com/NVIDIA/Fuser/blob/87365adb01b25df8160130a19ca704e8f38c20a3/csrc/runtime/allocations.cpp#L50-L54 can be computed based on the complete fusion just fine.

File: csrc/runtime/fusion_kernel_runtime.cpp [hunk 11]
```diff
@@ -361,71 +394,69 @@ void FusionKernelRuntime::compileFusionParallel(KernelArgumentHolder args) {
...
 
-    // map output args to tensor map
-    args_manager.updateWithSegmentOutputs(
-        group_to_run->outputs(), group_runtime_outputs, run_order_id);
+  // As we pass pointers taken from unique_ptrs to worker threads,
+  // exception handling needs to wait for the worker threads before
+  // cleaning up unique_ptr resources. This try-catch structure is
+  // ugly. Perhaps, we should reconsider passing unique_ptr-backed
+  // data between threads.
+  try {
```
Comment (wujingyue) [inline csrc/runtime/fusion_kernel_runtime.cpp:420]: After extracting inferOutputSizes to a separate loop, do we still need nested try-catch?

File: csrc/runtime/fusion_kernel_runtime.cpp [hunk 12]
```diff
@@ -330,6 +330,45 @@ KernelArgumentHolder FusionKernelRuntime::runWithInputs(
...
+      args, runtime_workspace_, segmented_fusion_->inputs());
+
+  // group should share cache id.
+  const auto group_cache_id = args.getCacheId();
+
+  for (int64_t run_order_id = 0; run_order_id < num_groups; ++run_order_id) {
+    auto group_to_run = runtime_workspace_.group_run_order.at(run_order_id);
+    // TODO: index mode should be updated per segmented kernel
+    // Prepare input vector
+    all_runtime_inputs.push_back(
```
Comment (wujingyue) [inline csrc/runtime/fusion_kernel_runtime.cpp:349]: Alternatively, we can index all_runtime_inputs by group_id instead of run_order_id. This way, when you compileKernel these segments, you don't need to read run_order at all.

File: csrc/runtime/fusion_kernel_runtime.cpp (hunk 11 above)
Comment (naoyam) [reply csrc/runtime/fusion_kernel_runtime.cpp:420]: Less likely, but still yes since there's a time window where the main thread potentially gets an exception before `wait` is called. I think it's a good practice to remove the potential vulnerable window as much as possible.

More fundamentally, though, I believe it's just a bad idea to pass unique_ptr-backed pointers between threads.

File: csrc/runtime/fusion_kernel_runtime.cpp (hunk 12 above)
Comment (naoyam) [reply csrc/runtime/fusion_kernel_runtime.cpp:349]: That seems to make the code simpler. Thanks for the suggestion.

Comment (naoyam) [reply csrc/runtime/fusion_kernel_runtime.cpp:350]: On second thought, it doesn't seem to buy much since we need `run_order` anyway as long as `compileFusionParallel` compiles segments in the run order. That doesn't seem to be required, but I don't see any particular motivation to change that.

File: csrc/runtime/fusion_kernel_runtime.cpp (hunk 10 above)
Comment (naoyam) [reply csrc/runtime/fusion_kernel_runtime.cpp:360]: I think you're right. I'll leave it as is since it doesn't seem like a small change.

File: csrc/runtime/fusion_kernel_runtime.cpp (hunk 12 above)
Comment (wujingyue) [reply csrc/runtime/fusion_kernel_runtime.cpp:350]: > compileFusionParallel compiles segments in the run order

Just to make sure we are on the same page, there's shape inference and there's compilation. Shape inference needs to be in the run order. Compilation doesn't and in fact runs in parallel. Therefore, the sage of run_order at https://github.com/NVIDIA/Fuser/pull/4373/files#diff-67ea17ca8b2cc538ed907fe9c9546fe45fe300237d1302379a14a0c0c0e79fcbR423 is unnecessary. 

I can clean this up after this PR.

File: csrc/runtime/fusion_kernel_runtime.h [hunk 13]
```diff
@@ -174,6 +174,15 @@ class FusionKernelRuntime {
   NVF_API const std::vector<std::unique_ptr<HeuristicParams>>& schedulers()
       const;
 
+  // Create KernelArgumentHolders for all of the segments. Sorted in
+  // the run order.
+  std::vector<KernelArgumentHolder> prepareInputs(
+      const KernelArgumentHolder& args) const;
+
+  int64_t numGroups() const {
+    return (int64_t)runtime_workspace_.group_run_order.size();
```
Comment (wujingyue) [inline csrc/runtime/fusion_kernel_runtime.h:183]:
```suggestion
    int64_t n_groups = std::ssize(runtime_workspace_.group_run_order);
    NVF_ERROR_EQ(n_groups, std::ssize(segmented_fusion_->groups()));
    return n_groups;
```

**Review by wujingyue — APPROVED** [review]

File: csrc/runtime/fusion_kernel_runtime.cpp (hunk 12 above)
Comment (naoyam) [reply csrc/runtime/fusion_kernel_runtime.cpp:350]: Right, it doesn't need to be the same order for functionality, but I just feel like it makes to sense to keep the order for debugging. What I commonly do is to run a failing test with `NVFUSER_DISABLE=parallel_compile NVFUSER_DUMP=segmented_fusion,fusion_ir`. Oftentimes there's some problematic segment. As the segmented fusion is printed in the dependency order, intuitively it's easier to digest what's happening if the segments are compiled in the same order as the dumped output of the segmented fusion. 

Not a strong reason to keep the ordering, but that's the reason I wasn't motivated to change.

**Comment by naoyam** [comment]
!test
