### PR TITLE
Split Hopper MMA by warp-tile before instruction tile

### LINKED ISSUE #3636: Split by warp tile in Hopper matmul scheduler
Our current Hopper matmul scheduler ignores the `warp_tile` option and only splits the CTA tile by the instruction tile. This means that currently we fail to execute a kernel compiled with this valid config:
```
MMA macro: Hopper_64_8_16
CircularBufferOptions:
  circular_buffer_smem_write: true
  circular_buffer_smem_read: true
  smem_circular_buffer_stage: 3
  smem_circular_buffer_prefetch_gap: 1
SupportedVectorization:
  a: 8
  b: 8
  epilogue: 8
MatMulTileOptions: warp tile [64, 64, 32], CTA tile [128, 128, 32]
Async global mem load: true
Indexing mode: int32_t
Tile rasterization order: row-major
Grid swizzle factor: 1
Cluster dimensions: 2 1 1
Use shared memory epilogue: 1
Promote re-use of prologue shared memory: 0
Split-K factor: 8
```
The error we see is
> RuntimeError:  INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/runtime/executor_params.cpp":30, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Selected invalid number of threads for cuda: 4224

We should change our scheduling to instead first split by warp tile and to parallelize TIDy on the cta/warp split instead of cta/instr split. In this way, we can still use large tiles along with smaller instructions without using far too many warps.

### PR DESCRIPTION
**Pull request by jacobhinkle**
Currently we ignore the warp tile parameter when scheduling Hopper matmuls (see #3636). This PR introduces a test with different CTA, warp, and instruction tiles and modifies the Hopper scheduler to split by warp tile in addition to instruction tile. Note that the instruction tile split results in two serial loop domain so we wind up executing multiple mma  instructions in each main loop. In the included example, `warp_tile` is 64, 128, 16 and the macro is `Hopper_64_8_16`. In this case, there are 128/8 = 16 instruction tiles per warp tile so the generated main loop looks like this:
```c++
  #pragma unroll 3
  for(nvfuser_index_t i33 = 0; i33 < i4; ++i33) {
    nvfuser_index_t i34;
    i34 = 48 + (16 * i33);
    nvfuser_index_t i35;
    i35 = (3 + i33) % 4;
    unsigned i36;
    i36 = i7 + (8192 * i35);
    unsigned i37;
    i37 = i10 + (4096 * i35);
    nvfuser_index_t i38;
    i38 = i33 % 4;
    unsigned i39;
    i39 = i13 + (4096 * i38);
    uint64_t i40;
    i40 = 4611686293305294848ULL | ((262143ULL & (uint64_t)(i39)) >> 4ULL);
    unsigned i41;
    i41 = i15 + (8192 * i38);
    if (((Hopper::electSync(4294967295U) && b22) && b23)) {
      mbarrier::arriveExpectTX(toSmem((&T8[((3LL + i33) % 4)])), 8192U);
      #pragma unroll
      for(nvfuser_index_t i31 = 0; i31 < 4; ++i31) {
        Hopper::cpAsyncBulkTensorTileG2S((Hopper::CpAsyncBulkTensorTileG2SIndex<2>{ ptr5, (Array<nvfuser_index_t, 2, 1>{(i6 + (64 * i31)), i34}), toSmem((&T8[((3LL + i33) % 4)])) }), (i36 + (2048 * i31)));
      }
      mbarrier::arriveExpectTX(toSmem((&T8[((3LL + i33) % 4)])), 4096U);
      #pragma unroll
      for(nvfuser_index_t i32 = 0; i32 < 2; ++i32) {
        Hopper::cpAsyncBulkTensorTileG2S((Hopper::CpAsyncBulkTensorTileG2SIndex<2>{ ptr8, (Array<nvfuser_index_t, 2, 1>{(i9 + (64 * i32)), i34}), toSmem((&T8[((3LL + i33) % 4)])) }), (i37 + (2048 * i32)));
      }
    }
    mbarrier::waitParity(toSmem((&T8[(i33 % 4)])), (uint32_t)(((i33 / 4) % 2)));
    #pragma unroll
    for(nvfuser_index_t i25 = 0; i25 < 16; ++i25) {
      unsigned i42;
      i42 = (i41 + (2048 * (i25 / 8))) + (16 * (i25 % 8));
      asm volatile(
        "{\n"
        "  .reg .pred p0; \n"
        "  setp.ne.b32 p0, %6, 0;\n"
        "  wgmma.mma_async.sync.aligned.m64n8k16.f32.f16.f16 {%0, %1, %2, %3}, %4, %5, p0, %7, %8, %9, %10;\n"
        "}\n"
        :"+f"((*reinterpret_cast<Array<float, 4, 1>*>(&T2[(4 * i25)]))[0]),
         "+f"((*reinterpret_cast<Array<float, 4, 1>*>(&T2[(4 * i25)]))[1]),
         "+f"((*reinterpret_cast<Array<float, 4, 1>*>(&T2[(4 * i25)]))[2]),
         "+f"((*reinterpret_cast<Array<float, 4, 1>*>(&T2[(4 * i25)]))[3])
        :"l"(i40),
         "l"((4611686293305294848ULL | ((262143ULL & (uint64_t)(i42)) >> 4ULL))),
         "n"((uint32_t)(true)),
         "n"(1),
         "n"(1),
         "n"(1),
         "n"(1)
      );
    }
    __syncthreads();
    asm volatile("wgmma.commit_group.sync.aligned;\n");
    asm volatile("wgmma.wait_group.sync.aligned %0;\n"::"n"(0LL):"memory");
  }
```

Fixes #3636

### CODE REVIEW

**Comment by jacobhinkle** [comment]
!test

**Comment by jacobhinkle** [comment]
The bank conflict came from stmatrix scheduling which needs to be updated. I will do that in a separate PR. For now, I've disabled smem epilogue in the included test.

**Comment by jacobhinkle** [comment]
!test

**Comment by jacobhinkle** [comment]
When I manually disable stmatrix but keep TMA store, I still hit a bank conflict and misaligned address in the smem read when doing the TMA store.

**Comment by jacobhinkle** [comment]
mma result before this PR:
```
T2_l_float[iblockIdx.y55{( ceilDiv(i1, 128) )}, iblockIdx.x53{( ceilDiv(i6, 256) )}, rS51{( ceilDiv(i0, 16) )}, ithreadIdx.y61{64}, iS58{64}, iS60{8}, rS52{16}]
 root domain : (rS6{i0}, iS7{i1}, iS8{i6})
 logical domain : (iS7{i1}, iS8{i6}, rS6{i0})
 contiguity: t t n
  Split: iS7{i1} by factor 128 -> iblockIdx.y55{( ceilDiv(i1, 128) )}, iS56{128}
  Split: iS8{i6} by factor 256 -> iblockIdx.x53{( ceilDiv(i6, 256) )}, iS54{256}
  Split: rS6{i0} by factor 16 -> rS51{( ceilDiv(i0, 16) )}, rS52{16}
  Split: iS56{128} by factor 64 -> iS57{2}, iS58{64}
  Split: iS54{256} by factor 8 -> iS59{32}, iS60{8}
  Merge: iS57{2} and iS59{32} -> ithreadIdx.y61{64}
 loop domain : (iblockIdx.y55{( ceilDiv(i1, 128) )}, iblockIdx.x53{( ceilDiv(i6, 256) )}, rS51{( ceilDiv(i0, 16) )}, ithreadIdx.y61{64}, iS58{64}, iS60{8}, rS52{16})
```
And after this PR:
```
T2_l_float[iblockIdx.y55{( ceilDiv(i1, 128) )}, iblockIdx.x53{( ceilDiv(i6, 256) )}, rS51{( ceilDiv(i0, 16) )}, ithreadIdx.y65{4}, iS59{1}, iS63{16}, iS60{64}, iS64{8}, rS52{16}]
 root domain : (rS6{i0}, iS7{i1}, iS8{i6})
 logical domain : (iS7{i1}, iS8{i6}, rS6{i0})
 contiguity: t t n
  Split: iS7{i1} by factor 128 -> iblockIdx.y55{( ceilDiv(i1, 128) )}, iS56{128}
  Split: iS8{i6} by factor 256 -> iblockIdx.x53{( ceilDiv(i6, 256) )}, iS54{256}
  Split: rS6{i0} by factor 16 -> rS51{( ceilDiv(i0, 16) )}, rS52{16}
  Split: iS56{128} by factor 64 -> iS57{2}, iS58{64}
  Split: iS54{256} by factor 128 -> iS61{2}, iS62{128}
  Merge: iS57{2} and iS61{2} -> ithreadIdx.y65{4}
  Split: iS58{64} by factor 64 -> iS59{1}, iS60{64}
  Split: iS62{128} by factor 8 -> iS63{16}, iS64{8}
 loop domain : (iblockIdx.y55{( ceilDiv(i1, 128) )}, iblockIdx.x53{( ceilDiv(i6, 256) )}, rS51{( ceilDiv(i0, 16) )}, ithreadIdx.y65{4}, iS59{1}, iS63{16}, iS60{64}, iS64{8}, rS52{16})
```

**Comment by jacobhinkle** [comment]
Note that I can enable smem epilogue and the test passes if I use `Hopper_64_64_16` and I disable stmatrix.

File: csrc/scheduler/hopper_multi_matmul.cpp [hunk 1]
```diff
@@ -34,20 +34,53 @@ void HopperMultipleMatmulScheduler::transformLikeMmaOutput(
...
+  // We split this into warp tiles then instruction tiles
+  if (is_mma_result) {
+    // Original: [..., M, N, K]
+    tv->split(-3, params_->tile_sizes.warp_tile.m);
+    tv->split(-3, getM(params_->mma_macro));
+    tv->split(-2, params_->tile_sizes.warp_tile.n);
+    tv->split(-2, getN(params_->mma_macro));
+    // K dimension is present for mma_result
+    tv->split(-1, params_->tile_sizes.warp_tile.k);
+    tv->split(-1, getK(params_->mma_macro));
```
Comment (jacobhinkle) [inline csrc/scheduler/hopper_multi_matmul.cpp:49]: @rdspring1 is this enough or is #3616 still needed?

File: csrc/scheduler/hopper_multi_matmul.cpp [hunk 2]
```diff
@@ -34,20 +34,53 @@ void HopperMultipleMatmulScheduler::transformLikeMmaOutput(
...
-  // After Reorder: [..., Mo, No, Mio, Nio, Mii, Nii]
-  tv->merge(apply_k_dim_offset(-4));
-  // After Merge: [..., Mo, No, Mio * Nio, Mii, Nii]
-  tv->axis(apply_k_dim_offset(-3))->parallelize(ParallelType::TIDy);
-  // After Parallelize: [..., Mo, No, Mio * Nio (TIDy), Mii, Nii]
+  // The input is originally block tiled so that the inner dims are the CTA tile
+  // size
+  // Original: [..., M, N(, K)]
+  // We split this into warp tiles then instruction tiles
+  if (is_mma_result) {
```
Comment (jacobhinkle) [inline csrc/scheduler/hopper_multi_matmul.cpp:41]: TODO: since there is no code in common between these branches, we should split this into two separate functions.

File: csrc/scheduler/hopper_multi_matmul.cpp (hunk 1 above)
Comment (rdspring1) [reply csrc/scheduler/hopper_multi_matmul.cpp:49]: It is all that is required for scheduler changes.

**Review by rdspring1 — COMMENTED** [review]
Do we need to remove this limitation to handle all matmul parameter configurations?

`CTA tile must match warp tile K dimension for Hopper matmul but found MatMulTileOptions: warp tile [64, 256, 32], CTA tile [128, 256, 64]`

**Comment by rdspring1** [comment]
I see `C++ exception with description " INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/runtime/executor.cpp":1421, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. CUDA error: CUDA_ERROR_INVALID_VALUE failed with error invalid argument` with warp specialization enabled.

**Comment by jacobhinkle** [comment]
> I see `C++ exception with description " INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/runtime/executor.cpp":1421, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. CUDA error: CUDA_ERROR_INVALID_VALUE failed with error invalid argument` with warp specialization enabled in test `HSH_NT_UseScheduler_MultipleInstructionsPerWarpTile`

I just checked this by modifying the test to expect 5 warpgroups instead of four and by adding a `WarpSpecialized(ParallelType::TIDy)` argument to these `circularBuffer` calls: https://github.com/NVIDIA/Fuser/blob/f5e084c8ae62227b9f54876ff525a107ff2f64de/csrc/scheduler/hopper_multi_matmul.cpp#L677-L690
The result for me is a passing test but perf drops.

**Comment by jacobhinkle** [comment]
> Do we need to remove this limitation to handle all matmul parameter configurations?
> 
> `CTA tile must match warp tile K dimension for Hopper matmul but found MatMulTileOptions: warp tile [64, 256, 32], CTA tile [128, 256, 64]`

I might be confused here. The thing is that the K dimension is treated differently from the M and N dimensions in these tile definitions. The instruction tile's K dimension is clear, and the warp tile's K dimension (I think) signifies how much data we should load at a time then we can loop to compute instructions over all the loaded data. The CTA tile's M and N dimensions specify the tiling of the output, but what does the `cta_tile.k` signify? This is why I was thinking we'd keep this restriction.

Note that this restriction `cta_tile.k == warp_tile.k` is enforced on Ampere as part of `scheduleWarpTileWithReduction`.

**Comment by jacobhinkle** [comment]
!test

**Comment by jacobhinkle** [comment]
!test

**Comment by jacobhinkle** [comment]
!build

File: csrc/scheduler/hopper_multi_matmul.cpp [hunk 3]
```diff
@@ -365,6 +401,7 @@ void HopperMultipleMatmulScheduler::scheduleOperands() {
                             const std::vector<TensorView*>& smem_operands,
                             MmaOperand operand_type) {
     blockTileTensors(smem_operands);
+    parallelizeBlocks(smem_operands);
```
Comment (jacobhinkle) [inline csrc/scheduler/hopper_multi_matmul.cpp:404]: We might as well also parallelize these. Note that we could just call this from `blockTileTensors` since we are always parallelizing outer dims for every tensor.

**Comment by rdspring1** [comment]
!test

File: csrc/scheduler/hopper_multi_matmul.cpp [hunk 4]
```diff
@@ -29,25 +29,61 @@
...
-      "transformLikeMmaOutput requires at least four iterDomains but ",
-      tv->toString(),
-      " only has ",
-      tv->domain()->loop().size(),
-      ".");
-
-  // Original: [..., Mo, No, Mi, Ni]
+void HopperMultipleMatmulScheduler::transformLikeMmaOutputWithK(
+    TensorView* tv) {
+  // The input is originally block tiled so that the inner dims are the CTA tile
```
Comment (rdspring1) [inline csrc/scheduler/hopper_multi_matmul.cpp:34]: Do we have any conditions to check here?

**Review by rdspring1 — APPROVED** [review]
LGTM

**Comment by jacobhinkle** [comment]
!test

**Comment by jacobhinkle** [comment]
!build
